ckeditor/ckeditor5

packages/ckeditor5-clipboard/src/utils/plaintexttohtml.ts, packages/ckeditor5-clipboard/tests/utils/plaintexttohtml.js
Fix (clipboard): Replace tab with four spaces when pasting data from clipboard. Closes #12806.
---
---
_Replacing tab with four spaces to be consistent with CKEditor 4._
1. Visit https://www.editpad.org/.
2. Prepare text with tabs.
3. Copy the code from editpad.org and paste to CKEditor 5.
4. Compare with current version https://ckeditor.com/ckeditor-5/demo/.
=> Replace tab with four spaces when pasting data from clipboard

packages/ckeditor5-table/src/tablecolumnresize/tablewidthresizecommand.js, packages/ckeditor5-table/tests/tablecolumnresize/tablewidthresizecommand.js
Other (table): Reset column widths when table width is reset. Closes #12916.
=> Other (table): Reset column widths when table width is reset

packages/ckeditor5-image/docs/_snippets/features/image-style-custom.js, packages/ckeditor5-image/docs/features/images-styles.md
Docs (image): Fixed down arrow label for image style buttons in docs. Closes #12468.
---
Double check the label - that was the best we were able to come up with 😂
=> Fixed down arrow label for image style buttons in docs

docs/updating/release-process.md, docs/updating/versioning-policy.md
Docs: Removed "CKEditor 5" from navigation on "Updating" page. Closes [#2319](https://github.com/cksource/ckeditor5-internal/issues/2319).
---
Removed CKEditor 5 branding from the navigation on the [Updating](https://ckeditor.com/docs/ckeditor5/latest/updating/index.html) page.
Before:
After:
=> Docs: Removed "CKEditor 5" from navigation on "Updating" page.

docs/framework/guides/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md, docs/framework/guides/abbreviation-plugin-tutorial/abbreviation-plugin-level-2.md, docs/framework/guides/abbreviation-plugin-tutorial/abbreviation-plugin-level-3.md, docs/framework/guides/creating-simple-plugin-timestamp.md, docs/umberto.json, tests/manual/abbreviation-level-1.md, tests/manual/abbreviation-level-2.md, tests/manual/abbreviation-level-3.md
Docs: Rename "abbreviation plugin" tutorials. Closes https://github.com/cksource/ckeditor5-internal/issues/2352.
---
=> Docs: Rename "abbreviation plugin" tutorials

packages/ckeditor5-utils/src/dom/global.ts
Type: Message. Closes https://github.com/ckeditor/ckeditor5/issues/12971.
---
Currenlty jest tests failing when upgrading ckeditor from 34 to 35.
=> Use global not as variable name to fix problem with Jest

packages/ckeditor5-html-support/docs/features/general-html-support.md
Docs: adding the GHS+RTC info to known issues. Closes cksource/ckeditor5-internal#2408
---
=> Docs: adding the GHS+RTC info.

packages/ckeditor5-mention/src/mentioncommand.js
Docs: correcting error code. Closes cksource/ckeditor5-internal#2310
---
The error code example used a dollar sign `$` which apparently disappears during code generation in Umberto. Using a double `$$` made only the second one appear. Possible follow-up for the DevOps/Umberto team.
=> Docs: correcting error code.

packages/ckeditor5-ckfinder/src/ckfindercommand.js, packages/ckeditor5-ckfinder/tests/ckfindercommand.js
Feature (track-changes): Add track changes integration for CKFinder feature.
Other (ckfinder): Set correct value (false) for `CKFinderCommand#affectsData`. Now the command's state depends only on related commands (`insertImage` and `link`). Closes #13213.
=> Set correct value (false) for CKFinderCommand#affectsData

packages/ckeditor5-engine/src/conversion/upcasthelpers.ts, packages/ckeditor5-engine/tests/conversion/upcasthelpers.js
Fix (table): Fix tableCell content inconsistency after executing editor.data.set. Closes #13053.
Connected to: https://github.com/cksource/collaboration-features/issues/4061
=> Fix tableCell content inconsistency after executing editor.data.set

packages/ckeditor5-table/src/tablecolumnresize/converters.js, packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js
Fix (table): PlainTableOutput and TableColumnResize compatibility. Closes #13164.
=> Fix (table): PlainTableOutput and TableColumnResize compatibility

packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesui.js, packages/ckeditor5-table/src/tableproperties/tablepropertiesui.js, packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesui.js, packages/ckeditor5-table/tests/tableproperties/tablepropertiesui.js
Type: Other (table): Do not execute property command on table property window open. Closes #13262.
=> Other (table): Do not execute property command on table property window open

docs/umberto.json, scripts/docs/build-docs.js, scripts/docs/buildapi.js, scripts/docs/parse-arguments.js, tsconfig.docs.json
Internal: Added support for the `--ts` switch to build the API docs for TypeScript sources. See #12521.
---
I added a few cosmetic changes to the `umberto.json` file. This file is programmatically modified with `JSON.stringify()`, which has a built-in way to indent JSON. Now, the content of the `umberto.json` file is adjusted to `JSON.stringify()` output.
=> Added support for the `--ts` switch to build the docs for TypeScript sources

packages/ckeditor5-engine/src/view/domconverter.ts, packages/ckeditor5-engine/src/view/observer/mutationobserver.ts, packages/ckeditor5-engine/src/view/renderer.ts
Internal (engine): Fixed the return type from `DomConverter#mapViewToDom`.
---
=> Rewriting types for domconverter#mapViewToDom

packages/ckeditor5-html-support/src/integrations/dualcontent.js, packages/ckeditor5-html-support/src/schemadefinitions.js, packages/ckeditor5-html-support/tests/integrations/dualcontent.js
Fix (html-support): Fix description lists with name-value groups wrapped in div elements upcasting using GHS. Closes #12240.
---
=> Fix description lists upcasting using ghs

packages/ckeditor5-clipboard/tests/dragdrop.js, packages/ckeditor5-engine/src/view/domconverter.ts, packages/ckeditor5-engine/tests/view/domconverter/view-to-dom.js, packages/ckeditor5-html-support/tests/htmlcomment-integration.js, packages/ckeditor5-list/src/documentlist/converters.ts, packages/ckeditor5-list/tests/documentlist/integrations/markers.js, packages/ckeditor5-table/src/converters/downcast.js, packages/ckeditor5-table/src/converters/upcasttable.js, packages/ckeditor5-table/src/tableediting.js, packages/ckeditor5-table/tests/converters/upcasttable.js, packages/ckeditor5-table/tests/table-integration.js
Fix (engine, list, table): Markers should not be lost on list items and in table cells in the data pipeline. Closes #13285.
---
=> Markers should be properly downcasted and upcasted on bogus paragraphs

packages/ckeditor5-engine/src/model/model.ts, packages/ckeditor5-engine/tests/model/model.js
Internal (engine): `Model#insertContent()` and `Model#insertObject()` should pass all parameters to the event as it would be a decorated method. Closes #13379.
---
=> Model#insertContent() and Model#insertObject() should pass all parameters to the event as it would be a decorated method.

packages/ckeditor5-engine/src/model/model.ts
Internal (engine): Renamed label in TS tuple to avoid Babel parse error. Closes #13392.
---
=> Renamed label in TS tuple to avoid Babel parse error.

docs/features/editor-placeholder.md, docs/features/read-only.md, docs/features/toolbar.md, docs/features/ui-language.md, packages/ckeditor5-clipboard/docs/features/drag-drop.md, packages/ckeditor5-clipboard/docs/features/paste-plain-text.md, packages/ckeditor5-minimap/docs/features/minimap.md, packages/ckeditor5-paste-from-office/docs/features/paste-from-google-docs.md, packages/ckeditor5-paste-from-office/docs/features/paste-from-word.md, packages/ckeditor5-undo/docs/features/undo-redo.md
Docs: adding missing contribute links. Closes cksource/ckeditor5-internal#2672
---
=> Docs: adding missing contribute links.

packages/ckeditor5-engine/src/index.ts, tsconfig.json
Internal (engine): Added `DowncastAddMarkerEvent` and `ViewRenderEvent` types to the package exports.
Internal: Added `DOM.Iterable` library to known type definitions in TypeScript configuration.
---
The `DOM.Iterable` adds `[Symbol.iterator]()` for allowed DOM types. Therefore, the following code is not reported as incorrect by TypeScript:
```ts
const editor = this.editor;
const view = editor.editing.view;
const domRoot = view.getDomRoot()!;
const classes = [
'ck-foo',
'ck-bar',
// Clone all editing root classes.
...domRoot.classList
];
```
=> Re-export some view types. Add `DOM.Iterable` to TS config.

scripts/docs/build-content-styles.js
Internal: Normalized path to classic editor sources for content styles to always use slashes instead of backslashes. Otherwise, generating content styles will end with an error on Windows.
=> Normalized path to classic editor sources for Windows to use slashes instead of backslashes

packages/ckeditor5-paragraph/src/insertparagraphcommand.ts, packages/ckeditor5-paragraph/src/paragraph.ts, packages/ckeditor5-paragraph/src/paragraphbuttonui.ts, packages/ckeditor5-paragraph/src/paragraphcommand.ts
Internal (paragraph): Clean-up docs for `ckeditor5-paragraph`. Closes #12703.
=> Clean-up docs for `ckeditor5-paragraph`

packages/ckeditor5-undo/src/basecommand.ts, packages/ckeditor5-undo/src/redocommand.ts, packages/ckeditor5-undo/src/undo.ts, packages/ckeditor5-undo/src/undocommand.ts, packages/ckeditor5-undo/src/undoediting.ts, packages/ckeditor5-undo/src/undoui.ts
Internal (undo): Clean-up docs for `ckeditor5-undo`. Closes #12707 .
=> Clean-up docs for `ckeditor5-undo`

docs/_snippets/installation/plugins-mapping/plugins-mapping.html, docs/features/image-upload.md, docs/features/using-file-managers.md, docs/installation/getting-started/predefined-builds.md, docs/umberto.json, packages/ckeditor5-adapter-ckfinder/_src/uploadadapter.js, packages/ckeditor5-adapter-ckfinder/src/uploadadapter.ts, packages/ckeditor5-ckbox/ckeditor5-metadata.json, packages/ckeditor5-ckbox/docs/features/ckbox.md, packages/ckeditor5-ckbox/src/ckbox.js, packages/ckeditor5-ckbox/src/ckboxuploadadapter.js, packages/ckeditor5-ckfinder/ckeditor5-metadata.json, packages/ckeditor5-ckfinder/docs/features/ckfinder.md, packages/ckeditor5-ckfinder/src/ckfinder.js
Docs: Created File management category for CKBox and CKFinder. Closes [#2662](https://github.com/cksource/ckeditor5-internal/issues/2662).
---
For this task, I've done the following things:
1. Created a new _File management_ section for the CKBox and CKFinder guides.
2. In the _Image upload_ section, added a new document _Using file managers_. It's basically a CTA to go to one of the two guides that have been moved.
3. Added some minor linguistic corrections to a couple of documents.
=> Docs: Created File management category for CKBox and CKFinder.

packages/ckeditor5-mention/_src/mention.js, packages/ckeditor5-mention/src/mentionconfig.ts, packages/ckeditor5-mention/src/mentionui.ts, packages/ckeditor5-mention/tests/manual/mention-custom-dropdownlimit.js, packages/ckeditor5-mention/tests/manual/mention-custom-dropdownlimit.md, packages/ckeditor5-mention/tests/mentionui.js
Feature (mention): Should be possible to limit the dropdown on singular feed level. Closes #13504 .
---
=> Optional `dropdownLimit` property at a level of singular feed.

packages/ckeditor5-ckbox/docs/features/ckbox.md, packages/ckeditor5-ckfinder/docs/features/ckfinder.md
Docs: Removed suffixes from articles in File management category. Closes [#2759](https://github.com/cksource/ckeditor5-internal/issues/2759).
---
I've removed the "file manager" suffixes from the articles in the _File management_ category.
=> Docs: Removed suffixes from articles in File management category.

docs/framework/guides/contributing/code-style.md
Docs: Added docs for eslint rule `ckeditor5-rules/non-public-members-as-internal`.
---
=> Added docs for eslint rule `ckeditor5-rules/non-public-members-as-internal`.

.gitignore, packages/ckeditor5-engine/tsconfig.release.json, packages/ckeditor5-utils/tsconfig.release.json, scripts/release/clean.js, scripts/release/publish.js, tsconfig.json, tsconfig.release.json
Internal: Generate `.d.ts` files for all packages. Closes #11722.
=> Generate `.d.ts` files for all packages

scripts/release/publish.js
Internal: Ability to specify the npm tag when publishing. See #13533.
---
Requires: https://github.com/ckeditor/ckeditor5-dev/pull/844.
=> Ability to specify the npm tag when publishing

packages/ckeditor5-list/src/documentlist.ts, packages/ckeditor5-list/src/documentlistproperties.ts
Internal (list): Load the plugin configuration in `DocumentList` and `DocumentListProperties` plugins to enable module augmentation and proper editor config suggestions
=> Add missing config import in DocumentList plugin

packages/ckeditor5-mention/src/mentionconfig.ts
Fix (mention): Make a `text` property optional in `MentionFeedObjectItem` type. Closes #13550.
---
=> Make a `text` property optional in `MentionFeedObjectItem` type

docs/_snippets/features/placeholder-custom.js, docs/_snippets/features/placeholder.js, packages/ckeditor5-autoformat/docs/_snippets/features/autoformat.js, packages/ckeditor5-basic-styles/docs/_snippets/features/basic-styles.js, packages/ckeditor5-block-quote/docs/_snippets/features/block-quote-source.js, packages/ckeditor5-code-block/docs/_snippets/features/code-block-custom-languages.js, packages/ckeditor5-code-block/docs/_snippets/features/code-block.js, packages/ckeditor5-find-and-replace/docs/_snippets/features/find-and-replace.js, packages/ckeditor5-font/docs/_snippets/features/custom-font-color-and-background-color-options.js, packages/ckeditor5-font/docs/_snippets/features/custom-font-family-options.js, packages/ckeditor5-font/docs/_snippets/features/custom-font-size-named-options.js, packages/ckeditor5-font/docs/_snippets/features/custom-font-size-numeric-options.js, packages/ckeditor5-font/docs/_snippets/features/font.js, packages/ckeditor5-indent/docs/_snippets/features/custom-indent-block-classes.js, packages/ckeditor5-indent/docs/_snippets/features/indent.js, packages/ckeditor5-minimap/docs/_snippets/features/minimap.js, packages/ckeditor5-typing/docs/_snippets/features/text-transformation-extended.js, packages/ckeditor5-typing/docs/_snippets/features/text-transformation.js
Docs: unifying demos toolbars.
---
_The first batch of toolbars. Part of_ cksource/ckeditor5-internal#2797
Based on the "Editor toolbar with few features" setup as described here: [https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed](https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed)
All basic features in the setup are available in the editor builds (hence underline was removed).
Batch One contains the following guides:
*   autoformatting
*   automatic text transformations
*   basic text styles
*   block indent
*   block quote
*   code block
*   content minimap
*   editor placeholder
*   find and replace
*   font: family, size, color, …
=> Docs: unifying demos toolbars Batch One

docs/_snippets/features/read-only-hide-toolbar.js, docs/_snippets/features/read-only.js, packages/ckeditor5-clipboard/docs/_snippets/features/drag-drop.js, packages/ckeditor5-clipboard/docs/_snippets/features/paste-plain-text.js, packages/ckeditor5-find-and-replace/docs/_snippets/features/find-and-replace.js, packages/ckeditor5-minimap/docs/_snippets/features/minimap.js, packages/ckeditor5-paste-from-office/docs/_snippets/features/paste-from-office.js, packages/ckeditor5-remove-format/docs/_snippets/features/remove-format.js, packages/ckeditor5-restricted-editing/docs/_snippets/features/restricted-editing.js, packages/ckeditor5-select-all/docs/_snippets/features/select-all.js, packages/ckeditor5-source-editing/docs/_snippets/features/source-editing-imports.js, packages/ckeditor5-source-editing/docs/_snippets/features/source-editing-with-markdown.js, packages/ckeditor5-source-editing/docs/_snippets/features/source-editing.js, packages/ckeditor5-special-characters/docs/_snippets/features/special-characters-extended-category.js, packages/ckeditor5-special-characters/docs/_snippets/features/special-characters-limited-categories.js, packages/ckeditor5-special-characters/docs/_snippets/features/special-characters-new-category.js, packages/ckeditor5-special-characters/docs/_snippets/features/special-characters.js
Docs: unifying demos toolbars.
---
_The third batch of toolbars. Part of_ cksource/ckeditor5-internal#2797
Based on the "Editor toolbar with few features" setup as described here: [https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed](https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed)
All basic features in the setup are available in the editor builds (hence underline was removed).
Batch Three contains the following guides:
*   paste from Google Docs
*   paste from Office
*   paste plain text
*   drag and drop
*   read-only support
*   remove formatting
*   restricted editing
*   select all
*   source editing
*   special characters
=> Docs: unifying demos toolbars Batch Three

packages/ckeditor5-engine/src/index.ts
Minor changes in typings needed for CF revision history TS migration.
`documentfragment.markers` - Should this field be `readonly`? While the change in revision history can be fixed using pure TS changes, I'm not sure why it is readonly. From what I can see, it is not possible to pass markers via constructor so setting markers for document fragment (assuming we just want to create document fragment without attaching in to the model) seems difficult.
=> Other (engine, core): Changes in TS typings

packages/ckeditor5-highlight/src/index.ts
Internal: Add missing export in `hightlight` plugin
=> Internal: Add missing export in `hightlight` plugin

scripts/check-manual-tests.sh
Internal: The `check-manual-tests` should not produce DLL builds. An integrator should provide them before calling the checker script.
=> check-maunal-tests should not build DLL

scripts/release/clean.js
Internal: The `release:clean` script should not remove the lib/ directory from packages.
=> Clean does not touch the `lib/` directory

docs/_snippets/examples/balloon-block-editor.html, docs/_snippets/examples/balloon-block-editor.js, docs/_snippets/examples/balloon-editor.js, docs/_snippets/examples/bottom-toolbar-editor.js, docs/_snippets/examples/classic-editor.js, docs/_snippets/examples/document-editor.js, docs/_snippets/examples/inline-editor.js, docs/_snippets/framework/tutorials/external-data-widget.js, docs/_snippets/framework/tutorials/inline-widget.js, docs/_snippets/framework/tutorials/using-react-in-widget.html, docs/examples/builds/balloon-editor.md, docs/examples/builds/classic-editor.md, docs/examples/builds/document-editor.md, docs/examples/builds/inline-editor.md, docs/examples/custom/bottom-toolbar-editor.md, docs/examples/framework/content-placeholder.md, docs/examples/framework/data-from-external-source.md, docs/examples/framework/using-react-in-a-widget.md, packages/ckeditor5-mention/docs/examples/chat-with-mentions.md, packages/ckeditor5-theme-lark/docs/_snippets/examples/theme-lark.js, packages/ckeditor5-theme-lark/docs/examples/theme-customization.md
Docs: unifying demos toolbars.
---
_The eighth batch of toolbars. Part of_ cksource/ckeditor5-internal#2797
Based on the "Editor toolbar with few features" setup as described here: [https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed](https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed)
All basic features in the setup are available in the editor builds.
Batch Eight contains the following examples:
*   classic build
*   inline build
*   balloon build
*   balloon block build
*   document build
*   bottom toolbar editor
*   chat with mentions
*   theme customization
*   data from external source
*   react components
*   content placeholder
=> Docs: unifying demos toolbars Batch Eight

docs/_snippets/features/toolbar-breakpoint.js, docs/_snippets/features/toolbar-grouping.js, docs/_snippets/features/toolbar-nested-icon.js, docs/_snippets/features/toolbar-nested-label.js, docs/_snippets/features/toolbar-nested-simple.js, docs/_snippets/features/toolbar-nested-tooltip.js, docs/_snippets/features/toolbar-separator.js, docs/_snippets/features/toolbar-wrapping.js, docs/features/toolbar.md
Docs: comprehensive toolbar guide demo tollbars refactor.
Closes: cksource/ckeditor5-internal#2878
Also closes: https://github.com/cksource/ckeditor5-internal/issues/2797
---
_The fifth batch of toolbars. Part of_ cksource/ckeditor5-internal#2797
Based on the "Editor toolbar with few features" setup as described here: [https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed](https://www.notion.so/WIP-Toolbar-composition-guidelines-5196b3852e70462b98b8023d4d0f6cd7?pvs=4#a78453199acb480ab776e2b9907b1eed)
All basic features in the setup are available in the editor builds (hence underline was removed).
Batch Five contains the following guides:
*   editor toolbar
=> Docs: unifying demos toolbars Batch Five

docs/updating/migration-from-ckeditor-4.md
Docs: Added a CKE4:CKE5 comparison table to the migration guide. Closes cksource/ckeditor5-internal#2968.
---
=> CKE4:CKE5 comparison table in the migration guide

packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector.html
Docs: Prevent showing scroll in mini-inspectors in upcast/downcast guides. Closes #12949.
---
Affected guides:
https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/conversion/downcast.html
https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/conversion/upcast.html
=> Docs: Prevent showing scroll in mini-inspectors in upcast/downcast guides

packages/ckeditor5-mention/src/index.ts
Fix (mention): Mentions should reexport MentionFeed and ItemRenderer.
Closes #13705.
---
=> Mentions should reexport MentionFeed and ItemRenderer

packages/ckeditor5-paste-from-office/src/filters/list.ts, packages/ckeditor5-paste-from-office/tests/filters/list.js
Fix (paste-from-office): Fix handling of bold text in RTL lists pasted from MS Word. Closes #13711.
=> Fix handling of bold text in RTL lists.

packages/ckeditor5-core/src/editor/utils/dataapimixin.ts, packages/ckeditor5-editor-multi-root/src/augmentation.ts, packages/ckeditor5-editor-multi-root/src/index.ts, packages/ckeditor5-editor-multi-root/src/multirooteditor.ts, packages/ckeditor5-editor-multi-root/tests/multirooteditor.js, packages/ckeditor5-engine/src/index.ts, packages/ckeditor5-engine/src/model/differ.ts, packages/ckeditor5-engine/src/model/node.ts, packages/ckeditor5-engine/src/model/operation/rootattributeoperation.ts, packages/ckeditor5-engine/src/model/writer.ts, packages/ckeditor5-engine/tests/model/differ.js, packages/ckeditor5-engine/tests/model/operation/rootattributeoperation.js, packages/ckeditor5-engine/tests/model/writer.js
Other (engine): `RootAttributeOperation` is now correctly handled by `Differ`. Root attribute changes will be returned in `Differ#getChangedRoots()`.
Internal (editor-multi-root): Introduced API to easily save and load root attributes. Introduced `EditorConfig#rootsAttributes` and `MultiRootEditor#getRootsAttributes()`. Closes #13395.
Internal (editor-multi-root): Introduced `MultiRootEditor#getFullData()`. The method returns document data for all roots in multi-root editor.
Internal (editor-multi-root): `MultiRootEditor#addRoot()` has a new option `attributes`.
Internal (engine): `model.Writer#detachRoot()` will now remove attributes from the detached root.
---
Most things as internal because the changes will be in the changelog as "introduced multi-root editor type".
See …
=> Allowed to easily set, change, save and load root attributes

docs/framework/contributing/code-style.md
Docs: Added docs for ESLint rule `ckeditor5-rules/no-build-extensions`.
---
Part of ckeditor/ckeditor5-linters-config#14.
=> Added docs for ESLint rule `ckeditor5-rules/no-build-extensions`.

packages/ckeditor5-enter/package.json, packages/ckeditor5-enter/src/enterobserver.ts, packages/ckeditor5-enter/tests/enterobserver.js
Fix (enter): Pressing <kbd>Shift</kbd>+<kbd>Enter</kbd> in Safari should insert `<br>` instead of splitting block. Closes #13321.
---
=> Pressing Shift+Enter in Safari should fire soft enter event

packages/ckeditor5-source-editing/src/sourceediting.ts, packages/ckeditor5-source-editing/tests/sourceediting.js
Feature (source-editing): Remove the underscore from `_updateEditorData` method name and make it public. Closes #11008.
---
=> Remove underscore from _updateEditorData method name and make it public.

README.md, docs/framework/index.md, docs/installation/getting-started/quick-start-other.md, docs/installation/index.md
Docs: Update CKEditor 5 descriptions to mention that CKEditor 5 is built using TypeScript. Closes cksource/ckeditor5-internal#3036.
=> Update CKEditor 5 descriptions to reflect the fact that now CKEditor 5 is built using TS not ES6

packages/ckeditor5-language/src/textpartlanguageui.ts, packages/ckeditor5-language/tests/manual/textpartlanguage-italic.html, packages/ckeditor5-language/tests/manual/textpartlanguage-italic.js, packages/ckeditor5-language/tests/manual/textpartlanguage-italic.md, packages/ckeditor5-language/theme/language.css
Other (language): TextPartLanguage doesn't style text as italic when language is set. Closes #12672.
MINOR BREAKING CHANGE (language): Text with language set is no longer styled as italic. To re-enable previous behavior, add style `.ck-content span[lang] { font-style: italic;  }` to your css.
---
=> Remove italic style from TextPartLanguage feature.

scripts/docs/snippetadapter.js
Internal: Created a map for snippet adapter that redirects imports of non-existing files from `node_modules/` to the `packages/` directory. Closes #13835.
---
=> Created aliases when building docs

packages/ckeditor5-editor-multi-root/src/multirooteditor.ts, packages/ckeditor5-editor-multi-root/tests/multirooteditor.js
Other: `MultiRootEditor` will first fire all `detachRoot` events and then all `addRoot` events if there are detached and added roots in the same batch.
=> `MultiRootEditor` will first fire all `detachRoot` events and then all `addRoot` events if there are detached and added roots in the same batch

packages/ckeditor5-list/src/listproperties/listpropertiesediting.ts, packages/ckeditor5-list/tests/listproperties/listpropertiesediting.js
Fix (list): `ListPropertiesEditing` should not crash if there was a list in an image caption element. Closes #13858.
=> ListPropertiesEditing should not crash if there was a list in an image caption element

packages/ckeditor5-editor-multi-root/src/multirooteditor.ts, packages/ckeditor5-editor-multi-root/tests/multirooteditor.js
Other (editor-multi-root): Multi-root editor will now throw if `EditorConfig#initialData` is mismatched with initial roots set in `MultiRootEditor#create()`.
=> Multi-root editor will now throw if `EditorConfig#initialData` is mismatched with initial roots set in `MultiRootEditor#create()`

packages/ckeditor5-engine/src/model/markercollection.ts
Type: Doc fix. Closes #000.
---
Did not include a issue due to it being a typo
Related area of docs:
https://github.com/ckeditor/ckeditor5/blob/6325b271765d14ffc3921cd0a012edd2dc423848/packages/ckeditor5-engine/src/model/markercollection.ts#L282
=> docs (engine): Small typo

packages/ckeditor5-engine/src/model/writer.ts, packages/ckeditor5-enter/src/index.ts, packages/ckeditor5-heading/src/headingediting.ts, packages/ckeditor5-html-support/src/converters.ts, packages/ckeditor5-html-support/src/datafilter.ts, packages/ckeditor5-html-support/src/generalhtmlsupport.ts, packages/ckeditor5-html-support/src/integrations/codeblock.ts, packages/ckeditor5-html-support/src/integrations/customelement.ts, packages/ckeditor5-html-support/src/integrations/documentlist.ts, packages/ckeditor5-html-support/src/integrations/heading.ts, packages/ckeditor5-html-support/src/integrations/image.ts, packages/ckeditor5-html-support/src/integrations/mediaembed.ts, packages/ckeditor5-html-support/src/integrations/table.ts, packages/ckeditor5-html-support/src/utils.ts, packages/ckeditor5-html-support/tests/_utils/utils.js, packages/ckeditor5-html-support/tests/integrations/heading.js
Fix (html-support): Remove HTML classes from paragraph created after pressing enter in heading. Closes #11578.
=> Remove HTML classes from paragraph created after pressing enter in heading

packages/ckeditor5-core/src/editor/editorconfig.ts
Fix (core): Add `licenseKey` property to `EditorConfig` interface. Closes #13906.
=> Fix (core): Add `licenseKey` property to `EditorConfig` interface

docs/_snippets/updating/plugins-mapping/plugins-mapping.html, docs/updating/ckeditor4-configuration-compatibility.md
Docs: Updated CKE4 plugin and configuration compatibility tables with templates and format painter. Closes cksource/ckeditor5-internal#3138.
---
_Also:_
*   _Removed WSC from the configuration compatibility table as it's no longer available in CKE4 so the links are invalid._
*   _Added `FullPage` API as an equivalent to CKE4's `fullPage` configuration option._
=> Update CKE4 plugin and configuration compatibility tables after Productivity Pack is released

packages/ckeditor5-engine/src/view/domconverter.ts, packages/ckeditor5-engine/tests/view/domconverter/domconverter.js, packages/ckeditor5-html-support/src/datafilter.ts, packages/ckeditor5-html-support/tests/integrations/customelement.js, packages/ckeditor5-utils/src/dom/isvalidattributename.ts, packages/ckeditor5-utils/src/index.ts, packages/ckeditor5-utils/tests/dom/isvalidattributename.js
Fix (engine): Editor should not crash when a custom element with an invalid attribute name is pasted. Closes #13841.
---
=> GHS should ignore invalid attribute.

docs/umberto.json
Docs: Moved exports and import to a common Document conversion category. Closes cksource/ckeditor5-internal#3104.
---
Another PR is needed to complete this task: https://github.com/cksource/ckeditor5-internal/pull/3176
=> Move exports and import to a common Document conversion category

packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts, packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js
Internal (ui): It should now be possible to select text in the color picker with Ctrl+A.
---
=> Ctrl+A doesn't work in color picker input

scripts/release/isckeditor5package.js
Internal: Added script that checks if a package is CKEditor 5 dependency. See ckeditor/ckeditor5#13953.
---
Part of https://github.com/ckeditor/ckeditor5-dev/pull/871.
=> Added script that checks if a package is CKEditor 5 dependency

packages/ckeditor5-font/src/ui/colortableview.ts, packages/ckeditor5-font/tests/ui/colortableview.js
Internal(ui): Color picker form should accept enter key handling.
Closes [#3177](https://github.com/cksource/ckeditor5-internal/issues/3177).
---
=> Color picker view should handle enter key

packages/ckeditor5-font/tests/integration.js, packages/ckeditor5-font/tests/ui/colorui.js, packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
Internal(font): Fix output format in color picker.
---
The flow causing the bug was as follows:
1.  Color is picked from color picker. It's in `hex` format. Property `color` in color picker is set.
2.  On `color` property change, it's converted to desired output format (HSL by default). This fires another nested `.on( 'change:color' )` call. The first one is on hold - the `_hexColor` property is not updated yet.
3.  The second color change is propagated to `colorTableView` and higher. Formatting in HSL format is set in the model.
4.  Afterwards, the first `color` property change is resumed. It re-triggers the changes in `colorTableView`, but this time with the older value - in `hex` format. It overwrites the previously set model property. In color picker everything seems to be fine - …
=> Fix output color format in color picker

packages/ckeditor5-utils/src/index.ts, packages/ckeditor5-utils/src/version.ts, scripts/release/update-version-references.js
Internal (utils): Added the `releaseDate` property containing the latest CKEditor 5 release date.
=> Release date in CKEditor 5

packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.ts, packages/ckeditor5-find-and-replace/tests/ui/findandreplaceformview.js, packages/ckeditor5-image/src/imageinsert/ui/imageinsertpanelview.ts, packages/ckeditor5-image/tests/imageinsert/ui/imageinsertpanelview.js, packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts, packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js, packages/ckeditor5-media-embed/src/ui/mediaformview.ts, packages/ckeditor5-media-embed/tests/ui/mediaformview.js, packages/ckeditor5-ui/src/dropdown/dropdownpanelview.ts, packages/ckeditor5-ui/tests/dropdown/dropdownpanelview.js
Fix (ui): Select all (Ctrl+A) should now be enabled by default in input field placed in dropdown panel. Closes #13982.
---
The main fix in upstream: https://github.com/ckeditor/ckeditor5/pull/13990
PR in internal: https://github.com/cksource/ckeditor5-internal/pull/3191
PR in cf: https://github.com/cksource/collaboration-features/pull/5224
Please remember to review and merge **all of them**.
=> Better handling of Ctrl+a in input in dropdown views

scripts/release/prepare-packages.js, scripts/release/update-version-references.js
Internal: Added support for updating the release date references in CKEditor 5. Closes #13972.
---
Notes:
- Removed the ability to make a commit. In the new release process a commit will be done at the end.
- Now, this script exports a function to make it possible to use it in the new release process.
=> Added support for updating the release date references in CKEditor 5

packages/ckeditor5-engine/src/conversion/conversion.ts
Fix (engine): TypeScript should suggest `editingDowncast` and `dataDowncast` in `conversion.for`. Closes #13750.
---
Because of the [bug described here](https://github.com/microsoft/TypeScript/issues/54177), I couldn't just add `'dataDowncast' | 'editingDowncast'` to the string union. Instead, we now have three overload signatures:
* One for all predefined downcast group names,
* One for `upcast`,
* A "fallback" signature that accepts any group name, but tries to determine whether it's downcast or upcast based on whether the group name ends with "Downcast" or "Upcast".
=> TypeScript should suggest `editingDowncast` and `dataDowncast` in `conversion.for`

packages/ckeditor5-font/docs/_snippets/features/custom-font-color-and-background-color-options.js, packages/ckeditor5-font/docs/features/font.md
Internal(font): Add color picker feature documentation.
---
I wasn't able to create a link to [http://192.168.100.6:8080/ckeditor5/37.1.0/api/module\_ui\_colorpicker\_utils-ColorPickerConfig.html#member-format](http://192.168.100.6:8080/ckeditor5/37.1.0/api/module_ui_colorpicker_utils-ColorPickerConfig.html#member-format) - ``{@link module:ui/colorpicker/utils~ColorPickerConfig#format `config.fontColor.colorPicker.format`}`` , which seems correct, remained unconverted. Is there any issue with type members link conversion? I didn't manage to find a similar example in docs unfortunately.
=> Color picker documentation

packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
Fix: Opening color picker on firefox throws an error. Closes [#3243](https://github.com/cksource/ckeditor5-internal/issues/3243).
---
=> Opening color picker on firefox throws an error

packages/ckeditor5-ui/src/editorui/poweredby.ts, packages/ckeditor5-ui/tests/editorui/poweredby.js, packages/ckeditor5-ui/tests/manual/poweredby/poweredby.html, packages/ckeditor5-ui/theme/globals/_poweredby.css
Internal (ui): Don't display the "powered by" logo if the editor is short or narrow. Closes https://github.com/cksource/ckeditor5-internal/issues/3217.
---
Requires https://github.com/ckeditor/ckeditor5/pull/14074.
* I got rid of the compact look with "powered by" showing up on `:hover`.
* I restricted min width to 250px and min height to 50px for the logo to show up.
=> Don't display the "powered by" logo if the editor is short or narrow

packages/ckeditor5-ui/src/editorui/poweredby.ts, packages/ckeditor5-ui/tests/editorui/poweredby.js
Internal (ui): Display "Powered by" logo in editor with scrollable parent on Firefox.
Closes cksource/ckeditor5-internal#3256.
---
=> Display "Powered by" logo in editor with scrollable parent on Firefox.

packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
Fix: Color picker does not update or save on iOS. Closes #14109.
---
=> Color picker does not update or save on iOS

packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
Internal (ui): Fix selecting the color through color picker multiple times in Safari. Closes #14119.
---
=> Fix selecting color in color picker in Safari

packages/ckeditor5-ui/src/button/buttonview.ts, packages/ckeditor5-ui/tests/button/buttonview.js
Internal (ui): Buttons in `iOS` should not steal focus after click. Closes #14112.
---
=> Fixed focus handling on buttons in iOS

packages/ckeditor5-html-support/src/integrations/table.ts, packages/ckeditor5-html-support/tests/integrations/table.js, packages/ckeditor5-style/src/integrations/table.ts, packages/ckeditor5-style/src/styleutils.ts, packages/ckeditor5-style/tests/integrations/table.js
Internal (style): Styles for `<thead>` and `<tbody>` should be enabled only for tables that have one. Closes #14113.
Internal (html-support): Attributes for `<thead>` and `<tbody>` should be removed when not relevant for a table. See #14113.
---
=> Styles for `<thead>` and `<tbody>` should be enabled only for tables that have one

packages/ckeditor5-ui/src/editorui/poweredby.ts, packages/ckeditor5-ui/tests/editorui/poweredby.js
Internal (ui): The "powered by" logo should not be accessible using the keyboard or by a screen reader. Closes #14118.
=> The "powered by" logo should not be accessible using the keyboard or by a screen reader

packages/ckeditor5-core/src/editor/editorconfig.ts, packages/ckeditor5-ui/src/editorui/poweredby.ts, packages/ckeditor5-ui/tests/editorui/poweredby.js, packages/ckeditor5-ui/tests/manual/poweredby/poweredby.html, packages/ckeditor5-ui/tests/manual/poweredby/poweredby.js
Internal (ui): The "powered by" label should be configurable. Closes https://github.com/cksource/ckeditor5-internal/issues/3286.
=> The "powered by" label should be configurable.

docs/assets/snippet-styles.css
Internal: Should hide the logo.
---
Source: https://github.com/cksource/ckeditor5-internal/issues/3223#issuecomment-1549360961
=> Logo visibility.

docs/updating/update-to-38.md
Docs: Added a note to the migration guide about a way to disable color pickers in font color and font background color features. Closes https://github.com/cksource/ckeditor5-internal/issues/3273.
---
This PR is built on top of https://github.com/ckeditor/ckeditor5/pull/14105.
=> A note to the migration guide about a way to disable color pickers

docs/support/license-and-legal.md
Docs: Added information about the Free for Open Source to the License guide. Closes https://github.com/cksource/ckeditor5-internal/issues/3295.
=> Add information about the Free for Open Source to the License guide

scripts/release/preparepackages.js, scripts/release/utils/buildckeditor5buildscallback.js
Other: Re-build CKEditor 5 builds after updating references in the new release process. Closes #14177.
---
This PR requires changes from https://github.com/ckeditor/ckeditor5-dev/pull/883.
=> Re-build CKEditor 5 builds after updating references in the new release process

packages/ckeditor5-ui/src/index.ts
Fix (ui): Fixes export of `ColorPaletteIcon` from `ckeditor5-ui`. Closes #14205.
---
=> Fix export ColorPaletteIcon from ckeditor5-ui.

packages/ckeditor5-heading/package.json, packages/ckeditor5-heading/src/title.ts, packages/ckeditor5-heading/tests/title-integration.js, packages/ckeditor5-html-support/package.json, packages/ckeditor5-html-support/src/htmlcomment.ts, packages/ckeditor5-html-support/tests/htmlcomment-integration.js, packages/ckeditor5-table/package.json, packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.ts, packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.ts, packages/ckeditor5-word-count/package.json, packages/ckeditor5-word-count/src/wordcount.ts, packages/ckeditor5-word-count/tests/wordcount.js
Fix: Added multi-root support for: title, HTML comments, table resize, word count and block toolbar.
=> Fix (heading, html-support, minimap, table, ui, word-count): Support multiple roots

packages/ckeditor5-html-support/src/converters.ts, packages/ckeditor5-html-support/src/datafilter.ts, packages/ckeditor5-html-support/src/generalhtmlsupport.ts, packages/ckeditor5-html-support/src/integrations/codeblock.ts, packages/ckeditor5-html-support/src/integrations/customelement.ts, packages/ckeditor5-html-support/src/integrations/dualcontent.ts, packages/ckeditor5-html-support/src/integrations/heading.ts, packages/ckeditor5-html-support/src/integrations/image.ts, packages/ckeditor5-html-support/src/integrations/mediaembed.ts, packages/ckeditor5-html-support/src/integrations/script.ts, packages/ckeditor5-html-support/src/integrations/style.ts, packages/ckeditor5-html-support/src/integrations/table.ts, packages/ckeditor5-html-support/src/utils.ts, packages/ckeditor5-html-support/tests/datafilter.js, packages/ckeditor5-html-support/tests/generalhtmlsupport.js, packages/ckeditor5-html-support/tests/integrations/codeblock.js, packages/ckeditor5-html-support/tests/integrations/customelement.js, packages/ckeditor5-html-support/tests/integrations/documentlist.js, packages/ckeditor5-html-support/tests/integrations/dualcontent.js, packages/ckeditor5-html-support/tests/integrations/heading.js, packages/ckeditor5-html-support/tests/integrations/image.js, packages/ckeditor5-html-support/tests/integrations/mediaembed.js, packages/ckeditor5-html-support/tests/integrations/script.js, packages/ckeditor5-html-support/tests/integrations/style.js, packages/ckeditor5-html-support/tests/integrations/table.js, packages/ckeditor5-style/tests/integrations/table.js, packages/ckeditor5-style/tests/stylecommand.js
MINOR BREAKING CHANGE (html-support): Change `htmlAttributes` to `htmlXAttributes` where `X` represents the name of the view element. See #14216.
=> Change `htmlAttributes` to `htmlXAttributes`

packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
Docs: Fix info box text in the Simple upload adapter guide. Closes https://github.com/ckeditor/ckeditor5/issues/14172
=> Fix info box text in the Simple upload adapter guide

docs/installation/integrations/angular.md
Docs: Fix the misleading link in the Angular guide. Closes https://github.com/ckeditor/ckeditor5/issues/14100.
---
=> Docs: Fix the misleading link in the Angular guide.

packages/ckeditor5-engine/src/conversion/upcasthelpers.ts, packages/ckeditor5-heading/src/headingediting.ts, packages/ckeditor5-html-support/src/datafilter.ts, packages/ckeditor5-html-support/src/dataschema.ts, packages/ckeditor5-html-support/src/htmlcomment.ts, packages/ckeditor5-html-support/src/integrations/dualcontent.ts, packages/ckeditor5-html-support/src/integrations/heading.ts, packages/ckeditor5-html-support/src/integrations/image.ts, packages/ckeditor5-html-support/src/integrations/script.ts, packages/ckeditor5-html-support/src/integrations/style.ts, packages/ckeditor5-html-support/src/integrations/table.ts, packages/ckeditor5-html-support/src/schemadefinitions.ts, packages/ckeditor5-html-support/tests/integrations/documentlist.js, packages/ckeditor5-html-support/tests/integrations/heading.js
Feature (html-support): Remove unrelated `html*Attributes` from elements. See #14216.
=> Remove unrelated `html*Attributes` from elements

packages/ckeditor5-html-support/src/integrations/documentlist.ts, packages/ckeditor5-html-support/src/schemadefinitions.ts, packages/ckeditor5-html-support/tests/generalhtmlsupport.js, packages/ckeditor5-html-support/tests/integrations/documentlist.js, packages/ckeditor5-style/tests/integrations/documentlist.js
Feature (html-support): Changing list type removes styles from the old type. Closes #14216.
=> Change `htmlListAttributes` to `htmlUlAttributes` or  `htmlOlAttributes` depending on the list type

packages/ckeditor5-engine/src/view/styles/utils.ts, packages/ckeditor5-engine/tests/view/styles/border.js, packages/ckeditor5-engine/tests/view/styles/utils.js, packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesediting.js
Fix (engine): The CSS shorthand value normalizer should work for values with white spaces. Closes #14309.
---
* FYI: Performance comparison https://jsperf.app/firamo (quite a surprise to me).
* This is a dependency of https://github.com/cksource/ckeditor5-internal/issues/2978.
=> The CSS shorthand value normalizer should work for values with white spaces

docs/framework/contributing/code-style.md
Internal: Backport docs for new eslint rules to `stable` branch. See #13434 and #14091.
---
⚠️ Merge only after these PRs are merged, released and used in this repository: https://github.com/ckeditor/ckeditor5-linters-config/pull/16, https://github.com/ckeditor/ckeditor5-linters-config/pull/18 and https://github.com/ckeditor/ckeditor5-linters-config/pull/22 ⚠️
=> Backport docs for new eslint rules to `stable` branch

packages/ckeditor5-paste-from-office/src/index.ts, packages/ckeditor5-paste-from-office/src/pastefromoffice.ts, packages/ckeditor5-paste-from-office/tests/_utils/fixtures.js, packages/ckeditor5-paste-from-office/tests/_utils/utils.js, packages/ckeditor5-paste-from-office/tests/data/integration.js, packages/ckeditor5-paste-from-office/tests/data/normalization.js, packages/ckeditor5-paste-from-office/tests/pastefromoffice.js
Internal (paste-from-office): Made the PFO testing framework open. Also, the feature should be able to work on already parsed `inputTransformation` data. Closes https://github.com/ckeditor/ckeditor5/issues/14377.
---
Required by https://github.com/cksource/ckeditor5-internal/pull/3366.
=> Made the PFO testing framework open

packages/ckeditor5-table/theme/table.css, packages/ckeditor5-table/theme/tablecolumnresize.css
Fix (table): Text will no longer go beyond its cell when columns are resized by resize handler in Firefox. Closes [#14386](https://github.com/ckeditor/ckeditor5/issues/14386).
Fix (export-pdf): Text will no longer go beyond its cell when columns are resized by resize handler in exported PDFs. Closes [#3355](https://github.com/cksource/ckeditor5-internal/issues/3355).
---
=> Discovery: Export to PDF: text goes beyond its cell when columns are resized by resize handler

packages/ckeditor5-font/src/ui/colortableview.ts, packages/ckeditor5-font/tests/ui/colortableview.js
Fix (font): The accept button in the color picker will no longer submit forms . Closes #14361.
---
=> Replacing type from 'submit' to 'button'

packages/ckeditor5-engine/src/view/observer/inputobserver.ts, packages/ckeditor5-engine/tests/view/observer/inputobserver.js
Fix (engine): The editor should not crash while pressing backspace in an empty editor (in Firefox). Closes #14411. Closes #14050.
---
=> Fixed beforeInput target ranges that start before the editable element.

packages/ckeditor5-html-support/src/index.ts, packages/ckeditor5-style/src/styleutils.ts, packages/ckeditor5-style/tests/manual/styledropdown.html, packages/ckeditor5-style/tests/manual/styledropdown.js, packages/ckeditor5-style/tests/stylecommand.js
Fix (style): Styles dropdown should allow styling `<div>` elements. Closes #13341.
---
=> Styles dropdown should apply to DIV elements.

packages/ckeditor5-html-support/src/schemadefinitions.ts, packages/ckeditor5-html-support/tests/integrations/customelement.js, packages/ckeditor5-html-support/tests/tickets/13803.js
Fix (html-support): GHS should allow linking of custom elements. Closes #13803 .
---
We took the simplest approach. Enabled only linking of custom elements (in GHS). This will work only with full content enabled in GHS. In the future, we should modify how inline object elements (like `<button>`, `<video>`, etc) are handled in GHS. It should not use `registerRawContentMatcher()` because it blocks integration with other features (for picture element it would break `PictureEditing`, for `<button>` it breaks custom features using button element (https://github.com/ckeditor/ckeditor5/issues/13268).
=> GHS should allow linking custom elements.

packages/ckeditor5-show-blocks/theme/showblocks.css
Internal (show-blocks): Increase the specificity of the show blocks feature styling. Closes #14435.
---
The selector proposed in [https://github.com/ckeditor/ckeditor5/issues/14435#issuecomment-1602159551](https://github.com/ckeditor/ckeditor5/issues/14435#issuecomment-1602159551) (`.ck.ck-editor__editable.ck-editor__editable_inline.ck-show-blocks[dir=ltr] p` with specificity \[ 0 5 1 \]) turned out to be to weak for our docs as it depends on the order of stylesheets loading. Therefore I decided to add one more condition (`:not(.ck-widget)`) which we should be safe with (at least until we support the feature for widgets) and it bumps the score to \[ 0 6 1 \]. Also, I added explicit styles for both LTR and RTL editors to keep the specificity equal in both cases.
=> Add more classes and attributes for selectors.

packages/ckeditor5-ui/package.json, packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.ts, packages/ckeditor5-ui/tests/toolbar/block/blocktoolbar.js, packages/ckeditor5-utils/src/dom/resizeobserver.ts, packages/ckeditor5-utils/tests/dom/resizeobserver.js
Internal (ui): Set up block toolbar resize mechanism on given editable after the toolbar button is attached to it, instead of when editor is initialized. Closes #14445.
=> Set up block toolbar resize mechanism on given editable after the toolbar button is attached to it, instead of when editor is initialized

packages/ckeditor5-engine/src/conversion/downcasthelpers.ts
Docs: fix the typo in the `slotFor` \[skip ci\]. Closes #14438.
=> Docs: fix slotFor typo.

packages/ckeditor5-engine/src/conversion/downcasthelpers.ts
Docs: replace the wrong function name in the comment. Closes #14438.
=> Docs: fix wrong function name.

.eslintrc.js
Internal: Excluded some ESLint rules from both JavaScript and TypeScript tests. See #14451.
=> Exclude some eslint rules from both JS and TS tests

scripts/release/preparepackages.js
Internal: Used default `AbortSignal` in tasks during the release process.
This PR requires changes from https://github.com/ckeditor/ckeditor5-dev/pull/894.
=> Release tools: Used default `AbortSignal` in tasks during the release process

packages/ckeditor5-font/tests/integration.js, packages/ckeditor5-table/tests/utils/ui/table-properties.js, packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts, packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js
Internal (ui): The color picker view should not throw if focusing the component in FF/Safari/iOS but the color input is not available. Closes https://github.com/ckeditor/ckeditor5/issues/14462. Closes https://github.com/ckeditor/ckeditor5/issues/14468.
=> The color picker view should not throw if focusing the component in FF/Safari/iOS but the color input is not available

scripts/release/utils/isckeditor5packagefactory.js
Internal: Fixed release tools script that checks whether a package is a CKEditor 5 dependency by limiting the search scope to predefined paths only. Closes #14513.
---
The CS Client path is not needed because it is not considered as a CKEditor 5 dependency anyway.
=> Fixed script that checks whether a package is a CKEditor 5 dependency

docs/_snippets/examples/bottom-toolbar-editor.js, packages/ckeditor5-ui/src/dropdown/utils.ts, packages/ckeditor5-ui/tests/dropdown/utils.js, packages/ckeditor5-utils/src/focustracker.ts
Feature (ui): Dropdowns will stay open after clicking on an HTML element added to the dropdown's focus tracker.
=> Additional configuration for context elements in dropdown

packages/ckeditor5-paragraph/src/insertparagraphcommand.ts, packages/ckeditor5-paragraph/tests/insertparagraphcommand.js, packages/ckeditor5-widget/tests/widgettypearound/widgettypearound.js
Fix (paragraph): "insertParagraph" command doesn't insert two paragraphs when position is at the edge of the line. Closes [#13866](https://github.com/ckeditor/ckeditor5/issues/13866).
---
=> insertParagraph command creates additional empty paragraph when used at the end of block element

docs/installation/integrations/angular.md
Docs: Added documentation in Angular guide that `ckeditor5-angular` package requires peer dependencies. See ckeditor/ckeditor5-angular#376.
---
=> Documentation in Angular guide about peer dependencies

packages/ckeditor5-engine/src/conversion/downcasthelpers.ts
markerToData missing comma in json object
---
Documentation did contain invalid json. I fixed it
=> Fix documentation

packages/ckeditor5-engine/src/index.ts, packages/ckeditor5-image/src/imageupload/imageuploadediting.ts, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js
Task (image): The image width should not be changed after uploading if the width or height was previously set. Closes #14531.
---
=> Keep image sizes after image upload

packages/ckeditor5-engine/src/view/domconverter.ts, packages/ckeditor5-engine/src/view/view.ts, packages/ckeditor5-engine/tests/view/domconverter/domconverter.js, packages/ckeditor5-engine/tests/view/view/view.js
Fix (engine): The DOM selection should not obscure the clickability of dropdown items on iOS. Closes #5753.
---
=> Clearing DOM selection on editable blur on iOS.

packages/ckeditor5-image/src/imageresize/imageresizehandles.ts, packages/ckeditor5-image/src/imagesizeattributes.ts, packages/ckeditor5-image/src/imageutils.ts, packages/ckeditor5-image/tests/imagesizeattributes.js
Task (image): Image width and height should be set on image change (resize, alignment, etc.). Closes #14557.
---
=> Set image width and height on image change

packages/ckeditor5-ui/src/panel/sticky/stickypanelview.ts, packages/ckeditor5-ui/tests/panel/sticky/stickypanelview.js
Fix(ui): Sticky panel will no longer log a warning to the console on initialisation. Closes #14582.
---
This change [https://github.com/ckeditor/ckeditor5/blob/0634ea16bb1429688ee1aa27c62f17ab9837ca36/packages/ckeditor5-ui/src/panel/sticky/stickypanelview.ts#L184](https://github.com/ckeditor/ckeditor5/blob/0634ea16bb1429688ee1aa27c62f17ab9837ca36/packages/ckeditor5-ui/src/panel/sticky/stickypanelview.ts#L184) was necessary to keep the tests passing.
=> Prevent throwing the warning by sticky panel

packages/ckeditor5-utils/src/dom/scroll.ts, packages/ckeditor5-utils/tests/dom/scroll.js
Feature(utils): Made the `scrollAncestorsToShowRect()` function take the limiter element, which will stop it from scrolling further ancestors. Closes #14598.
---
The code coverage was essentially provided in `scrollAncestorsToShowTarget()` function tests.
=> Make the `scrollAncestorsToShowRect()` function take the limiter element

packages/ckeditor5-paste-from-office/src/filters/table.ts, packages/ckeditor5-paste-from-office/src/normalizers/mswordnormalizer.ts, packages/ckeditor5-paste-from-office/tests/_data/table/tablecellproperties/model.html, packages/ckeditor5-paste-from-office/tests/filters/table.js
Fix (paste from word): CKE5 properly reflects table alignments from Microsoft Word . Closes #8752.
---
=> CKE5 properly reflects table alignments from Microsoft Word 

packages/ckeditor5-utils/src/observablemixin.ts
Internal (typescript): Extending the `SingleBindChain#to` method with new parameters.
---
Before this change, we could bind only 4 variables. This PR extends it to 5, however, it should be done in a more generic way.
=> Extending the SingleBindChain#to method with new parameters

scripts/ci/check-packages-code-coverage.js, scripts/ci/travis-check.js
Internal: CI: Added the `skipCompilingFramework` flag for the testing script to avoid compiling the CKEditor 5 framework twice when executing the same command in different scenarios.
See cksource/collaboration-features#5338.
---
=> CI: Added the "skipCompilingFramework" flag for testing script

scripts/docs/get-latest-changelogs.js
Internal: The release highlights section will no longer be removed from the documentation changelog if it has no URL to a blog post.
Internal: Blogpost URL in the release highlights section will now be a functional link instead of raw text.
---
=> Fixed empty changelog

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/editorui/editorui.css
Fix (theme-lark): Adjusted the balloon tip color to match the rest of the panel. Closes #14652.
---
=> Adjust the balloon tip color

packages/ckeditor5-image/src/imagesizeattributes.ts, packages/ckeditor5-image/tests/imagesizeattributes.js
Fix (image): Pictures with images of different proportions should be displayed correctly. Closes #14579.
---
=> Properly handle pictures with images of different proportions

packages/ckeditor5-typing/src/input.ts, packages/ckeditor5-typing/tests/input.js
Fix (typing): The editor should scroll to the selection after inserting the text. Closes #13411.
---
=> Editor should scroll to the selection after inserting text.

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/dropdown.css, packages/ckeditor5-ui/src/dropdown/dropdownpanelview.ts, packages/ckeditor5-ui/tests/dropdown/dropdownpanelview.js
Fix (ui): Dropdown view should not be closed when interacting with a scrollbar. Closes #14364.
---
=> Prevent closing dropdown view on scrollbar click.

docs/updating/update-to-39.md, docs/updating/updating-ckeditor-5.md
Docs (updating): migration guide for changed placeholder API. Closes #14675.
---
=> Migration guide for changed placeholder API

packages/ckeditor5-paragraph/src/insertparagraphcommand.ts, packages/ckeditor5-paragraph/tests/insertparagraphcommand.js
Fix (paragraph): Fixed inserting paragraph after/before a widget inside a table cell. Closes #14714.
---
=> Fixed inserting paragraph after a widget inside a table cell.

packages/ckeditor5-html-support/src/integrations/image.ts, packages/ckeditor5-html-support/tests/integrations/image.js
Fix (html-support): Link on image should not be lost when loading content with LinkImage and full GHS enabled. Closes #12831.
---
=> Link on image should not be lost with LinkImage and full GHS.

scripts/release/preparepackages.js
Internal: Disabled commiting on nightly release. See ckeditor/ckeditor5#14728.
=> Disabled commiting on nightly release

packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js, packages/ckeditor5-table/theme/tablecolumnresize.css
Fix (table): fix scrolling bug when headings are in the table. Closes [#3489](https://github.com/cksource/ckeditor5-internal/issues/3489).
---
=> Fix (table): fix scrolling bug when headings are in the table

packages/ckeditor5-engine/src/view/observer/mutationobserver.ts, packages/ckeditor5-utils/src/dom/getelementsintersectionrect.ts, packages/ckeditor5-utils/src/version.ts, tsconfig.json
Fix: Don't rely on `global` object available only in Node. Fixes https://github.com/ckeditor/vite-plugin-ckeditor5/issues/17 and #14801.
Internal: Load only specified typings for TypeScript. Closes #14173.
=> fix: load only specified typings for TypeScript

docs/umberto.json
Internal: Enabled Google Analytics v4 in the nightly documentation. 
---
- Closes cksource/ckeditor5-internal#3579.
- Requires: https://github.com/cksource/umberto/pull/1169.
---
=> Google Analytics v4

.github/workflows/stale.yml
Add config for the stale action. Closes https://github.com/cksource/ckeditor5-internal/issues/3552.
---
=> Add config for the stale action.

.github/workflows/stale.yml
Internal: Lowered the timeframe to 2 years and fixed the list of labels to exclude.
---
From what I can see the exempt-issue-labels option requires an exact match. I may be wrong (I didn't dig super deep), but it doesn't hurt us to have those labels listed explicitly.
=> Lowered the timeframe to 2 years and fixed the list of labels to exclude

.circleci/template.yml, scripts/ci/generate-circleci-configuration.js, scripts/ci/is-community-pr.js
Internal: CircleCI: Improved detecting a community PR.
---
- Extracted the common logic to a command. Thanks @przemyslaw-zan, for the tip (cke5-inspector).
- Simplified the `is-community-pr.js` script by removing the `process.exit()` parts.
- Thanks to simplifying the PR community detection logic, it can be executed before bootstrapping the project to speed up a job.
- ~First commit contains enabled the coverage build for the `ci/improve-community-pr-detection` to see what happens if I create a PR from a forked repository.~ Creating a PR to a feature branch does not trigger CI anymore.
=> CircleCI: Improved detecting a community PR

packages/ckeditor5-utils/src/keyboard.ts, packages/ckeditor5-utils/tests/keyboard.js
Fix (utils): Wrong tooltip when hovering toolbar buttons on Chrome on iOS. Closes #13812.
---
=> Wrong tooltip when hovering toolbar buttons on Chrome on iOS

docs/framework/contributing/development-environment.md, docs/framework/quick-start.md, docs/installation/getting-started/quick-start-other.md, docs/installation/plugins/installing-plugins.md, package.json, scripts/ci/trigger-ckeditor5-continuous-integration.js
Other: Updated the required version of Node.js to 18 for the development environment. See #14924.
=> Node version bump

packages/ckeditor5-utils/src/dom/rect.ts, packages/ckeditor5-utils/tests/dom/position.js
Fix(utils): Should correct calculate coordinates to element in refer to target element in any situations. Closes #14992 .
---
=> Fix for shifting Rect with deep level of scrollable positioned ancestors.

packages/ckeditor5-clipboard/src/dragdropexperimental.ts, packages/ckeditor5-clipboard/tests/dragdropexperimental.js
Fix (clipboard): improve displaying preview in "drag and drop". Closes #14968.
---
=> Preview logic requires tweaking

packages/ckeditor5-image/src/imageupload/imageuploadediting.ts, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js
Fix (image): Image should not be replaced when dropped below a widget.
Closes #14710.
Closes #14740.
---
=> Don't replace the image if dropped below

packages/ckeditor5-ui/src/search/searchresultsview.ts, packages/ckeditor5-ui/src/search/text/searchtextview.ts, packages/ckeditor5-ui/tests/search/searchresultsview.js, packages/ckeditor5-ui/tests/search/text/searchtextview.js
Internal (ui): Manual scrolling of `SearchResultsView` should not blur the whole search component. 
Made the `SearchResultsView` focusable. `SearchTextView` should focus the `#resultsView` instead of `#filteredView` upon focus().
=> Manual scrolling of SearchResultsView should not blur the whole search component.

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/textarea/textarea.css, packages/ckeditor5-ui/src/textarea/textareaview.ts, packages/ckeditor5-ui/theme/components/textarea/textarea.css
Internal (theme-lark): `TextareaView` should have the right height if `#minRows` is 1 and the content is empty in FF.
=> TextareaView should have the right height in FF

scripts/clean-up-svg-icons.js
Other: Added support to execute `yarn run clean-up-svg-icons` script without arguments to optimize all icons in the entire project. Closes #14912.
=> Added support to execute `yarn run clean-up-svg-icons` script without arguments to optimize the entire project

packages/ckeditor5-table/src/tablecellproperties/ui/tablecellpropertiesview.ts, packages/ckeditor5-table/src/tableproperties/ui/tablepropertiesview.ts, packages/ckeditor5-table/src/ui/colorinputview.ts, packages/ckeditor5-table/tests/tablecellproperties/ui/tablecellpropertiesview.js, packages/ckeditor5-table/tests/tableproperties/ui/tablepropertiesview.js, packages/ckeditor5-table/tests/ui/colorinputview.js, packages/ckeditor5-ui/src/focuscycler.ts, packages/ckeditor5-ui/src/index.ts, packages/ckeditor5-ui/src/labeledfield/labeledfieldview.ts, packages/ckeditor5-ui/src/list/listview.ts, packages/ckeditor5-ui/src/search/filteredview.ts, packages/ckeditor5-ui/src/search/searchinfoview.ts, packages/ckeditor5-ui/src/search/searchresultsview.ts, packages/ckeditor5-ui/src/search/text/searchtextview.ts, packages/ckeditor5-ui/tests/focuscycler.js, packages/ckeditor5-ui/tests/labeledfield/labeledfieldview.js, packages/ckeditor5-ui/tests/list/listview.js, packages/ckeditor5-ui/tests/search/searchinfoview.js, packages/ckeditor5-ui/tests/search/searchresultsview.js, packages/ckeditor5-ui/tests/search/text/searchtextview.js
Feature (ui): Implemented `FocusCycler#forwardCycle` and `#backwardCycle` events.
Internal (ui): Made `SearchResultsView` a focus-friendly container. Made `SearchInfoView` focusable.
=> Implemented `FocusCycler#forwardCycle` and `#backwardCycle` events

packages/ckeditor5-core/lang/contexts.json
Internal (core, template): Moved a translation context from `ckeditor5-template` to `ckeditor5-core` to make it shareable.
---
Needed by https://github.com/cksource/ckeditor5-commercial/pull/5524.
=> Moved a translation context from `ckeditor5-template` to `ckeditor5-core`

docs/examples/builds/balloon-block-editor.md, packages/ckeditor5-clipboard/docs/features/drag-drop.md, packages/ckeditor5-ui/docs/features/blocktoolbar.md
Docs: Changes to the drag and drop behavior in guides. Closes https://github.com/ckeditor/ckeditor5/issues/15074
---
=> Docs: Changes to the drag and drop behavior in guides.

packages/ckeditor5-image/src/image/imageblockediting.ts, packages/ckeditor5-image/src/image/imageinlineediting.ts, packages/ckeditor5-image/tests/image/imageblockediting.js, packages/ckeditor5-image/tests/image/imageinlineediting.js
Internal (image): Image `width` and `height` attributes should be added when pasting a copied image. Closes #15088.
---
=> Add image width and height on image paste

packages/ckeditor5-list/ckeditor5-metadata.json
Internal (list): Added metadata for to-do document lists. Closes #15107.
---
=> Added metadata for to-do document lists

packages/ckeditor5-image/theme/image.css
Internal (image): A floating image should be clickable when next to a to-do document list. Closes #15115.
---
=> Fixed z-index of floating images next to a document list.

packages/ckeditor5-clipboard/src/dragdrop.ts, packages/ckeditor5-clipboard/tests/dragdropblocktoolbar.js
Fix (clipboard): Drag and drop preview should not have black background on iOS. Closes #15085.
---
=> Drag-and-drop preview is blackened when using the block balloon.

packages/ckeditor5-clipboard/src/dragdrop.ts, packages/ckeditor5-clipboard/src/dragdroptarget.ts, packages/ckeditor5-clipboard/tests/dragdroptarget.js
Fix (clipboard): Fixed dragging from and into a container without other elements. Closes #15087.
---
=> Fixed dragging from and into container without other elements.

packages/ckeditor5-ui/src/textarea/textareaview.ts, packages/ckeditor5-ui/tests/textarea/textareaview.js
Fix (ui): Textarea will no longer update the height when the element has been removed from DOM. It fixes the warnings thrown in the console.
---
=> Handling textarea auto resize warnings

packages/ckeditor5-ui/src/dropdown/dropdownview.ts, packages/ckeditor5-ui/tests/dropdown/dropdownview.js
Internal (ui): The dropdown panel view's `#isVisible` property should be bound to the parent before rendering to allow other listeners' callbacks act when the panel is already visible.
---
**Backstory**: The AI assistant UI plugin creates the commands dropdown and brings some `dropdownView.on( 'change:isOpen', .. )` behavior while registering in the component factory. I couldn't get my head around the fact that when `isOpen` changes to `true`, the panel is not visible in DOM yet, though. My intuition says that any listener attached (with normal priority) after the component has been created (`DropdownView#constructor()`) should execute after default component behaviors, such as displaying the panel as soon as `isOpen` is `true`. To my surprise, the binding was set in …
=> The dropdown panel view's `#isVisible` property should be bound earlier

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/formheader/formheader.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/labeledfield/labeledfieldview.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/list/list.css, packages/ckeditor5-ui/theme/components/button/button.css, packages/ckeditor5-ui/theme/components/formheader/formheader.css
Other (ui, theme-lark): Improved layout of `FormHeaderView`, `ButtonView`, and `ListItemView` components in RTL UI.
---
* What surprised me a lot was that we didn't have proper support for text (content) alignment in lists and buttons. I brought it in this PR. [See it for yourself](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#demo-2).
* A piece of https://github.com/cksource/ckeditor5-commercial/pull/5594.
* See https://github.com/cksource/ckeditor5-commercial/issues/5593.
=> RTL layout improvements to UI components

packages/ckeditor5-table/src/tablecaption/toggletablecaptioncommand.ts, packages/ckeditor5-table/src/tablecaption/utils.ts, packages/ckeditor5-table/src/tableproperties/commands/tablepropertycommand.ts, packages/ckeditor5-table/src/tableproperties/tablepropertiesui.ts, packages/ckeditor5-table/src/utils/common.ts, packages/ckeditor5-table/src/utils/ui/contextualballoon.ts, packages/ckeditor5-table/src/utils/ui/widget.ts, packages/ckeditor5-table/tests/tablecaption/utils.js, packages/ckeditor5-table/tests/tableproperties/commands/tablealignmentcommand.js, packages/ckeditor5-table/tests/tableproperties/commands/tablebackgroundcolorcommand.js, packages/ckeditor5-table/tests/tableproperties/commands/tablebordercolorcommand.js, packages/ckeditor5-table/tests/tableproperties/commands/tableborderstylecommand.js, packages/ckeditor5-table/tests/tableproperties/commands/tableborderwidthcommand.js, packages/ckeditor5-table/tests/tableproperties/commands/tableheightcommand.js, packages/ckeditor5-table/tests/tableproperties/commands/tablewidthcommand.js, packages/ckeditor5-table/tests/tableproperties/tablepropertiesui.js, packages/ckeditor5-table/tests/utils/common.js, packages/ckeditor5-table/tests/utils/ui/contextualballoon.js
Fix (table): Table properties should be enabled if a table is selected from the outside. Closes #15040. Closes #15041. Closes #10983.
---
=> Table properties should be enabled if table is selected from the outside

packages/ckeditor5-core/src/editor/utils/elementapimixin.ts, packages/ckeditor5-core/tests/editor/utils/elementapimixin.js
Other(core): Should stop calling function `data.get()` when it's not needed while destroying the editor instance. Closes #15009 .
---
=> Stop calling function `data.get()` when it's not needed while destroying the editor instance.

scripts/release/publishpackages.js
Internal: Verify if packages define an entry point before publishing a new release. See ckeditor/ckeditor5#15127.
- Requires: https://github.com/ckeditor/ckeditor5-dev/pull/926.
=> Release - verify an entry point before publishing

packages/ckeditor5-image/src/imagesizeattributes.ts, packages/ckeditor5-image/tests/imagesizeattributes.js
Fix (image): Aspect ratio should be updated on image replace. Closes #15179.
---
=> Update aspect-ratio on image replace

.circleci/template.yml, scripts/clean-up-svg-icons.js
Other: Added support for the `--verify-only` flag in the `yarn run clean-up-svg-icons` script that checks if all SVG files are optimized.
Internal: Added SVG files validator on CI. Closes #15142.
---
Currently all SVG files are optimized.
If we remove files added to exceptions, the `yarn clean-up-svg-icons --verify-only "packages/ckeditor5-ui/theme/**"` command will return the following results:
=> Added support for verifying if all SVG files are optimized and enabled validator on CI

docs/installation/integrations/angular.md
Docs: Update angular error event documentation
---
Since [this issue](https://github.com/ckeditor/ckeditor5-angular/issues/392)  ([PR](https://github.com/ckeditor/ckeditor5-angular/pull/390)) initialization errors are included in this event.
This updates the documentation to reflect that.
=> angular.md: update error event text (include init errors)

packages/ckeditor5-clipboard/src/utils/plaintexttohtml.ts, packages/ckeditor5-clipboard/tests/pasting-integration.js, packages/ckeditor5-clipboard/tests/utils/plaintexttohtml.js
Fix (clipboard): Pasting a link address should not convert its parts that look like HTML entities. Closes #15036.
---
To reproduce the issue:
1. Create (or use the below one) HTML link that contains HTML entity (like `&times`, `&para`, `&quot` etc.) in its href, e.g. https://example.com?x=1&quot=2&timestamp=t
2. Right-click the link and choose the **Copy Link Address** option.
3. Paste into the editor.
Without this fix, the parts `&quot` and `&times` are replaced with corresponding characters.
=> Encode the ampersand character when pasting link address

packages/ckeditor5-html-support/package.json, packages/ckeditor5-html-support/src/schemadefinitions.ts, packages/ckeditor5-html-support/tests/tickets/14683.js
Fix (html-support): Additional attributes for the link element (e.g. CSS class) should not be applied after pressing Enter. Closes #14683.
---
=> Additional attributes for link element should not be copied on enter.

docs/installation/getting-started/predefined-builds.md
Docs: adding the `essentials` package contents to the predefined builds plugins list. Closes https://github.com/ckeditor/ckeditor5/issues/15237
---
=> Docs: adding essentials package contents to predefined builds plugins list

packages/ckeditor5-ckbox/tests/ckboxcommand.js, packages/ckeditor5-image/docs/features/images-installation.md, packages/ckeditor5-image/docs/features/images-overview.md, packages/ckeditor5-image/src/imageconfig.ts, packages/ckeditor5-image/src/imageutils.ts, packages/ckeditor5-image/tests/autoimage.js, packages/ckeditor5-image/tests/image/insertimagecommand.js, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js, packages/ckeditor5-image/tests/imageupload/imageuploadprogress.js, packages/ckeditor5-image/tests/imageupload/imageuploadui.js, packages/ckeditor5-image/tests/imageupload/uploadimagecommand.js, packages/ckeditor5-image/tests/imageutils.js, packages/ckeditor5-image/tests/manual/imageinsert.html, packages/ckeditor5-image/tests/manual/imageinsert.js, packages/ckeditor5-image/tests/pictureediting.js, packages/ckeditor5-list/tests/documentlist/integrations/insertcontent.js
Other (image): Changes default `image.insert.type` configuration to `"block"` and adds `"auto"` option. Closes #15158.
MINOR BREAKING CHANGE (image): By default images are inserted as block images (not inline). To switch to previous behavior (determining image type by insertion context), set the editor config `image.insert.type` to `"auto"`.
---
=> Change default image.insert.type configuration to "block"

docs/updating/update-to-40.md
Docs: Added HTML markups to show changes in images in the migration guide to v40. Closes #15010.
---
=> Add HTML markups for changes in images to migration guide to v40.

packages/ckeditor5-table/lang/translations/fi.po
In Finnish, there are two separate words for caption in table-context and for caption in tv subtitle-context. Currently this  "Enter table caption" translation is saying "Take table subtitles in use" which is nonsensical.
This translation fix changes the caption translations to make more sense in Finnish. Source: It's my native language.
There are many Finnish public sector websites that are using Drupal and as such CKEditor on their platform. I'm currently working on the Finnish capital (Helsinki) website and came across this problem. We'd appreciate very much if this could be fixed. :)
I tried to add this via transifex, but I do not have time to wait for approval process and bureaucracy for this simple fix I wanted to upstream. I might be able to add these changes at a later date if I'm …
=> Fix Finnish translation for table caption

packages/ckeditor5-editor-multi-root/src/multirooteditor.ts, packages/ckeditor5-editor-multi-root/tests/multirooteditor.js, packages/ckeditor5-engine/tests/model/schema.js
Feature (editor-multi-root): Added `MultiRootEditor#registerRootAttribute()`. All roots attributes used by features should now be registered. Roots attributes passed in editor config are now automatically registered. Closes #15246.
MINOR BREAKING CHANGE (editor-multi-root): If you use a custom plugin that uses roots attributes, it is recommended to use newly added `MultiRootEditor#registerRootAttribute()` to register the custom root attribute.
=> Added `MultiRootEditor#registerRootAttribute()`

packages/ckeditor5-ckbox/lang/contexts.json, packages/ckeditor5-ckbox/package.json, packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditcommand.ts, packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditediting.ts, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js, packages/ckeditor5-ckbox/tests/manual/ckbox.js
Fix (ckbox): Should not allow leave page in case edited image is processed on server . Closes [#5700](https://github.com/cksource/ckeditor5-commercial/issues/5700).
---
=> Add pending action when image is being processed

packages/ckeditor5-ckbox/package.json, packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditcommand.ts, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js
Fix (ckbox): Image caption should stay after image editing. Closes [#5686](https://github.com/cksource/ckeditor5-commercial/issues/5686).
---
=> Image caption should stay after image editing

packages/ckeditor5-find-and-replace/src/findandreplaceui.ts, packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.ts, packages/ckeditor5-media-embed/src/mediaembedui.ts, packages/ckeditor5-special-characters/src/specialcharacters.ts, packages/ckeditor5-special-characters/src/ui/specialcharactersview.ts, packages/ckeditor5-ui/src/dialog/dialogactionsview.ts, packages/ckeditor5-ui/src/dialog/dialogview.ts, packages/ckeditor5-ui/src/focuscycler.ts, packages/ckeditor5-ui/src/index.ts
Internal (ui): Made focus cycling in various dialogs easier by moving the generic integration code to the DialogView class.
=> Simplified focus cycling in dialogs

packages/ckeditor5-media-embed/src/mediaembedediting.ts, packages/ckeditor5-media-embed/tests/mediaembedediting.js
Feature: Add support for short Dailymotion URLs (`dai.ly`) in media-embed. 
---
Short Dailymotion URLs can be found in you share the video through the dedicated sharing button:
Example: https://www.dailymotion.com/video/x8ks8y1
=> Add support for dai.ly urls in MediaEmbedEditing

packages/ckeditor5-editor-classic/src/classiceditorui.ts, packages/ckeditor5-find-and-replace/src/findandreplaceui.ts, packages/ckeditor5-ui/src/dialog/dialog.ts, packages/ckeditor5-ui/src/dialog/dialogactionsview.ts, packages/ckeditor5-ui/src/dialog/dialogview.ts, packages/ckeditor5-ui/src/toolbar/toolbarview.ts, packages/ckeditor5-ui/tests/manual/dialog/dialog.ts
*   Allow only one dialog instance across all the editor instances (opening a dialog in another editor closes and destroys the old one).
*   Introduce `isOn` state for the buttons using the dialog.
*   Destroy and recreate the `DialogView` instead of resetting it.
*  But make sure the integrator's view is not destroyed in the process and can be re-used next time the dialog shows up.
* Ensured the correct part of the dialog gets focused when the dialog shows up. 
* Maintained the correct focus cycling order after code refactoring.
---
=> Dialogs - single instance, `isOn` button state, recreating instead of resetting the view

packages/ckeditor5-engine/src/conversion/downcastdispatcher.ts, packages/ckeditor5-engine/tests/conversion/downcastdispatcher.js
Fix (engine): Fixed crash happening in a very peculiar scenario involving reconversion of an element containing a marker. Closes #15411.
=> Mapper bindings are removed too late when reconversion is involved

packages/ckeditor5-ui/theme/components/tooltip/tooltip.css
Internal(ui): Increased tooltips z-index to make them visible over the dialog element.
---
Not only dialog tooltips will be displayed over it, but also e.g. toolbar buttons - but that's consistent with the industry standards.
=> Make all tooltips visible over the dialog

packages/ckeditor5-list/tests/listproperties/listpropertiesui.js
Internal (list): Fix failing test.
---
This test only fails locally with the browser focused. Due to the test setup (dropdown lazy loading), the first list item is already focused when the dropdown is open for the second time. With the changes at the dialog feature branch, element is not re-focused if it's already focused, so the spy is not called. I added a hard reset on focus tracker at the end of the setup steps to make sure the testing scenario is the same in all envs.
=> Fix failing test from the `List` package

docs/framework/contributing/code-style.md
Docs: Explain eslint rule requiring file extensions in imports. Related to #13673.
---
=> Docs: Explain eslint rule requiring file extensions in imports

scripts/eslint-formatter.js
Internal: Fix error caused by eslint rule not having `ruleId`. Related to #5731.
---
=> Internal: Fix error caused by eslint rule not having `ruleId`

packages/ckeditor5-ui/src/dropdown/utils.ts
Docs (ui): Adds correct type to example in `ckeditor5-ui/dropdown/utils.ts`. Closes #15533.
---
=> Add missing type to example of addListToDropdown in ui/dropdown/utils.

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dialog/dialog.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/formheader/formheader.css
Internal(ui): Changed the header sizes.
---
Note that UIs that do not use the `FormHeaderView` (like comments archive) are unaffected by this change.
=> Unify header styles with the new dialog headers

packages/ckeditor5-source-editing/src/sourceediting.ts, packages/ckeditor5-source-editing/tests/sourceediting.js, packages/ckeditor5-ui/tests/manual/dialog/dialog.ts
Internal(source-editing): Hide the visible dialog when switching to the source editing mode.
---
=> Integrate source editing with dialogs

packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditcommand.ts, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js, packages/ckeditor5-ckbox/tests/manual/ckbox.html, packages/ckeditor5-ckbox/tests/manual/ckbox.js
Fix (ckbox): Fixed relative URL image editing. 
Closes https://github.com/cksource/ckeditor5-commercial/issues/5856.
---
=> Fixed relative URL images editing.

packages/ckeditor5-ui/src/bindings/draggableviewmixin.ts
Internal(ui): Fixed the Safari quirks.
---
Besides the `TouchEvent` problem, there was another issue with dragging: it was causing the text selection. It was fixed by adding the `preventDefault()` call.
=> Fix dialogs on Safari

packages/ckeditor5-ui/src/dialog/dialogview.ts, packages/ckeditor5-ui/tests/dialog/dialogview.js, packages/ckeditor5-ui/tests/manual/dialog/dialog.ts
Internal(ui): Fix tab cycling in dialog that only has action buttons.
---
Addresses https://github.com/ckeditor/ckeditor5/pull/15577#discussion_r1434025222.
=> Fix cycling in dialog actions

packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditcommand.ts, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js
Internal (ckbox): In on-premises should use serviceOrigin in image-editing. Closes [#5834](https://github.com/cksource/ckeditor5-commercial/issues/5834).
---
=> Use serviceOrigin in image editing

packages/ckeditor5-html-support/tests/integrations/image.js, packages/ckeditor5-link/src/linkimageediting.ts, packages/ckeditor5-link/tests/linkimage-integration.js
Fix (link): Fixed the editor crash using the `LinkImage` plugin loaded before `Image`, which ends with extending the schema definitions before they are registered. Closes #15617.
---
=> LinkImage should not crash if initialized before Image

packages/ckeditor5-html-support/src/datafilter.ts, packages/ckeditor5-html-support/tests/integrations/list.js
Fix (html-support): The editor should not stuck in an infinite post-fixing loop while modifying a list structure inside a GHS element. Closes #15527. Closes #15565.
---
=> Fixed infinite post-fixers loop.

packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.ts, packages/ckeditor5-image/src/imageinsert/ui/imageinsertformview.ts, packages/ckeditor5-image/src/imageinsert/ui/imageinserturlview.ts, packages/ckeditor5-image/src/imagetextalternative/ui/textalternativeformview.ts, packages/ckeditor5-link/src/ui/linkactionsview.ts, packages/ckeditor5-link/src/ui/linkformview.ts, packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts, packages/ckeditor5-media-embed/src/ui/mediaformview.ts, packages/ckeditor5-special-characters/src/ui/specialcharactersview.ts, packages/ckeditor5-style/src/ui/stylegridview.ts, packages/ckeditor5-table/src/tablecellproperties/ui/tablecellpropertiesview.ts, packages/ckeditor5-table/src/tableproperties/ui/tablepropertiesview.ts, packages/ckeditor5-table/src/ui/colorinputview.ts, packages/ckeditor5-ui/src/collapsible/collapsibleview.ts, packages/ckeditor5-ui/src/colorselector/colorgridsfragmentview.ts, packages/ckeditor5-ui/src/colorselector/colorpickerfragmentview.ts, packages/ckeditor5-ui/src/colorselector/colorselectorview.ts, packages/ckeditor5-ui/src/dialog/dialogactionsview.ts, packages/ckeditor5-ui/src/dialog/dialogview.ts, packages/ckeditor5-ui/src/focuscycler.ts, packages/ckeditor5-ui/src/index.ts, packages/ckeditor5-ui/src/list/listview.ts, packages/ckeditor5-ui/src/search/searchresultsview.ts, packages/ckeditor5-ui/src/search/text/searchtextview.ts, packages/ckeditor5-ui/src/toolbar/toolbarview.ts, packages/ckeditor5-ui/tests/focuscycler.js
Other (ui): `FocusCycler`'s `#focusables` collection should only contain `FocusableView` instances. Closes #14973.
MINOR BREAKING CHANGE (ui): The view collection required by [`FocusCycler#constructor()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_focuscycler-FocusCycler.html#function-constructor) must only contain views implementing the [`FocusableView`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_focuscycler-FocusableView.html) interface. Failing to do so will result in a TypeScript error. Please make sure each and every view passed to this collection implements the `focus()` method.
---
**Requires https://github.com/cksource/ckeditor5-commercial/pull/5886**
=> FocusCycler's #focusables collection should only contain FocusableView instances

packages/ckeditor5-link/src/linkui.ts, packages/ckeditor5-link/tests/linkui.js
Internal (link): Fix focus when link form is opened for editing. Closes #15664.
Internal (link): If URL field is not empty, allow saving form even if no change was made. See #15664.
---
=> Internal (link): Fix focus when link form is opened for editing

docs/updating/update-to-41.md
Docs: Added an entry about moving several icons in a commercial repository.
---
=> Docs: An entry about moving icons in commercial repository in update to 41.x guide.

packages/ckeditor5-link/src/autolink.ts, packages/ckeditor5-link/tests/autolink.js
Fix (link): Image should not disappear after dragging in Windows OS in Chromium browsers. #15700.
---
OS differences:
```js
data.dataTransfer.getData( 'text/plain' )
```
dragged image on Windows OS returns:
```plaintext
http://127.0.0.1:8125/ckeditor5-clipboard/tests/manual/sample.jpg
```
on MacOS there is empty string.
=> Prevented to images disappear after dragging (Windows OS in Chromium browsers).

packages/ckeditor5-ui/src/colorselector/colorgridsfragmentview.ts, packages/ckeditor5-ui/tests/colorselector/colorselectorview.js
Internal(ui): Fix focus management in font color dropdown. Closes cksource/ckeditor5-commercial#5919.
---
This PR should not affect the actual editor behavior. It's meant to fix e2e tests.
=> Fix focus management in font color dropdown

packages/ckeditor5-core/src/context.ts, packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/src/editor/editorconfig.ts, packages/ckeditor5-core/tests/context.js, packages/ckeditor5-core/tests/editor/editor.js, packages/ckeditor5-utils/src/index.ts, packages/ckeditor5-utils/src/locale.ts, packages/ckeditor5-utils/src/translation-service.ts, packages/ckeditor5-utils/tests/locale.js, packages/ckeditor5-utils/tests/translation-service.js
Feature (core,utils): Should use translations that are passed in the config. Closes https://github.com/ckeditor/ckeditor5/issues/15713.
---
=> Allow passing a 'translations' object in the configuration

packages/ckeditor5-ui/src/tooltipmanager.ts, packages/ckeditor5-ui/tests/tooltip/tooltipmanager.js
Feature(ui): Tooltip manager will now detect changes in the tooltip text and position in the element with the currently visible tooltip.
---
=> Add the mutation observer to `TooltipManager`

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/tooltip/tooltip.css
Other (ui): Mutli-line tooltips will now have `max-width` set to `200px` by default.
---
=> Add max-width for multiline tooltips

packages/ckeditor5-table/src/tableutils.ts, packages/ckeditor5-table/tests/tableutils.js
Fix (table): `TableUtils#getColumns()` should exclude elements other than `tableCell` (e.g. marker elements) while counting. Closes cksource/ckeditor5-commercial#5968.
---
This PR is an improvement over https://github.com/ckeditor/ckeditor5/pull/15843.
=> TableUtils#getColumns() should exclude elements other than `tableCell` (e.g. marker elements) while counting.

packages/ckeditor5-source-editing/src/utils/formathtml.ts, packages/ckeditor5-source-editing/tests/utils/formathtml.js
Fix (source-editing): Source editing should not add white spaces to pre-formatted code lines. Closes #15084.
---
I don't like our approach in this helper. Using RegExp to manipulate HTML was not the best idea in the first place and there's always a risk of the whole thing breaking up. A parser would be a better choice but that would mean a re-write of the helper. I briefly researched how `DOMParser` could help us and this only confirmed my suspicion that a lot of work is necessary. We could also use an external library to prettify the source output.
=> Source editing should not add white spaces to pre-formatted code lines

packages/ckeditor5-image/src/imageresize/imageresizehandles.ts, packages/ckeditor5-image/tests/imageresize/imageresizehandles.js
Fix (image):  Inline image resizing miscalculations / Resizing an image to make it smaller sometimes does the opposite. Closes #10267.
=>  Inline image resizing miscalculations / Resizing an image to make it smaller sometimes does the opposite 

packages/ckeditor5-find-and-replace/src/findandreplace.ts, packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts, packages/ckeditor5-find-and-replace/src/findandreplacestate.ts, packages/ckeditor5-find-and-replace/src/findandreplaceui.ts, packages/ckeditor5-find-and-replace/src/findandreplaceutils.ts, packages/ckeditor5-find-and-replace/src/findcommand.ts, packages/ckeditor5-find-and-replace/tests/findandreplace.js, packages/ckeditor5-find-and-replace/tests/findandreplaceediting.js, packages/ckeditor5-find-and-replace/tests/findandreplaceutils.js, packages/ckeditor5-find-and-replace/tests/ui/findandreplaceformview.js
Fix(find-and-replace): Highlighted search result is no longer highlighted if the user has modified part of the found phrase in the text editor. 
---
Closes #15680
=> Fix ability to change found text while the dialog is open

packages/ckeditor5-heading/src/headingconfig.ts, packages/ckeditor5-heading/src/headingediting.ts
Feat (heading): Adjust typings in headings options. Closes #15790.
=> Adjust typings in headings options

packages/ckeditor5-image/src/imageinsert/imageinsertviaurlui.ts, packages/ckeditor5-image/tests/imageinsert/imageinsertviaurlui.js
Fix (image): Fixes the initialization of `ImageInsertViaUrlUI` so it does not depend on configured plugins order. Closes #15869.
---
=> Rename ImageInsertViaUrlUI.init() to afterInit().

packages/ckeditor5-mention/src/mentioncommand.ts, packages/ckeditor5-mention/tests/mentioncommand.js
Fix (mention): Inserting a mention should not add an extra white space if there was one already. A white space should not follow a mention inserted in brackets. Closes #4651.
---
In this PR I addressed two issues:
* The original one from https://github.com/ckeditor/ckeditor5/issues/4651 
* ( `foo [] bar` -> `mention` -> `foo @mention[] bar` instead of `foo @mention [] bar`)
* An extra one that I figured out was cheap to implement and would benefit the users
* `([])` -> `mention` -> `(@mention)` instead of `(@mention )`
I think there are many improvements left related to inserting mentions in different places, for instance, I would expect `"[]` -> type a mention -> `"@mention ` -> type `"` -> `"@mention"` but this one falls into text transformation category.
=> Inserting a mention should not add extra white spaces

packages/ckeditor5-core/lang/contexts.json, packages/ckeditor5-table/lang/contexts.json
Other (ckeditor5): Moved translation keys for Toggle caption off & Toggle caption on to core, changed for a more generic purpose (for more than table).
Closes #15397.
---
This will result in more accurate translations which will also respect objects other than table.
=> Moved the toggle caption on/off labels to core package.

docs/tutorials/crash-course/model-and-schema.md
Internal: Resolve conflict between master and stable.
---
=> Resolve conflict between master and stable

packages/ckeditor5-ckbox/src/ckboxediting.ts, packages/ckeditor5-ckbox/src/ckboxui.ts, packages/ckeditor5-ckbox/tests/ckboxediting.js, packages/ckeditor5-ckfinder/src/ckfinderui.ts, packages/ckeditor5-image/src/imageinsert/imageinsertui.ts, packages/ckeditor5-image/src/imageinsert/imageinsertviaurlui.ts, packages/ckeditor5-image/src/imageupload/imageuploadui.ts, packages/ckeditor5-image/tests/imageinsert/imageinsertui.js, packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.ts, packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.ts, packages/ckeditor5-ui/tests/toolbar/balloon/balloontoolbar.js, packages/ckeditor5-ui/tests/toolbar/block/blocktoolbar.js
Fix (ckbox): Plugin order should not matter when it comes to registering schema for `ckboxImageId` attribute. Closes #15581.
Fix (ui): BlockToolbar and BalloonToolbar plugins order should not matter when it comes to registering toolbar items. Closes #15581.
MINOR BREAKING CHANGE (ui): The contents of the `BlockToolbar` and `BalloonToolbar` are now filled on the `EditorUIReadyEvent` instead of `afterInit()`.
---
This PR solves actually 3 issues:
1.  When adding the `CKBox` plugin before the  `ImageBlock` and `ImageInline` plugins, the schema for schema for `ckboxImageId` attribute was not registered.
2.  Loading `BlockToolbar` (or `BalloonToolbar`) before `CKBox` (or actually any other plugin that registers toolbar buttons in `afterInit()`) resulted in the button not being registered.
3. …
=> BlockToolbar and BalloonToolbar should init after all plugins are init-ed (and afterInit-ed).

packages/ckeditor5-link/docs/features/link.md, packages/ckeditor5-link/src/linkconfig.ts, packages/ckeditor5-link/src/linkediting.ts, packages/ckeditor5-link/src/linkui.ts, packages/ckeditor5-link/src/ui/linkactionsview.ts, packages/ckeditor5-link/src/utils.ts, packages/ckeditor5-link/tests/linkediting.js, packages/ckeditor5-link/tests/ui/linkactionsview.js, packages/ckeditor5-link/tests/utils.js
Feature (link): Added the ability to specify allowed URL protocols by introducing the `link.allowedProtocols` configuration property. Closes #14304.
---
I'm unsure which is better: whether the `allowedProtocols` should override the default protocols list or merge with it, when set.
Kept the old regex intact (only added replace tag for the custom list), but there's definitely room for improvement there, I described it at https://github.com/ckeditor/ckeditor5/issues/15915
=> Allow URLs with custom protocols in links 

packages/ckeditor5-clipboard/src/clipboardmarkersutils.ts, packages/ckeditor5-clipboard/src/index.ts, packages/ckeditor5-clipboard/tests/clipboardmarkersutils.js, packages/ckeditor5-table/src/tableclipboard.ts
Internal (clipboard): Fix incorrect copy and paste behavior when copied marker is present in another marker. Closes [#15942](https://github.com/ckeditor/ckeditor5/issues/15942).
Internal (clipboard): Fix disappearing widgets with markers after move. Closes [#15952](https://github.com/ckeditor/ckeditor5/issues/15952).
=> Handle insert markers edge cases

packages/ckeditor5-image/src/imageresize/imageresizeediting.ts, packages/ckeditor5-image/tests/imageresize/imageresizeediting.js
Fix(image): Loading the `ImageResize` plugin before `ImageBlock` or `ImageInline` should not crash the editor. Closes #15994 .
---
=> Fixed editor crash when order of plugins `ImageResize`, `ImageBlock` or `ImageInline` had matters.

packages/ckeditor5-ckbox/ckeditor5-metadata.json, packages/ckeditor5-ckfinder/ckeditor5-metadata.json, packages/ckeditor5-easy-image/ckeditor5-metadata.json, packages/ckeditor5-link/ckeditor5-metadata.json
Internal (ckbox, ckfinder, easy-image, link): The metadata structures were redefined so that plugins requiring the `Image` plugin work with `ImageBlock`, `ImageInline`, or both. Hence, it isn't necessary to load the entire plugin. Closes #15992.
---
=> Metadata: Replace the `Image` dependency with "oneOf" (`ImageBlock` or `ImageInline`)

packages/ckeditor5-minimap/src/minimapiframeview.ts
Fix (minimap): Add missing `tabindex` to minimap iframe element. Closes https://github.com/cksource/ckeditor5-commercial/issues/6020.
=> Content minimap steals focus

packages/ckeditor5-clipboard/src/clipboardmarkersutils.ts, packages/ckeditor5-clipboard/tests/clipboardmarkersutils.js
Fix (clipboard): The imported Word document that contains suggestions will no longer cause errors. 
Closes https://github.com/cksource/ckeditor5-commercial/issues/6081.
=> Do not regenerate name of markers that are not copyable

packages/ckeditor5-image/theme/imagecaption.css
Fix (image): Typo in imagecaption css variable.
---
For CSS variable `--ck-color-image-caption-highligted-background` in [imagecaption.css](https://github.com/ckeditor/ckeditor5/blob/44deaa14/packages/ckeditor5-image/theme/imagecaption.css#L9)
=> Fix (image): Fix typo in imagecaption css variable (highligted -> highlighted)

packages/ckeditor5-mention/src/index.ts
Other (mention): Export `MentionsView`, `MentionListItemView`, `DomWrapperView` classes and `MentionFeedObjectItem` type. Closes #16044.
---
=> Export few more types and classes from mention package

packages/ckeditor5-ui/src/tooltipmanager.ts, packages/ckeditor5-ui/tests/tooltip/tooltipmanager.js
Internal: Force fully unpin tooltip before pin due to memleak issues in tests.
=> Fix memory leak in `tooltipmanager.js` test

packages/ckeditor5-ui/src/menubar/utils.ts
Internal (revision-history): Add menu bar integration. Related to https://github.com/ckeditor/ckeditor5/issues/15894.
---
=> Add menu bar integration to revision history

packages/ckeditor5-core/src/editor/editorconfig.ts, packages/ckeditor5-editor-classic/src/classiceditor.ts, packages/ckeditor5-editor-classic/src/classiceditorui.ts, packages/ckeditor5-editor-classic/src/classiceditoruiview.ts, packages/ckeditor5-editor-classic/tests/manual/classiceditor.js, packages/ckeditor5-ui/src/menubar/menubarview.ts, packages/ckeditor5-ui/src/menubar/utils.ts
Internal (ui,editor-classic): Streamline menu bar normalization. Made the feature an opt-in in the `ClassicEditor`. Related to https://github.com/ckeditor/ckeditor5/issues/15894.
---
=> Change configuration handling to make menu bar opt-in in classic editor.

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/menubar/menubarmenulistitembutton.css, packages/ckeditor5-ui/tests/manual/menubar/menubar.js, tests/manual/all-features.js
Internal (theme-lark): Fixed the spacing in buttons without icons.
=> Fixed the spacing in buttons without icons

packages/ckeditor5-restricted-editing/src/restrictededitingmodeui.ts, packages/ckeditor5-restricted-editing/tests/manual/restrictedediting.js, packages/ckeditor5-ui/src/menubar/utils.ts
Internal (document-outline): Added Table of contents button in default menu bar structure. 
Internal (restricted-editing): Refactored the restricted editing buttons in the menu bar.
=> ToC and restricted editing improvments

packages/ckeditor5-core/src/editor/editorconfig.ts, packages/ckeditor5-editor-decoupled/src/decouplededitor.ts, packages/ckeditor5-editor-decoupled/src/decouplededitorui.ts, packages/ckeditor5-editor-decoupled/src/decouplededitoruiview.ts, packages/ckeditor5-editor-decoupled/tests/manual/decouplededitor.html, packages/ckeditor5-editor-decoupled/tests/manual/decouplededitor.js, packages/ckeditor5-theme-lark/theme/ckeditor5-editor-classic/classiceditor.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/menubar/menubar.css
Internal (editor-decoupled): Add menu bar to decoupled editor. Related to https://github.com/ckeditor/ckeditor5/issues/15894.
---
=> Add menu bar to decoupled editor.

packages/ckeditor5-ui/src/tooltipmanager.ts, packages/ckeditor5-ui/tests/tooltip/tooltipmanager.js
Internal (ui):  Prevent tooltips from overlapping the menu bar.
---
=> Prevent tooltips from overlapping the menu bar

packages/ckeditor5-ui/src/menubar/utils.ts, packages/ckeditor5-ui/tests/menubar/utils.js
Internal (ui):  Hovering a tooltip in a menu bar item no longer closes that item. Closes #16157.
---
After leaving the cursor from tooltip, the `evt.source.element` is pointed to `Numbered List` menu item instead of grid. It needs probably more investigation _why_ it happens, but I'd do that in case of any additional bugs with this functionality.  One possible reason might be that `Numbered List` contains submenu. Current solution on the other hand works for now.
=> Hovering over the menu bar element using the tooltip, the menu closes unexpectedly

packages/ckeditor5-table/src/tableui.ts, packages/ckeditor5-table/src/ui/inserttableview.ts, packages/ckeditor5-table/tests/tableui.js, packages/ckeditor5-table/tests/ui/inserttableview.js
Fix (table) Table insert in menu bar always start at 1x1 on menu open. Closes #16156.
---
=> Reset insert table view in menu bar

packages/ckeditor5-widget/src/widget.ts, packages/ckeditor5-widget/tests/widget.js
Feature (widget): Added `tab` and `esc` generic key handlers for widgets. Closes #16071.
---
=> Added tab and esc generic key handlers for widgets.

packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
Internal (ui): Fix incorrect color picker doc of `resetValidationStatus` method.
=> Fix incorrect color picker doc 

packages/ckeditor5-code-block/src/codeblockediting.ts, packages/ckeditor5-code-block/tests/codeblockediting.js, packages/ckeditor5-image/src/imageupload/imageuploadediting.ts, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js, packages/ckeditor5-list/src/legacytodolist/legacytodolistediting.ts, packages/ckeditor5-list/src/todolist/todolistediting.ts, packages/ckeditor5-list/tests/legacytodolist/legacytodolistediting.js, packages/ckeditor5-list/tests/todolist/todolistediting.js, packages/ckeditor5-ui/src/arialiveannouncer.ts, packages/ckeditor5-ui/tests/editorui/arialiveannouncer.js, packages/ckeditor5-ui/tests/panel/balloon/contextualballoon.js, packages/ckeditor5-ui/theme/components/arialiveannouncer/arialiveannouncer.css
Internal (ui):  Refactor aria live announcer to use `aria-relevant: additions` attribute with GC mechanism
MINOR BREAKING CHANGE (ui): Drop region name argument from `AriaLiveAnnouncer#announce`  method. 
---
Part of https://github.com/ckeditor/ckeditor5/pull/16197
Part of https://github.com/cksource/ckeditor5-commercial/pull/6166
=> Refactor aria live announcer to use `aria-relevant: additions` attribute with GC mechanism

packages/ckeditor5-code-block/lang/contexts.json, packages/ckeditor5-code-block/package.json, packages/ckeditor5-code-block/src/codeblockediting.ts, packages/ckeditor5-code-block/src/utils.ts, packages/ckeditor5-code-block/tests/codeblockediting.js, packages/ckeditor5-image/lang/contexts.json, packages/ckeditor5-image/src/imageupload/imageuploadediting.ts, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js, packages/ckeditor5-list/lang/contexts.json, packages/ckeditor5-list/src/legacytodolist/legacytodolistediting.ts, packages/ckeditor5-list/src/todolist/todolistediting.ts, packages/ckeditor5-list/tests/legacytodolist/legacytodolistediting.js, packages/ckeditor5-list/tests/todolist/todolistediting.js, packages/ckeditor5-ui/src/arialiveannouncer.ts, packages/ckeditor5-ui/tests/editorui/arialiveannouncer.js, packages/ckeditor5-ui/tests/panel/balloon/contextualballoon.js, packages/ckeditor5-ui/theme/components/arialiveannouncer/arialiveannouncer.css
Feature (code-block): Introduced screen reader announcements for entering or exiting code block elements in the document editor. Closes #16053.
Other (ui): Refactored the `AriaLiveAnnouncer` to use the `aria-relevant` attribute and make concurrent announcements queued by screen readers.
MINOR BREAKING CHANGE (ui): The region name argument of the `AriaLiveAnnouncer#announce()`  method has been dropped. Please check out the latest API documentation for more information. 
https://github.com/cksource/ckeditor5-commercial/issues/6031.
https://github.com/cksource/ckeditor5-commercial/issues/6033
Part of: 
https://github.com/cksource/ckeditor5-commercial/pull/6163
Announcer refactor:
https://github.com/ckeditor/ckeditor5/pull/16199
=> Aria live announcements A11y improvements

packages/ckeditor5-list/src/list/listui.ts, packages/ckeditor5-list/tests/list/listui.js
Fix (List): Order of `List` and `ListProperties` plugins should not affect the appearance of the icon in the toolbar. Closes #16192.
---
=> The list properties toolbar is overriden by List plugin

packages/ckeditor5-engine/src/view/observer/selectionobserver.ts, packages/ckeditor5-engine/tests/view/observer/selectionobserver.js, packages/ckeditor5-typing/src/input.ts, packages/ckeditor5-typing/src/inserttextobserver.ts, packages/ckeditor5-typing/tests/input.js, packages/ckeditor5-typing/tests/inserttextobserver.js
Fix (typing, engine): Predictive text should not get doubled while typing. Closes #16106.
---
=> [IME] Tracking the composed range so content can be replaced while composing

packages/ckeditor5-engine/src/view/observer/focusobserver.ts, packages/ckeditor5-engine/tests/view/observer/focusobserver.js
Fix (engine): The reverse typing effect should not happen after the focus change. Closes #14702.
---
This PR is based on the community PR #16066. Thanks, @urbanspr1nter!
=> Added handling of editable focus on beforeinput event.

packages/ckeditor5-autoformat/tests/autoformat.js, packages/ckeditor5-typing/src/deleteobserver.ts, packages/ckeditor5-typing/tests/deleteobserver.js
Fix (autoformat): Pressing the backspace after autoformat should retain the typed content after undoing the block format change. Closes #16240.
Internal (typing): Fixed the target range size verification for backspace handling. See #16240.
---
=> Fixed delete range fixing inside attribute elements.

packages/ckeditor5-widget/lang/contexts.json, packages/ckeditor5-widget/src/widget.ts, packages/ckeditor5-widget/tests/widget.js
Feature (widget): Add information in a11y dialog that it is possible to move focus from nested editable back to the widget.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6040
=> Add widget ESC shortuct accessibility dialog entry

packages/ckeditor5-editor-multi-root/tests/manual/multirooteditor.js
Tests (editor-multi-root): Properly remove the menu bar element on editor destroy. 
---
=> Remove menu bar on editor destroy.

packages/ckeditor5-ui/src/tooltipmanager.ts, packages/ckeditor5-ui/tests/tooltip/tooltipmanager.js
Fix (ui): The `TooltipManager` should verify if the tooltip is not already unpinned while trying to update its position. 
Closes https://github.com/cksource/ckeditor5-commercial/issues/6219.
---
This is fixing the following flow:
- Unlink command executed => Model change => View change => View render
- View on render event => fire `layoutChanged` event
- EditorUI on `layoutChanged` event => fire UI `update` event:
1.
- `LinkUI` on UI `update` event => no link => `_hideUI()` => call `EditingView` `focus()`
- `TooltipManager` on `focus` (editable) event => no `getDescendantWithTooltip()` => call `_unpinTooltip()`
- Note that it calls `stopListening( editor.ui, 'update' )`
2.
- This is the same `update` event as above, the stop listening is affecting only future events, not the current one. …
=> The TooltipManager should verify if the tooltip is not already unpinned while trying to update its position.

CHANGELOG.md
Docs: Added info about related to the silent release of NIM.
---
See: https://github.com/ckeditor/ckeditor5/issues/16360#issuecomment-2112148609
=> Added info about related to the silent release of NIM

packages/ckeditor5-utils/src/env.ts, packages/ckeditor5-utils/tests/env.js
Fix (utils): Prevented error thrown when `ckeditor5-utils/src/env.ts` is used in an environment without `window` global object. Closes #16368.
=> Prevented error thrown when `ckeditor5-utils/src/env.ts` is used in an environment without window global object

packages/ckeditor5-link/src/ui/linkformview.ts, packages/ckeditor5-link/tests/ui/linkformview.js
Fix (link): Set `inputmode=url` to link balloon form input. Closes #16389.
=>  Miscellaneous accessibility improvements

packages/ckeditor5-ui/src/tooltipmanager.ts, packages/ckeditor5-ui/tests/tooltip/tooltipmanager.js
Internal (ui): Ensure tooltips are not pinned when the element is not being hovered over.
---
1. Marked as `internal` - it's not regression. The issue was introduced in [commit](https://github.com/ckeditor/ckeditor5/commit/9a6b96b9c35864433929e13e8ae7ecfb8ee70f2e) that hasn't been released yet.
2. Closes https://github.com/ckeditor/ckeditor5/issues/16383
https://github.com/ckeditor/ckeditor5/assets/3949262/e57962ac-a5ec-4f47-bcb9-9f0faac91262
https://github.com/ckeditor/ckeditor5/assets/3949262/d94223ba-b096-40ca-8858-b6bc5fb4f8a8
=> Tooltip flashes while clicking toolbar items

docs/installation/integrations/react.md
Docs: Add `onAfterDestroy` callback description to React integration docs.
1. Editor uses async destroy method that does not work super fine with React lifecycle. 
2. Editor is most of the time destroyed _after_ unmounting of component or changing its ID property. 
3. This callback makes sure that all side effects (such as added editable HTML DOM nodes) are removed _after_ destroying all plugins attached to the editor. 
4. `onAfterDestroy` is being batched, so in other words rapid `id` change (10 in row) will trigger only ~1 call of this callback which prevents race conditions in `Strict Mode`. 
1. The `onAfterDestroy` callback has been added in this [commit](https://github.com/ckeditor/ckeditor5-react/commit/ce6cad06e7a847b48189ddfaeed57921ce314874#diff-17a78b4174b47153db11ac4738dfbb3608e …
=> Add `onAfterDestroy` callback description to react docs

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/spinner/spinner.css
Fix(theme-lark): Name of spinner animation should be unique now. Closes #16390 .
---
_It was't always broken but only when in editor was used plugin that has spinner (like Export to PDF), that's why it works ok in CKBox Feature demo and didn't in Full Feature example (there was animation name collision - here `CKEditor5` and there `CKBox` animation was called `rotate`)_.
=> Spinner animation keyframe name changed to be unique.

packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditcommand.ts, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js
Fix (ckbox): The image toolbar stays attached to the image after closing CKBox. Closes #16153.
---
=> Update ui on close image ckbox dialog.

docs/tutorials/widgets/implementing-an-inline-widget.md
Docs: Updating the "Implementing an inline widget" tutorial to new installation methods.
---
Links to supporting repo won't work because PR is not merged to the master yet.
Here's PR to to the repo with the supporting files: https://github.com/ckeditor/ckeditor5-tutorials-examples/pull/10
=> Updating the "Implementing an inline widget" tutorial to new installation methods

docs/tutorials/widgets/implementing-a-block-widget.md
Docs: Updating the "Implementing a block widget" tutorial to new installation methods.
---
Links to supporting repo won't work because PR is not merged to the master yet.
Here's PR to to the repo with the supporting files: https://github.com/ckeditor/ckeditor5-tutorials-examples/pull/9
=> Updating the "Implementing a block widget" tutorial to new installation methods

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenu.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenubutton.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenulistitem.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenulistitembutton.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenupanel.css, packages/ckeditor5-ui/src/bindings/clickoutsidehandler.ts, packages/ckeditor5-ui/src/dropdown/menu/dropdownmenulistitemview.ts, packages/ckeditor5-ui/src/dropdown/menu/dropdownmenupanelview.ts, packages/ckeditor5-ui/src/dropdown/menu/dropdownmenuportalview.ts, packages/ckeditor5-ui/src/dropdown/menu/dropdownmenurootlistview.ts, packages/ckeditor5-ui/src/dropdown/menu/dropdownmenuview.ts, packages/ckeditor5-ui/src/dropdown/menu/events.ts, packages/ckeditor5-ui/src/dropdown/menu/filterview/dropdownmenulistfilteredview.ts, packages/ckeditor5-ui/src/dropdown/menu/utils/dropdownmenubehaviors.ts, packages/ckeditor5-ui/src/dropdown/utils.ts, packages/ckeditor5-ui/src/index.ts, packages/ckeditor5-ui/theme/components/dropdown/menu/dropdownmenu.css, packages/ckeditor5-ui/theme/components/dropdown/menu/dropdownmenubutton.css, packages/ckeditor5-ui/theme/components/dropdown/menu/dropdownmenupanel.css
Feature (ui): Add dropdown menu large menus scrolling support.
---
Current implementation of menu (copied from menubar) does not support scrolling. Submenus are rendered in `MenuPanelView` element, which is kinda problematic in terms of `overflow: scroll`. This PR moves submenu rendering to `ck-body-wrapper`, fixes focus and makes menu keyboard accessible.
=> Add scrollable dropdown submenus

packages/ckeditor5-core/package.json, packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/tests/editor/editor.js, packages/ckeditor5-editor-balloon/src/ballooneditor.ts, packages/ckeditor5-editor-classic/src/classiceditor.ts, packages/ckeditor5-editor-decoupled/src/decouplededitor.ts, packages/ckeditor5-editor-inline/src/inlineeditor.ts, packages/ckeditor5-editor-multi-root/src/multirooteditor.ts
Other (core): The `EditorWatchdog`, `ContextWatchdog`, and `Context` classes are now exposed as static fields of the `Editor` class. Closes #13852.
---
=> The `EditorWatchdog`, `ContextWatchdog`, and `Context` classes are now exposed as static fields of the `Editor` class.

docs/tutorials/widgets/data-from-external-source.md, docs/tutorials/widgets/implementing-an-inline-widget.md
Docs: Updating the "Data from an external source" tutorial to new installation methods.
---
Links to supporting repo won't work because PR is not merged to the master yet.
Here's PR to to the repo with the supporting files: https://github.com/ckeditor/ckeditor5-tutorials-examples/pull/11
=> Updating the "Data from an external source" tutorial to new installation methods

packages/ckeditor5-engine/src/view/domconverter.ts, packages/ckeditor5-engine/tests/view/documentfragment.js, packages/ckeditor5-engine/tests/view/domconverter/whitespace-handling-integration.js
Fix (engine): Preserve repeated spaces in text that is contained within an element that renders (repeated) white space. Closes #16124
---
This pull request offers a possible solution for #16124.
It will preserve (repeated) whitespace when the text is contained within a block that preserves whitespace during rendering, which is done through the `white-space` CSS property. This is similar to what the code for the `<pre>` element is already doing.
Existing code within CKEditor is already taking care of swapping out the repeated spaces by `&nbsp;`-patterns, so they are also preserved when the data is extracted again.
=> Preserve repeated spaces when text is wrapped with a CSS `white-space` rule

packages/ckeditor5-engine/src/index.ts
Other (engine): Export `ViewDocumentBlurEvent` and `ViewDocumentFocusEvent` types from the main index.
---
These two types are used in our Angular integration and are imported from the `@ckeditor/ckeditor5-engine/src/view/observer/focusobserver` file which is not available in the new installation methods.
=> Export `ViewDocumentBlurEvent` and `ViewDocumentFocusEvent` types from the main index

packages/ckeditor5-engine/src/model/differ.ts, packages/ckeditor5-engine/tests/model/differ.js
Feature (engine): Introduced `DiffItemInsert#action`, `DiffItemInsert#before` and `DiffItemRemove#action` which give more information about the change that happened in the model. Refer to the API docs to learn more. Closes #15800.
=> Do not use element reference in DifferItemInsert and DifferItemRemove

packages/ckeditor5-engine/src/index.ts
Other (engine): Export `XmlDataProcessor` from the main index.
---
This class is used in `@wiris/mathtype-ckeditor5` plugin and is imported from the `@ckeditor/ckeditor5-engine/src/dataprocessor/xmldataprocessor` file which is not available in the new installation methods.
=> Export `XmlDataProcessor` from the main index.

scripts/build-ckeditor5.mjs, scripts/release/utils/getckeditor5packagejson.js
Other (ckeditor5): Rename `index.js` to `ckeditor5.js` in new installation method builds.
---
=> Other (ckeditor5): Rename `index.js` to `ckeditor5.js` in NIM builds

packages/ckeditor5-image/ckeditor5-metadata.json
Internal (image): Moved the `insertImageViaUrl` UI component in metadata to the proper plugin.
---
=> Image metadata and "insertImageViaUrl"

scripts/release/preparepackages.js, scripts/release/publishpackages.js, scripts/release/utils/parsearguments.js
Internal: Support for publishing the CKEditor 5 alpha releases automatically once a testing phase starts.
---
* See: https://github.com/ckeditor/ckeditor5-dev/releases/tag/v40.2.1
=> Support for nightly alpha releases

packages/ckeditor5-theme-lark/theme/ckeditor5-editor-classic/classiceditor.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/toolbar/toolbar.css
Other (editor-classic): Add a separator between the menu bar and the toolbar.
---
=> Add border to menu bar

packages/ckeditor5-ui/src/arialiveannouncer.ts, packages/ckeditor5-ui/tests/editorui/arialiveannouncer.js
Fix (ui): Remove unnecessary `role=region` from aria live views due to failing `landmarks should be unique` a11y axe rule.  Closes https://github.com/ckeditor/ckeditor5/issues/16544. 
1. There is no need to set `role=region` on `aria-live` regions because it's ignored by readers if associated HTML element has no label attributes.
2. `role=region` is an alternative to `aria-live` and should not be used together. 
3. Checked using `NVDA` and it sounds fine.
=> A11y best practice: Landmarks should be unique

packages/ckeditor5-heading/theme/heading.css, packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/list/list.css
Fix (theme-lark): Fixed incorrect (too short) height of buttons placed inside lists (e.g. buttons in annotations menus). This was an accidental regression introduced in one of the recent releases. Closed by #16409.
---
Closes cksource/ckeditor5-commercial#6248.
1. Regression introduced in this [commit](https://github.com/ckeditor/ckeditor5/commit/f072048026c5407467e343c116c71ff5a9d236b4#diff-89c661e74afa6f00cb58fc5bcd651f40c1750417127eae21b1d44d0f94ebf722L46-L50). It looks like accidental removal, menubar is not affected.
2. It fixes an issue causing incorrect height of heading dropdown items in our demos. See more in [comment](https://github.com/ckeditor/ckeditor5/pull/16409#issuecomment-2148971633). 
3. Further explanation https://cksource.slack.com/archives/C05R4RM7HRC/p1717416949627779 …
=> Fix incorrect height of buttons placed in list

packages/ckeditor5-ckbox/src/ckboxcommand.ts, packages/ckeditor5-ckbox/src/ckboxconfig.ts, packages/ckeditor5-ckbox/src/ckboxediting.ts, packages/ckeditor5-ckbox/tests/ckboxcommand.js
Feature (ckbox): Added more configuration options passed down to the CKBox. Closes [#3695](https://github.com/cksource/ckeditor5-internal/issues/3695)
---
=> CKBox: Update configuration options passed down to CKBox instance by ckbox-plugin

packages/ckeditor5-clipboard/src/pasteplaintext.ts, packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts, packages/ckeditor5-clipboard/tests/pasteplaintext.js, packages/ckeditor5-clipboard/tests/utils/viewtoplaintext.js, packages/ckeditor5-code-block/src/codeblockediting.ts, packages/ckeditor5-code-block/tests/codeblockediting.js
Feature (clipboard): Added handling for the elements with `dataPipeline:transparentRendering` property in the `text/plain` data transfer. Closes https://github.com/ckeditor/ckeditor5/issues/16583.
---
Theoretically, we could also solve it without adding a custom element property, but it's more complex: we need to convert the element to model one and then check in schema if it is an inline object or something similar.
=> Added handling for the inline view container elements in the `text/plain` data transfer

docs/getting-started/index.md
Docs: Cleanup, highlighted key links and misc improvements.
---
*   Quick Start -> Quick start.
*   Mentioned Next.js in the list of frameworks (because it's super important).
*   Removed the note about Powered by -> I think it was added there when we introduced this logo, so it's less of an issue now.
*   Highlighted key links -> To me, they were lost in the surrounding text. In fact, I think that at least  2-3 of those section should clearly separate the CTA link by moving it e.g. to the end of the paragraph or a new paragraph.
=> Docs: Cleanup, highlighted key links and misc improvements.

packages/ckeditor5-ui/src/menubar/utils.ts
Fix (ui): Changed the place of restricted editing buttons in the menu bar. Closes #16609.
---
=> Changed the place of restricted editing buttons in menu bar

packages/ckeditor5-engine/src/conversion/upcasthelpers.ts, packages/ckeditor5-engine/tests/conversion/upcasthelpers.js, packages/ckeditor5-table/tests/table-integration.js, packages/ckeditor5-table/tests/tableclipboard-paste.js
Fix (engine): Formatting should not get lost on a text with a marker in a table cell during upcast. 
Reverted a now-obsolete fix for markers not getting auto-paragraphed together with text. 
---
See https://github.com/cksource/ckeditor5-commercial/issues/5287. See https://github.com/cksource/ckeditor5-commercial/issues/4061.
=> Formatting should not get lost on a text with a marker in a table cell during upcast

packages/ckeditor5-find-and-replace/src/findandreplacestate.ts, packages/ckeditor5-find-and-replace/src/findandreplaceutils.ts, packages/ckeditor5-find-and-replace/src/findcommand.ts, packages/ckeditor5-find-and-replace/tests/findcommand.js
Fix (find-and-replace): Do not replace only the first found word when using it with `Track Changes` plugin.
MINOR BREAKING CHANGE (find-and-replace): The `FindCommand#execute` now accepts a `findCallback` that can return an array of results or an object containing an array of results together with the `searchText` used to invalidate search results in commands like `find previous`, `find next`, and `replace search`.
---
Closes: https://github.com/cksource/ckeditor5-commercial/issues/6193
Commercial PR: https://github.com/cksource/ckeditor5-commercial/pull/6275
1. When search is performed, `FindCommand#execute` is called. 
2. It can be called with `callback` or `string` as a search [parameter](https://github.com/ckeditor/ckeditor5/blob/5ed6fb17ea3cb07571468213361035f4846ad483/packages/ckedit …
=> Find and replace always replaces the first match when track changes is enabled

packages/ckeditor5-ui/src/button/filedialogbuttonview.ts
Fix (ui): Add `/* #__PURE__ */` comments before mixin calls to properly tree-shake unused classes. Closes #16651.
---
=> Add `/* #__PURE__ */` comments before mixin calls to properly tree-shake unused classes.

packages/ckeditor5-list/src/list/converters.ts, packages/ckeditor5-list/src/list/listediting.ts, packages/ckeditor5-list/tests/list/converters-data-single-block.js, packages/ckeditor5-list/tests/list/converters-data.js
Fix (list): Text nodes directly inside `<ul>` or `<ol>` should not be removed while loading editor data. Closes #16450.
---
=> List upcast converters should not remove invalid nodes.

packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts, packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js
Fix (ui): No longer crash while selecting color in table cell formatting form. Closes https://github.com/ckeditor/ckeditor5/issues/16664
---
1. Caused by this [commit](https://github.com/ckeditor/ckeditor5/commit/caea11e431fc56f911f4cf4ad4f73bc74d36a8b9#diff-1594461a97d09ec34385b4bd65b6d02f1426d81063af97cbdd197ae2941f8635R303).
2. I missed edge-case where `isValid` is called on color selector that has `hideInput` config flag set to `true`.
3. It means that `isValid` was called on a non-existing hex input DOM node, and it raised an exception. 
4. I added regression tests.
=> No longer crash after selecting color in table cell formatting form

docs/getting-started/quick-start.md
Docs: Quick start improvements.
---
I made commits one by one to make clear why I change those things.
There is one thing left to fix which is this paragraph:
> Copy these files to your project directory. You may use the \[CDN configuration\](#installing-ckeditor-5-from-cdn) as an example. You can also refer to framework integration guides for sample implementations.
I don't actually even understand what we're trying to say here.
I'd see it more less like this:
> Copy these files to your project directory (e.g. to a `vendor/` directory).
> 
> You can open the `index.html` file to check the sample included in the ZIP archive. Note, that you need to do that via an HTTP server.
> 
> Using the CKEditor&nbsp;5 via a ZIP archive is nearly identical to the other two installation methods (npm and …
=> Quick start improvements

packages/ckeditor5-ckbox/src/ckboxutils.ts, packages/ckeditor5-ckbox/tests/ckboxutils.js
Fix (ckbox): Use a safer way to convert numbers to strings to avoid issues with some bundlers. Closes https://github.com/ckeditor/ckeditor5/issues/16040
---
1. PR based on: https://github.com/ckeditor/ckeditor5/pull/16041
2. I added unit test to prevent regressions.
=> Use safer way for stringifying number in CKBox categories fetcher

packages/ckeditor5-table/src/tableutils.ts, packages/ckeditor5-table/tests/tableutils.js
Fix (table): Horizontal split button no longer splits larger table cell spans into more than two parts. Closes https://github.com/ckeditor/ckeditor5/issues/14658.
---
**Before fix**
https://github.com/user-attachments/assets/01df2845-3cae-48ae-81d7-d0120f39e11f
**After fix**
https://github.com/user-attachments/assets/3b1072d5-73a6-4fe4-9600-3b119eab081f
=> Fix unexpected behavior in splitting cells in certain tables

.circleci/template.yml, scripts/release/utils/getckeditor5packagejson.js
Fix (ckeditor5): Update the `exports` field in `package.json` to fix issues with loading CSS and translations in older bundlers. See #16638.
Internal: Remove the "Lint generated packages" step from CI due to a limitation of the validation library.
---
:warning: This PR targets the `release` branch! :warning:
=> Fix issues with loading CSS and translations in older bundlers

packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditcommand.ts, packages/ckeditor5-ckbox/src/ckboxuploadadapter.ts, packages/ckeditor5-ckbox/src/ckboxutils.ts, packages/ckeditor5-ckbox/tests/ckboxuploadadapter.js, packages/ckeditor5-ckbox/tests/ckboxutils.js
Other (ckbox): The plugin no longer slows down the editor startup because it fetches the token in the background instead of during the editor’s initialization. Closes https://github.com/ckeditor/ckeditor5/issues/16760
MINOR BREAKING CHANGE (ckbox): The `CKBoxUtils#getWorkspaceId` and `CKBoxUtils#getToken` methods now return a promise instead of a resolved value.
=> CKBox plugins should not wait for token fetch.

packages/ckeditor5-page-break/theme/pagebreak.css
Other (page-break): No longer generate extra empty page after placing page-break after element with margin.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6289
Commercial PR: https://github.com/cksource/ckeditor5-commercial/pull/6437
Look at this demo: http://localhost:8125/ckeditor5/external/ckeditor5-commercial/packages/ckeditor5-pagination/tests/manual/pagination.html
=> Pagination fails to recalculate and adds empty page to the document when inserting manual page break in some scenarios

packages/ckeditor5-ui/src/panel/balloon/balloonpanelview.ts, packages/ckeditor5-ui/src/tooltipmanager.ts, packages/ckeditor5-ui/tests/panel/balloon/balloonpanelview.js, packages/ckeditor5-ui/tests/tooltip/tooltipmanager.js
Fix (ui): Hide the pinned balloon panel view when the pin target is no longer visible. Closes https://github.com/ckeditor/ckeditor5/issues/16739. 
https://github.com/user-attachments/assets/7c859ea6-8d94-49b8-a4c4-31ad788ae384
https://github.com/user-attachments/assets/98bc68b0-7be6-4fe4-bc8a-1b499a329228
1. `SourceEditing` fires `change:isSourceEditingMode` after toggling source editing mode.
2. Some of the commands (e.g. `TableColumnResizeEditing`) tend to trigger `update ui` event while calling `_disableCommands` in `change:isSourceEditingMode` listener placed inside `SourceEditing` plugin.
3. These plugins tend to modify content or classes of editable, causing `update ui` to be fired, which lead to pin every tooltip again, even if pin target is hidden. 
4. I added pin target …
=> Close toolbars on open or close source view

packages/ckeditor5-code-block/src/codeblockediting.ts, packages/ckeditor5-code-block/tests/codeblockediting.js, packages/ckeditor5-engine/src/index.ts, packages/ckeditor5-mention/src/mentionui.ts, packages/ckeditor5-mention/tests/mentionui.js
Fix (mention): Escape mentions markers when building regular expression to prevent crashes when markers like '\\' are used. Closes #16818.
Internal (code-block): Disallow formatting attributes on nodes inside code block (instead of disallowing all attributes on text nodes). This is at the same time broader and more precise rule.
=> Fixes related to merge fields feature

packages/ckeditor5-autoformat/src/index.ts
Other (autoformat): The `blockAutoformatEditing` and the `inlineAutoformatEditing` are now exported from the package index. Closes #16815.
---
=> Added exports for the `blockAutoformatEditing` and the `inlineAutoformatEditing`.

packages/ckeditor5-ckbox/src/ckboxediting.ts, packages/ckeditor5-engine/docs/framework/deep-dive/schema.md, packages/ckeditor5-engine/src/index.ts, packages/ckeditor5-engine/src/model/model.ts, packages/ckeditor5-engine/src/model/schema.ts, packages/ckeditor5-engine/tests/model/model.js, packages/ckeditor5-engine/tests/model/schema.js, packages/ckeditor5-list/src/todolist/todolistediting.ts
Feature (engine): `Schema#addChildCheck()` and `Schema#addAttributeCheck()` can now register a callback for specific item or attribute, which should improve performance when using custom callback checks. Callback checks should be added only for specific item or attribute if possible. See the API reference. Closes #15834.
Fix (engine): `Schema#checkChild()` will now correctly check custom callback checks for each item in the context.
Other (engine): Introduced `Schema#trimLast()`.
Internal: Used specific callback checks in some of the features.
Docs (engine): Improved schema deep dive guide and added missing section related to attributes custom callback checks.
MINOR BREAKING CHANGE: `Schema` callbacks added through `addChildCheck()` will no longer add event listeners with `high` priority …
=> Schema addChildCheck/addAttributeCheck filtering

packages/ckeditor5-ckbox/lang/contexts.json, packages/ckeditor5-ckbox/src/ckboxediting.ts, packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditui.ts, packages/ckeditor5-ckbox/src/utils.ts, packages/ckeditor5-ckbox/tests/ckboxediting.js, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditui.js, packages/ckeditor5-image/lang/contexts.json, packages/ckeditor5-image/src/imageupload/imageuploadediting.ts, packages/ckeditor5-image/src/imageupload/imageuploadui.ts, packages/ckeditor5-image/src/imageupload/uploadimagecommand.ts, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js, packages/ckeditor5-image/tests/imageupload/imageuploadui.js, packages/ckeditor5-image/tests/imageupload/uploadimagecommand.js
Feature (ckbox, image): The image upload and edit buttons are disabled if the user has no permission to upload any asset.  
Closes https://github.com/cksource/ckeditor5-commercial/issues/6428.
---
=> Permissions integration in CKBox

packages/ckeditor5-ckbox/lang/contexts.json, packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditui.ts, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditui.js, packages/ckeditor5-image/lang/contexts.json, packages/ckeditor5-image/src/imageupload/imageuploadediting.ts, packages/ckeditor5-image/src/imageupload/imageuploadui.ts, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js, packages/ckeditor5-image/tests/imageupload/imageuploadui.js
Fix (ckbox): Rename notification message when no permission to upload image. Closes #16830.
---
=> CKBox Permission change tooltip name

packages/ckeditor5-engine/src/model/differ.ts, packages/ckeditor5-engine/tests/model/differ.js
Fix (engine): No longer crash editor when trying to style a very long paragraph. Closes https://github.com/ckeditor/ckeditor5/issues/16819
---
It looks like 200k arguments, passed to `.push` method of the Array, causes Google Chrome crashing.  I switched it to plain for loop and it works fine.
=> Fix crashing differ on large paragraphs

packages/ckeditor5-special-characters/src/specialcharacters.ts, packages/ckeditor5-special-characters/tests/specialcharacters.js
Internal (special-characters): Toolbar and menu bar button should be marked as toggleable. Closes #16858.
---
I added `isToggleable` for both menu bar and toolbar buttons. I see it is done the same way for AI Assistant and Comments archive so I assume this is the pattern we follow.
=> Special characters menu item is not correctly marked when enabled

packages/ckeditor5-list/src/list/converters.ts, packages/ckeditor5-list/src/todolist/todolistediting.ts, packages/ckeditor5-list/tests/todolist/todolistediting.js
Fix (List): Should not lost data of `todoListChecked` attribute in to-do lists. Closes #15602.
---
=> Fix `todoListChecked` data lost in to-do list

packages/ckeditor5-ui/package.json, packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.ts, packages/ckeditor5-ui/tests/manual/balloontoolbar/balloontoolbar-multi-root.html, packages/ckeditor5-ui/tests/manual/balloontoolbar/balloontoolbar-multi-root.js, packages/ckeditor5-ui/tests/manual/balloontoolbar/balloontoolbar-multi-root.md, packages/ckeditor5-ui/tests/toolbar/balloon/balloontoolbar.js
Feature (ui): Add support for balloon toolbar in multi root editor. Closes https://github.com/ckeditor/ckeditor5/issues/14803
---
=> Add support for balloon toolbar in multi root editor

packages/ckeditor5-media-embed/src/mediaembedediting.ts, packages/ckeditor5-media-embed/tests/mediaembedediting.js
Feature (media-embed): Support new Twitter domain (x.com) and Instagram Reels. Closes https://github.com/ckeditor/ckeditor5/issues/16435
---
Based on this PR: https://github.com/ckeditor/ckeditor5/pull/16461
I added unit tests.
=> Support Instagram reels and twitter new domain

docs/getting-started/integrations/angular.md, docs/getting-started/integrations/next-js.md, docs/getting-started/integrations/react-multiroot.md, docs/getting-started/integrations/react.md, docs/getting-started/integrations/vuejs-v2.md, docs/getting-started/integrations/vuejs-v3.md, docs/getting-started/legacy-getting-started/integrations/angular.md, docs/getting-started/legacy-getting-started/integrations/react.md, docs/getting-started/legacy-getting-started/integrations/vuejs-v2.md, docs/getting-started/legacy-getting-started/integrations/vuejs-v3.md
Docs: Adjust linking to new collaboration samples.
---
This PR updates links to collaborations samples repo according to new structure. The changes to samples itself can be viewed in this PR - https://github.com/cksource/ckeditor5-collaboration-samples/pull/152.
=> Adjust linking to new collaboration samples

packages/ckeditor5-table/theme/table.css
Fix (table): Larger tables are no longer truncated in print mode.  Closes https://github.com/ckeditor/ckeditor5/issues/16856
---
Caused by https://github.com/ckeditor/ckeditor5/issues/6186
Closes: https://github.com/cksource/ckeditor5-commercial/issues/6507
Before:
After:
=> Fix truncate tables in printing mode while using export to pdf

docs/getting-started/integrations/react.md
Docs: Adjust React context `onReady` callback docs. Closes https://github.com/ckeditor/ckeditor5/issues/16896
---
After React 19 migration and race condition fixes, `onReady` method behavior changed a bit. Originally found here https://github.com/ckeditor/ckeditor5-react/issues/513
=> Adjust React context `onReady` callback docs

scripts/translations/utils.js
Internal: Exclude TypeScript declaration files when collecting translation source files.
---
=> Exclude TypeScript declaration files when collecting translation source files

packages/ckeditor5-utils/src/uid.ts, packages/ckeditor5-utils/tests/uid.js
Internal (utils): Remove `Math.random()` from `uid` implementation.
See https://github.com/cksource/ckeditor5-internal/issues/3742.
---
=> Remove Math.random from uid.

packages/ckeditor5-cloud-services/src/cloudservicesconfig.ts, packages/ckeditor5-cloud-services/src/token/token.ts, packages/ckeditor5-cloud-services/tests/token/token.js
Fix (cloud-services): The `Token` refresh should retry after failure to avoid disconnection and data loss in real-time collaboration. 
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6561.
=> Token should retry after refresh failure to avoid eventual client disconnection from the editing session

docs/assets/snippet-styles.css
Docs: Ensured CKEditor 5 UI lists are not affected by Umberto's `.formatted` margins. Closes #16935.
=> Ensured CKEditor 5 UI lists are not affected by Umberto's `.formatted` margins

packages/ckeditor5-html-support/src/integrations/heading.ts, packages/ckeditor5-html-support/src/schemadefinitions.ts, packages/ckeditor5-html-support/tests/integrations/heading.js
Fix (html-support): `hgroup` and `summary` elements should work with source editing. Closes #16947 .
---
=> hgroup and summary should work with source editing

packages/ckeditor5-ui/src/panel/balloon/balloonpanelview.ts, packages/ckeditor5-ui/tests/panel/balloon/balloonpanelview.js, packages/ckeditor5-utils/src/dom/isvisible.ts, packages/ckeditor5-utils/tests/dom/isvisible.js
Fix (ui): Restored the ability to pin balloons to text nodes in the DOM tree. Closes https://github.com/ckeditor/ckeditor5/issues/16958 https://github.com/ckeditor/ckeditor5/issues/16889.
---
1. Introduced in https://github.com/ckeditor/ckeditor5/issues/16739 , we added visibility check before mounting of tooltips to avoid displaying them on hidden elements (which was causing another issue). 
2. Regression was caused by `isVisible` function. It was returning `false` for `$text` nodes, so it was impossible to pin balloons to such nodes.
3. I extracted docs example to standalone manual test. Apply this patch to your git repo to test it on your own [pin-balloons-demo.patch](https://github.com/user-attachments/files/16706397/pin-balloons-demo.txt) …
=> Fix pinning the balloons to `#text` nodes

packages/ckeditor5-paste-from-office/tests/_data/table/tablecellproperties/model.html, packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesediting.ts, packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesui.ts, packages/ckeditor5-table/src/tablecellwidth/tablecellwidthediting.ts, packages/ckeditor5-table/src/tableproperties/tablepropertiesediting.ts, packages/ckeditor5-table/src/tableproperties/tablepropertiesui.ts, packages/ckeditor5-table/src/utils/table-properties.ts, packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesediting.js, packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesui.js, packages/ckeditor5-table/tests/tableclipboard-paste.js, packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js, packages/ckeditor5-table/tests/tableproperties/tablepropertiesui.js, packages/ckeditor5-table/tests/utils/table-properties.js
Fix (table): Changed default table and table cell properties to match the content styles. Fixes problem with setting `border = none` on the table. Closes #6841. 
---
More context: #16810.
It's follow-up of this PR: #16002  
Fixes that have to be applied:
1.  https://github.com/ckeditor/ckeditor5/issues/16810#issuecomment-2258181045
2.  https://github.com/ckeditor/ckeditor5/pull/16002#issuecomment-2270562447
I decided to keep this in new PR due to change of ownership of this issue and keeping history of previous PR untouched.
Aligned with actual data
```
<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0 width=597 style='border-collapse:collapse;mso-table-layout-alt:fixed;
border:none;
^^^^^^^^^
mso-border-alt:solid windowtext .5pt;mso-yfti-tbllook:1184;mso-padding-alt:
0cm …
```
=> Make `border=none` setting work in tables

packages/ckeditor5-clipboard/src/clipboardobserver.ts, packages/ckeditor5-clipboard/tests/dragdrop.js, packages/ckeditor5-editor-multi-root/package.json, packages/ckeditor5-editor-multi-root/tests/manual/multirooteditor.html, packages/ckeditor5-editor-multi-root/tests/manual/multirooteditor.js, packages/ckeditor5-utils/src/dom/getrangefrommouseevent.ts, packages/ckeditor5-utils/src/index.ts, packages/ckeditor5-utils/tests/dom/getrangefrommouseevent.js, packages/ckeditor5-widget/src/widget.ts, packages/ckeditor5-widget/tests/widget.js
Fix (editor-multi-root): No longer lose selection on clicking editable containing only one block element. Closes https://github.com/ckeditor/ckeditor5/issues/16806
---
I adjusted multi-root demos with additional plugins to make debugging block items easier.
Debug log: https://github.com/ckeditor/ckeditor5/issues/16806#issuecomment-2275645126
https://github.com/user-attachments/assets/b2ccd2c6-7149-4d2c-9e6a-f89f3c5be012
https://github.com/user-attachments/assets/d9f89d58-3cf0-4048-be5d-385f09314ff8
https://github.com/user-attachments/assets/d52fc851-2323-42e3-afb7-c1d51ee666e3
=> Fix focusing block widgets inside multi root editor

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenulistitembutton.css, packages/ckeditor5-ui/src/dropdown/menu/dropdownmenubuttonview.ts, packages/ckeditor5-ui/tests/dropdown/menu/dropdownmenubuttonview.js
Fix (ui):  `DropdownMenuButtonView` should inherit from `ListItemButtonView` for color consistency in various states. Closes #16973.
---
**Before**
**After**
=>  DropdownMenuButtonView should inherit from ListItemButtonView for color consistency in various states

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenubutton.css
Fix (theme-lark): Dropdown menus should be rendered using unified paddings for categories and items. Closes #16971.
---
**Before**
**After**
=> Dropdown menus should be rendered using unified paddings for categories and items

packages/ckeditor5-ui/src/dropdown/menu/dropdownmenubehaviors.ts, packages/ckeditor5-ui/src/dropdown/menu/dropdownmenunestedmenuview.ts, packages/ckeditor5-ui/src/menubar/menubarmenuview.ts, packages/ckeditor5-ui/src/menubar/menubarview.ts, packages/ckeditor5-ui/src/menubar/utils.ts, packages/ckeditor5-ui/tests/dropdown/menu/dropdownmenubehaviors.js, packages/ckeditor5-ui/tests/menubar/utils.js
Fix (ui): Nested menus should not get their panels focused when the main button is clicked. Closes #16857.
=> Nested menus should not get their panels focused when the main button is clicked

packages/ckeditor5-widget/src/widget.ts, packages/ckeditor5-widget/tests/widget.js
Internal (widget): It's now possible to focus a root that has only side image. Closes https://github.com/ckeditor/ckeditor5/issues/16992
---
https://github.com/user-attachments/assets/072b6831-c9c0-4cbe-a139-c78ed178b004
https://github.com/user-attachments/assets/d5d6f768-06a9-470f-9959-20559d17fe94
=> Fix multi-root editor focus root which has side image.

.circleci/template.yml
Internal: Restore the `medium` resource class for the notifier job. See #17011.
---
=> CI: restore "medium" resource class for the notifier job

packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.ts, packages/ckeditor5-ui/tests/toolbar/block/blocktoolbar.js
Fix (ui): Balloon Editor toolbar no longer sticks out of the limiter element while scrolling. Closes https://github.com/ckeditor/ckeditor5/issues/17002
---
https://github.com/user-attachments/assets/6c495658-f549-4d24-9707-277886b28d4a
https://github.com/user-attachments/assets/aeb17168-d7eb-4622-80fc-384dec3145bd
=> Hide block toolbar when disable parent button

packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableediting.css, packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widget.css
Internal (theme-lark): Fix missing border in focused table cells within selection. Closes https://github.com/ckeditor/ckeditor5/issues/16979
---
Caused by: https://github.com/ckeditor/ckeditor5/pull/16880
=> Fix missing border in selected focused table cells

packages/ckeditor5-widget/src/widget.ts, packages/ckeditor5-widget/tests/widget.js
Internal (widget): It's now possible to focus root containing only table of contents or embed elements on Safari. Closes https://github.com/ckeditor/ckeditor5/issues/16978
---
It looks like `caretRangeFromPoint` behaves differently on Chrome and Safari when `click` event target occurs in an element that contains `contenteditable=false`.
On Chrome, `contenteditable=false` is being focused.
On Safari it is not, and it used to focus near `contenteditable=true` in the other root element.
https://github.com/user-attachments/assets/36482ca7-f863-47c3-902c-1b52dea29a9a
https://github.com/user-attachments/assets/8d95c398-cec6-4a0f-8871-f5bda95be549
=> Fix inconsistent behave of `getRangeFromMouseEvent` on Safari

docs/getting-started/integrations/angular.md, docs/getting-started/integrations/react.md, docs/getting-started/integrations/vuejs-v3.md
Docs: Add `Potential issues with Jest testing` section to React integration docs.
---
Related to https://github.com/ckeditor/ckeditor5-react/issues/225
I added this section to address the increasing number of reports regarding issues with Jest testing in React applications. This explanation clarifies the limitations of Jest when used with CKEditor 5 and provides a solution for more accurate testing by using jest-puppeteer or a mock snippet.
=> Docs: Add `Potential issues with Jest testing` React docs section

docs/getting-started/legacy-getting-started/predefined-builds.md, docs/getting-started/legacy-getting-started/quick-start.md
Docs: Hard-code editor version in CDN links to legacy builds.
---
=> Docs: Hard-code editor version in CDN links to legacy builds

docs/getting-started/integrations-cdn/react-default-cdn.md, docs/getting-started/integrations-cdn/vuejs-v3.md, docs/getting-started/integrations/react-default-npm.md, docs/getting-started/integrations/vuejs-v3.md, docs/getting-started/setup/loading-cdn-resources.md
Docs: Update Vue docs for use with npm and CDN.
Docs: Add `Loading CDN resources` page.
---
Internally, we need to decide if we want to promote importing the `<Ckeditor>` component locally or registering it globally and if we should move examples to the Composition API.
=> Update Vue docs for use with npm and CDN

package.json, packages/ckeditor5-ckbox/src/ckboxui.ts, packages/ckeditor5-ckfinder/src/ckfinderui.ts, packages/ckeditor5-code-block/src/codeblockediting.ts, packages/ckeditor5-engine/src/view/observer/selectionobserver.ts, packages/ckeditor5-link/src/utils/manualdecorator.ts, packages/ckeditor5-list/src/list/converters.ts, packages/ckeditor5-ui/src/colorselector/colorgridsfragmentview.ts, packages/ckeditor5-utils/src/count.ts
Internal: Bumps `eslint-config-ckeditor5 version` to 7.0.0 and removes unused variables. Closes #17010.
---
=> Bump eslint-config-ckeditor5 version and remove unused variables

packages/ckeditor5-ckbox/src/ckboximageedit/ckboximageeditcommand.ts, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js, packages/ckeditor5-image/src/image/insertimagecommand.ts, packages/ckeditor5-image/tests/image/insertimagecommand.js
Fix (ckbox): Editing inline images using `CKBox` no longer changes and reinserts them simultaneously. Closes https://github.com/ckeditor/ckeditor5/issues/17056
---
https://github.com/user-attachments/assets/efe3edbf-ae76-4af5-8b09-735a6916a436
https://github.com/user-attachments/assets/0b31cce2-7ee7-454e-8216-5655cc08106a
=> Editing inline images using CKBox changes and reinserts them at the same time

docs/updating/nim-migration/migration-to-new-installation-methods.md, docs/updating/nim-migration/online-builder.md, docs/updating/nim-migration/predefined-builds.md
Docs: Add information about the UMD builds to NIM migration guides.
---
=> Docs: Add information about the UMD builds to NIM migration guides.

packages/ckeditor5-engine/src/view/observer/domeventobserver.ts, packages/ckeditor5-engine/tests/view/observer/domeventobserver.js
Feature (engine): Add `usePassive` option to the `DomEventObserver` that enables listening passive events. Closes https://github.com/ckeditor/ckeditor5/issues/16412
Based on this PR https://github.com/ckeditor/ckeditor5/pull/16466. I added test.
=> Add support for `usePassive` option to the `DomEventObserver`

packages/ckeditor5-media-embed/src/mediaembedediting.ts, packages/ckeditor5-media-embed/tests/mediaembedediting.js
Feature (media-embed): It's now possible to embed YouTube shorts. Closes https://github.com/ckeditor/ckeditor5/issues/17090
=> Allow youtube shorts links in media embed

packages/ckeditor5-engine/tests/view/observer/selectionobserver.js
Tests (engine): Delay selections in `should not enter infinite loop` test due to changes in Chrome 129.
---
It looks like the newest Chrome version debounces `selectionchange` events, and I made a small delay to prevent this. In other words - firing multiple selection updates in small period of the time results in one `selectionchange` event instead of few. 
Fixes:
After bumping Chrome from `128` to `129` in test suite. 
edit: More likely Karma <--> Chrome driver issue, works fine in real browser.
=> Delay selections in `should not enter infinite loop` test due to changes in latest Chrome

docs/framework/contributing/git-commit-message-convention.md, docs/framework/contributing/testing-environment.md
Internal: Added a "Squash commits" section to the "Git commit message convention" guide.
Internal: Removed the `--debug` modifier from the "Running automated tests" section in the "Testing environment" guide as it is not supported after switching sources to TypeScript.
---
=> Dev tools guide updates

packages/ckeditor5-basic-styles/src/index.ts
Other (basic-styles): Export `AttributeCommand` class. Closes https://github.com/ckeditor/ckeditor5/issues/17105
=> Export `AttributeCommand` class from basic styles package

packages/ckeditor5-ui/package.json, packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.ts, packages/ckeditor5-ui/tests/manual/blocktoolbar/blocktoolbar.js, packages/ckeditor5-ui/tests/manual/blocktoolbar/scrollable-blocktoolbar.js, packages/ckeditor5-ui/tests/toolbar/block/blocktoolbar.js
Fix (ui): Fix scrolling in dropdowns when block toolbar button is active. Closes https://github.com/ckeditor/ckeditor5/issues/17067
https://github.com/user-attachments/assets/35409134-1146-4113-a71d-b545d7d64379
https://github.com/user-attachments/assets/f685fdbd-eb13-4f83-b7e7-04a4050b8e10
=> Fix scrolling in dropdowns when block toolbar button is active

packages/ckeditor5-engine/src/model/operation/transform.ts, packages/ckeditor5-engine/src/model/range.ts, packages/ckeditor5-engine/tests/model/operation/transform/undo.js, packages/ckeditor5-engine/tests/model/range.js
Fix (engine): Fixed incorrect marker handling in some scenarios involving undo and real-time collaboration, which earlier lead to `model-nodelist-offset-out-of-bounds` error.
Fix (engine): Fixed incorrect handling of merge changes during undo in some scenarios involving real-time collaboration, which earlier led to `model-nodelist-offset-out-of-bounds` error.
Fix (engine): Fixed conflict resolution error, which led to editor crash in some scenarios where two users removed bigger intersecting part of the content and used undo.
Fix (engine): Fixed incorrect undo behavior leading to an editor crash when a user pressed enter key multiple times, then pressed backspace that many times, then undone all the changes. Closes #9296.
=> Fix MarkerOperation x MoveOperation OT for undo cases

packages/ckeditor5-clipboard/src/index.ts, packages/ckeditor5-image/src/index.ts, packages/ckeditor5-link/src/index.ts
Other (link, image, clipboard): Exported several classes and utilities from ckeditor5-link and ckeditor5-image packages.
---
Related https://github.com/cksource/ckeditor5-commercial/issues/6576.
=> Exported several classes and utilities from various packages

docs/getting-started/advanced/integrating-from-source-webpack.md, docs/getting-started/legacy-getting-started/integrations/react.md, docs/getting-started/legacy-getting-started/integrations/vuejs-v2.md, docs/getting-started/legacy-getting-started/integrations/vuejs-v3.md, docs/getting-started/legacy-getting-started/quick-start-other.md
Internal: Pin the `@ckeditor/ckeditor5-dev-*` packages to v43. See #17203.
---
=> Pin the `@ckeditor/ckeditor5-dev-*` packages to v43

package.json, scripts/release/preparepackages.mjs, scripts/release/publishpackages.mjs
Internal: Improved the `listr2` due to the recent ESM changes.
---
Part of cksource/ckeditor5-internal#3827.
=> Improved the `listr2` due to the recent ESM changes

scripts/ci/check-unit-tests-for-package.mjs, scripts/ci/generate-circleci-configuration.mjs
Internal: Added the retrying test execution mechanism on CI. Closes #17169
---
Added `--retries` process `argv` argument to specify how many times tests should be retries. It's 3 by default.
=> Add retrying CI test support

packages/ckeditor5-list/src/list/listediting.ts, packages/ckeditor5-list/tests/list/integrations/clipboard-single-block.js, packages/ckeditor5-list/tests/list/integrations/clipboard.js, tests/manual/all-features-dll.js, tests/manual/all-features.html, tests/manual/all-features.js
Fix (list): Inserting or dropping a paragraph after the end of a list should not convert the paragraph to a list item. Closes #17224.
---
=> Bookmark insert paragraph fix

packages/ckeditor5-bookmark/src/bookmarkconfig.ts, packages/ckeditor5-bookmark/src/bookmarkediting.ts, packages/ckeditor5-bookmark/tests/bookmarkediting.js, packages/ckeditor5-bookmark/tests/manual/bookmark.js
Internal: Rename config option from `enableNonEmptyBookmarkConversion` to `enableNonEmptyAnchorConversion`.
---
=> [Bookmark] Change config option name.

packages/ckeditor5-bookmark/tests/bookmarkediting.js, packages/ckeditor5-bookmark/tests/manual/bookmark.html, packages/ckeditor5-bookmark/tests/manual/bookmark.js
Internal: Tests for upcast the `blockquote` with `bookmark` inside.
---
_All works as expected, the blockquote is not splitted. The code block tests were dane earlier (added on more test with extended content)._
=> [Bookmark] Tests for upcast blockquote with bookmark inside.

packages/ckeditor5-engine/src/view/domconverter.ts, packages/ckeditor5-engine/tests/view/domconverter/whitespace-handling-integration.js
Fix (engine): The content of an inline object should be handled as a flow root so whitespaces should be trimmed as the content of an inline object element is inside a block element. Closes #17199.
---
=> Fixed handling of whitespaces inside inline objects.

docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md, docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-2.md, docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-3.md, docs/tutorials/crash-course/editor.md, docs/tutorials/creating-simple-plugin-timestamp.md, docs/tutorials/widgets/data-from-external-source.md, docs/tutorials/widgets/implementing-a-block-widget.md, docs/tutorials/widgets/implementing-an-inline-widget.md, docs/tutorials/widgets/using-react-in-a-widget.md
Docs: Use `npx degit` instead of `git clone` in tutorials. See #17182.
=> Use `npx degit` instead of `git clone` in tutorials

packages/ckeditor5-media-embed/docs/_snippets/features/media-embed-preview.html, packages/ckeditor5-media-embed/docs/_snippets/features/media-embed.html
Docs: Remove twitter from media embed docs.
---
Twitter https CORS issue. Let's revert later.
```:x: Access to XMLHttpRequest at 'https://cdn.syndication.twimg.com/tweet-result?features=tfw_timeline_list%3A%3Btfw_follower_count_sunset%3Atrue%3Btfw_tweet_edit_backend%3Aon%3Btfw_refsrc_session%3Aon%3Btfw_fosnr_soft_interventions_enabled%3Aon%3Btfw_mixed_media_15897%3Atreatment%3Btfw_experiments_cookie_expiration%3A1209600%3Btfw_show_birdwatch_pivots_enabled%3Aon%3Btfw_duplicate_scribes_to_settings%3Aon%3Btfw_use_profile_image_shape_enabled%3Aon%3Btfw_video_hls_dynamic_manifests_15082%3Atrue_bitrate%3Btfw_legacy_timeline_sunset%3Atrue%3Btfw_tweet_edit_frontend%3Aon&id=1441013225554948096&lang=en&token=3hr2r84nn4z&4t3d0a=67um8dg6hec6&fhs95v=1g44e8hf095a&5tdnzw=a3i8b8zrlcet&ku3qc9=2p8e0mjvohno& …
```
=> Remove twitter from media embed docs

packages/ckeditor5-media-embed/docs/_snippets/features/media-embed-preview.html, packages/ckeditor5-media-embed/docs/_snippets/features/media-embed.html, packages/ckeditor5-media-embed/docs/features/media-embed.md
Docs: restoring X (Twitter) in demos.
---
=> Docs: restoring X in demos.

packages/ckeditor5-link/src/utils/automaticdecorators.ts, packages/ckeditor5-link/tests/unlinkcommand.js
Fix (link): No longer crash editor after removing link from image when `LinkConfig#addTargetToExternalLinks: true` is set. Closes https://github.com/ckeditor/ckeditor5/issues/17252
---
Decorator responsible for attaching some of the attributes enabled by `addTargetToExternalLinks` is executed _after_ downcast dispatcher responsible for removing `a` elements inside `<figure class="image ..."` element. It caused the crash, because dispatcher `getDispatcherForLinkedImage` assumed that image is always present in decorated element.  Dispatcher responsible for removing `a` tags is defined in `downcastImageLink#221` in `link/linkimageediting.ts` file. 
I did not change priority of dispatchers to avoid other regressions and changes in public API.
=> No longer crash editor after removing link from image when `LinkConfig#addTargetToExternalLinks` is enabled

packages/ckeditor5-ui/src/dialog/dialogview.ts, packages/ckeditor5-ui/tests/dialog/dialogview.js, packages/ckeditor5-ui/theme/components/dialog/dialog.css
Other (ui): Disabled dragging support for modal windows. Closes #17290.
Other (ui): Disabled positioning restrictions for modal windows caused by `config.ui.viewportOffset`. Closes #17290.
=> Modal window positioning and UX improvements

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dialog/dialog.css, packages/ckeditor5-ui/src/dialog/dialog.ts, packages/ckeditor5-ui/tests/dialog/dialog.js
Internal (ui): Moved the document scroll lock for modal windows from `<body>` to `<html>` to make it bulletproof. Closes #17298.
=> Moved the document scroll lock for modal windows from <body> to <html>

packages/ckeditor5-bookmark/src/bookmarkediting.ts, packages/ckeditor5-bookmark/src/bookmarkui.ts
Fix (bookmarks): Avoid global state to improve icons tree-shaking.
---
Two global variables in the new bookmarks plugin prevented the `icons` object from the `core` package from being properly tree-shaken.
=> Fix: Avoid global state to improve icons tree-shaking.

packages/ckeditor5-ui/src/dialog/dialogview.ts, packages/ckeditor5-ui/tests/dialog/dialogview.js, packages/ckeditor5-ui/tests/manual/dialog/dialog-esc-key-handling.html, packages/ckeditor5-ui/tests/manual/dialog/dialog-esc-key-handling.md, packages/ckeditor5-ui/tests/manual/dialog/dialog-esc-key-handling.ts
Fix (ui): The dialog plugin should not handle Esc key press when default-prevented by the guest view. Closes #17343.
=> The dialog plugin should not handle Esc key press when default-prevented by the guest view

packages/ckeditor5-link/src/linkui.ts, packages/ckeditor5-link/tests/linkui.js
Other (link): Hide the settings button if there are no manual decorators. See #17230
=> Hide the settings button if there are no manual decorators.

packages/ckeditor5-editor-classic/src/classiceditorui.ts, packages/ckeditor5-editor-classic/tests/classiceditorui.js
Fix (editor-classic): Excluded modal windows from the Classic editor's integration between dialogs and the sticky toolbar. Closes #17339.
=> Excluded modal windows from the Classic editor's integration with dialogs

packages/ckeditor5-utils/src/dom/scroll.ts, packages/ckeditor5-utils/tests/dom/scroll.js
Fix (utils): No longer scroll to the top of the document if pasted element is larger than scrollable editable. Closes https://github.com/ckeditor/ckeditor5/issues/17079
---
It looks like `scrollWindowToShowRect` assumes that passed target elements entirely fits in the first scrollable parent _viewport rect_, which is not true for large tables (or any other widgets) pasted into editable. These pasted elements often are large enough to have a huge negative `top` position value that is calculated from the top of the viewport. It was causing `window.scrollTo` to fallback scroll to `0` top offset.
This PR enforces scrollable target rect to be the size of the first scrollable ancestor if it overflows it. 
https://github.com/user-attachments/assets/b188b75c-0c25-43ce-8f37-fdff2efcdefc …
=> No longer scroll to the top of the document if pasted element is larger than scrollable editable.

packages/ckeditor5-editor-balloon/src/ballooneditor.ts, packages/ckeditor5-editor-classic/src/classiceditor.ts, packages/ckeditor5-editor-decoupled/src/decouplededitor.ts, packages/ckeditor5-editor-inline/src/inlineeditor.ts, packages/ckeditor5-editor-multi-root/src/multirooteditor.ts
Internal: Fix incorrect `inheritDoc` comment above editor name.
=> Fix incorrect `inheritDoc` comment above editor name.

packages/ckeditor5-link/lang/contexts.json, packages/ckeditor5-link/src/linkui.ts, packages/ckeditor5-link/src/ui/linkadvancedview.ts, packages/ckeditor5-link/tests/linkui.js, packages/ckeditor5-link/tests/ui/linkadvancedview.js
Other (link): Rename the `cancel` event to `back` in `LinkAdvancedView`. See  #17230.
=> Rename the `cancel` event to `back` in `LinkAdvancedView`

packages/ckeditor5-mention/src/mentioncommand.ts, packages/ckeditor5-mention/src/mentionui.ts, packages/ckeditor5-mention/tests/mentioncommand.js, packages/ckeditor5-mention/tests/mentionui.js
Feature (mention): Allow for the mention marker to be longer than 1 character.
---
=> Allow for mentions markers to be longer than 1 character

docs/framework/development-tools/package-generator/javascript-package.md, docs/framework/development-tools/package-generator/typescript-package.md
Docs: Aligned docs for changes in `ckeditor/ckeditor5-package-generator` that uses now Vitest instead of Karma for running unit tests.
---
Related changes in `ckeditor/ckeditor5-package-generator`: https://github.com/ckeditor/ckeditor5-package-generator/pull/187
=> Aligned docs for changes in package generator

packages/ckeditor5-link/src/index.ts
Fix (link): Revert adding icons re-export. See #17358.
---
:warning: This PR targets the `release` branch :warning:
=> Revert adding icons re-export

packages/ckeditor5-core/src/editor/utils/editorusagedata.ts, packages/ckeditor5-core/tests/editor/utils/editorusagedata.js
Internal (core): Removes dependence on `crypto.randomUUID`.
---
`crypto.randomUUID` is not available outside secure context (localhost or https).
=> Remove dependence on randomUUID

docs/getting-started/integrations-cdn/quick-start.md, docs/getting-started/integrations/quick-start.md, docs/getting-started/legacy-getting-started/quick-start.md, docs/getting-started/licensing/license-key-and-activation.md, packages/ckeditor5-ckbox/docs/features/ckbox.md, packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/src/editor/editorconfig.ts
Internal: Adjust license key comment, update trial signup links in docs.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6755
=> Adjust license key comment, update links in docs.

scripts/dll/webpack.config.dll.mjs
Internal: Fixed `dll:build` script not working on Windows. Closes #17401.
---
=> Fixed `dll:build` script not working on Windows

packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts, packages/ckeditor5-find-and-replace/src/findandreplacestate.ts, packages/ckeditor5-find-and-replace/src/replacecommand.ts, packages/ckeditor5-find-and-replace/tests/ui/findandreplaceformview.js
Fix (find-and-replace): Find and replace no longer randomly jumps to the first found item after the replace operation. Closes https://github.com/ckeditor/ckeditor5/issues/16648
---
After removal of marker, we used to reset search to the first changed item.  It's buggy because changed items refer to search results affected by the update algorithm, which used to change found elements, even if they were not replaced. It caused "random" jumps between items after replace. 
The example might be this list of results:
I replaced one word in a paragraph containing few search results with `2`, `3` and `4` indices. It updated item with `3` index, but it turns out that algorithm updated also items with `2` i `4` IDs. It's counterintuitive, and leaded to the incorrect assumption in the editing flow …
=> No longer jump to the first item after replacing phrase

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/menubar/menubarmenubutton.css
Fix (theme-lark): Letter descenders should not be clipped in the top-level menu bar categories. Closes #17422.
---
https://github.com/user-attachments/assets/56abd62e-65c1-4c9d-8d6f-82227ff13d25
=> Letter descenders should not be clipped in the top-level menu bar categories

packages/ckeditor5-core/src/editor/editor.ts
Docs: Fix wrong rendering error codes in docs.
---
=> Fix wrong rendering error codes in docs.

packages/ckeditor5-clipboard/src/dragdroptarget.ts, packages/ckeditor5-clipboard/tests/dragdroptarget.js
Fix (clipboard): An in-text drop of an inline object with elements inside should be possible. Closes #16101.
---
=> Fixed dragging inline object with content.

docs/getting-started/legacy-getting-started/integrations/vuejs-v2.md, docs/getting-started/legacy-getting-started/integrations/vuejs-v3.md
Docs: Rename `configure` to `config` in Vite Webpack docs. Closes https://github.com/ckeditor/ckeditor5/issues/17402
Docs: Add missing SVG exclude to Webpack configuration in Vite docs.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6769, https://github.com/cksource/ckeditor5-commercial/issues/6769
=> Update Vite webpack docs.

packages/ckeditor5-engine/src/model/operation/transform.ts, packages/ckeditor5-engine/tests/model/operation/transform/undo.js
Fix (engine): Fixed editor crash after pasting over previously pasted content and undoing both actions. Closes #17267.
=> Fixed editor crash after pasting over previously pasted content and undoing both actions

packages/ckeditor5-core/src/editor/utils/editorusagedata.ts, packages/ckeditor5-core/tests/editor/licensecheck.js
Internal: Rename `integrations` to `integration` usage data format.
=> Fix wrong integrations key name in license checks.

packages/ckeditor5-engine/src/model/operation/transform.ts, packages/ckeditor5-engine/tests/model/operation/transform/undo.js
Revert: Fixed editor crash after pasting over previously pasted content and undoing both actions (ckeditor/ckeditor5#17427).
=> Revert "Fixed editor crash after pasting over previously pasted content and undoing both actions"

packages/ckeditor5-ui/src/editorui/bodycollection.ts, packages/ckeditor5-ui/tests/editorui/bodycollection.js
On pages with lots of content and a large number of editors being created at once, the `querySelector` in `attachToDom()` shows up as a non-trivial in performance profiling. The `ck-body-wrapper` element is always added as a direct child of the `body`, so we can speed up the lookup a lot by just iterating over the children of the `body` rather than running `querySelector()`.
=> Optimize body wrapper lookup

packages/ckeditor5-markdown-gfm/src/index.ts
Internal (markdown-gfm): Export `GFMDataProcessor` and `MarkdownToHtml` from package. Closes https://github.com/ckeditor/ckeditor5/issues/17395
=> Export `GFMDataProcessor` and `MarkdownToHtml` from `ckeditor5-markdown-gfm`

packages/ckeditor5-ui/src/editorui/bodycollection.ts, packages/ckeditor5-ui/tests/editorui/bodycollection.js
Internal (ui): `BodyCollection#attachToDom()` should create another wrapper if the previous one got disconnected from DOM.
---
* This is related to https://github.com/ckeditor/ckeditor5/pull/17321.
* This PR addresses the failing tests after ☝️ when running the CI in the whole-project-production mode `yarn run test --repositories=ckeditor5 --production --reporter=dots --browsers=ChromeHeadless`.
* The previous PR removed [the code that blindly re-created the `.ck-body-wrapper` whenever it was not found in DOM](https://github.com/ckeditor/ckeditor5/pull/17321/files#diff-8d63c3c62f81def6671131d89c046acd07efae17491403c4cbc009e8957ecde0L85-L87).
* That blind logic turned out to be relevant in our CI environment which I didn't realize. 
* [There's a test helper that cleans all remaining …
=> BodyCollection#attachToDom() should create another wrapper if the previous one got disconnected from DOM

docs/getting-started/integrations-cdn/react-default-cdn.md, docs/getting-started/integrations-cdn/vuejs-v3.md, scripts/release/assets/zip/index.html
Docs: Add Vue 3.x TS CDN section.
+ minor fix in the ZIP index file
=> Add Vue 3.x / React TS docs section.

packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/tests/editor/licensecheck.js
Internal: Watchdog should not restart the editor when there are license-related errors.
---
=> Don't restart editor by watchdog after license-related errors.

packages/ckeditor5-image/src/imageupload/imageuploadediting.ts, packages/ckeditor5-image/tests/imageupload/imageuploadediting.js
Fix (upload): Editor should no longer crash when executing undo while an image is still being uploaded.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6817
It looks like `undo` moves uploaded node to graveyard, which causes abort image uploading here:
https://github.com/ckeditor/ckeditor5/blob/ck/6817/packages/ckeditor5-image/src/imageupload/imageuploadediting.ts#L227
```
if ( isInsertedInGraveyard ) {
// If the image was inserted to the graveyard for good (**not** replaced by another image),
// only then abort the loading process.
if ( !insertedImagesIds.has( uploadId ) ) {
loader.abort();
}
} else {
```
which causes `aborted` exception, that is caught here:
https://github.com/ckeditor/ckeditor5/blob/ck/6817/packages/ckeditor5-image/src/imageupload/imageuploadediting.t …
=> No longer abort already destroyed `FileLoader` in `FileRepository`.

packages/ckeditor5-utils/src/inserttopriorityarray.ts
Fix (utils): Use binary search in `insertToPriorityArray()` for better performance when handling big tables.
---
Reduces the time needed to render a table in the `tableHuge` test by ~67%.
=> Use binary search in `insertToPriorityArray`

packages/ckeditor5-cloud-services/src/token/token.ts, packages/ckeditor5-cloud-services/tests/token/token.js
Fix (cloud-services): Handle refresh token when editor destroyed during token fetching. Closes #17462.
---
The issue was caused by the race condition when token fetching request is initialized, editor is destroyed in the meantime and then the request rejects, reinitiating the token refresh logic.
I added `Token._isDestroyed` property to abort all further refresh action when token is already destroyed.
=> Handle refresh token when editor destroyed during token fetching

docs/features/feature-digest.md, docs/getting-started/licensing/license-and-legal.md, docs/getting-started/licensing/license-key-and-activation.md, docs/getting-started/licensing/usage-based-billing.md, docs/getting-started/setup/loading-cdn-resources.md, docs/getting-started/setup/typescript-support.md, package.json, packages/ckeditor5-bookmark/docs/features/bookmarks.md
=> Bumping dates in docs

scripts/docs/snippetadapter.mjs
Internal: Search for package dependencies in snippet adapter only in known directories where package can exist.
---
Closes cksource/ckeditor5-internal#3881.
=> Search for package dependencies in snippet adapter only in known directories where package can exist

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/icon/icon.css
Fix(theme-lark):Should prevent of blurry the UI icons while zooming in the page. Closes #17510.
---
=> Stop blurry in the UI icons while zooming in the browser.

packages/ckeditor5-find-and-replace/package.json, packages/ckeditor5-find-and-replace/src/findandreplaceutils.ts, packages/ckeditor5-find-and-replace/tests/findandreplaceediting.js
Fix (find-and-replace): It should be possible to search within content of inline widgets. Closes #11162 
---
Looks like [proposed solution works](https://github.com/ckeditor/ckeditor5/issues/11162), I added test.
=> It should be possible to search within content of inline widgets.

docs/getting-started/index.md, docs/getting-started/licensing/license-and-legal.md, docs/getting-started/licensing/usage-based-billing.md
Docs: Updated license terms docs based on content from ckeditor.com.
---
I de-title-cased two titles.
=> Updated license terms docs based on content from ckeditor.com

packages/ckeditor5-engine/src/conversion/mapper.ts
Other (engine): Improve performance of the `getModelLength` method.
---
While this looks like a simple change, it introduces significant performance improvements by avoiding recursion and calling `this._viewToModelLengthCallbacks.get()` on nodes without name or when the map is empty (most cases).
| Test name                    	| Improvement in % 	| Improvement in ms 	|
|------------------------------	|-----------------:	|------------------:	|
| `lists`                      	|            -4.9% 	|            -100ms 	|
| `formatting-long-paragraphs` 	|           -15.0% 	|            -730ms 	|
| `inline-styles`              	|           -22.2% 	|           -2310ms 	|
| `wiki`                       	|            -4.0% 	|            -140ms 	|
We could gain even more performance by removing the …
=> Improve mapper performance

docs/getting-started/licensing/usage-based-billing.md, docs/updating/update-to-44.md
Docs: update to v44 guide.
---
=> Docs: update to v44 guide.

packages/ckeditor5-list/src/list/converters.ts, packages/ckeditor5-list/src/list/utils/listwalker.ts, packages/ckeditor5-list/src/list/utils/model.ts, packages/ckeditor5-list/src/list/utils/postfixers.ts, packages/ckeditor5-list/tests/list/utils/postfixers.js
Other (list): Use iterator instead of generator in ListWalker for better performance.
---
The generator introduces some unnecessary overhead. This PR makes the `lists` performance demo 9% faster.
=> Use iterator instead of generator in ListWalker for better performance.

packages/ckeditor5-bookmark/src/bookmarkui.ts, packages/ckeditor5-bookmark/tests/bookmarkui.js
Fix(bookmark): Should return focus to editor after deleting the bookmark.
---
=> Return focus to editable after executing a delete command.

packages/ckeditor5-bookmark/src/bookmarkui.ts, packages/ckeditor5-bookmark/src/ui/bookmarkformview.ts, packages/ckeditor5-bookmark/tests/bookmarkui.js, packages/ckeditor5-bookmark/tests/ui/bookmarkformview.js, packages/ckeditor5-image/src/imageresize/imageresizebuttons.ts, packages/ckeditor5-image/src/imageresize/resizeimagecommand.ts, packages/ckeditor5-image/tests/imageresize/imageresizebuttons.js, packages/ckeditor5-image/tests/manual/imageresizebuttons.js, packages/ckeditor5-image/tests/manual/textalternative.js, packages/ckeditor5-link/src/linkui.ts, packages/ckeditor5-link/src/ui/linkformview.ts, packages/ckeditor5-link/tests/linkui.js, packages/ckeditor5-link/tests/ui/linkformview.js, packages/ckeditor5-theme-lark/theme/ckeditor5-bookmark/bookmarkform.css, packages/ckeditor5-theme-lark/theme/ckeditor5-link/linkform.css
Internal (bookmark, link, image): Do not show back button if balloon was not opened using another balloon.
Fix (image): No longer crash editor when using image resize buttons in toolbar. 
Take a look at back button arrows.
https://github.com/user-attachments/assets/f5964832-3b2f-4fce-9078-3c61ee0355b8
https://github.com/user-attachments/assets/850dca9c-f012-4348-94d8-edd6b59caba8
=> Do not show back button if balloon was not opened using another balloon.

packages/ckeditor5-font/tests/integration.js, packages/ckeditor5-ui/src/colorpicker/utils.ts, packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js, packages/ckeditor5-ui/tests/colorselector/colorselectorview.js
Fix (ui): No longer add surrounding spaces to colors produced by hex inputs. Closes https://github.com/ckeditor/ckeditor5/issues/17386
=> Make the format color more consistent across UI.

packages/ckeditor5-link/src/linkui.ts, packages/ckeditor5-link/tests/linkui.js
Internal (link): Open link form on top of the link toolbar if user clicked toolbar button on selected link. Focus no longer stays in link toolbar.
---
Part of #17230 
https://github.com/user-attachments/assets/d0e86583-9115-4b9a-a9eb-b4d6654a4121
https://github.com/user-attachments/assets/5e0eec5a-dac4-4faa-8eb0-96989401ff03
=> Show link form on second click in toolbar.

packages/ckeditor5-link/src/index.ts
This adds the `ensureSafeUrl` export to the `ckeditor5-link` package in the same vein as a couple of the other link utilities (i.e. `addLinkProtocolIfApplicable`, `isLinkableElement`). The `ensureSafeUrl` is useful sanitization logic when building a custom UI around CKEditor5.
Commit message:
Other (link): Exported `ensureSafeUrl` icons from ckeditor5-link package.
=> Feature (ckeditor5-link): Add ensureSafeUrl to exports.

packages/ckeditor5-clipboard/src/clipboardpipeline.ts, packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts, packages/ckeditor5-clipboard/tests/clipboardpipeline.js, packages/ckeditor5-clipboard/tests/utils/viewtoplaintext.js, packages/ckeditor5-image/src/image/imageblockediting.ts
Feature (clipboard): Pass information to the downcast converter when clipboard pipeline is used to allow for customization.
Feature (clipboard): `viewToPlainText()` helper will now parse the view `RawElement` instances.
---
=> Pass information to the downcast converter when clipboard pipeline is used

packages/ckeditor5-emoji/src/emojimention.ts, packages/ckeditor5-emoji/tests/emojimention.js
Internal: Fixed the `EmojiFeed` plugin showing feeds when the first character is empty space. Closes #17577.
---
=> Fixed the `EmojiFeed` plugin showing feeds when the first character is empty space.

packages/ckeditor5-table/lang/translations/uk.po
Internal (table): Improved the `uk` translations. Closes #17614.
Thanks, @iskatel-ua.
---
the translations were mixed up which misleads the user
=> little mistake ukrainian lang

packages/ckeditor5-list/src/list/converters.ts, packages/ckeditor5-list/src/list/listediting.ts, packages/ckeditor5-list/src/list/utils/postfixers.ts, packages/ckeditor5-list/tests/list/utils/postfixers.js
Other (list): Skip already visited list elements during reconversion and post fixing for better performance. Fixes #17625.
---
This change makes the `lists` performance demo ~18% faster.
=> Skip already visited list elements during reconversion and post fixing

packages/ckeditor5-emoji/src/emojimention.ts, packages/ckeditor5-emoji/tests/emojimention.js
Internal: Not initializing emoji plugin when merge fields use `:` as first char in prefix. Closes #17591
---
=> Not initializing emoji plugin when merge fields use `:` as first char in prefix.

packages/ckeditor5-engine/src/index.ts, packages/ckeditor5-engine/src/view/observer/touchobserver.ts, packages/ckeditor5-engine/tests/view/observer/touchobserver.js, packages/ckeditor5-typing/src/twostepcaretmovement.ts, packages/ckeditor5-typing/tests/twostepcaretmovement.js
Fix (typing): Fix not working two-step caret movement on iOS devices. Closes https://github.com/ckeditor/ckeditor5/issues/17171
---
It looks like `mousedown` events behaves differently on iOS and Android. On iOS, it's called **after** selection change, but on Android it's called immediately after `touchstart` which happens **before** selection change.  I added `touchstart` event observer, to track clicks before selection change occurs.
=> Fix not working two step caret movement on iOS devices.

packages/ckeditor5-list/src/legacylistproperties/legacylistpropertiesediting.ts, packages/ckeditor5-list/src/listproperties/listpropertiesediting.ts, packages/ckeditor5-list/src/listproperties/listpropertiesui.ts, packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts, packages/ckeditor5-list/src/listproperties/utils/style.ts, packages/ckeditor5-list/tests/legacylistproperties/legacylistpropertiesediting.js, packages/ckeditor5-list/tests/listproperties/converters.js, packages/ckeditor5-list/tests/listproperties/listpropertiesediting.js, packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js, packages/ckeditor5-list/tests/listproperties/utils/style.js, packages/ckeditor5-paste-from-office/tests/_data/list/many-one-item/model.word2016.html, packages/ckeditor5-paste-from-office/tests/_data/list/multi-block-block-after/model.word.html, packages/ckeditor5-paste-from-office/tests/_data/list/multi-block/model.word.html, packages/ckeditor5-paste-from-office/tests/_data/list/nested-multiple/model.word2016.html, packages/ckeditor5-paste-from-office/tests/_data/list/nested/model.word2016.html
Feature (list): Add support for `lower-alpha` / `upper-alpha` list type highlighting in list style properties buttons. Closes https://github.com/ckeditor/ckeditor5/issues/17424
Fix (list): The list style buttons should show proper list type after clicking list for the first time.
MINOR BREAKING CHANGE (list): `lower-alpha` and `upper-alpha` list styles are now upcasted to `lower-latin` and `upper-latin` styles.
---
According to https://www.w3.org/TR/1998/PR-CSS2-19980324/lists.html#list-props:
```
lower-latin or lower-alpha
Lower case ascii letters (a, b, c, ... z). 
upper-latin or upper-alpha
Upper case ascii letters (A, B, C, ... Z). 
```
So it's valid to highlight the same list style property button.
https://github.com/user-attachments/assets/387bf1c1-98f4-4a13-a424-46618dad1027 …
=> Add support for `latin-alpha` / `upper-alpha` list type highlighting in list style properties buttons.

packages/ckeditor5-table/src/converters/upcasttable.ts, packages/ckeditor5-table/tests/converters/upcasttable.js
Fix (table): Prevent table corruption when setting editor data with `th` cells following `colspan` rows. Closes #17556, #17404
---
Our table upcasting does not recognize colspans correctly during calculation of the header rows. This PR ensures that rows that follow the rows with colspans are not longer used as table headings.
<details>
<summary>Check this HTML</summary>
```html
<figure class="table">
<table>
<tbody>
<tr>
<th>&nbsp;</th>
<td colspan="2" rowspan="2">&nbsp;</td>
</tr>
<tr>
<th>&nbsp;</th>
</tr>
<tr>
<th>&nbsp;</th>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
</figure>
<figure class="table">
<table>
<tbody>
<tr>
<th>&nbsp;</th>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr>
<th>&nbsp;</th>
<td colspan="2" rowspan="2">&nbsp;</td>
</tr>
<tr>
<th>&nbsp;</th>
</tr>
<tr> …
```
=> Fix incorrect upcast scan table heuristics responsible for creating heading rows.

packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/tests/editor/licensecheck.js
Internal: Update the logic of the license check.
---
=> Internal: Update the logic of the check.

packages/ckeditor5-html-support/docs/features/general-html-support.md
Docs: updating known issues.
---
=> Docs: updating known issues.

packages/ckeditor5-emoji/src/emojipicker.ts, packages/ckeditor5-emoji/src/ui/emojicategoriesview.ts, packages/ckeditor5-emoji/src/ui/emojigridview.ts, packages/ckeditor5-emoji/src/ui/emojiinfoview.ts, packages/ckeditor5-emoji/src/ui/emojipickerview.ts, packages/ckeditor5-emoji/src/ui/emojisearchview.ts, packages/ckeditor5-emoji/src/ui/emojitoneview.ts, packages/ckeditor5-emoji/tests/emojipicker.js, packages/ckeditor5-emoji/tests/manual/emoji.js, packages/ckeditor5-emoji/tests/ui/emojicategoriesview.js, packages/ckeditor5-emoji/tests/ui/emojigridview.js, packages/ckeditor5-emoji/tests/ui/emojiinfoview.js, packages/ckeditor5-emoji/tests/ui/emojipickerview.js, packages/ckeditor5-emoji/tests/ui/emojisearchview.js, packages/ckeditor5-emoji/tests/ui/emojitoneview.js, packages/ckeditor5-emoji/theme/emojicategories.css, packages/ckeditor5-emoji/theme/emojigrid.css, packages/ckeditor5-emoji/theme/emojiinfo.css, packages/ckeditor5-emoji/theme/emojipicker.css, packages/ckeditor5-emoji/theme/emojitone.css, packages/ckeditor5-theme-lark/theme/ckeditor5-emoji/emoji.css, packages/ckeditor5-theme-lark/theme/ckeditor5-emoji/emojigrid.css, packages/ckeditor5-theme-lark/theme/ckeditor5-emoji/emojiinfo.css
Internal: Added fake selection to emoji plugin. Closes #17654.
---
=> Added fake selection to emoji plugin

scripts/docs/utils.mjs
Internal: Use `import.meta.resolve` instead of `require.resolve`. Fixes #17671.
---
We've added the `exports` field to the `package.json` files with `types` and `import` fields, but no `require` because our packages are ESM-only. This is the reason for the `require.resolve` call fails.
=> Internal: Use `import.meta.resolve` instead of `require.resolve`.

packages/ckeditor5-table/docs/features/tables-styling.md
Docs: Config snippet with setting the default table and table cell styles should work as expected.
---
:warning: _target: `stable` branch_
=> Fixed properly closing brackets in styling table snippet.

scripts/release/utils/updatepackageentrypoint.mjs
Internal: Add `default` to `exports` entries in `package.json` files. Fixes #17671.
---
In a few places in our tools, we use `require` instead of `import` to get data from packages. Instead of fixing all of them and potentially introducing breaking changes, it's easier to add a fallback `default` entry to the `exports` field.
=> Fix: Add `default` to `exports` entries in `package.json` files.

packages/ckeditor5-link/src/linkcommand.ts, packages/ckeditor5-link/tests/linkcommand.js, packages/ckeditor5-link/tests/linkui.js, packages/ckeditor5-link/tests/manual/link.html, packages/ckeditor5-link/tests/manual/link.js, packages/ckeditor5-typing/src/twostepcaretmovement.ts
Feature (link): Formatting is no longer lost after changing a URL or a displayed-text of the selected link.
=> Partial update of link text with attributes preservation.

packages/ckeditor5-engine/src/model/selection.ts, packages/ckeditor5-engine/src/model/treewalker.ts, packages/ckeditor5-engine/src/view/treewalker.ts, packages/ckeditor5-engine/tests/model/treewalker.js, packages/ckeditor5-engine/tests/view/treewalker.js
Other (engine): Improve performance of `getSelectedBlocks` when selection contains only one block element. Closes #17629.
---
This greatly improves how long it takes to make a selection over a big table.
---
Use `Squash and merge`, as it's a fairly simply change with too many commits.
=> Improve performance of `getSelectedBlocks`

packages/ckeditor5-link/src/autolink.ts, packages/ckeditor5-link/tests/autolink.js
Fix (link): Trailing punctuation is no longer included in auto-linked URL. Closes https://github.com/ckeditor/ckeditor5/issues/14497
---
https://github.com/user-attachments/assets/c3a9f78d-5a4d-4974-b0c0-178074c80866
https://github.com/user-attachments/assets/17327e56-b67c-4d78-8e47-c7913a74fb76
=> Add punctuation support in auto-links.

packages/ckeditor5-ui/src/dialog/dialog.ts, packages/ckeditor5-ui/tests/dialog/dialog.js
Fix (ui): Destroying another editor instance while modal is open will no longer unlock page scroll. Closes #17585.
---
=> Add a condition for reenabling the page scroll when Dialog plugin is destroyed

packages/ckeditor5-emoji/src/ui/emojiinfoview.ts, packages/ckeditor5-emoji/tests/ui/emojiinfoview.js
Internal: Removed unicode characters from the bottom of emoji picker. Closes #17655.
---
=> Removed unicode characters from the bottom of emoji picker.

packages/ckeditor5-cloud-services/src/cloudservices.ts, packages/ckeditor5-cloud-services/tests/cloudservices.js
Fix (cloud-services): No longer keep refreshing token if `tokenUrl` method failed in the initialization of the plugin. Closes https://github.com/ckeditor/ckeditor5/issues/17531
---
Related to https://github.com/ckeditor/ckeditor5/issues/17462. 
The `init` method of the `Token` tries to initialize the token, but if the first initialization fails (that one in `init` of `cloud-services`) it keeps the refresh interval running after destroying of the editor. The editor was destroyed because `Token.init` throws exception directly in `cloud-services` init method (which leads to editor crash).
=> Do not attach refresh token interval if initialization of token failed in `init()` method of `CloudServices` plugin.

packages/ckeditor5-link/src/ui/linkformview.ts, packages/ckeditor5-link/tests/ui/linkformview.js
Fix (link): Remove tooltip from save button in link form view. 
---
Incorrect tooltip:
=> Remove tooltip from `insert` / `update` link form save button. 

packages/ckeditor5-emoji/src/emojipicker.ts, packages/ckeditor5-emoji/src/ui/emojicategoriesview.ts, packages/ckeditor5-emoji/tests/emojipicker.js, packages/ckeditor5-emoji/tests/ui/emojicategoriesview.js
Internal: Storing selected emoji category in state so that it is restored when emoji picker is reopened. Closes #17657.
---
=> Storing selected emoji category in state so that it is restored when emoji picker is reopened.

packages/ckeditor5-emoji/src/ui/emojisearchview.ts, packages/ckeditor5-emoji/tests/ui/emojisearchview.js
Internal: Fixed reset button not resetting the emoji picker state. See #17659.
---
=> Fixed reset button not resetting the emoji picker state.

packages/ckeditor5-upload/src/adapters/simpleuploadadapter.ts, packages/ckeditor5-upload/src/uploadconfig.ts, packages/ckeditor5-upload/tests/adapters/simpleuploadadapter.js
Feature (upload): It should now be possible to pass the callback to the `SimpleUploadConfig#headers` property. Closes https://github.com/ckeditor/ckeditor5/issues/15693
=> It should now be possible to pass the callback to the `SimpleUploadConfig#headers` property.

packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/tests/editor/licensecheck.js
Internal (editor): Do not append `.` character after portal link.
=> Remove `.` from editor warning.

packages/ckeditor5-engine/src/model/batch.ts, packages/ckeditor5-engine/src/model/operation/operation.ts, packages/ckeditor5-engine/tests/model/model.js, packages/ckeditor5-engine/tests/model/utils/getselectedcontent.js, packages/ckeditor5-engine/tests/model/writer.js
Other (engine): Do not store non-document operation with batches. This improves memory efficiency for huge documents. Closes #17678.
---
To verify correctness of this change, I checked three things:
*   All places where we add `applyOperation` listener. All places except of two filter non-document operations. One place is legacy lists, I skipped it. Other place is in commercial repo. The listener can work like it does but I will create a PR to fix it. This confirms, that we generally do not care about these operations.
*   I checked uses of `Batch#operations` to see if there are risky places where we might check the contents of `operations` for _reasons_. We do it very rarely. The places where we do it, it is fine after the change.
*   I checked uses of `Operation#batch`. This property is …
=> Do not store non-document operation with batches

packages/ckeditor5-engine/src/model/operation/operation.ts
Docs (engine): Fix incorrect API docs.
=> Fix incorrect API docs

packages/ckeditor5-editor-balloon/tests/ballooneditorui.js, packages/ckeditor5-editor-classic/tests/classiceditorui.js, packages/ckeditor5-editor-decoupled/tests/decouplededitorui.js, packages/ckeditor5-editor-inline/src/inlineeditorui.ts, packages/ckeditor5-editor-inline/tests/inlineeditorui.js, packages/ckeditor5-editor-multi-root/src/multirooteditorui.ts, packages/ckeditor5-editor-multi-root/tests/multirooteditorui.js
Fix (editor-inline, editor-multi-root):  No longer crash the editor during `destroy()` when the editable was manually detached before destroying. Closes https://github.com/ckeditor/ckeditor5/issues/16561
---
Some editor types check if elements exist before destroying, while others don't. Here's what works correctly:
https://github.com/ckeditor/ckeditor5/blob/ck/16561/packages/ckeditor5-editor-classic/src/classiceditorui.ts#L141-L143
https://github.com/ckeditor/ckeditor5/blob/ck/16561/packages/ckeditor5-editor-balloon/src/ballooneditorui.ts#L102-L104
https://github.com/ckeditor/ckeditor5/blob/ck/16561/packages/ckeditor5-editor-decoupled/src/decouplededitorui.ts#L96-L98
These editors don't have the checks yet:
https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-editor-inline …
=> No longer crash during `destroy()` of `MultiRootEditor` or `InlineEditor` when the editable was detached manually before destroying.

packages/ckeditor5-theme-lark/theme/ckeditor5-bookmark/bookmark.css
Fix (bookmark): Prevent bookmark popup flickering when clicking paragraphs with trailing bookmarks.
---
When a widget (e.g., a bookmark anchor) is clicked, two consecutive `update` events may fire:
1. First, when the widget gets focused (this is fine)
3. Second, when the selection changes shortly after (beware, dragons live here)
While the widget usually stays selected, sometimes the selection may move to a different element (e.g., to the start of the parent paragraph). This can cause the toolbar to flicker as it's quickly shown and hidden.
This issue particularly affects widgets like anchors that contain a single SVG element. 
Making the element `inline-block` seems to reduce flickering. 
https://github.com/user-attachments/assets/c931542c-fe3a-439a-9cf8-2070355d72a9 …
=> Prevent bookmark popup flickering when clicking paragraphs with trailing bookmarks.

packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js, packages/ckeditor5-engine/src/view/placeholder.ts, packages/ckeditor5-engine/tests/view/placeholder.js, packages/ckeditor5-image/src/imagesizeattributes.ts, packages/ckeditor5-image/tests/imagesizeattributes.js, tests/_data/data-sets/ghs.js, tests/_data/data-sets/index.js
Other (engine): Improve performance of the placeholders.
Other (image): Attribute `loading="lazy"` will be automatically added in editing view to images with `height` and `width` attributes set to improve loading performance.
Tests: Added new `ghs` manual performance test.
MINOR BREAKING CHANGE (image): Starting from this release, images that have `height` and `width` attributes set will automatically receive `loading="lazy"` attribute in the editing area. This happens only for the content loaded into the editor, the data output produced by the editor remains the same. The reason for this change is to improve user experience in documents that may contain hundreds of images.
---
This is a continuation of #17589.
When looking at the numbers reported by the performance tests, we can see that …
=> Improve performance of placeholder and add ghs performance test

packages/ckeditor5-table/src/tablecellproperties/ui/tablecellpropertiesview.ts, packages/ckeditor5-table/src/tableproperties/ui/tablepropertiesview.ts, packages/ckeditor5-table/src/utils/ui/table-properties.ts, packages/ckeditor5-table/tests/tablecellproperties/ui/tablecellpropertiesview.js, packages/ckeditor5-table/tests/tableproperties/ui/tablepropertiesview.js, packages/ckeditor5-ui/src/toolbar/toolbarview.ts, packages/ckeditor5-ui/tests/toolbar/toolbarview.js
Feature (table): Improve aria attributes in table and cell align toolbars. Closes #17722
---
I added role `role=radiogroup` and `role=radio` to table properties radio buttons like this one:
It means that `pressed` state of button will be indicated in `aria-checked` attribute.
=> Add `aria-checked` attribute to align toolbars in table properties.

packages/ckeditor5-clipboard/src/clipboardpipeline.ts, packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts, packages/ckeditor5-clipboard/tests/clipboardpipeline.js, packages/ckeditor5-clipboard/tests/utils/viewtoplaintext.js, packages/ckeditor5-image/src/image/insertimagecommand.ts, packages/ckeditor5-image/src/index.ts, packages/ckeditor5-image/tests/image/insertimagecommand.js, packages/ckeditor5-mention/src/mentioncommand.ts, packages/ckeditor5-mention/src/mentionui.ts, packages/ckeditor5-mention/tests/mentioncommand.js, packages/ckeditor5-mention/tests/mentionui.js, packages/ckeditor5-ui/src/tooltipmanager.ts, packages/ckeditor5-ui/tests/tooltip/tooltipmanager.js
Feature (image): Added a possibility to break the current block by `InsertImageCommand` with `breakBlock` flag. Closes https://github.com/ckeditor/ckeditor5/issues/17742.
Feature (ui): The `.ck-with-instant-tooltip` class can now be used to display the tooltip without the delay. Closes https://github.com/ckeditor/ckeditor5/issues/17743.
Feature (mention): Allow the [mention marker](https://ckeditor.com/docs/ckeditor5/latest/api/module_mention_mentionconfig-MentionFeed.html#member-marker) to be longer than 1 character. Closes https://github.com/ckeditor/ckeditor5/issues/17744.
Fix (ui): Tooltip will no longer show after quickly hovering and moving the mouse away before the tooltip shows. Closes 
https://github.com/ckeditor/ckeditor5/issues/16949.
Fix (ui): Tooltip will no longer disappear …
=> Improvements in `insertImage` command, tooltip manager and mention

packages/ckeditor5-emoji/docs/features/emoji.md, packages/ckeditor5-emoji/src/emojiconfig.ts, packages/ckeditor5-emoji/src/emojimention.ts, packages/ckeditor5-emoji/src/emojipicker.ts, packages/ckeditor5-emoji/src/ui/emojitoneview.ts, packages/ckeditor5-emoji/tests/emojimention.js, packages/ckeditor5-emoji/tests/emojipicker.js, packages/ckeditor5-emoji/tests/ui/emojipickerview.js, packages/ckeditor5-emoji/tests/ui/emojitoneview.js
Internal: Added skin tone config option for Emoji plugin. Closes #17736.
---
=> Added skin tone config option

packages/ckeditor5-emoji/lang/translations/en.po, packages/ckeditor5-emoji/src/emojipicker.ts, packages/ckeditor5-emoji/src/ui/emojigridview.ts, packages/ckeditor5-emoji/src/ui/emojipickerview.ts, packages/ckeditor5-emoji/tests/emojimention.js, packages/ckeditor5-emoji/tests/emojipicker.js, packages/ckeditor5-emoji/tests/ui/emojigridview.js
Internal: The "No results" message will now display properly when the picker is opened via the mention feature with no search results. Closes #17731.
---
=> Fixed display of the no results message

packages/ckeditor5-clipboard/src/index.ts
Other (clipboard): Export `ViewDocumentPasteEvent` from clipboard. 
---
It's needed in `paste` event firing in `AI` plugin.
Commercial PR: https://github.com/cksource/ckeditor5-commercial/pull/6319
=> Export `ViewDocumentPasteEvent` from `Clipboard` plugin.

packages/ckeditor5-html-support/tests/manual/ghs-no-features.html, packages/ckeditor5-html-support/tests/manual/objects.html
Internal: Use `placehold.co` instead of `placeholder.com`. Closes #17762.
=> Internal: Use `placehold.co` instead of `placeholder.com`

packages/ckeditor5-utils/src/collectstylesheets.ts, packages/ckeditor5-utils/src/index.ts, packages/ckeditor5-utils/tests/collectstylesheets.js
Feature (utils): Add `collectStylesheets` that allows to pick stylesheets from provided urls.
Commercial PR: https://github.com/cksource/ckeditor5-commercial/pull/6945
=> Add `collectStylesheets` that allows to pick stylesheets from provided urls.

packages/ckeditor5-image/ckeditor5-metadata.json
Internal (image): Add metadata for `ImageUtils` and `ImageEditing` plugins. Closes #17765.
---
=> Add metadata for `ImageUtils` and `ImageEditing` plugins

packages/ckeditor5-image/ckeditor5-metadata.json
Internal (image): Fix path to `ImageEditing` plugin in metadata.
---
=> Fix path in image metadata

packages/ckeditor5-engine/src/index.ts, packages/ckeditor5-font/src/index.ts, packages/ckeditor5-ui/src/index.ts, packages/ckeditor5-utils/src/index.ts
Other (font): Export `ColorSelectorDropdownView` type. Closes #17783.
Other (ui): Export `DocumentColorCollection` class. Closes #17783.
Other (engine): Export `SchemaCompiledItemDefinition` type. Closes #17783.
Other (utils): Export `add` function. Closes #17783.
---
Two other exports from the #17783 are already exported (`ClassicEditorUIView` and `DowncastAttributeEvent`). So this PR closes the ticket.
=> Added missing exports.

packages/ckeditor5-basic-styles/src/code/codeediting.ts, packages/ckeditor5-basic-styles/tests/code/codeediting.js
Fix(basic-styles): Should not convert element with style `word-wrap: break-word` into `<code>` tag. Closes #17789.
MINOR BREAKING CHANGE (basic-styles): Elements which contains attribute `style` with `word-wrap: break-word` won't be converted to `<code>`. See #17789.
---
=> `Code` conversion fix (removed: `word-wrap: break-word`).

packages/ckeditor5-list/src/listconfig.ts, packages/ckeditor5-list/src/listproperties/listpropertiesediting.ts, packages/ckeditor5-list/src/listproperties/listpropertiesui.ts, packages/ckeditor5-list/src/listproperties/utils/config.ts, packages/ckeditor5-list/tests/listproperties/listpropertiesui.js, packages/ckeditor5-list/tests/manual/list-properties.html, packages/ckeditor5-list/tests/manual/list-properties.js
Feature (list): Allow to specify which list style types are shown in list type selector dropdown. Closes #17176
---
I added `listTypesStyles` to `list` config property, so it's now possible to limit which list types styles are available in lit dropdown.
Example:
```ts
// ... editor config
list: {
properties: {
styles: {
listTypesStyles: {
numbered: [
'decimal',
'decimal-leading-zero',
'lower-roman',
'upper-roman'
],
bulleted: [
'disc',
'circle',
'square'
]
}
}
}
}
```
Which renders to:
Where this one is default behavior:
=> Allow to specify which list style types are shown in list type selector dropdown.

packages/ckeditor5-list/src/listconfig.ts
Internal (list): Fix typo in list config `@default` jsdoc.
---
Caused by https://github.com/ckeditor/ckeditor5/pull/17734
=> Fix typo in list config `@default` jsdoc.

packages/ckeditor5-ckbox/src/ckboxcommand.ts, packages/ckeditor5-ckbox/src/ckboxconfig.ts, packages/ckeditor5-ckbox/tests/ckboxcommand.js, packages/ckeditor5-ckbox/tests/manual/ckbox.js
Feature (ckbox): Allow to specify which files chosen from CKBox are downloadable. Closes #15928 
```ts
export interface CKBoxConfig {
// ...
/**
* Controls when to enable the download attribute for inserted links.
*
* By default, files are downloadable.
*
* ```ts
* const ckboxConfig = {
*   downloadableFiles: asset => asset.data.extension !== 'pdf'
* };
* ```
*/
downloadableFiles?: ( asset: CKBoxRawAssetDefinition ) => boolean;
};
```
=> Allow to specify which files choosen from CKBox are downloadable.

packages/ckeditor5-clipboard/src/clipboardpipeline.ts, packages/ckeditor5-clipboard/tests/clipboardpipeline.js, packages/ckeditor5-code-block/tests/codeblockediting.js
Feature (clipboard): Add ability to detect paste events originating from editor. Closes #15935 
---
The main use case is we need to track if the user has pasted content from outside the editor so we can decide if the content needs to be modified before it’s added into CKEditor. See more https://github.com/ckeditor/ckeditor5/issues/15935#issuecomment-1968599167
=> Add `sourceEditorId` property to clipboard input events.

packages/ckeditor5-emoji/src/ui/emojicategoriesview.ts, packages/ckeditor5-emoji/src/ui/emojigridview.ts, packages/ckeditor5-emoji/src/ui/emojipickerview.ts, packages/ckeditor5-emoji/src/ui/emojisearchview.ts, packages/ckeditor5-emoji/src/ui/emojitoneview.ts, packages/ckeditor5-emoji/tests/ui/emojigridview.js
Internal: The `EmojiGridView` class stores already created tile views in a local cache property for further usage to avoid re-creating them again. Closes #17776.
Internal: Added missing `destroy()` calls for view components.
---
=> Store tiles in a local cache to avoid re-creating them again

packages/ckeditor5-html-support/src/emptyblock.ts, packages/ckeditor5-html-support/tests/emptyblock.js, packages/ckeditor5-html-support/tests/manual/emptyblock.html, packages/ckeditor5-html-support/tests/manual/emptyblock.js, packages/ckeditor5-html-support/tests/manual/emptyblock.md
Internal (html-support): Add clipboard integration to `EmptyBlock` plugin.
---
Original PR: https://github.com/ckeditor/ckeditor5/pull/17756
=> Add clipboard integration to `EmptyBlock` plugin.

packages/ckeditor5-emoji/src/ui/emojicategoriesview.ts, packages/ckeditor5-emoji/src/ui/emojigridview.ts, packages/ckeditor5-emoji/src/ui/emojipickerview.ts, packages/ckeditor5-emoji/src/ui/emojisearchview.ts, packages/ckeditor5-emoji/src/ui/emojitoneview.ts, packages/ckeditor5-emoji/tests/ui/emojicategoriesview.js, packages/ckeditor5-emoji/tests/ui/emojigridview.js, packages/ckeditor5-emoji/tests/ui/emojipickerview.js, packages/ckeditor5-emoji/tests/ui/emojisearchview.js, packages/ckeditor5-emoji/tests/ui/emojitoneview.js, packages/ckeditor5-emoji/theme/emojicategories.css
Internal: Improved accessibility of the emoji picker. Closes #17815.
---
The following items have been improved in this PR. In the attached issue, you can find the previous values.
* Skin tone dropdown (label)
* Skin tone menu options (descriptions)
* Category switches miss a few attributes
* An active button:
```html
<button
class="ck ck-button ck-on ck-button_with-text ck-emoji__category-item_active"
role="tab"
type="button"
tabindex="-1"
aria-label="Smileys &amp; Expressions"
data-cke-tooltip-text="Smileys &amp; Expressions"
data-cke-tooltip-position="s"
aria-selected="true"
>
<span class="ck ck-button__label">😀</span>
</button>;
```	
* A non-active button:
```html
<button
class="ck ck-button ck-off ck-button_with-text"
role="tab"
type="button"
tabindex="-1"
aria-label="Gestures &amp; …
```
=> Improved accessibility of the emoji picker

packages/ckeditor5-engine/src/conversion/mapper.ts, packages/ckeditor5-engine/src/view/documentfragment.ts, packages/ckeditor5-engine/src/view/element.ts, packages/ckeditor5-engine/src/view/node.ts, packages/ckeditor5-engine/tests/conversion/mapper.js
Other (engine): Introduced dynamic caching in `Mapper` in order to improve view-to-model mapping performance, and as a result improve editor load and data save performance. Closes #17623.
Other (engine): New parameter `data` was added for `change:children` event fired by `ViewElement` and `ViewDocumentFragment` when their children change. `data` is an object with `index` property, which says at which index the change happened. Related to #17623.
Other (engine): `Mapper#registerViewToModelLength()` is now deprecated and will be removed in one of upcoming releases. Note: if this method is used, the caching mechanism for `Mapper` will be turned off which may degrade performance when handing big documents. Note: this method is used by the deprecated legacy lists feature. See #17623.
MINOR …
=> Dynamic caching in `Mapper` for better performance

packages/ckeditor5-source-editing/ckeditor5-metadata.json
Internal (source-editing): Fix uiComponents icon metadata.
---
This is a cherry-picked commit which was added to `release` branch in this PR https://github.com/ckeditor/ckeditor5/pull/17847.
=> Fix source editing `uiComponents` icon metadata (`master` backport)

packages/ckeditor5-emoji/src/emojimention.ts, packages/ckeditor5-emoji/tests/emojimention.js
Internal: Fixed emoji config marker already used warning in Revision History. Closes cksource/ckeditor5-commercial#6980.
---
=> Fixed emoji config marker already used warning in Revision History.

packages/ckeditor5-emoji/src/emojimention.ts, packages/ckeditor5-emoji/tests/emojimention.js, packages/ckeditor5-emoji/tests/manual/emoji.html, packages/ckeditor5-emoji/tests/manual/emoji.md
Internal: `EmojiMention` feed does not return any items when the repository is not loaded correctly. Closes #17842.
---
=> Improved EmojiMention feed when repository failed to load

packages/ckeditor5-emoji/theme/emojigrid.css
Internal: Improved the emoji grid view on small screens by setting its height to max 40% of the viewport height. Closes #17862.
---
https://github.com/user-attachments/assets/a45847e9-7973-4f7d-8ca5-053ec4014326
https://github.com/user-attachments/assets/e3b54327-f42d-4aaa-8f87-15f04d054120
=> Improved the emoji grid view on small screens

packages/ckeditor5-image/docs/_snippets/features/build-image-optimizer-source.js, packages/ckeditor5-image/docs/_snippets/features/image-image-optimizer-ckbox.html, packages/ckeditor5-image/docs/_snippets/features/image-image-optimizer-ckbox.js, packages/ckeditor5-image/docs/_snippets/features/image-image-optimizer-uploadcare.html, packages/ckeditor5-image/docs/_snippets/features/image-image-optimizer-uploadcare.js, packages/ckeditor5-image/docs/features/images-image-optimizer.md, packages/ckeditor5-image/docs/features/images-overview.md
Docs: Added image optimizer
---
=> Docs: Added image optimizer

docs/features/image-upload.md, docs/features/using-file-managers.md, packages/ckeditor5-image/docs/_snippets/features/image-image-optimizer-uploadcare.js
Docs (uploadcare): Remove Instagram from Uploadcare related docs.
---
Related to recent changes from https://github.com/ckeditor/ckeditor5/pull/17858 and removing Instagram support from UC plugin.
=> Remove Instagram from Uploadcare related docs

.eslintrc.js, LICENSE.md, packages/ckeditor5-emoji/LICENSE.md, packages/ckeditor5-emoji/src/augmentation.ts, packages/ckeditor5-emoji/src/emojimention.ts, packages/ckeditor5-emoji/src/emojipicker.ts, packages/ckeditor5-emoji/src/emojirepository.ts, packages/ckeditor5-emoji/src/emojiutils.ts, packages/ckeditor5-emoji/src/index.ts, packages/ckeditor5-emoji/src/utils/emojiutils.ts, packages/ckeditor5-emoji/src/utils/isemojisupported.ts, packages/ckeditor5-emoji/tests/emojimention.js, packages/ckeditor5-emoji/tests/emojipicker.js, packages/ckeditor5-emoji/tests/emojirepository.js, packages/ckeditor5-emoji/tests/utils/emojiutils.js, packages/ckeditor5-emoji/tests/utils/isemojisupported.js, scripts/bump-year.mjs
Internal: Fixed emoji filtering and improved the filtering performance. Closes #17834.
---
=> Fixed emoji filtering and improved the filtering performance.

packages/ckeditor5-emoji/src/emojiconfig.ts, packages/ckeditor5-emoji/src/emojirepository.ts, packages/ckeditor5-emoji/src/utils/isemojisupported.ts, packages/ckeditor5-emoji/tests/emojimention.js, packages/ckeditor5-emoji/tests/emojipicker.js, packages/ckeditor5-emoji/tests/emojirepository.js, packages/ckeditor5-emoji/tests/integration.js
Internal: Download the emoji database only once and make it available for other editors. Closes #17838.
---
=> Download the emoji database only once and make it available for other editors

packages/ckeditor5-emoji/src/emojimention.ts, packages/ckeditor5-emoji/tests/emojimention.js
Internal: Return empty emoji feed list if the query starts with a marker character. Closes #17851.
---
https://github.com/user-attachments/assets/d9998881-7ba7-451c-9324-5d303440c906
=> Return empty emoji feed list if the query starts with a marker character

docs/_snippets/examples/bottom-toolbar-editor.js, docs/_snippets/examples/document-editor.js, packages/ckeditor5-ckbox/src/utils.ts, packages/ckeditor5-clipboard/src/clipboardmarkersutils.ts, packages/ckeditor5-clipboard/src/dragdrop.ts, packages/ckeditor5-cloud-services/src/uploadgateway/fileuploader.ts, packages/ckeditor5-code-block/src/codeblockcommand.ts, packages/ckeditor5-engine/src/view/stylesmap.ts, packages/ckeditor5-ui/src/button/filedialogbuttonview.ts, packages/ckeditor5-ui/src/colorgrid/colorgridview.ts, packages/ckeditor5-ui/src/colorselector/colorgridsfragmentview.ts, packages/ckeditor5-ui/src/search/text/searchtextview.ts, tsconfig.json
Other: Update TypeScript `target` to `es2022`. Closes #17886.
=> Update TypeScript `target` to `es2022`.

scripts/ci/check-dependencies-versions-match.mjs
Internal: Add range exceptions to `check-dependencies-versions-match` script.
---
Related to cksource/ckeditor5-commercial#6939
=> Internal: Add range exceptions to `check-dependencies-versions-match` script.

packages/ckeditor5-table/src/plaintableoutput.ts, packages/ckeditor5-table/tests/manual/plaintableoutput.html, packages/ckeditor5-table/tests/manual/plaintableoutput.js, packages/ckeditor5-table/tests/plaintableoutput.js, packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js
Fix (table): Plain table should be properly aligned in the output. Closes #17888.
---
The table class that we use for `<figure>` elements has `margin-left` and `margin-right` set to `auto`. Since a `plain table` is not wrapped in a `<figure>` element, it lacked the proper margin. That's why I added the same class used for `<figure>` to the `<table>` element in the data output.
=> Plain table should be properly aligned in the output

packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts, packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js, packages/ckeditor5-ui/tests/colorselector/colorselectorview.js
Fix (ui): Fixed an issue where the first selected color was applied instead of the second selected color when using the font color picker for the first time after loading the page. Closes https://github.com/ckeditor/ckeditor5/issues/17069
---
https://github.com/user-attachments/assets/7b69a7dc-b0cd-4f3e-ba10-1298bea343a0
https://github.com/user-attachments/assets/7071c6bb-af7b-45bf-82f4-28fe53208c43
=> Fix font color picker not working properly on first change on Chrome

.circleci/template.yml
Internal: Notify about CI failures on `master-it84` branch.
---
=> Notify about CI failures on `master-it84` branch

scripts/ci/check-dependencies-versions-match.mjs
Internal: Allows the installation of the "@codemirror/theme-one-dark" package using the caret range.
---
=> Extended packagers in the "check-dependencies-versions" script

.eslintrc.js, docs/framework/contributing/code-style.md, package.json
Internal: Add the `ckeditor5-rules/allow-svg-imports-only-in-icons-package` eslint rule.
---
Related to #16546.
=> Add the `ckeditor5-rules/allow-svg-imports-only-in-icons-package` eslint rule.

packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/tests/editor/licensecheck.js
Internal (core): Fix typo in license type warning.
---
**Before**
`You are using a evaluation license [..]`
**After**
`You are using an evaluation license [..]`
=> Fix typo in license type warning.

packages/ckeditor5-table/src/tablelayout/tablelayoutediting.ts, packages/ckeditor5-table/src/utils/structure.ts, packages/ckeditor5-table/tests/manual/tablelayout.html, packages/ckeditor5-table/tests/manual/tablelayout.js, packages/ckeditor5-table/tests/tablelayout/tablelayoutediting.js
Internal (table): Fix missing `tableType` attribute in `cropTableToDimensions` output. 
---
Parent PR: https://github.com/ckeditor/ckeditor5/pull/17931
Grandparent PR: https://github.com/ckeditor/ckeditor5/pull/17849
=> Add basic clipboard support for table layout editing.

packages/ckeditor5-emoji/docs/features/emoji.md, packages/ckeditor5-emoji/src/emojirepository.ts
Docs: Improve emoji's docs.
---
=> Improve emoji's docs.

scripts/docs/snippetadapter.mjs
Internal: Avoid defining fallback for crypto when building snippets. Closes #17991.
=> Avoid defining fallback for crypto when building snippets

packages/ckeditor5-engine/src/index.ts
Feature (engine): Export `SchemaContext` class from package. Closes https://github.com/ckeditor/ckeditor5/issues/18003
=> Export `SchemaContext` from engine package.

packages/ckeditor5-link/tests/manual/linkproviders.js, packages/ckeditor5-theme-lark/theme/ckeditor5-link/linkform.css, packages/ckeditor5-theme-lark/theme/ckeditor5-link/linkprovideritems.css
Internal (link): Add text overflow ellipsis to link providers form header and items. Closes https://github.com/ckeditor/ckeditor5/issues/18018
---
**Before**
**After**
=> Add text overflow ellipsis to link providers form header and items.

packages/ckeditor5-emoji/docs/features/emoji.md, packages/ckeditor5-emoji/src/emojiconfig.ts, packages/ckeditor5-emoji/src/emojirepository.ts, packages/ckeditor5-emoji/tests/emojirepository.js, packages/ckeditor5-emoji/tests/manual/emoji.html, packages/ckeditor5-emoji/tests/manual/emoji.js, packages/ckeditor5-emoji/tests/manual/emoji.md
Other (emoji): Introduced the `emoji.useCustomFont` option to disable the filtering mechanism. Closes #18029.
Internal: Added additional logging for the Emoji Plugin when the emoji font is not installed on the OS. Closes #17988.
---
=> Added additional logging for the Emoji Plugin when the emoji font is not installed on the OS.

docs/getting-started/integrations-cdn/angular.md, docs/getting-started/integrations/angular.md
Docs: Fix outdated Angular snippets in docs.
---
Notion issue https://www.notion.so/Fix-outdated-Angular-snippets-in-installation-guide-1abbb9a6723280a6b142c09d0b116461
=> Fix outdated angular snippets in docs

packages/ckeditor5-editor-classic/src/classiceditoruiview.ts, packages/ckeditor5-editor-decoupled/src/decouplededitoruiview.ts, packages/ckeditor5-editor-inline/src/inlineeditoruiview.ts, packages/ckeditor5-editor-multi-root/src/multirooteditoruiview.ts, packages/ckeditor5-fullscreen/src/fullscreencommand.ts, packages/ckeditor5-fullscreen/src/handlers/abstracteditor.ts, packages/ckeditor5-fullscreen/src/handlers/classiceditor.ts, packages/ckeditor5-fullscreen/src/handlers/decouplededitor.ts, packages/ckeditor5-fullscreen/tests/_utils/revisionhistorymock.js, packages/ckeditor5-fullscreen/tests/fullscreenediting.js, packages/ckeditor5-fullscreen/tests/handlers/abstracteditor.js, packages/ckeditor5-fullscreen/tests/handlers/classiceditor.js, packages/ckeditor5-fullscreen/tests/handlers/decouplededitor.js, packages/ckeditor5-fullscreen/theme/fullscreen.css, packages/ckeditor5-ui/src/editorui/editoruiview.ts, packages/ckeditor5-ui/src/menubar/menubarview.ts, packages/ckeditor5-ui/src/menubar/utils.ts, packages/ckeditor5-ui/tests/editorui/editorui.js, packages/ckeditor5-ui/tests/menubar/menubarview.js, packages/ckeditor5-ui/tests/menubar/utils.js
Internal (fullscreen): Add integration with revision history.
Fix (ui): Do not open disabled menu bar menu on arrow down press. Closes https://github.com/ckeditor/ckeditor5/issues/17915.
Feature (ui): Add `MenuBarView#disable()` and `MenuBarView#enable()` methods. They disable/enable all top-level menus in menu bar. Closes https://github.com/ckeditor/ckeditor5/issues/17940.
Internal (ui): Add a `toolbar` property to the `EditorUIView` class for coherent access for all editor types.
Internal (ui): Make `EditorUI#_initMenuBar()` method public and rename it accordingly to allow for runtime toolbar creation.
---
* Requires `ck/fullscreen-revision-history` in the related repository (one of the used types needs to be exported).
* Disabling menu bar was supposed to be done through a flag. …
=> Add integration for fullscreen feature with revision history

packages/ckeditor5-theme-lark/theme/ckeditor5-table/tablelayout.css
Internal: Make the layout table outline visible when layout table is inside another layout table inside edge cells.
---
CSS Fix - works on every modern browser except `Safari`.
_Before:_
https://github.com/user-attachments/assets/92cc208b-4d37-4234-804f-347398b97cd8
_After:_
https://github.com/user-attachments/assets/e765d456-57a8-470d-b8e1-fe658026ce2e
=> Fix for overflow on nested layout tables.

packages/ckeditor5-core/lang/contexts.json, packages/ckeditor5-fullscreen/lang/contexts.json, packages/ckeditor5-fullscreen/src/fullscreenediting.ts, packages/ckeditor5-fullscreen/tests/fullscreenediting.js
Internal: Add keystroke for fullscreen mode.
---
=> Add keystroke for fullscreen mode

packages/ckeditor5-theme-lark/theme/ckeditor5-bookmark/bookmark.css, packages/ckeditor5-theme-lark/theme/ckeditor5-link/linkform.css
Other(bookmark): Increase `.ck-bookmark` CSS selector specificity to not rely on build order.
Other(link): Increase `.ck.ck-link-form` CSS selector specificity to not rely on build order.
---
_The issue was spotted in our documentation._
=> Increase CSS selectors specificity.

packages/ckeditor5-ckbox/src/ckboxutils.ts, packages/ckeditor5-ckbox/tests/ckboxediting.js, packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js, packages/ckeditor5-ckbox/tests/ckboxuploadadapter.js, packages/ckeditor5-ckbox/tests/ckboxutils.js
Fix (ckbox): Resolved issue where images from private categories were not appearing in the selector.  Closes #18044
---
This PR align CKBox plugin to support new authorization process call just after startup of the editor. 
See more: https://ckeditor.com/docs/ckbox/latest/features/private-categories.html#authorization-process
Caused by https://github.com/cksource/ckeditor5-commercial/issues/7158
=> Add authorize private categories access call to CKBox API after start of the editor.

package.json, scripts/docs/snippetadapter.mjs
Internal: Snippet adapter should always check `node_modules` of `ckeditor5` repository when resolving dependencies.
Internal: Lock `@wiris/mathtype-ckeditor5` version to fix issues present in the latest release.
---
* Closes https://github.com/cksource/ckeditor5-internal/issues/3976.
* Link to `@wiris/mathtype-ckeditor5` issue: https://github.com/wiris/html-integrations/issues/1093
=> Fix snippet adapter is global docs deploy

scripts/docs/snippetadapter.mjs
Docs: Fix images in `Export to PDF` and `Export to Word` examples. Closes #18142.
---
This PR adds `defer` to `global.js` and `ckbox.js` scripts, so they load only once the entire HTML is loaded. Also, the scripts are re-ordered, so the `global.js` always runs first.
=> Docs: Fix images in `Export to PDF` and `Export to Word` examples

package.json
Internal: Revert MathType downgrade.
---
This PR reverts change made in #18141, because new MathType release fixed the original issue.
=> Internal: Revert MathType downgrade

packages/ckeditor5-table/theme/table.css, packages/ckeditor5-table/theme/tablecolumnresize.css, packages/ckeditor5-table/theme/tablelayout.css, packages/ckeditor5-theme-lark/theme/ckeditor5-table/tablelayout.css
Fix(table): Improved CSS scoping for table wrapped and not wrapped with `<figure>`. Closes #18169.
---
_These changes introduce a more refined approach to styling figure wrappers for tables and defining styles when a table does not have a wrapper. This enhancement is particularly useful when utilizing the PlainTableOutput plugin. Additionally, an adjustment has been made to ensure that styles apply only to the direct children of a table, preventing any unintended impact on nested tables._
=> Improving table styles.

packages/ckeditor5-fullscreen/src/handlers/abstracteditor.ts, packages/ckeditor5-fullscreen/tests/handlers/abstracteditor.js, packages/ckeditor5-source-editing/src/sourceediting.ts, packages/ckeditor5-source-editing/tests/sourceediting.js
Internal (fullscreen): Improve source editing integration with document outline in fullscreen mode.
---
1. Source editing integration was not perfect, it didn't take into account a situation when there are multiple document outline containers on the page.
2. Fullscreen has to detect when source mode is open and toggle "Document outline" header visibility.
=> Improve source editing integration with document outline in fullscreen mode

packages/ckeditor5-table/tests/tablelayout/tablelayoutediting.js
Internal (table): Remove `role=textbox` from editing downcast layout tables tests.
=> Remove `role=textbox` from editing downcast layout tables tests.

packages/ckeditor5-heading/src/headingconfig.ts
Fix (heading): Added missing `converterPriority` type definition to `HeadingOption` interface. Closes #18182.
---
_The test in_ [_https://github.com/ckeditor/ckeditor5/blob/6fc725f9264aa4e279d13862e9dea2a1a110755e/packages/ckeditor5-heading/tests/integration.js#L126-L146_](https://github.com/ckeditor/ckeditor5/blob/6fc725f9264aa4e279d13862e9dea2a1a110755e/packages/ckeditor5-heading/tests/integration.js#L126-L146) _covers this property._
=> Added missing converterPriority type definition to HeadingOption interface

packages/ckeditor5-link/src/autolink.ts, packages/ckeditor5-link/tests/autolink.js
Fix (link): The Autolink feature will now correctly autolink `http://localhost` and `http://localhost:port`. Closes #18185
---
The fact that localhost wasn't handled was an explicit decision, but I don't understand it. It's a known domain, present on all OSes. The only one of this kind, so special treatment makes sense.
Some more context (dunno if it opens for others, I can paste here if not):
* https://chatgpt.com/share/e/67e1daba-87d4-8001-aac4-bcded82d2402
=> Added localhost to known domains in the Autolink feature

packages/ckeditor5-bookmark/src/bookmarkui.ts, packages/ckeditor5-bookmark/tests/bookmarkui.js, packages/ckeditor5-theme-lark/theme/ckeditor5-bookmark/bookmarktoolbar.css, packages/ckeditor5-theme-lark/theme/ckeditor5-link/linktoolbar.css
Fix(link): Should not wrap toolbar items in `Link` UI. Closes #18200.
Fix(bookmark): Should not wrap toolbar items in `Bookmark` UI. Closes #18200.
---
⚠️ Target branch: `release`.
=> Fix for wrapping toolbar items in `Link` and `Bookmark` UI.

packages/ckeditor5-engine/src/conversion/upcasthelpers.ts, packages/ckeditor5-engine/tests/conversion/upcasthelpers.js, packages/ckeditor5-table/src/converters/tableproperties.ts, packages/ckeditor5-table/src/tablecellproperties/commands/tablecellpropertycommand.ts, packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesediting.ts, packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesui.ts, packages/ckeditor5-table/src/tableproperties/commands/tablepropertycommand.ts, packages/ckeditor5-table/src/tableproperties/tablepropertiesediting.ts, packages/ckeditor5-table/src/tableproperties/tablepropertiesui.ts, packages/ckeditor5-table/src/tableproperties/ui/tablepropertiesview.ts, packages/ckeditor5-table/src/utils/table-properties.ts, packages/ckeditor5-table/src/utils/ui/table-properties.ts, packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesediting.js, packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesui.js, packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js, packages/ckeditor5-table/tests/tableproperties/tablepropertiesui.js, packages/ckeditor5-table/tests/utils/ui/table-properties.js, packages/ckeditor5-theme-lark/theme/ckeditor5-table/tablelayout.css
Internal (table): Separate table and table cell properties view instances for separate defaults. Closes https://github.com/ckeditor/ckeditor5/issues/18219
---
=> Separate table and table cell properties view instances for separate defaults

.circleci/template.yml, scripts/ci/generate-circleci-configuration.mjs
Internal: Moved the Commercial-related tasks from the CKEditor 5 repository to CC.
---
* See: https://github.com/cksource/ckeditor5-commercial/issues/7274.
=> Remove Commercial-related tasks from CI

.circleci/template.yml, scripts/ci/generate-circleci-configuration.mjs
Internal: Moved the Commercial-related tasks from the CKEditor 5 repository to CC.
---
This is a cherry-pick from `#release` to `#master` (#18249).
=> Remove Commercial-related tasks from CI (#master)

packages/ckeditor5-table/theme/tablelayout.css
Fix (table): Nested tables outline should not been cut of at the bottom during hovering. Closes #18262.
---
=> Nested tables outline visibility.

packages/ckeditor5-fullscreen/src/handlers/classiceditorhandler.ts, packages/ckeditor5-fullscreen/tests/handlers/classiceditorhandler.js
Internal (fullscreen): Fix rounded corners on UI components in fullscreen mode. Closes https://github.com/ckeditor/ckeditor5/issues/18276.
---
Fix is only necessary in classic editor. Decoupled editor applies `.ck-rounded-corners` on each component that needs it separately.
=> Fix rounded corners on UI components in fullscreen mode

packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.js, packages/ckeditor5-page-break/docs/_snippets/features/page-break.js, tests/manual/all-features.js, tests/manual/memory/memory.js
Docs: Fix snippets that assume styles come from the `snippet.css` file. Closes #18285.
Internal: Fix manual tests that assume styles come from the `snippet.css` file. Closes #18285.
=> Fix snippets and manual tests using snippet styles

packages/ckeditor5-bookmark/src/bookmarkui.ts, packages/ckeditor5-bookmark/tests/bookmarkui.js, packages/ckeditor5-link/src/linkui.ts, packages/ckeditor5-link/tests/linkui.js
Internal (bookmark, link): Third click on "Add bookmark"/ "Link" no longer opens the balloon at the top of the editor. Closes #18253.
---
It looks like focusing editable during execution `callback` of click outside handler causes the issue. Most likely race condition in focus / selection management, or built-in browser heuristic that is executed during click event. 
https://github.com/user-attachments/assets/289866e8-9905-4cd4-ab20-413bfb03d77e
https://github.com/user-attachments/assets/cbc3259f-22fc-4b0e-93e8-4795891fa461
=> Third click on "Add bookmark"/ "Link" no longer opens the balloon at the top of the editor.

packages/ckeditor5-link/src/linkimageediting.ts, packages/ckeditor5-link/tests/linkimageediting.js
Fix (link): Fix not working toggling decorators on images with links. Closes #18265 
---
It looks like we do not remove manual decorators set on image with links in editing mode.
=> Fix not working removal manual decorators from image with links.

packages/ckeditor5-bookmark/src/bookmarkui.ts, packages/ckeditor5-bookmark/tests/bookmarkui.js
Internal (bookmark): Restore the default CSS class for bookmark toolbar.
---
:warning: target branch: `release`.
=> Restore the default class for bookmark toolbar.

packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.ts, packages/ckeditor5-table/tests/manual/tablelayout.js, packages/ckeditor5-table/tests/tablecolumnresize/_utils/utils.js, packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js, packages/ckeditor5-table/theme/tablecolumnresize.css, packages/ckeditor5-theme-lark/theme/ckeditor5-table/tablelayout.css
Fix (table): Widgets UI elements should be visible when are inside tables. Closes #18268.
---
⚠️ `release` branch is the target.
ℹ️  To prevent cut off any element that lies inside a layout table (or content table) we decided to calculate the table resizer on demand instead of using `overflow: hidden` hack with huge value of top and bottom to make sure that resizer element will be streched to the top and bottom of the table.
=> Remove `overflow: hidden` from table while using TableColumnResize.

packages/ckeditor5-emoji/src/emojipicker.ts, packages/ckeditor5-emoji/tests/emojipicker.js
Internal (emoji): Third click on emoji toolbar button no longer opens the balloon at the top of the editor. Closes https://github.com/ckeditor/ckeditor5/issues/18253
---
Missing part of this PR: https://github.com/ckeditor/ckeditor5/pull/18281
=> Do not focus the editable if user clicked outside of emoji balloon.

packages/ckeditor5-table/theme/tablelayout.css, packages/ckeditor5-theme-lark/theme/ckeditor5-table/tablelayout.css, packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widget.css, packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widgettypearound.css
Internal (table): Selected or hovered widget should not hide the parent's table ui widgets. See #18245.
Internal (theme-lark): Selected or hovered widget should not hide the parent's table ui widgets. See #18245.
---
---
=> Fix for nesting widgets while hovering to prevent cut of the parent UI elements.

packages/ckeditor5-fullscreen/docs/_snippets/features/fullscreen-default.js, packages/ckeditor5-fullscreen/docs/_snippets/features/fullscreen-pageless.html, packages/ckeditor5-fullscreen/docs/_snippets/features/fullscreen-pageless.js, packages/ckeditor5-fullscreen/src/fullscreenediting.ts, packages/ckeditor5-fullscreen/src/fullscreenui.ts, packages/ckeditor5-fullscreen/src/handlers/abstracteditorhandler.ts, packages/ckeditor5-fullscreen/tests/fullscreenediting.js, packages/ckeditor5-fullscreen/tests/fullscreenui.js, packages/ckeditor5-fullscreen/tests/handlers/abstracteditorhandler.js, packages/ckeditor5-word-count/tests/wordcount.js
Internal (fullscreen): Fullscreen will restore the window and container scroll position while closing. Closes https://github.com/ckeditor/ckeditor5/issues/18246.
Internal (fullscreen): Fullscreen will preserve the scroll to the current selection in the editable when toggling fullscreen. Closes https://github.com/ckeditor/ckeditor5/issues/18259.
---
* On entering fullscreen mode, it will save the scroll position of all (scrollable) ancestors and restore them after leaving.
* Fullscreen will scroll the editor contents to the selection upon entering and leaving. 
* Small CSS fixes: for table margin in fullscreen mode and smaller padding for pageless demo.
=> Improve fullscreen scrolling

packages/ckeditor5-ui/src/panel/sticky/stickypanelview.ts, packages/ckeditor5-ui/tests/panel/sticky/stickypanelview.js, packages/ckeditor5-ui/theme/components/panel/stickypanel.css
Internal (ui): Sticky toolbar with viewport top offset and visual viewport is now truly sticky. See #18022. See #7718.
---
=> Sticky toolbar with viewport top offset and visual viewport is now truly sticky

packages/ckeditor5-fullscreen/docs/_snippets/features/fullscreen-default.html
Internal (fullscreen): Make revision history sidebar is wider in the Fullscreen mode docs demo. Closes https://github.com/cksource/ckeditor5-commercial/issues/7310.
Internal (fullscreen): Improve tippy balloon position. Closes https://github.com/cksource/ckeditor5-commercial/issues/7311.
---
Fixed by making the whole guide container wider.
Before:
After:
=> Improve fullscreen demo revision history sidebar styling

packages/ckeditor5-fullscreen/docs/_snippets/features/fullscreen-pageless.html
Internal (fullscreen): Set proper width and height for the pageless editor demo when it has little content. Closes https://github.com/ckeditor/ckeditor5/issues/18318.
---
=> Improve pageless demo visuals in fullscreen guide

packages/ckeditor5-fullscreen/src/fullscreenediting.ts, packages/ckeditor5-fullscreen/src/fullscreenui.ts, packages/ckeditor5-fullscreen/tests/fullscreenediting.js, packages/ckeditor5-fullscreen/tests/fullscreenui.js
Internal (fullscreen): Fix Alt+F10 behavior with fullscreen on non-Blink browsers. Closes https://github.com/ckeditor/ckeditor5/issues/18247.
---
Continuation of https://github.com/ckeditor/ckeditor5/pull/18273. 
Turns out, we also need to manually reset the toolbar `focusedElement` - it isn't set to `null` when toggling fullscreen, so if you do it using a button or shortcut but with toolbar focused, then toolbar can't be "refocused" later by Alt+F10.
=> Fix Alt+F10 behavior with fullscreen on non-Blink browsers

packages/ckeditor5-ui/src/dropdown/utils.ts, packages/ckeditor5-ui/tests/dropdown/utils.js
Fix (ui): Optimized performance of dropdowns when opening with many items. Closes #18094  
---
Previously, after adding each item, the entire list of other items was checked and their flags were updated accordingly. This resulted in behavior close to O(n²) complexity. In the new solution, only the added (or removed) items are checked, and the full item list is updated only once when a new toggleable is added. This change reduced the processing time from **5.6s** to **1.6s**.
=> Speed-up rendering of dropdowns with large amount of items.

packages/ckeditor5-image/src/imageresize/imageresizeediting.ts, packages/ckeditor5-image/src/imagesizeattributes.ts, packages/ckeditor5-image/tests/imageresize/imageresizeediting.js, packages/ckeditor5-image/tests/imagesizeattributes.js
Fix (image): Consume `image_resize` class and `aspect-ratio` style during the upcast of the images. Closes #18287 
---
Previously, the `image_resize` class was incorrectly consumed by the General HTML Support (GHS) plugin. This class is meant to be handled by the `ImageResize` plugin only, as it is automatically applied by it. This PR ensures that GHS no longer consumes this attribute.
=> Add missing consume for `image_resize` class on image elements.

packages/ckeditor5-html-support/package.json, packages/ckeditor5-html-support/src/datafilter.ts, packages/ckeditor5-html-support/tests/datafilter.js
Fix (html-support): Removing formatting from empty HTML no longer crashes the editor. Closes https://github.com/ckeditor/ckeditor5/issues/18089
Fix (html-support): Pasting empty HTML element no longer crashes the editor. Closes https://github.com/ckeditor/ckeditor5/issues/18100
=> Remove `htmlEmptyElement` if all `htmlXX` attributes removed.

packages/ckeditor5-fullscreen/src/handlers/abstracteditorhandler.ts, packages/ckeditor5-fullscreen/tests/handlers/abstracteditorhandler.js, packages/ckeditor5-fullscreen/tests/manual/fullscreen.html
Fix (fullscreen): Fix restoring scroll position after leaving fullscreen mode for containers with `scroll-behavior: smooth`. Closes https://github.com/ckeditor/ckeditor5/issues/18378.
---
=> Fix restoring scroll position after leaving fullscreen mode for containers with `scroll-behavior: smooth`

packages/ckeditor5-typing/src/delete.ts, packages/ckeditor5-typing/tests/delete.js
Fix (typing): The list items and headings at the beginning of the editable area can be changed to a plain paragraph on backspace keypress. Closes #18356.
---
Caused by https://github.com/ckeditor/ckeditor5/issues/17383 and https://github.com/ckeditor/ckeditor5/pull/17809
=> No longer keep todo list items placed on start of the editable when press backspace.

packages/ckeditor5-editor-multi-root/src/augmentation.ts, packages/ckeditor5-editor-multi-root/src/multirooteditor.ts
Docs (editor-multi-root): Updated documentation related to multi-root roots lazy loading, informing about limitations of this functionality. Closes #18197.
=> Add disclaimer to multi-root lazy loading with information about its limitations

packages/ckeditor5-link/src/autolink.ts, packages/ckeditor5-link/tests/autolink.js
Fix (link): Handle newline-suppressed scenarios (e.g. limit elements) in AutoLink plugin. Closes https://github.com/ckeditor/ckeditor5/issues/15862.
Thanks @jonscheiding!
---
On top of what @jonscheiding  covered, I added a test case for a second scenario. It's a bit more theoretical and does not result in a crash now – just nothing happens. In real life it can be triggered e.g. in this case:
After the change, the link will be autolinked on enter. Before, nothing happens.
=> Fixes #15862: Handle newline-suppressed scenarios (e.g. limit elements) in AutoLink plugin

packages/ckeditor5-code-block/docs/features/code-blocks.md, packages/ckeditor5-code-block/src/codeblockconfig.ts, packages/ckeditor5-code-block/src/codeblockediting.ts, packages/ckeditor5-code-block/tests/codeblockediting.js, packages/ckeditor5-code-block/tests/codeblockui.js
Feature (ckeditor5-code-block): Go/Golang programming language added to the `ckeditor5-code-block`. Closes #18403.
Thanks to @abdorrahmani!
---
=> Add Go language to code-block

scripts/check-manual-tests.sh
Internal: Manual tests on CI will now use `--no-identity-file` option by default, if no `--identity-file` option was specified.
---
=> Passed default option for manual tests on ci

packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.ts, packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js
Fix (table): Should apply the proper `width` attribute when it's  applied both on `<table>` and `<figure>` element. Closes #18469.
---
=> Fixed upcasting the `width` attribute from figure table wrapper.

packages/ckeditor5-core/src/editor/editor.ts, packages/ckeditor5-core/tests/editor/licensecheck.js
Internal (core): Non-production license notifications should only be displayed once per page load.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/7398.
=> Improve how license type messages are logged to the console.

packages/ckeditor5-fullscreen/src/handlers/abstracteditorhandler.ts
Fix (fullscreen): Allow for setting the custom filters on annotations while in fullscreen mode. Closes https://github.com/ckeditor/ckeditor5/issues/18485.
---
Diff looks worse than it actually is, most of the common logic was moved to `switchToWideSidebar()` function.
There are two scenarios to cover: wide sidebar is already in use (so it will be configured in Sidebar plugin and the element already exists) or not (Sidebar doesn't have a container set and the sidebar element is not created yet). Depending on the case, we need to perform the same actions in different order - it's explained in the inline comments.
There is a separate PR with tests in the comments package.
=> Fix setting the filters on annotations while in fullscreen mode

packages/ckeditor5-engine/src/view/renderer.ts, packages/ckeditor5-engine/tests/view/renderer.js
Fix (engine): Editor should not crash after clearing content with a widget selected. Closes #18123. Closes #18458.
---
=> Editor should not crash after clearing content with a widget selected.

packages/ckeditor5-fullscreen/theme/fullscreen.css
Internal (fullscreen): Fullscreen: change manu bar and toolbar borders. Closes https://github.com/ckeditor/ckeditor5/issues/18515.
---
Removed side borders and border radius.
Before:
After:
Before:
After:
=> Fullscreen: change manu bar and toolbar borders

packages/ckeditor5-engine/src/view/observer/selectionobserver.ts, packages/ckeditor5-engine/tests/view/observer/selectionobserver.js
Fix (engine): Copying content in read-only mode should use the current document selection. Closes #18514.
---
This is fixing the issue introduced in #17870.
=> The model selection in read-only mode should be always updated

packages/ckeditor5-engine/docs/framework/deep-dive/schema.md
Docs (engine): Updated guide with table showing schema for editor model elements.
---
I was doing research related to what model elements we have and how their schema is set. Some of them were not present in the table that we have in guides so I decided to add them.
I also removed legacy `listItem` element.
I skipped adding some of the special model elements.
=> Updated guide with table showing schema for editor model elements

package.json
Internal: Restored the missing `--quiet` parameter for a pre-commit hook
Part of https://github.com/cksource/ckeditor5-internal/issues/4027.
=> Restored the missing `--quiet` parameter for a pre-commit hook

packages/ckeditor5-engine/src/conversion/upcasthelpers.ts, packages/ckeditor5-engine/tests/conversion/upcasthelpers.js, packages/ckeditor5-paste-from-office/tests/_data/table/tablecellproperties/model.html, packages/ckeditor5-table/src/converters/tableproperties.ts, packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesediting.ts, packages/ckeditor5-table/src/tablecellwidth/tablecellwidthediting.ts, packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.ts, packages/ckeditor5-table/src/tableproperties/tablepropertiesediting.ts, packages/ckeditor5-table/src/utils/common.ts, packages/ckeditor5-table/tests/manual/tablepropertieslegacyhtml.html, packages/ckeditor5-table/tests/manual/tablepropertieslegacyhtml.js, packages/ckeditor5-table/tests/manual/tablepropertieslegacyhtml.md, packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesediting.js, packages/ckeditor5-table/tests/tablecellwidth/tablecellwidthediting.js, packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js
Other (table): The legacy HTML table attributes are now normalized to editor features (`width`, `height`, `bgcolor`). Closes #18575.
Other (engine): The `atributeToAtribute` and `elementToAtribute` upcast helpers should not consume anything if conversion callback returns `undefined` value. See #18575.
---
=> Added upcast converters for legacy HTML table attributes.

packages/ckeditor5-list/src/listformatting/listitemfontfamilyintegration.ts, packages/ckeditor5-list/tests/listformatting/listitemfontfamilyintegration.js
Internal (list): Adds upcast converter for the `listItemFontColor` attribute. Closes #18559.
---
=> Upcast converter for listItemFontColor

packages/ckeditor5-find-and-replace/src/findandreplace.ts, packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts, packages/ckeditor5-find-and-replace/src/findandreplacestate.ts, packages/ckeditor5-find-and-replace/src/findandreplaceui.ts, packages/ckeditor5-find-and-replace/src/findandreplaceutils.ts, packages/ckeditor5-find-and-replace/src/findcommand.ts, packages/ckeditor5-find-and-replace/src/index.ts, packages/ckeditor5-find-and-replace/src/replaceallcommand.ts, packages/ckeditor5-find-and-replace/src/replacecommand.ts, packages/ckeditor5-find-and-replace/src/replacecommandbase.ts
Internal (find-and-replace): Added re-exports and aligned naming in the `ckeditor5-find-and-replace` package.
---
=> Added re-exports and aligned naming in the `ckeditor5-find-and-replace` package

packages/ckeditor5-font/src/fontbackgroundcolor/fontbackgroundcolorui.ts, packages/ckeditor5-font/src/fontcolor/fontcolorui.ts, packages/ckeditor5-font/src/index.ts, packages/ckeditor5-font/src/ui/colorui.ts, packages/ckeditor5-font/src/utils.ts, packages/ckeditor5-font/tests/_utils/testcolorplugin.js, packages/ckeditor5-font/tests/fontbackgroundcolor/fontbackgroundcolorui.js, packages/ckeditor5-font/tests/fontcolor/fontcolorui.js, packages/ckeditor5-font/tests/ui/colorui.js, packages/ckeditor5-heading/docs/features/title.md, packages/ckeditor5-heading/src/augmentation.ts, packages/ckeditor5-heading/src/index.ts, packages/ckeditor5-heading/src/title.ts, packages/ckeditor5-html-embed/src/index.ts
Internal (font): Added re-exports and aligned naming in the `ckeditor5-font` package.
Internal (heading): Added re-exports and aligned naming in the `ckeditor5-heading` package.
Internal (html-embed): Added re-exports in the `ckeditor5-html-embed` package.
---
=> Added re-exports and aligned naming in the `ckeditor5-font`, `ckeditor5-heading` and `ckeditor5-html-embed` packages

packages/ckeditor5-html-support/docs/features/full-page-html.md, packages/ckeditor5-html-support/docs/features/general-html-support.md, packages/ckeditor5-html-support/src/converters.ts, packages/ckeditor5-html-support/src/datafilter.ts, packages/ckeditor5-html-support/src/dataschema.ts, packages/ckeditor5-html-support/src/generalhtmlsupport.ts, packages/ckeditor5-html-support/src/generalhtmlsupportconfig.ts, packages/ckeditor5-html-support/src/index.ts, packages/ckeditor5-html-support/src/integrations/codeblock.ts, packages/ckeditor5-html-support/src/integrations/customelement.ts, packages/ckeditor5-html-support/src/integrations/dualcontent.ts, packages/ckeditor5-html-support/src/integrations/horizontalline.ts, packages/ckeditor5-html-support/src/integrations/image.ts, packages/ckeditor5-html-support/src/integrations/list.ts, packages/ckeditor5-html-support/src/integrations/mediaembed.ts, packages/ckeditor5-html-support/src/integrations/script.ts, packages/ckeditor5-html-support/src/integrations/style.ts, packages/ckeditor5-html-support/src/integrations/table.ts, packages/ckeditor5-html-support/src/schemadefinitions.ts, packages/ckeditor5-style/src/styleutils.ts
Internal (html-support): Added re-exports and aligned naming in the `ckeditor5-html-support` package.
Internal (style): Aligned to renames from the `ckeditor5-html-support` package.
---
Commercial PR: https://github.com/cksource/ckeditor5-commercial/pull/7925.
=> Added re-exports and aligned naming in the `ckeditor5-html-support` package

packages/ckeditor5-code-block/tests/codeblock-integration.js, packages/ckeditor5-markdown-gfm/docs/api/markdown-gfm.md, packages/ckeditor5-markdown-gfm/docs/features/markdown.md, packages/ckeditor5-markdown-gfm/src/gfmdataprocessor.ts, packages/ckeditor5-markdown-gfm/src/html2markdown/html2markdown.ts, packages/ckeditor5-markdown-gfm/src/index.ts, packages/ckeditor5-markdown-gfm/src/markdown.ts, packages/ckeditor5-markdown-gfm/src/markdown2html/markdown2html.ts, packages/ckeditor5-markdown-gfm/src/pastefrommarkdownexperimental.ts, packages/ckeditor5-markdown-gfm/tests/_utils/utils.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/blockquotes.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/code.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/escaping.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/gfmdataprocessor.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/headers.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/horizontal-rules.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/html.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/images.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/links.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/lists.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/paragraphs.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/strikethrough.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/strong-emphasis.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/tables.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/tabs.js, packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/text.js, packages/ckeditor5-markdown-gfm/tests/manual/gfmdataprocessor/gfmdataprocessor.js, packages/ckeditor5-markdown-gfm/tests/markdown.js
Internal (markdown-gfm): Added re-exports and aligned naming in the `ckeditor5-markdown-gfm` package.
Internal (code-block): Aligned to renames from the `ckeditor5-markdown-gfm` package.
---
=> Added re-exports and aligned naming in the `ckeditor5-markdown-gfm` package

docs/umberto.json, packages/ckeditor5-link/src/index.ts, packages/ckeditor5-link/src/linkcommand.ts, packages/ckeditor5-link/src/linkediting.ts, packages/ckeditor5-link/src/linkimageediting.ts, packages/ckeditor5-link/src/ui/linkformview.ts, packages/ckeditor5-link/src/ui/linkpropertiesview.ts, packages/ckeditor5-link/src/ui/linkprovideritemsview.ts, packages/ckeditor5-link/src/utils/manualdecorator.ts, packages/ckeditor5-link/tests/linkcommand.js, packages/ckeditor5-link/tests/linkui.js, packages/ckeditor5-link/tests/ui/linkpropertiesview.js, packages/ckeditor5-link/tests/utils/manualdecorator.js
Internal (link): Added re-exports and aligned naming in the `ckeditor5-link` package.
---
=> Added re-exports and aligned naming in the `ckeditor5-link` package

packages/ckeditor5-list/src/index.ts, packages/ckeditor5-list/src/legacylist/legacyconverters.ts, packages/ckeditor5-list/src/legacylist/legacyutils.ts, packages/ckeditor5-list/src/legacytodolist/legacytodolistconverters.ts, packages/ckeditor5-list/src/list/listediting.ts
Internal (list): Added re-exports and aligned naming in the `ckeditor5-list` package.
---
=> Added re-exports and aligned naming in the `ckeditor5-list` package

packages/ckeditor5-table/theme/table.css
Fix (table): Improve calculation of pagination page-breaks on documents with long tables. Closes https://github.com/ckeditor/ckeditor5/issues/18600
---
=> [Hotfix] Improve calculation of pagination page-breaks on documents with long tables

packages/ckeditor5-typing/src/input.ts, packages/ckeditor5-typing/tests/input.js
Fix (typing): Typing over multiple selected blocks next to a code block or a block quote should not crash the editor. Closes #18722.
---
=> Fixed typing over multiple blocks selected.

packages/ckeditor5-engine/src/conversion/mapper.ts, packages/ckeditor5-engine/tests/conversion/mapper.js
Fix (engine): Fixed editor crash that happened in a specific scenario, when editing heavily formatted text, text with multiple comments, or text with comments and formatting. Closes #18727.
Internal (engine): Renames in `MapperCache` methods so names correctly reflect what the methods do.
=> Fixed MapperCache cache invalidation when view item is inserted at a beginning of a non-tracked element

packages/ckeditor5-widget/src/index.ts, packages/ckeditor5-widget/src/widgetresize/resizer.ts, packages/ckeditor5-widget/src/widgetresize/resizerstate.ts, packages/ckeditor5-widget/src/widgetresize/sizeview.ts, packages/ckeditor5-widget/tests/widgetresize/resizerstate.js, packages/ckeditor5-widget/tests/widgetresize/sizeview.js
Internal: Fixed missing reexport and rename for `WidgetResizeState`.
---
=> Fixed missing reexport and rename for `WidgetResizeState`.

docs/updating/migration-to-cdn/vanilla-js.md
Docs: expanding the update guide. Closes https://github.com/ckeditor/ckeditor5/issues/18746
---
=> Docs: expanding the update guide.

packages/ckeditor5-list/src/augmentation.ts, packages/ckeditor5-list/src/index.ts, packages/ckeditor5-list/src/listformatting.ts, packages/ckeditor5-list/src/listformatting/listitemitalicintegration.ts, packages/ckeditor5-list/tests/listformatting.js, packages/ckeditor5-list/tests/listformatting/listitemitalicintegration.js, packages/ckeditor5-list/theme/listformatting.css
Internal (list): Added upcast and downcast converters for `listItemItalic` attribute. Closes #18712.
---
=> List item italic upcast and downcast converters

packages/ckeditor5-clipboard/theme/clipboard.css
Fix (clipboard): Add z-index to clipboard drop target line. Closes #18380.
---
=> Add z-index to clipboard drop target line.

packages/ckeditor5-list/src/list/converters.ts, packages/ckeditor5-list/src/listformatting/listitemboldintegration.ts, packages/ckeditor5-list/src/listformatting/listitemfontsizeintegration.ts, packages/ckeditor5-list/src/listformatting/listitemitalicintegration.ts, packages/ckeditor5-list/tests/listformatting/listitemboldintegration.js, packages/ckeditor5-list/tests/listformatting/listitemfontsizeintegration.js, packages/ckeditor5-list/tests/listformatting/listitemitalicintegration.js
Added a workaround for Safari glitch with list marker styling.
---
* Closes #18790
---
=> Added a workaround for Safari glitch with list marker styling.

packages/ckeditor5-list/src/list/converters.ts, packages/ckeditor5-list/src/list/listediting.ts, packages/ckeditor5-list/src/listproperties/listpropertiesediting.ts, packages/ckeditor5-list/tests/listproperties/listpropertiesediting.js
*A brief summary of what this PR changes.*
---
* Closes https://github.com/cksource/ckeditor5-commercial/issues/8005.
* Closes https://github.com/cksource/ckeditor5-commercial/issues/8012.
---
Test added here as it is more straightforward to test that way: https://github.com/cksource/ckeditor5-commercial/pull/8014
=> List items should not be rewrapped for unrelated attribute change.

packages/ckeditor5-table/src/converters/tableproperties.ts, packages/ckeditor5-table/src/tableproperties/tablepropertiesediting.ts, packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js
Fix upcasting of `background-color` in tables. 
---
* Closes https://github.com/ckeditor/ckeditor5/issues/18803
---
Most likely related to https://github.com/ckeditor/ckeditor5/commit/71660f26fa2df1764edba36a3cd9ebdf2f278639#diff-251f3fa2633ce2469b2b3c1f3732db3b548eab2595295337591bc14c8caf3b15R57-R62
=> Fix upcasting of `background-color` in tables. 

scripts/docs/build-ckeditor-packages.mjs
Show the actual error that caused the docs build to fail instead of only showing a generic `error Command failed with exit code 1` message.
---
* Closes #18810
---
**Before:**
**After:**
=> Display errors when building the editor for docs

docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md, docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-2.md, docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-3.md, tests/manual/abbreviation-level-2.md
Update imports in abbreviation tutorial docs.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/18799
=> Update imports in abbreviation tutorial docs.

docs/getting-started/integrations-cdn/dotnet.md, docs/getting-started/integrations-cdn/laravel.md, docs/getting-started/integrations-cdn/next-js.md, docs/getting-started/integrations-cdn/nuxt.md, docs/getting-started/integrations-cdn/quick-start.md, docs/getting-started/integrations-cdn/salesforce.md, docs/getting-started/integrations-cdn/spring-boot.md, docs/getting-started/integrations-cdn/svelte.md, docs/getting-started/integrations/css.md, docs/getting-started/integrations/dotnet.md, docs/getting-started/integrations/laravel.md, docs/getting-started/integrations/next-js.md, docs/getting-started/integrations/nuxt.md, docs/getting-started/integrations/quick-start.md, docs/getting-started/integrations/salesforce.md, docs/getting-started/integrations/sharepoint.md, docs/getting-started/integrations/spring-boot.md, docs/getting-started/integrations/svelte.md
Docs: updating selected integration guides metadata.
---
* Closes https://github.com/cksource/ckeditor5-commercial/issues/8019
---
=> Docs: updating metadata.

docs/framework/contributing/code-style.md, eslint.config.mjs, scripts/constants.mjs
Internal: Lint changelog entries.
---
* Closes #18777
---
:warning: Blocked by ckeditor/ckeditor5-linters-config#71
=> Lint changelog entries

docs/updating/nim-migration/customized-builds.md
Docs: Remove outdated warning from NIM migration guide.
=> Docs: Remove outdated warning from NIM migration guide.

scripts/ci/check-manual-tests-directory-structure.mjs, scripts/ci/exports/policy/validate-command-exports.mjs, scripts/ci/exports/utils/getfilepaths.mjs, scripts/ci/exports/utils/module.mjs, scripts/ci/validate-module-re-exports.mjs
Modified export validator to ensure command is exported as value instead of type.
---
* Closes ckeditor/ckeditor5#18804
---
=> Modified export validator to ensure command is exported as value instead of type.

scripts/release/utils/parsearguments.mjs
Set concurrency in release scripts to guarantee at least 1 CPU core and 1 GB of free RAM per task.
* See https://github.com/cksource/ckeditor5-commercial/issues/8048.
---
This PR addresses an out-of-memory (OOM) issue by capping the maximum build concurrency.
I benchmarked the impact of different concurrency levels on build performance. The results were:
* **1 → 4 concurrent builds**: Significant improvement, reducing build time from ~450 s to ~270 s.
* **4 → 8 concurrent builds**: Modest improvement, dropping to ~240 s.
* **8 → 16 concurrent builds**: No measurable performance gain.
~~Given the diminishing returns beyond 4 concurrent builds and to avoid more complex solutions (for example, based on CPU cores **and** available memory), this PR sets the maximum concurrency to 4 as a …
=> Set concurrency in release scripts to guarantee at least 1 CPU core and 1 GB of free RAM per task

.changelog/20250723121141_ck_18856.md, packages/ckeditor5-utils/src/dom/global.ts, scripts/ci/validate-module-re-exports.mjs
Fixed the `Identifier 'global' has already been declared.` error being thrown in some environments due to global variable name in `ckeditor5-utils` package.
---
* Closes #18856
---
=> Fixed duplicate global identifier

scripts/docs/snippetadapter.mjs
Occasionally, `snippet.js` runs before `snippet.css` is parsed and available via `document.querySelector`, causing instability in the verify utility on demos relying on `querySnippetCSSUrl`. This PR ensures that the CSS is loaded and available before `snippet.js` is executed, stabilizing PDF export functionality in the docs.
---
Source PR:
https://github.com/ckeditor/ckeditor5/pull/18887/files#diff-5b4762b6792aa2a933df1fc08e8441b6949b053be4cc4dd8703be6d8f3ac7254R288
=> Docs: Make sure `snippet.css` is included before `snippet.js`.

packages/ckeditor5-minimap/docs/_snippets/features/minimap.js
This PR introduces a patch for the CKEditor minimap feature to fix font loading issues in the minimap preview. When external CSS files define fonts using relative paths (e.g. `url('../fonts/MyFont.woff2')`), the iframe used by the minimap incorrectly resolves these paths, causing fonts to be missing in the preview.
The patch overrides the minimap iframe rendering method to rewrite font URLs in CSS styles, making them resolve correctly relative to the CSS file location. This ensures that fonts are properly loaded and displayed in the minimap preview.
This is a temporary workaround that rewrites font URLs in CSS styles for the minimap preview. It should be removed once the underlying issue is fixed in #18896.
---
* Caused by: https://github.com/ckeditor/ckeditor5/issues/18896
=> Docs: Fix fonts in minimap docs snippet.

packages/ckeditor5-ui/src/dropdown/utils.ts, packages/ckeditor5-ui/src/index.ts, packages/ckeditor5-ui/tests/dropdown/utils.js
Extended dropdown component utils to allow creating a dropdown list with custom `ButtonLabelView` (passed from outside code, not auto-created).
---
None.
---
Required for https://github.com/cksource/ckeditor5-commercial/pull/8070.
=> Allow using custom button labels in a dropdown component [WIP]

.changelog/20250820065521_ck_1889.md, packages/ckeditor5-engine/src/view/observer/selectionobserver.ts, packages/ckeditor5-engine/tests/view/observer/selectionobserver.js
No longer crash the editor when a selection change occurs within a detached element and during rendering of the editing.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/18744
---
Occasionally, such as when removing markers during a focus change, the selection may end up inside a view element whose parent has already been detached from the DOM but is still present in the view DOM mappings. In most cases this is harmless, but if the `selectionchange` event fires before the view is fully synchronized with the DOM converter, some elements in the selection may become orphans.
For example:
The `comment` marker has been removed from the view, but it's still present in DOM converter mappings.
=> No longer crash editor when selection change occurs within detached lement and during rendering of the editing.

package.json
Use multithread linting.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/19010.
---
`--concurrency=4` runs much faster on CI than `--concurrency=auto` and has no performance impact locally on a 22-core machine.
=> Use multithread linting

.circleci/template.yml
Use patterns instead of globs to match branches on CI.
---
* Closes #000
---
=> Use patterns instead of globs to match branches on CI (`#release-v45`)

scripts/release/switchlatestnpm.mjs
Fixed release:switch-latest-npm script
This PR applies cherry-picked changes from https://github.com/ckeditor/ckeditor5/pull/19066
---
* See #19058
---
=> Fixed release:switch-latest-npm script

scripts/release/utils/getreleasedescription.mjs
> [!WARNING]
> Target: **`#release`**.
Use a path to the "ckeditor5" package when calculating a new version for nightly releases.
---
* Closes https://github.com/ckeditor/ckeditor5-commercial/issues/8285.
---
Please, check the changes manually.
=> Use a path to the "ckeditor5" package when calculating a new version

.circleci/config.yml, .circleci/template.yml, scripts/ci/generate-circleci-configuration.mjs
Setting chrome version in generated Circle CI config using `chrome-version` parameter.
Added a new `chromeVersion` parameter to `.circleci/config.yml` with a default value of `140.0.7339.127`.
Inheriting `parameters` in `template.yml` from `config.yml`.
Enhanced the `generate-circleci-configuration.mjs` script to accept a `--chrome-version` command line argument.
---
* Closes #000
---
=> Setting chrome version in generated Circle CI config using `chrome-version` parameter.

.circleci/config.yml, .circleci/template.yml
Disable corepack on CI.
---
* See ckeditor/ckeditor5-commercial#8335.
=> Disable corepack on CI

.changelog/20250923165802_ck_19134.md, packages/ckeditor5-table/docs/features/tables-styling.md, packages/ckeditor5-table/tests/manual/tabledefaultproperties.html, packages/ckeditor5-table/theme/table.css
Reverted changes related to `:where()` pseudo-class in table styles.
---
As many Node.js tools/packages do not handle `:where()` selectors properly, we decided to roll back this change as it might cause issues on the integration side.
=> Reverted changes related to `:where()` pseudo-class in table styles.

scripts/release/clean.mjs
Use `glob()` with a pattern for matching directories only instead of manually reading a directory to avoid crashing the `release:clean` script.
---
* Closes ckeditor/ckeditor5-commercial#8476.
---
I used both repositories to check.
```
node ./scripts/release/clean.mjs
Done!
touch packages/.DS_Store
ls -la packages/ | grep DS_Store
-rw-r--r--@  1 pomek  staff     0 Sep 25 12:43 .DS_Store
node external/ckeditor5/scripts/release/clean.mjs --cwd .
Done!
```
Btw, the pull request targets the `#release` branch.
=> Do not crash when found a file inside the `packages/` directory

scripts/ci/exports/utils/module.mjs
Replaced broad `/external` check with a more precise for exporting public module members in `external/ckeditor5/packages`.
We want to keep the old behaviour, and mark all files from `ckeditor5/packages` as public API.
The rest of the files would have to be set manually to be marked as public API.
---
* Closes #18993
---
=> Module export validator improvements.

docs/features/math-equations.md
As the title suggests, it adds a CKEditor 5 CDN + MathType setup.
---
* Closes https://github.com/ckeditor/ckeditor5-commercial/issues/8561
---
=> Docs: Add a CKEditor 5 CDN + MathType setup

packages/ckeditor5-paste-from-office/src/filters/replacemsfootnotes.ts, packages/ckeditor5-paste-from-office/src/normalizers/mswordnormalizer.ts, packages/ckeditor5-paste-from-office/tests/filters/replacemsfootnotes.js
This PR adds support for pasting footnotes via paste-from-office from MS word. 
---
Footnotes PR: https://github.com/ckeditor/ckeditor5/pull/19132
Initiative issue: https://github.com/ckeditor/ckeditor5-commercial/issues/8165
Issue: https://github.com/ckeditor/ckeditor5-commercial/issues/8171
=> Add support for footnotes to paste from office.
