ckeditor/ckeditor5

- packages/ckeditor5-font/src/ui/colortableview.ts
- packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
- packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js
- packages/ckeditor5-ui/theme/components/colorpicker/colorpicker.css
Internal(ui): Accept only hex values in color input.
---
> Accept only hex values in color input

- docs/installation/working-with-typescript.md
Docs: adding minimal TypeScript version number. Closes cksource/ckeditor5-internal#3194
---
> Docs: adding TS version number.

- packages/ckeditor5-table/src/tableselection.ts
Fix (table): Remove comment with both `CK_DEBUG` and `istanbul` that breaks `vite` integration. See #13922.
---
> Remove comment with istanbul ignore.

- scripts/release/compiletypescriptcallback.js
- scripts/release/prepare-packages.js
Internal: Release process: prepare JavaScript and typings. Closes #13970.
---
> Release process: prepare JavaScript and typings

- packages/ckeditor5-font/tests/ui/colorui.js
Internal(font): Unskip color picker tests.
---
> Unskip color picker tests

- packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
- packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js
Internal(font): Remove some obsolete code.
---
> Remove obsolete code in color picker

- docs/framework/development-tools.md
Docs: Fix the CKEditor Inspector snippet. Closes #12156.
---
> Docs: Fix the CKEditor Inspector snippet.

- packages/ckeditor5-core/src/editor/editorconfig.ts
- packages/ckeditor5-ui/src/editorui/poweredby.ts
- packages/ckeditor5-ui/tests/manual/poweredby/poweredby.html
- packages/ckeditor5-ui/tests/manual/poweredby/poweredby.js
- packages/ckeditor5-ui/theme/globals/_poweredby.css
Internal (ui): Allowed configuration of the "powered by" feature. Closes cksource/ckeditor5-internal#3215.
---
**Requires #14056**
> Allowed configuration of the PBC

- packages/ckeditor5-utils/src/madewith.ts
- packages/ckeditor5-utils/tests/madewith.js
Internal (utils) : Should cover all edge cases in token verification.
Closes https://github.com/cksource/ckeditor5-internal/issues/3232.
---
All cases are covered 👉 https://github.com/cksource/ckeditor5-internal/issues/3232#issuecomment-1540224260
> Update the verify function to cover all possible cases.

- packages/ckeditor5-ui/src/editorui/poweredby.ts
- packages/ckeditor5-ui/tests/editorui/poweredby.js
- packages/ckeditor5-ui/theme/globals/_poweredby.css
Tests (ui): Added tests for the Powered by CKEditor feature. Closes cksource/ckeditor5-internal#3225
---
There are not the most thorough tests but they will do.
> Added tests for the Powered by CKEditor feature

- packages/ckeditor5-table/package.json
- packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.ts
- packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js
Internal (table): Make table resize work with multi-root editor.
> Internal (table): Make table resize work with multi-root editor

- docs/framework/tutorials/using-react-in-a-widget.md
Docs: Fix the webpack config in react widget tutorial. Closes #12180.
---
> Docs: Fix the webpack config in react widget tutorial.

- packages/ckeditor5-mention/tests/mention-integration.js
- packages/ckeditor5-typing/src/utils/getlasttextline.ts
- packages/ckeditor5-typing/tests/utils/getlasttextline.js
Fix (mention): Multiple mentions in the last table cell should not result in selection error. Closes #14025.
---
> Multiple mentions in the last cell result in selection error

- docs/installation/migration-from-ckeditor-4.md
- docs/updating/migration-from-ckeditor-4.md
Docs: Add information about CKE4 EOL to CKE4 migration sections. Closes https://github.com/cksource/ckeditor5-internal/issues/2975.
---
Extended Support Model is linked to the LP: https://ckeditor.com/ckeditor-4-support/
> Add information about CKE4 EOL to CKE4 migration sections

- scripts/release/utils/validatedependenciesversions.js
Internal: Added `skipPackages` argument to `validateDependenciesVersions()`.
---
> Added `skipPackages` argument to `validateDependenciesVersions()`.

- packages/ckeditor5-core/src/editor/editorconfig.ts
Docs: updated `licenseKey` API docs. Closes cksource/ckeditor5-internal#3308
---
> Docs: update API docs.

- packages/ckeditor5-restricted-editing/docs/_snippets/features/restricted-editing.js
Docs: updating CKBox configuration in restricted editing modes. Closes cksource/ckeditor5-internal#3311
---
> Docs: updating configuration.

- README.md
- docs/installation/getting-started/quick-start.md
Docs: Add a TypeScript section in the Quick start guide. Closes https://github.com/ckeditor/ckeditor5/issues/13831.
---
> Docs: Add a TypeScript section in the Quick start guide.

- packages/ckeditor5-ui/src/editorui/bodycollection.ts
- packages/ckeditor5-ui/tests/editorui/bodycollection.js
Feature (ui): `BodyCollection.bodyCollectionContainer` made public property. Closes #13928.
---
> BodyCollection.bodyCollectionContainer made public.

- packages/ckeditor5-font/tests/ui/colortableview.js
- packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
- packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js
Fix: Fixed key behaviour in color picker. Closes #[14218](https://github.com/ckeditor/ckeditor5/issues/14218).
---
> Fixed key behaviour in color picker

- packages/ckeditor5-engine/src/index.ts
Other (engine): Exports `ViewTreeWalker` from `ckeditor5-engine/src/index.ts`. Closes #14158.
---
> Export ViewTreeWalker from ckeditor5-engine/src/index.ts

- .markdownlint.json
Docs: Add an example config for markdown linting. Closes https://github.com/cksource/ckeditor5-internal/issues/3174.
---
> Docs: Add an example config for markdown linting.

- packages/ckeditor5-ui/theme/components/colorpicker/colorpicker.css
Fix (ui): Should fix the width of shrinked inputs fields in editor toolbar dropdowns. 
Closes #14230 .
---
> Fix of the broken form layouts containing text inputs.

- packages/ckeditor5-clipboard/docs/features/drag-drop.md
Fix the style of code snippets for drag and drop.
Type: Docs.
---
> Fix code snippets.

- docs/installation/integrations/angular.md
Docs: Update the Angular snippet. Closes https://github.com/cksource/ckeditor5-internal/issues/3315.
---
> Docs: Update the Angular snippet.

- docs/framework/contributing/testing-environment.md
Docs: Added docs for TS support for automated and manual tests. See #14170, #14171.
---
> Added docs for TS support for automated and manual tests.

- docs/framework/creating-simple-plugin-timestamp.md
Docs: Add a link to the Creating a basic plugin guide. Closes #12744.
---
> Docs: Add a link to the Creating a basic plugin guide.

- docs/framework/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
Docs: the export for AbbreviationUI Class is updated. Closes [#14338](https://github.com/ckeditor/ckeditor5/issues/14329).
---
> Docs: updating the export for the AbbreviationUI Class in the guide.

- docs/installation/integrations/css.md
- docs/installation/integrations/dotnet.md
- docs/installation/integrations/laravel.md
- docs/installation/integrations/other.md
Adding new guides to our Integrations docs on how the integrate the editor with Laravel and .NET.
> Add documentation articles for Laravel and .NET

- docs/assets/snippet-styles.css
- packages/ckeditor5-show-blocks/docs/_snippets/features/show-blocks.html
- packages/ckeditor5-show-blocks/docs/_snippets/features/show-blocks.js
- packages/ckeditor5-show-blocks/docs/api/show-blocks.md
- packages/ckeditor5-show-blocks/docs/features/show-blocks.md
- packages/ckeditor5-show-blocks/theme/showblocks.css
Docs (show-blocks): Add show blocks feature guide. Closes #14347.
---
> Show blocks docs

- packages/ckeditor5-html-support/src/integrations/documentlist.ts
- packages/ckeditor5-html-support/tests/integrations/documentlist.js
- packages/ckeditor5-html-support/tests/manual/documentlist.js
Internal (html-support): Fix inifite loop when adding a new elements to the nested document list. Closes #14434.
---
:warning: This branch targets the `release` branch :warning:
> Fix inifite loop when adding a new elements to the nested document list

- docs/features/productivity-pack.md
Dos: updating trials link for productivity pack.
---
Only merge after https://github.com/cksource/docs/pull/560
> Docs: trials link.

- CHANGELOG.md
- docs/updating/update-to-38.md
Docs: adding the v 38.1.0 update guide
---
Touches https://github.com/cksource/ckeditor5-internal/issues/3386
> Docs: 38.1.0 update guide

- packages/ckeditor5-mention/docs/_snippets/features/mention.js
Docs: shortening mention trigger. Closes https://github.com/cksource/ckeditor5-internal/issues/3393
---
Merge with https://github.com/cksource/ckeditor5-internal/pull/3399
> Docs: shortening mention trigger.

- scripts/release/changelog.js
- scripts/release/preparepackages.js
- scripts/release/publishpackages.js
- scripts/release/utils/constants.js
- scripts/release/utils/parsearguments.js
Internal: Release tools - enable execution from feature branches by specifying the `--branch` name. Closes #14472.
---
> Release the project from a feature branch

- packages/ckeditor5-font/tests/integration.js
- packages/ckeditor5-font/tests/ui/colorui.js
- packages/ckeditor5-table/src/ui/colorinputview.ts
- packages/ckeditor5-table/tests/ui/colorinputview.js
- packages/ckeditor5-table/tests/utils/ui/table-properties.js
- packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
- packages/ckeditor5-ui/src/colortable/colortableview.ts
- packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js
- packages/ckeditor5-ui/tests/colortable/colortableview.js
Internal (ui): Fix feedback loop in the color picker. Closes #14432.  
Internal (ui): Propagate the selected color to the color table in table properties. Closes #14415.
---
I requested the QA team assistance, so let's wait with merge until they accept the PR.
> Fix feedback loop in the color picker

- docs/umberto.json
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-clipboard/docs/_snippets/features/drag-drop.js
- packages/ckeditor5-clipboard/docs/features/drag-drop.md
- packages/ckeditor5-image/docs/features/images-text-alternative.md
Docs: various follow-ups to CKBox documentation.
Closes: https://github.com/cksource/ckeditor5-internal/issues/3404
Also closes: https://github.com/cksource/ckeditor5-internal/issues/3402
And also closes: https://github.com/cksource/ckeditor5-internal/issues/3427
> CKBox follow-ups

- docs/updating/release-process.md
Docs: update release process. Closes https://github.com/cksource/ckeditor5-internal/issues/3417
---
> Docs: update release process.

- docs/installation/migration-from-ckeditor-4.md
- docs/updating/migration-from-ckeditor-4.md
Docs: updating CKE4 info. Closes https://github.com/cksource/ckeditor5-internal/issues/3440
---
> Docs: updating CKE4 info.

- packages/ckeditor5-image/tests/manual/imagesizeattributesallcases.js
- packages/ckeditor5-image/theme/image.css
Task (image): Adds picture use cases to image sizes manual test. Closes #14532.
---
> Inline picture should not exceed the width of the parent container

- packages/ckeditor5-core/src/editor/utils/dataapimixin.ts
- packages/ckeditor5-source-editing/src/sourceediting.ts
- packages/ckeditor5-source-editing/tests/sourceediting.js
Fix (source-editing): Fixes infinite loop in source editing mode.  Closes #14469.
---
> Fix infinite loop in source-editing.

- docs/features/using-file-managers.md
Docs: Fixed minor typo "con venient" -> "convenient".
---
Noticed a minor typo while reading about different image plugins in CKEditor 5: con venient -> convenient
> con venient -> convenient

- docs/framework/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
Clarify setup directions & link to README.md
---
> A little extra detail for setup instructions

- docs/updating/migration-from-ckeditor-4.md
Docs: updating CKE4 EOL info. Closes https://github.com/cksource/ckeditor5-internal/issues/3460
---
> Docs: updating CKE4 EOL info.

- packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector-heading-interactive.js
- packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector-heading.js
- packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector-structure.js
- packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector-upcast-attribute.js
- packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector-upcast-element.js
Docs: Fix warnings in the conversion guides. Closes https://github.com/ckeditor/ckeditor5/issues/12555.
---
> Docs: Fix warnings in the conversion guides.

- package.json
- scripts/dll/webpack.config.dll.js
- scripts/dll/webpackFooterPlugin.js
Internal: Fixed deprecation warning in the `dll:build` script. Closes #10980.
---
> Fixed deprecation warning in the dll:build script

- packages/ckeditor5-table/src/utils/ui/table-properties.ts
- packages/ckeditor5-table/tests/utils/ui/table-properties.js
Fix(table): Support for capital case letters in color inputs. Closes [#14495](https://github.com/ckeditor/ckeditor5/issues/14495).
---
> Support for capital case letters in color inputs

- packages/ckeditor5-table/docs/features/tables-styling.md
Docs: minor fixes in code listings. Closes  https://github.com/ckeditor/ckeditor5/issues/14719
---
> Docs: minor fixes.

- docs/features/editor-placeholder.md
- docs/installation/getting-started/quick-start-other.md
- docs/updating/release-process.md
- docs/updating/update-to-39.md
- packages/ckeditor5-ckbox/src/ckboxuploadadapter.ts
- packages/ckeditor5-ckbox/src/utils.ts
- packages/ckeditor5-editor-multi-root/src/augmentation.ts
- packages/ckeditor5-editor-multi-root/src/multirooteditor.ts
Docs: post-release docs review. Part of https://github.com/cksource/ckeditor5-internal/issues/3529
---
> Docs: post-release docs review.

- scripts/release/changelog.js
- scripts/release/getchangelogoptions.js
Internal: Extracted changelog options to a separate file. See #14601.
---
> Extracted changelog options to a separate file.

- docs/examples/index.md
- docs/framework/index.md
- docs/index.md
- docs/installation/index.md
- docs/support/index.md
- docs/updating/changelog.md
- docs/updating/index.md
- docs/updating/maintaining.md
- docs/updating/release-process.md
- docs/updating/updating-ckeditor-5.md
- docs/updating/versioning-policy.md
Docs: updating headers. Closes https://github.com/cksource/ckeditor5-commercial/issues/5412
---
> Docs: updating headers.

- package.json
Internal: Added the `@ckeditor/ckeditor5-ckbox` dependency to the `ckeditor5` to avoid errors when building documentation.
> Added ckbox dependency

- docs/examples/index.md
- docs/framework/index.md
- docs/index.md
- docs/installation/index.md
- docs/updating/ckeditor4-configuration-compatibility.md
- docs/updating/ckeditor4-plugin-compatibility.md
- docs/updating/ckeditor4-troubleshooting.md
- docs/updating/index.md
- docs/updating/maintaining.md
- docs/updating/migration-from-ckeditor-4.md
- docs/updating/release-process.md
- docs/updating/updating-ckeditor-5.md
- docs/updating/versioning-policy.md
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-clipboard/docs/features/drag-drop.md
- packages/ckeditor5-image/docs/features/images-captions.md
- packages/ckeditor5-image/docs/features/images-inserting.md
- packages/ckeditor5-image/docs/features/images-installation.md
- packages/ckeditor5-image/docs/features/images-linking.md
- packages/ckeditor5-image/docs/features/images-overview.md
- packages/ckeditor5-image/docs/features/images-resizing.md
- packages/ckeditor5-image/docs/features/images-responsive.md
- packages/ckeditor5-image/docs/features/images-styles.md
- packages/ckeditor5-image/docs/features/images-text-alternative.md
Docs: removing nbsp from metadata. Closes https://github.com/cksource/ckeditor5-internal/issues/3553
---
> Docs: removing nbsp from metadata.

- scripts/docs/snippetadapter.js
Docs: Fixed console source maps warnings in docs snippets. Closes #14666.
---
> Fixed console source maps warnings in docs snippets.

- docs/examples/how-tos.md
- docs/installation/getting-started/api-and-events.md
- docs/installation/getting-started/extending-features.md
Docs: Change the plugin example, tweak some links and wordings.
---
> Implement feedback for the latest docs.

- scripts/ci/check-unit-tests-for-package.js
- scripts/ci/should-run-short-flow.js
- scripts/ci/travis-check.js
- scripts/ci/validate-metadata-icons.js
- scripts/release/preparepackages.js
- scripts/release/utils/parsearguments.js
Internal: Support for building the project on CircleCI.
> Support for building the project on CircleCI

- docs/installation/getting-started/predefined-builds.md
Docs: adding PfOE to superbuild. Closes https://github.com/cksource/ckeditor5-commercial/issues/5460
---
_Merge with https://github.com/cksource/ckeditor5-commercial/pull/5464_
> Docs: adding PfOE to superbuild.

- docs/api/index.md
- docs/installation/advanced/content-styles.md
- docs/installation/advanced/csp.md
- docs/installation/advanced/dll-builds-collaboration-features.md
- docs/installation/advanced/dll-builds.md
- docs/installation/advanced/integrating-from-source-vite.md
- docs/installation/advanced/integrating-from-source-webpack.md
- docs/installation/advanced/using-two-editors.md
- docs/installation/getting-started/api-and-events.md
- docs/installation/getting-started/configuration.md
- docs/installation/getting-started/editor-lifecycle.md
- docs/installation/getting-started/extending-features.md
- docs/installation/getting-started/getting-and-setting-data.md
- docs/installation/getting-started/predefined-builds.md
- docs/installation/getting-started/quick-start-other.md
- docs/installation/getting-started/quick-start.md
- docs/installation/index.md
- docs/installation/integrations/angular.md
- docs/installation/integrations/css.md
- docs/installation/integrations/dotnet.md
- docs/installation/integrations/laravel.md
- docs/installation/integrations/other.md
- docs/installation/integrations/overview.md
- docs/installation/integrations/react.md
- docs/installation/integrations/vuejs-v2.md
- docs/installation/integrations/vuejs-v3.md
- docs/installation/plugins/features-html-output-overview.md
- docs/installation/plugins/installing-plugins.md
- docs/installation/plugins/plugins.md
- docs/installation/working-with-typescript.md
Docs: getting started meta titles. Closes https://github.com/cksource/ckeditor5-internal/issues/3561
---
> Docs: getting started meta titles.

- docs/installation/getting-started/api-and-events.md
- docs/installation/getting-started/extending-features.md
Docs: Fix API and events opening sentence wording.
---
> Fix the wording and add additional link.

- docs/installation/getting-started/quick-start.md
Docs: updating superbuild config. Closes https://github.com/ckeditor/ckeditor5/issues/14850
---
> Docs: updating superbuild config.

- docs/installation/advanced/integrating-from-source-vite.md
Docs: Corrected paths in snippets in the Vite guide. Closes #14908.
---
> Docs: Corrected paths in snippets in the Vite guide

- packages/ckeditor5-ckbox/tests/_utils/ckbox-config.js
Docs: update CKBox token. Part of https://github.com/cksource/ckeditor5-commercial/issues/5489
---
_Docs sync with https://github.com/ckeditor/ckeditor5/pull/14920_
> Docs: update CKBox token.

- packages/ckeditor5-mention/src/mention.ts
- packages/ckeditor5-mention/src/mentioncommand.ts
- packages/ckeditor5-mention/src/mentionediting.ts
- packages/ckeditor5-mention/src/ui/domwrapperview.ts
Fix (mention): Fixes typing of `Mention#toMentionAttribute` method. Closes #14923.
---
> Fixes usage of MentionAttribute.

- docs/tutorials/crash-course/events-and-observables.md
Docs: Fix low level example for observables in crash course. Closes #14952.
> Docs: Fix low level example for observables in crash course

- docs/installation/getting-started/quick-start.md
Docs: adding licensing link to quick start. Closes https://github.com/ckeditor/ckeditor5/issues/14958
---
> Docs: adding licensing link to quick start.

- packages/ckeditor5-table/docs/_snippets/features/build-table-source.html
Docs: Fix table responsiveness. Closes https://github.com/ckeditor/ckeditor5/issues/14896.
---
> Docs: Fix table responsiveness.

- .circleci/template.yml
- scripts/ci/generate-circleci-configuration.js
Internal: Readded short flow on the stable branch and through commit message. Closes #14928.
---
In order to execute short flow add "[short-flow]" in the commit message.
> Readded short flow on the stable branch and through commit message.

- docs/installation/integrations/angular.md
- docs/installation/integrations/react.md
- docs/installation/integrations/vuejs-v2.md
- docs/installation/integrations/vuejs-v3.md
Docs: Update framework integration guides, so that collaboration samples are more visible.
> Update framework integration guides

- docs/tutorials/crash-course/plugin-configuration.md
Docs: Improve intro to the `Plugin configuration` tutorial. Closes #15006.
> Improve intro to the `Plugin configuration` tutorial

- scripts/ci/check-dependencies-versions-match.js
Internal: Added `devDependencies` to `check-dependencies-versions-match.js` script. Closes #14953.
---
> Added devDependencies to `check-dependencies-versions-match.js` script. 

- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-image/docs/features/images-overview.md
Docs: adding width and height info. Closes https://github.com/ckeditor/ckeditor5/issues/15010
---
> Docs: adding width and height info.

- packages/ckeditor5-ui/src/autocomplete/autocompleteview.ts
- packages/ckeditor5-ui/src/list/listitemgroupview.ts
- packages/ckeditor5-ui/tests/list/listitemgroupview.js
Internal (ui): List group view children should be extendable.
> List group view children should be extendable

- packages/ckeditor5-ui/src/autocomplete/autocompleteview.ts
- packages/ckeditor5-ui/src/highlightedtext/highlightedtextview.ts
- packages/ckeditor5-ui/src/search/searchinfoview.ts
- packages/ckeditor5-ui/src/search/text/searchtextqueryview.ts
- packages/ckeditor5-ui/src/search/text/searchtextview.ts
> Docs and refactoring

- packages/ckeditor5-clipboard/src/dragdropblocktoolbar.ts
- packages/ckeditor5-clipboard/tests/dragdropblocktoolbar.js
- packages/ckeditor5-clipboard/tests/manual/dragdrop-blocks.html
- packages/ckeditor5-clipboard/tests/manual/dragdrop-blocks.js
Internal (clipboard): The balloon block toolbar should be draggable in the RTL editor. Closes #15029.
---
> Balloon block editor: RTL support for dragged blocks.

- packages/ckeditor5-paste-from-office/docs/_snippets/features/build-paste-from-office-source.js
- packages/ckeditor5-table/docs/_snippets/features/table-column-resize.js
Docs: restoring column resize in demo. Closes https://github.com/ckeditor/ckeditor5/issues/15048
---
_Merge with https://github.com/cksource/ckeditor5-commercial/pull/5543_
> Docs: restoring column resize in demo.

- packages/ckeditor5-list/docs/_snippets/features/lists-document.js
- packages/ckeditor5-list/docs/_snippets/features/lists-source.js
- packages/ckeditor5-list/docs/features/document-lists.md
Docs: adding document to-do and simple lists to guide. Closes https://github.com/ckeditor/ckeditor5/issues/15076
---
_Close with https://github.com/cksource/ckeditor5-commercial/pull/5554_
> Docs: adding document to-do and simple lists to guide.

- packages/ckeditor5-image/ckeditor5-metadata.json
Internal (image): Updates metadata for images. Closes #15099.
---
> Updated metadata for images

- packages/ckeditor5-ckbox/src/ckboxediting.ts
- packages/ckeditor5-ckbox/tests/ckboxediting.js
Other (ckbox): Sets the default CKBox theme to `lark`. Closes #15096 .
---
> Set default CKBox theme to `lark`.

- docs/updating/update-to-40.md
- packages/ckeditor5-image/docs/features/images-overview.md
Docs: expanding the image guide. Part of https://github.com/ckeditor/ckeditor5/issues/15010
---
> Docs: expanding the image guide.

- packages/ckeditor5-core/src/editor/editorconfig.ts
- packages/ckeditor5-ui/src/toolbar/normalizetoolbarconfig.ts
Fix(ui,core): Fixes typings in `ToolbarConfig` by adding optional `icon` parameter. . Closes #15151 .
---
> Extend ToolbarConfig typings.

- packages/ckeditor5-special-characters/docs/_snippets/features/special-characters.html
Docs: update special characters demo. Closes https://github.com/ckeditor/ckeditor5/issues/13207
---
> Docs: update special characters demo

- docs/examples/index.md
- docs/umberto.json
Docs: expanding the Examples overview section. Closes https://github.com/cksource/ckeditor5-internal/issues/3560
---
> Docs: expanding the Examples overview section.

- packages/ckeditor5-engine/docs/framework/deep-dive/schema.md
Docs: removing stale link. Closes https://github.com/ckeditor/ckeditor5/issues/15173
---
> Docs: removing stale link.

- packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/list/list.css
- packages/ckeditor5-ui/src/list/listitemgroupview.ts
- packages/ckeditor5-ui/tests/list/listitemgroupview.js
Other (ui): The `ListItemGroupView` should allow using a custom label.
---
Required by https://github.com/cksource/ckeditor5-commercial/pull/5620
> The `ListItemGroupView` should allow using a custom label

- docs/_snippets/features/build-image-upload-source.html
- docs/_snippets/features/build-image-upload-source.js
- docs/_snippets/features/image-upload.html
- docs/_snippets/features/image-upload.js
- docs/features/image-upload.md
- docs/installation/advanced/csp.md
Docs: image upload guide updates. Closes https://github.com/cksource/ckeditor5-internal/issues/3435
---
> Docs: image upload guide updates

- docs/installation/advanced/integrating-from-source-webpack.md
Docs: updating the integrating with webpack guide. Closes https://github.com/ckeditor/ckeditor5/issues/15199
---
> Docs: updating the integrating with webpack guide

- packages/ckeditor5-theme-lark/theme/ckeditor5-ui/globals/_colors.css
Other (theme-lark): Created a custom property for a shared light red color. Closes #15217.
---
**A dependency of https://github.com/cksource/ckeditor5-commercial/pull/5643**
> Created a custom property for a shared light red color.

- docs/_snippets/framework/ui/ui-balloon.js
- docs/framework/architecture/ui-components.md
Docs: Add links to the API docs in the UI Components guide. Closes https://github.com/ckeditor/ckeditor5/issues/15187.
---
It also fixes the balloon position.
> Docs: Add links to the API docs in the UI Components guide

- packages/ckeditor5-paste-from-office/docs/features/paste-from-office.md
Docs: updating Office files. Closes https://github.com/ckeditor/ckeditor5/issues/15236
---
_Merge together with https://github.com/cksource/ckeditor5-commercial/pull/5655_
> Docs: updating Office files

- package.json
Internal: Use the latest working version of the "acorn" package. Closes #15256.
> Use the latest working version of the "acorn" package

- package.json
Reverts ckeditor/ckeditor5#15257
> Revert "Use the latest working version of the "acorn" package"

- docs/installation/integrations/drupal-real-time-collaboration.md
- docs/umberto.json
Docs: Drupal integration guide update. Closes https://github.com/cksource/ckeditor5-commercial/issues/5651
---
> Docs: Drupal integration guide update

- docs/_snippets/installation/getting-and-setting-data/manualsave.html
- packages/ckeditor5-autosave/docs/_snippets/features/autosave.html
Docs: autosave demo fix.  Closes https://github.com/ckeditor/ckeditor5/issues/15238
---
> Docs: autosave demo fix

- docs/updating/update-to-40.md
Docs: adding migration guide. Closes https://github.com/cksource/ckeditor5-internal/issues/3617
---
> Docs: adding migration guide.

- docs/umberto.json
Internal: Added domain of nightly docs to `permalinkDisableDomains` in umberto config.
---
> Updated the umberto config

- docs/updating/update-to-40.md
Docs: Update to 40.1 fixes.
---
> 40.1 migration guide review

- docs/_snippets/installation/advanced/dll-builds.js
- docs/installation/advanced/dll-builds.md
Internal:  Mute errors reported by web crawler regarding JSFiddle preview. Closes #15341.
---
>  Mute errors reported by web crawler regarding JSFiddle preview

- scripts/docs/snippetadapter.js
Docs: Reduce number of snippets built at the same time.
---
> Docs: Reduce number of snippets built at the same time

- docs/_snippets/features/image-upload.js
- packages/ckeditor5-ckbox/docs/_snippets/features/ckbox.js
- packages/ckeditor5-ckbox/src/ckboxconfig.ts
- packages/ckeditor5-image/docs/_snippets/features/image-responsive.js
Docs: Add the Powered by CKBox option. Closes https://github.com/cksource/ckeditor5-commercial/issues/5652.
---
There is another PR to merge: https://github.com/cksource/ckeditor5-commercial/pull/5725.
> Add the Powered by CKBox option

- packages/ckeditor5-editor-classic/src/classiceditorui.ts
- packages/ckeditor5-find-and-replace/src/findandreplaceui.ts
- packages/ckeditor5-ui/package.json
- packages/ckeditor5-ui/src/bindings/draggableviewmixin.ts
- packages/ckeditor5-ui/src/dialog/dialog.ts
- packages/ckeditor5-ui/src/dialog/dialogview.ts
- packages/ckeditor5-ui/src/index.ts
- packages/ckeditor5-ui/src/panel/sticky/stickypanelview.ts
- packages/ckeditor5-ui/tests/manual/dialog/dialog.html
- packages/ckeditor5-ui/tests/manual/dialog/dialog.ts
- packages/ckeditor5-ui/theme/components/dialog/dialog.css
Internal (ui): Implemented configurable initial dialog positions. Constrained dialog positions (and drag&drop) to the viewport.
---
This is a piece that contributes to the bigger PR https://github.com/ckeditor/ckeditor5/pull/15285.
> Dialog position and position constraints

- docs/installation/integrations/next-js.md
Docs: Add Next.js integration guide. Closes https://github.com/cksource/ckeditor5-commercial/issues/5671
---
> Add Next.js integration guide

- docs/installation/getting-started/quick-start.md
Type: update the superbuild snippet to add `AIAssistant` to the `removePlugins` array. Closes https://github.com/ckeditor/ckeditor5/issues/15305.
---
> Docs: update the superbuild snippet to remove AIAssistant

- package.json
Internal: Bumped the `sharp` library.
---
> Sharp bump

- .github/ISSUE_TEMPLATE/8-question.md
Internal: Adds a new question template on GitHub.
---
> Add a question template.

- docs/examples/how-tos.md
Docs: How to extend link dialog.
---
> How-to extend link dialog.

- scripts/vale/vale.js
Internal: `docs:lint` script will now use the value of `MinAlertLevel` from `.vale.ini` file as default value of the `alert` option. Previously, if the `-a`/`--alert` option was not specified `warning` would be used. `warning` is still a fallback value. Closes #15382.
---
> `docs:lint` script will now treat values from `.vale.ini` as defaults

- packages/ckeditor5-html-support/docs/api/html-support.md
Docs: Delete the experimental info-box for GHS. Closes: #15389.
---
> Delete the experimental info-box.

- docs/installation/integrations/react.md
Docs: Add context for integrating Vite with the custom CKEditor build. Closes #15396.
---
Related issues:
- https://github.com/ckeditor/ckeditor5/issues/9807
- https://github.com/ckeditor/ckeditor5/issues/15014
> Docs: Add context for integrating Vite with the custom CKEditor build.

- scripts/release/getchangelogoptions.js
Internal: Aligned the changelog format date to changes from #15379. Closes #15429.
---
* Requires: https://github.com/ckeditor/ckeditor5-dev/pull/930.
> Aligned the changelog format date to changes from #15379

- docs/_snippets/build-classic.js
- docs/_snippets/build-decoupled-document.js
- packages/ckeditor5-ckfinder/docs/_snippets/features/build-ckfinder-source.js
- packages/ckeditor5-ckfinder/docs/_snippets/features/ckfinder-options.js
- packages/ckeditor5-ckfinder/docs/_snippets/features/ckfinder-upload-only.js
- packages/ckeditor5-ckfinder/docs/_snippets/features/ckfinder.js
Docs: updating snippet build post-\`imageInsert\`. Closes cksource/ckeditor5-commercial#5807
---
> Docs: updating snippet build post-imageInsert.

- docs/installation/integrations/drupal-real-time-collaboration.md
- docs/support/license-key-and-activation.md
- docs/updating/update-to-32.md
- docs/updating/update-to-35.md
- docs/updating/update-to-37.md
- docs/updating/update-to-38.md
- packages/ckeditor5-upload/CHANGELOG.md
- scripts/vale/styles/CKEditor/Terms.yml
- scripts/vale/styles/Vocab/Docs/accept.txt
Docs: Changed "non real-time collaboration" to "asynchronous collaboration". Closes [cksource/ckeditor5-commercial#5615](https://github.com/cksource/ckeditor5-commercial/issues/5615).
---
> Vale: Introduce "asynchronous" in docs in place of "non-real-time"

- docs/_snippets/examples/balloon-block-editor.js
- docs/_snippets/examples/balloon-editor.js
- docs/_snippets/examples/inline-editor.js
- packages/ckeditor5-heading/docs/_snippets/features/title.js
- packages/ckeditor5-ui/docs/_snippets/features/blocktoolbar.js
- packages/ckeditor5-word-count/docs/_snippets/features/build-word-count-source.js
Docs: demo fixes. Closes cksource/ckeditor5-commercial#5814
---
Merge together with https://github.com/cksource/ckeditor5-commercial/pull/5815
> Docs: demo fixes.

- docs/features/index.md
- docs/framework/architecture/ui-components.md
- docs/support/license-key-and-activation.md
- docs/umberto.json
Docs (ai): Fixes for AI Assistant docs.
---
> Fixes for AI Assistant docs

- CHANGELOG.md
Docs: Update the \`40.2.0\` changelog.
---
> Update the `40.2.0` changelog.

- packages/ckeditor5-engine/tests/manual/tickets/4600/1.js
Tests(engine): Change domain for placeholder images. Closes #15536.
---
> Change domain for placeholder images in failing test.

- packages/ckeditor5-engine/src/conversion/downcasthelpers.ts
Docs: Remove flawed example in the comment. Closes #14682.
---
The `wrappedParagraph` failed with an error, decided to remove this one as there's a second one showcasing table.
> Remove flawed example in the comment.

- packages/ckeditor5-markdown-gfm/docs/_snippets/features/paste-from-markdown.html
Docs: updating paste markdown demo. Closes #15548
---
> Docs: updating paste markdown demo.

- docs/updating/migration-from-ckeditor-4.md
Docs: rewording the migration infobox. Closes cksource/ckeditor5-commercial#5852
---
> Docs: rewording the migration infobox.

- packages/ckeditor5-engine/src/model/schema.ts
Other (engine): Make the types of `Schema.addChildCheck` and `Schema.addAttributeCheck` callbacks more specific. See #15290.
---
> Make Schema.addChildCheck callback better typed.

- docs/framework/architecture/ui-components.md
Docs: Fixed icons paths in UI Components docs.
---
> Fixed icons paths in UI Components docs.

- packages/ckeditor5-list/src/documentlist.ts
- packages/ckeditor5-list/src/documentlistproperties.ts
- packages/ckeditor5-list/src/tododocumentlist.ts
- packages/ckeditor5-list/tests/documentlist.js
- packages/ckeditor5-list/tests/documentlistproperties.js
- packages/ckeditor5-list/tests/tododocumentlist.js
Internal (list): Fixed warning messages. Closes #15656.
---
> Fixed warning messages in Document List

- docs/updating/update-to-41.md
- packages/ckeditor5-list/docs/features/lists-editing.md
Docs: adding new merging lists behavior to update guide. Closes #15675
---
> Docs: adding new merging lists behavior to update guide.

- .vale.ini
- docs/features/productivity-pack.md
- docs/installation/getting-started/predefined-builds.md
- docs/updating/update-to-41.md
- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
- packages/ckeditor5-clipboard/docs/features/paste-plain-text.md
- packages/ckeditor5-font/docs/features/font.md
- packages/ckeditor5-markdown-gfm/README.md
- packages/ckeditor5-markdown-gfm/docs/_snippets/features/paste-from-markdown.html
- packages/ckeditor5-markdown-gfm/docs/api/markdown-gfm.md
- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
- packages/ckeditor5-markdown-gfm/docs/features/paste-markdown.md
- packages/ckeditor5-markdown-gfm/src/pastefrommarkdownexperimental.ts
- packages/ckeditor5-paste-from-office/docs/features/paste-from-google-docs.md
- packages/ckeditor5-paste-from-office/docs/features/paste-from-office.md
- scripts/vale/styles/CKEditor/Terms.yml
Docs: Reviewed the Case change and Paste Markdown documentation.
---
Issue: cksource/ckeditor5-internal#3648
PR in Commercial: cksource/ckeditor5-commercial#5902
> Review the Case change and Paste Markdown documentation

- CHANGELOG.md
- scripts/vale/styles/CKEditor/Terms.yml
- scripts/vale/styles/Vocab/Docs/accept.txt
> Docs: changelog review.

- docs/_snippets/framework/ui/ui-balloon.html
- docs/_snippets/framework/ui/ui-balloon.js
- docs/_snippets/framework/ui/ui-button.html
- docs/_snippets/framework/ui/ui-button.js
- docs/_snippets/framework/ui/ui-dialog.html
- docs/_snippets/framework/ui/ui-dialog.js
- docs/_snippets/framework/ui/ui-modal.html
- docs/_snippets/framework/ui/ui-modal.js
- docs/features/keyboard-support.md
- docs/framework/architecture/ui-components.md
- docs/framework/architecture/ui-library.md
- packages/ckeditor5-find-and-replace/docs/_snippets/features/find-and-replace-dropdown.html
- packages/ckeditor5-find-and-replace/docs/_snippets/features/find-and-replace-dropdown.js
- packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md
- packages/ckeditor5-link/src/ui/linkactionsview.ts
- packages/ckeditor5-link/src/ui/linkformview.ts
- packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts
- packages/ckeditor5-ui/src/bindings/draggableviewmixin.ts
- packages/ckeditor5-ui/src/dialog/dialog.ts
- packages/ckeditor5-ui/src/dialog/dialogview.ts
- packages/ckeditor5-ui/src/textarea/textareaview.ts
- packages/ckeditor5-ui/tests/dialog/dialog.js
- packages/ckeditor5-ui/tests/dialog/dialogview.js
- packages/ckeditor5-ui/tests/manual/dialog/dialog.ts
Docs: Added the entries about the dialog component.
---
> Docs for the dialogs

- docs/framework/architecture/ui-components.md
- docs/framework/architecture/ui-library.md
- docs/updating/update-to-41.md
- packages/ckeditor5-find-and-replace/docs/_snippets/features/find-and-replace-dropdown.html
- packages/ckeditor5-find-and-replace/docs/_snippets/features/find-and-replace.html
- packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md
- packages/ckeditor5-ui/src/bindings/draggableviewmixin.ts
- packages/ckeditor5-ui/src/dialog/dialog.ts
- packages/ckeditor5-ui/src/dialog/dialogactionsview.ts
- packages/ckeditor5-ui/src/dialog/dialogview.ts
- scripts/vale/styles/CKEditor/Terms.yml
- scripts/vale/styles/Vocab/Docs/accept.txt
Docs: Dialog documentation reviewed. Closes cksource/ckeditor5-internal#3655.
---
> Review dialog documentation

- packages/ckeditor5-media-embed/docs/_snippets/features/build-media-source.html
- packages/ckeditor5-media-embed/docs/_snippets/features/media-embed-preview.js
Docs: Fix media embed preview demo. Closes #15539.
---
> Docs: Fix media embed preview demo.

- .vale.ini
Type: Updated Vale TokenIgnores to ignore checking CKEditor 5 npm package names.
---
> Update Vale TokenIgnores to ignore checking CKEditor 5 npm package names

- packages/ckeditor5-ui/src/list/listview.ts
- packages/ckeditor5-ui/tests/list/listview.js
Fix(ui): The collection-remove-404 error if the collection includes a list item separator. Closes #15717.
---
> Fix(ui): The collection-remove-404 error if the collection includes a list item separator

- packages/ckeditor5-autosave/docs/features/autosave.md
Docs: updating autosave install. Closes #15753
---
> Docs: updating autosave install.

- docs/features/keyboard-support.md
Docs: updating the keyboard shortcuts table. Closes #15750
---
> Docs: updating the keyboard shortcuts table.

- docs/updating/update-to-25.md
- docs/updating/update-to-26.md
- docs/updating/update-to-27.md
- docs/updating/update-to-28.md
- docs/updating/update-to-29.md
- docs/updating/update-to-30.md
- docs/updating/update-to-31.md
- docs/updating/update-to-32.md
- docs/updating/update-to-33.md
- docs/updating/update-to-34.md
- docs/updating/update-to-35.md
- docs/updating/update-to-36.md
- docs/updating/update-to-37.md
- docs/updating/update-to-38.md
- docs/updating/update-to-39.md
- docs/updating/update-to-40.md
- docs/updating/update-to-41.md
Docs: adding release dates to releases. Closes #15760
---
> Docs: adding release dates to releases.

- docs/framework/architecture/ui-components.md
- docs/framework/architecture/ui-library.md
- packages/ckeditor5-ui/src/button/button.ts
- packages/ckeditor5-ui/src/icon/iconview.ts
Docs: adding custom icons to UI guide. Closes #12552
---
> Docs: adding custom icons to UI guide.

- docs/getting-started/index.md
- docs/getting-started/setup/configuration.md
Docs: fleshing out Getting started overview. Closes cksource/ckeditor5-commercial#5936
---
> Docs: fleshing out Getting started overview.

- packages/ckeditor5-image/docs/features/images-responsive.md
Docs: removing erroneous link. Closes #15735
---
> Docs: removing erroneous link.

- packages/ckeditor5-block-quote/src/blockquoteui.ts
- packages/ckeditor5-ui/src/menubar/menubarview.ts
Feature (block-quote): Add menu bar integration to block quote package. Related to #15894.
---
> Add menu bar integration to block quote.

- docs/installation/getting-started/getting-and-setting-data.md
Docs: fixing the snippet. Closes #15733
---
> Docs: fixing the snippet.

- docs/installation/advanced/using-two-editors.md
Docs: Update "Using two editors" docs.
---
> Updating using two editors docs

- packages/ckeditor5-horizontal-line/src/horizontallineui.ts
- packages/ckeditor5-ui/src/menubar/menubarview.ts
Feature (horizontal-line): Add menu bar integration. Related to https://github.com/ckeditor/ckeditor5/issues/15894.
---
> Add menu bar integration to horizontal line.

- packages/ckeditor5-image/src/augmentation.ts
- packages/ckeditor5-list/src/augmentation.ts
Fix (image,list): Fix TypeScript augmentation. Closes #15880.
---
:warning: This PR targets `release` branch :warning: 
Fix to the eslint rule will be done separately.
> Fix TypeScript augmentation

- docs/_snippets/framework/tutorials/using-react-in-widget.js
- packages/ckeditor5-image/src/augmentation.ts
- packages/ckeditor5-list/src/augmentation.ts
- packages/ckeditor5-theme-lark/tests/manual/reset.js
- packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
Internal: Fix issues reported by fixed eslint rule for checking file extensions in imports/exports. Closes #15880.
---
> Fix issues reported by fixed eslint rule for checking file extensions in imports/exports

- packages/ckeditor5-ckbox/docs/_snippets/features/ckbox.html
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-image/src/augmentation.ts
- packages/ckeditor5-list/src/augmentation.ts
Docs: CKBox guide updates. Closes cksource/ckeditor5-commercial#6063
---
> Docs: CKBox guide updates.

- packages/ckeditor5-utils/src/language.ts
- packages/ckeditor5-utils/tests/language.js
Other: Added dhivehi to the RTL languages list. Closes #15976.
Thanks to @Glaisher!
---
https://en.wikipedia.org/wiki/Dhivehi_language
> Added dhivehi to RTL languages list. resolves #15976

- packages/ckeditor5-ui/src/menubar/utils.ts
Feature (export-word): Add menu bar integration. Related to https://github.com/ckeditor/ckeditor5/issues/15894. Related to https://github.com/cksource/ckeditor5-commercial/pull/6075.
---
> Add menu bar integration to export word.

- packages/ckeditor5-language/src/textpartlanguageui.ts
- packages/ckeditor5-ui/src/index.ts
- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (language): Add menu bar integration. Related to https://github.com/ckeditor/ckeditor5/issues/15894.
---
> Add menu bar integration to text part language.

- packages/ckeditor5-ckfinder/lang/contexts.json
- packages/ckeditor5-ckfinder/src/ckfinderui.ts
- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (ckfinder): Introduced CKFinder integration with the menu bar.
> Added menu bar button for CKFinder

- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (track-changes): Add menu bar integration. Related to https://github.com/ckeditor/ckeditor5/issues/15894.
---
> Add menu bar integration to track changes.

- packages/ckeditor5-ckbox/src/ckboxui.ts
- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (ckbox): Introduced CKBox integration with the menu bar.
>  Introduced CKBox integration with the menu bar

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/react.md
- docs/umberto.json
- packages/ckeditor5-select-all/src/selectallcommand.ts
Docs: moving Tutorials around. Closes cksource/ckeditor5-commercial#6113
---
> Docs: moving Tutorials around.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-image/docs/features/images-overview.md
Docs: info about editing external images.  Closes cksource/ckeditor5-commercial#6092
---
> Docs: info about editing external images.

- packages/ckeditor5-ui/src/menubar/menubarmenuview.ts
- packages/ckeditor5-ui/src/menubar/menubarview.ts
- packages/ckeditor5-ui/src/menubar/utils.ts
- packages/ckeditor5-ui/theme/components/menubar/menubarmenupanel.css
Internal (ai): Add menu bar integration. Related to https://github.com/ckeditor/ckeditor5/issues/15894.
---
> Add menu bar integration to ai commands.

- packages/ckeditor5-core/lang/contexts.json
- packages/ckeditor5-core/src/accessibility.ts
Internal (core): Added menu bar entry in the a11y dialog.
---
> Menu bar entry in the a11y dialog.

- packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/menubar/menubarmenubutton.css
- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (ui): RTL support for the menu bar.
> RTL support for the menu bar

- packages/ckeditor5-ui/lang/contexts.json
- packages/ckeditor5-ui/src/menubar/utils.ts
- packages/ckeditor5-ui/tests/menubar/menubarview.js
Internal (ui): Defined the final structure of the menu bar. Localized sub-menu labels.
---
FYI: I updated two tests concerning localization to the latest API (the rest fails because of recent refactorings) and they passed.
> Defined the final structure of the menu bar, localized sub-menu labels.

- packages/ckeditor5-alignment/docs/features/text-alignment.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-clipboard/docs/features/drag-drop.md
- packages/ckeditor5-code-block/docs/features/code-blocks.md
- packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md
- packages/ckeditor5-font/docs/features/font.md
- packages/ckeditor5-heading/docs/features/headings.md
- packages/ckeditor5-heading/docs/features/title.md
- packages/ckeditor5-highlight/docs/features/highlight.md
- packages/ckeditor5-indent/docs/features/indent.md
- packages/ckeditor5-language/docs/features/language.md
- packages/ckeditor5-link/docs/features/link.md
- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
- packages/ckeditor5-mention/docs/features/mentions.md
- packages/ckeditor5-minimap/docs/features/minimap.md
- packages/ckeditor5-remove-format/docs/features/remove-format.md
- packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md
- packages/ckeditor5-special-characters/docs/features/special-characters.md
- packages/ckeditor5-typing/docs/features/text-transformation.md
- packages/ckeditor5-word-count/docs/features/word-count.md
Docs: moving the install sections. Closes #16011
---
> Docs: moving the install sections.

- packages/ckeditor5-utils/src/keyboard.ts
- packages/ckeditor5-utils/tests/keyboard.js
Feature (utils): Added Page Up and Page Down keys to the keyboard utilities (`keyCodes`, `getEnvKeystrokeText()`).
---
A piece of https://github.com/cksource/ckeditor5-commercial/pull/6130/files.
> Added Page Up and Page Down keys to the keyboard utilities

- packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/menubar/menubar.css
- packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/menubar/menubarmenu.css
Change (ui): Add menu bar items wrapping. Closes #16159.
---
> Update css to prevent menu bar overflowing

- packages/ckeditor5-list/src/list/converters.ts
- packages/ckeditor5-list/src/list/listediting.ts
- packages/ckeditor5-list/tests/list/converters-marker-changes.js
Internal (list): Custom marker should not be removed if inline element is removed from list item.
Closes https://github.com/cksource/ckeditor5-internal/issues/3680.
---
> Custom marker should not be removed if inline element is removed from list item.

- docs/examples/custom/bottom-toolbar-editor.md
- packages/ckeditor5-mention/docs/examples/chat-with-mentions.md
- packages/ckeditor5-theme-lark/docs/examples/theme-customization.md
- packages/ckeditor5-ui/docs/examples/custom-ui.md
Docs: updating advanced examples snippets. Closes cksource/ckeditor5-commercial#6171
---
> Docs: updating advanced examples snippets.

- docs/tutorials/crash-course/commands.md
- docs/tutorials/crash-course/editor.md
- docs/tutorials/crash-course/plugins.md
- docs/tutorials/crash-course/view.md
Docs: Update crash course tutorial. Closes #000.
---
> Adjust crash course tutorials for new instalation methods.

- CHANGELOG.md
- docs/features/accessibility.md
- docs/updating/changelog.md
Docs: Update CHANGELOG with the keyboard navigation.
---
> Update CHANGELOG with the keyboard navigation

- docs/getting-started/setup/csp.md
> Docs: updating CSP guide.

- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (merge-tags): Add the merge tag-related menu bar items.
> Add menu bar components to the default menu bar config.

- docs/getting-started/setup/css.md
Docs: New CSS guide. Closes cksource/ckeditor5-commercial#6200.
---
> [DRAFT] New CSS guide

- docs/getting-started/quick-start.md
> Docs: quick start update.

- docs/getting-started/setup/ui-language.md
Docs: updating UI language guide.
---
> Docs: updating UI language guide.

- packages/ckeditor5-clipboard/src/lineview.ts
- packages/ckeditor5-editor-inline/src/inlineeditoruiview.ts
- packages/ckeditor5-list/src/legacytodolist/legacytodolistediting.ts
- packages/ckeditor5-list/src/todolist/todolistediting.ts
- packages/ckeditor5-minimap/src/minimapiframeview.ts
- packages/ckeditor5-minimap/src/minimappositiontrackerview.ts
- packages/ckeditor5-select-all/src/selectallediting.ts
- packages/ckeditor5-ui/src/dialog/dialogview.ts
- packages/ckeditor5-ui/src/panel/balloon/balloonpanelview.ts
- packages/ckeditor5-ui/src/panel/balloon/contextualballoon.ts
- packages/ckeditor5-ui/src/panel/sticky/stickypanelview.ts
- packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.ts
- packages/ckeditor5-ui/src/toolbar/block/blockbuttonview.ts
- packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.ts
- packages/ckeditor5-ui/src/tooltipmanager.ts
- packages/ckeditor5-utils/src/emittermixin.ts
- packages/ckeditor5-utils/src/env.ts
- packages/ckeditor5-utils/src/keyboard.ts
- packages/ckeditor5-utils/src/unicode.ts
Internal: Improve tree-shaking by adding `#__PURE__` comments before function calls in global scope. See #16292.
---
> Internal: Improve tree-shaking by adding `#__PURE__` comments before function calls in global scope

- docs/getting-started/setup/menubar.md
- docs/getting-started/setup/toolbar.md
Docs: adding decoupled editor toolbar config. 
---
> Docs: adding decoupled editor toolbar config.

- docs/examples/builds/balloon-block-editor.md
- docs/examples/builds/balloon-editor.md
- docs/examples/builds/classic-editor.md
- docs/examples/builds/document-editor.md
- docs/examples/builds/inline-editor.md
- docs/examples/builds/multi-root-editor.md
- docs/examples/index.md
- docs/features/index.md
- docs/features/math-equations.md
- docs/features/spelling-and-grammar-checking.md
- docs/framework/index.md
- docs/getting-started/advanced/content-styles.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/setup/license-key-and-activation.md
- docs/getting-started/setup/ui-language.md
- docs/updating/ckeditor4-configuration-compatibility.md
- docs/updating/migration-from-ckeditor-4.md
- docs/updating/updating-ckeditor-5.md
- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
- packages/ckeditor5-editor-decoupled/docs/framework/document-editor.md
- packages/ckeditor5-font/tests/manual/font-color.md
- packages/ckeditor5-heading/docs/features/headings.md
- packages/ckeditor5-image/docs/features/images-styles.md
- packages/ckeditor5-ui/docs/framework/external-ui.md
Docs: removing builds.
---
_Merge with_ cksource/ckeditor5-commercial#6246
> Docs: removing builds.

- packages/ckeditor5-alignment/src/alignmentui.ts
- packages/ckeditor5-heading/src/headingbuttonsui.ts
- packages/ckeditor5-image/src/imageresize/imageresizebuttons.ts
- packages/ckeditor5-image/src/imagestyle/utils.ts
- packages/ckeditor5-table/src/tablecellproperties/ui/tablecellpropertiesview.ts
- packages/ckeditor5-table/src/tableproperties/ui/tablepropertiesview.ts
- packages/ckeditor5-table/src/utils/ui/contextualballoon.ts
- packages/ckeditor5-ui/src/colorselector/colorgridsfragmentview.ts
- packages/ckeditor5-ui/src/toolbar/toolbarview.ts
Other: Add `#__PURE__` comments before objects and arrays in global scope. Related to #16292.
---
> Other: Add `#__PURE__` comments before objects and arrays in global scope.

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/dotnet.md
- docs/getting-started/integrations/laravel.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/react.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/quick-start.md
- docs/getting-started/setup/license-key-and-activation.md
- docs/getting-started/setup/ui-language.md
Docs: pre-release fixes.
---
_Merge with_ cksource/ckeditor5-commercial#6249
> Docs: pre-release fixes.

- docs/umberto.json
- docs/updating/maintaining.md
- docs/updating/new-installation-methods.md
- docs/updating/release-process.md
- docs/updating/update-to-42.md
- docs/updating/versioning-policy.md
- packages/ckeditor5-core/src/plugincollection.ts
- packages/ckeditor5-upload/src/filerepository.ts
- packages/ckeditor5-utils/src/version.ts
Docs: updating error codes.
---
> Docs: updating error codes.

- packages/ckeditor5-watchdog/src/index.ts
Feature (watchdog): Export `EditorCreatorFunction` and `WatchdogConfig` types from the main index file.
---
> Feature (watchdog): Export `EditorCreatorFunction` and `WatchdogConfig` types.

- scripts/build-ckeditor5.mjs
Other (ckeditor5): Rename files in the browser build to `ckeditor5`.
---
> Other (ckeditor5): Rename files in the browser build to `ckeditor5`.

- scripts/release/preparepackages.js
- scripts/release/utils/getckeditor5packagejson.js
Other (ckeditor5): Add `main`, `module`, `types` and `exports` fields to `package.json` file. Closes #16257.
---
> Other (ckeditor5): Add `main`, `module`, `types` and `exports` fields to `package.json` file.

- scripts/build-ckeditor5.mjs
Revert (ckeditor): Revert "Rename files in the browser build to `ckeditor5`".
---
This reverts commit 6c14dfecadf778a10e5f041ff8cf2424f6fb5d13.
> Revert "Rename files in the browser build to `ckeditor5`".

- docs/tutorials/widgets/implementing-an-inline-widget.md
Docs: Added info about the upcoming merge fields feature in placeholder tutorial.
>  Added info about the upcoming merge fields feature in placeholder tutorial

- docs/framework/how-tos.md
- docs/getting-started/setup/editor-lifecycle.md
- packages/ckeditor5-image/docs/framework/deep-dive/upload-adapter.md
Docs: Improve documentation for new installation methods.
---
> Misc documentation fixes.

- packages/ckeditor5-media-embed/src/mediaembedui.ts
- packages/ckeditor5-media-embed/tests/mediaembedui.js
Internal (media-embed): Added enter key support for media embed dialog.
> Added enter key support for media embed dialog

- docs/getting-started/setup/menubar.md
Docs: Add information that menu bar is available for multi-root editor.
> Add information that menu bar is available for multi-root editor

- docs/getting-started/integrations/react.md
- docs/getting-started/legacy-getting-started/integrations/react.md
Docs: Add new required `contextWatchdog` prop to the `<CKEditorContext>` React component.
---
> Docs: Add new required `contextWatchdog` prop to the `<CKEditorContext>` React component

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/css.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/react.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/setup/css.md
- docs/getting-started/setup/typescript-support.md
- docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/tutorials/crash-course/editor.md
- docs/tutorials/creating-simple-plugin-timestamp.md
- docs/tutorials/widgets/data-from-external-source.md
- docs/tutorials/widgets/implementing-an-inline-widget.md
- docs/tutorials/widgets/using-react-in-a-widget.md
- packages/ckeditor5-theme-lark/docs/framework/theme-customization.md
Docs: Update filenames of CSS files in new installation methods.
---
> Docs: Update filenames of CSS files in new installation methods.

- docs/tutorials/crash-course/editor.md
Docs: Update link in crash course section.
---
New link will not work until this [PR](https://github.com/ckeditor/ckeditor5-tutorials-examples/pull/12) will not be merged.
> Update link in crash course docs

- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (ui): Updated menu bar default config setting and API docs.
> Updated menu bar default config setting and API docs

- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
Docs: updating CKFinder snippets.  Closes #16493
---
> Docs: updating CKFinder snippets.

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/react.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/quick-start.md
- docs/getting-started/setup/typescript-support.md
- docs/getting-started/setup/ui-language.md
- docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/tutorials/crash-course/editor.md
- docs/tutorials/creating-simple-plugin-timestamp.md
- docs/tutorials/widgets/data-from-external-source.md
- docs/tutorials/widgets/implementing-an-inline-widget.md
- docs/tutorials/widgets/using-react-in-a-widget.md
- packages/ckeditor5-theme-lark/docs/framework/theme-customization.md
Docs: separating css from plugin imports. Closes #16486
---
> Docs: separating css from plugin imports.

- docs/getting-started/quick-start.md
Docs: updating quick start toward premium features. Part of #16497
---
> Docs: updating quick start toward premium features.

- docs/getting-started/setup/css.md
Docs: Improve the styling guide. Closes #16488.
---
> Improve the styling guide

- docs/examples/builds/multi-root-editor.md
Docs: Fix vanilla multi-root example. See: #16479.
---
> Docs: Fix multi-root example

- packages/ckeditor5-editor-balloon/docs/api/editor-balloon.md
- packages/ckeditor5-editor-classic/docs/api/editor-classic.md
- packages/ckeditor5-editor-decoupled/docs/api/editor-decoupled.md
- packages/ckeditor5-editor-inline/docs/api/editor-inline.md
- packages/ckeditor5-editor-multi-root/docs/api/editor-multi-root.md
Docs: removing builds from API. Closes #16524
---
> Docs: removing builds from api.

- docs/getting-started/integrations/react-multiroot.md
Docs: Update the Multi-root React integration to NIM. Closes https://github.com/ckeditor/ckeditor5/issues/16479.
---
Besides updating snippets, I tried to update texts and remove build mentions.
> Docs: Update the Multi-root React integration to NIM.

- docs/getting-started/setup/getting-and-setting-data.md
- packages/ckeditor5-autosave/ckeditor5-metadata.json
- packages/ckeditor5-table/docs/features/tables-styling.md
Docs: Improving getting and setting data guide for NIM. Closes [#16531](https://github.com/ckeditor/ckeditor5/issues/16531).
---
> Update the getting and setting data guide.

- packages/ckeditor5-watchdog/package.json
- packages/ckeditor5-watchdog/tests/editorwatchdog.js
Tests (watchdog): Introduced mocks for collaboration features in the watchdog unit tests.
---
> Introduced mocks in the watchdog unit tests

- docs/updating/nim-migration/migration-to-new-installation-methods.md
Docs: Add information about the deprecation timelines.
---
> Add information about the deprecation timelines.

- docs/getting-started/integrations/react.md
Docs: Fix React integration snippet. Closes https://github.com/ckeditor/ckeditor5/issues/16495
---
> Docs: Fix React integration snippet.

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/react.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/setup/ui-language.md
- docs/updating/nim-migration/dll-builds.md
- docs/updating/nim-migration/migration-to-new-installation-methods.md
Docs: various small fixes in the NIM migration guides.
---
> NIM migration guide fixes

- packages/ckeditor5-core/src/editor/editor.ts
- packages/ckeditor5-core/src/editor/editorconfig.ts
- packages/ckeditor5-core/src/plugincollection.ts
Docs: updating legacy links in API. Closes #16569
---
> Docs: updating legacy links in API.

- docs/updating/update-to-42.md
Docs: Prepare the update guide for v42.
---
> Prepare the update guide for v42

- .eslintrc.js
- docs/framework/contributing/code-style.md
- package.json
Internal: Update eslint rules.
Docs: Add explanation for the `No legacy imports` eslint rule.
> Internal: Update eslint rules.

- docs/updating/nim-migration/custom-plugins.md
Docs: Update custom plugin migration guide.
---
> Docs: Update custom plugin migration guide.

- docs/tutorials/supporting-multiple-versions.md
- docs/updating/nim-migration/custom-plugins.md
Docs: Add the `Version compatibility of custom plugins` guide.
---
> Docs: Add the `Version compatibility of custom plugins` guide

- docs/getting-started/integrations/next-js.md
Docs: Clarify the Next.js integration guide. Closes https://github.com/ckeditor/ckeditor5/issues/16527
---
It also closes: https://github.com/ckeditor/ckeditor5/issues/16542
> Docs: Clarify the Next.js integration guide.

- scripts/release/deploycdn.js
- scripts/release/utils/getcdnversion.js
Internal: Support for alpha releases on CDN.
---
> Support for alpha releases on CDN.

- docs/getting-started/setup/css.md
- docs/getting-started/setup/optimizing-build-size.md
- scripts/release/preparepackages.js
Docs: Add the `Optimizing build size` document.
---
>  Docs: Add the `Optimizing build size` document

- docs/framework/development-tools/package-generator/javascript-package.md
- docs/framework/development-tools/package-generator/typescript-package.md
- docs/framework/development-tools/package-generator/using-package-generator.md
Docs: Changes to package-generator guide which reflects new approach with changed flag. Closes #000.
---
> Changes to package-generator guide which reflects new approach with changed flag.

- docs/getting-started/advanced/dll-builds-collaboration-features.md
- docs/support/index.md
- docs/updating/migration-from-ckeditor-4.md
- docs/updating/update-to-42.md
Docs: Update support page with up-to-date information.
Docs: Update DLLs import. Closes:  #16536.
---
> Update support page.

- docs/updating/nim-migration/migration-to-new-installation-methods.md
Docs: Update the migration guide.
---
> Migration guide feedback

- scripts/release/assets/zip/LICENSE.md
Other: Add `LICENSE.md` that will be in the released ZIP folder.
---
Merge with cksource/ckeditor5-commercial#6337
> License for the ZIP folder.

- packages/ckeditor5-engine/src/view/domconverter.ts
- packages/ckeditor5-engine/tests/view/domconverter/whitespace-handling-integration.js
- packages/ckeditor5-ui/src/menubar/utils.ts
Internal (merge-fields): Rename merge fields plugin.
> Rename merge fields plugin

- docs/getting-started/advanced/content-styles.md
- docs/getting-started/advanced/dll-builds-collaboration-features.md
- docs/getting-started/advanced/dll-builds.md
- docs/getting-started/advanced/integrating-from-source-vite.md
- docs/getting-started/advanced/integrating-from-source-webpack.md
- docs/getting-started/advanced/using-two-editors.md
- docs/getting-started/legacy-getting-started/api-and-events.md
- docs/getting-started/legacy-getting-started/extending-features.md
- docs/getting-started/legacy-getting-started/integrations/angular.md
- docs/getting-started/legacy-getting-started/integrations/overview.md
- docs/getting-started/legacy-getting-started/integrations/react.md
- docs/getting-started/legacy-getting-started/integrations/vuejs-v2.md
- docs/getting-started/legacy-getting-started/integrations/vuejs-v3.md
- docs/getting-started/legacy-getting-started/predefined-builds.md
- docs/getting-started/legacy-getting-started/quick-start-other.md
- docs/getting-started/legacy-getting-started/quick-start.md
- docs/getting-started/legacy-getting-started/working-with-typescript.md
Docs: Highlight legacy docs more.
---
I also fixed some minor (formatting) issues.
> Docs: Highlight legacy docs more.

- docs/getting-started/legacy-getting-started/quick-start-other.md
- docs/updating/update-to-29.md
Docs: Improve old online builder guide.
---
> Improve old online builder guide.

- docs/getting-started/setup/ui-language.md
Docs: Added missing CSS file for premium features in code snippet. Closes #000.
---
> Add missing CSS for premium features in code snippet.

- docs/getting-started/quick-start.md
- docs/updating/nim-migration/custom-plugins.md
- docs/updating/nim-migration/customized-builds.md
- docs/updating/nim-migration/dll-builds.md
- docs/updating/nim-migration/migration-to-new-installation-methods.md
- docs/updating/nim-migration/online-builder.md
Docs: Add migration guide for legacy Online Builder.
---
> Docs: Add migration guide for legacy Online Builder.

- scripts/release/deploycdn.js
Internal: Set proper content types for CDN files while deploying a new CKEditor 5 release.
---
> Internal: Set proper content types for CDN files.

- scripts/release/publishpackages.js
Internal: Added new task to verify if package was published correctly to npm. Closes #16625.
---
> Added new task to verify if package was published correctly to npm.

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/dotnet.md
- docs/getting-started/integrations/laravel.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/react.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/legacy-getting-started/legacy-imports.md
Docs: unifying license key call.
---
_Merge together with_ cksource/ckeditor5-commercial#6391
> Docs: unifying license key call.

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/dotnet.md
- docs/getting-started/integrations/laravel.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/react.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/quick-start.md
- docs/getting-started/setup/license-key-and-activation.md
- docs/updating/update-to-39.md
- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: license key call update.
---
_Merge with https://github.com/cksource/ckeditor5-commercial/pull/6392_
> Docs: license key call update.

- docs/assets/buildwarningbanner.js
Docs: Add a warning banner for legacy documentation.
---
> Docs: Add a warning banner for legacy documentation.

- docs/getting-started/integrations/angular.md
Docs: Update the Angular version table.
---
> Docs: Update the Angular version table.

- docs/getting-started/integrations/dotnet.md
- docs/getting-started/integrations/laravel.md
Docs: Add ZIP routes to non-JS integrations.
---
> Docs: Add ZIP routes to non-JS integrations

- docs/getting-started/integrations/angular.md
Docs: Switched order of the sections to reflect the popularity of them.
---
_As discussed today._
> Switched order of the sections to reflect the popularity of them.

- packages/ckeditor5-code-block/src/outdentcodeblockcommand.ts
- packages/ckeditor5-code-block/src/utils.ts
- packages/ckeditor5-code-block/tests/indentcodeblockcommand.js
- packages/ckeditor5-code-block/tests/outdentcodeblockcommand.js
Feature (code-block): to do.
---
> Make code block outdent command work with elements

- docs/umberto.json
- package.json
Docs: Add tracking id for `vwo` in `Umberto` config. Closes #000.
---
> Add tracking id for `vwo` in `Umberto` config.

- docs/features/productivity-pack.md
Docs: adding merge fields to productivity pack. 
---
_Merge with_ cksource/ckeditor5-commercial#6415
> Docs: adding merge fields to prodpak.

- docs/getting-started/integrations/angular.md
Docs: Unify the styles usage in the Angular guide.
---
> Docs: Unify the styles usage in the Angular guide.

- CHANGELOG.md
Internal: Changelog for v42.0.2.
---
> Changelog for v42.0.2

- docs/updating/update-to-25.md
- docs/updating/update-to-26.md
- docs/updating/update-to-27.md
- docs/updating/update-to-28.md
- docs/updating/update-to-29.md
- docs/updating/update-to-30.md
- docs/updating/update-to-31.md
- docs/updating/update-to-32.md
- docs/updating/update-to-33.md
- docs/updating/update-to-34.md
- docs/updating/update-to-35.md
- docs/updating/update-to-36.md
- docs/updating/update-to-37.md
- docs/updating/update-to-38.md
- docs/updating/update-to-39.md
- docs/updating/update-to-40.md
- docs/updating/update-to-41.md
- docs/updating/update-to-42.md
- docs/updating/update-to-43.md
Docs: adding update guide placeholder.
---
> Docs: adding update guide placeholder.

- docs/_snippets/features/keyboard-support.js
Docs: updating EtW V2 config in demos.
---
_Merge together with https://github.com/cksource/ckeditor5-commercial/pull/6486_
> Docs: updating EtW V2 config in demos.

- docs/getting-started/setup/license-key-and-activation.md
> Docs: adding link.

- docs/updating/update-to-43.md
Docs: Update guide for v43. Closes #16805.
---
> Update guide for v43.

- packages/ckeditor5-special-characters/docs/_snippets/features/special-characters.js
Docs: tooltip fix. Closes #16836
---
> Docs: tooltip fix.

- docs/getting-started/quick-start.md
- docs/getting-started/setup/configuration.md
- docs/getting-started/setup/editor-types.md
Docs: Add bundler information to the npm quick start. Closes #16823.
Docs: Improve Builder callouts. Closes #16764.
Docs: Improve Decoupled editor description. Closes #16811.
---
> Improve the docs

- docs/getting-started/quick-start.md
> Docs: a typo.

- docs/framework/development-tools/package-generator/using-package-generator.md
Docs: Added new param `--global-name` description to package-generator guide. Closes #000.
---
> New param `--global-name` description in package-generator guide.

- docs/updating/update-to-41.md
- docs/updating/update-to-42.md
- docs/updating/update-to-43.md
Docs: Update the v43 update guide.
---
> Updates to the v 43 update guide.

- docs/features/accessibility.md
Docs: Added annotations keystrokes information to the Accessibility support guide. Closes #16860.
> Added annotations keystrokes information to the Accessibility support guide

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/react-multiroot.md
- docs/getting-started/integrations/react.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/legacy-getting-started/integrations/angular.md
- docs/getting-started/legacy-getting-started/integrations/react.md
- docs/getting-started/legacy-getting-started/integrations/vuejs-v2.md
- docs/getting-started/legacy-getting-started/integrations/vuejs-v3.md
Docs: Adjust linking to new collaboration samples.
---
The same as https://github.com/ckeditor/ckeditor5/pull/16847 but targeting `stable`.
> Docs: Adjust linking to new collaboration samples.

- docs/getting-started/integrations/next-js.md
Docs: Sync documentation of stable to master.
---
> Sync documentation of stable to master.

- CHANGELOG.md
Docs: Fix link in the CHANGELOG.
---
> Fix link in the CHANGELOG.

- docs/getting-started/integrations/angular.md
Docs: Describe the known issue with localization in Angular 17. Closes #16816.
---
> Describe the known issue with localization in Angular 17.

- package.json
Internal: Bump Umberto to the latest version.
---
> Bump Umberto to the latest version

- docs/framework/architecture/ui-components.md
- docs/framework/contributing/testing-environment.md
- docs/framework/custom-editor-creator.md
- docs/framework/how-tos.md
- docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/tutorials/crash-course/editor.md
- docs/tutorials/crash-course/view.md
- docs/tutorials/creating-simple-plugin-timestamp.md
- docs/tutorials/widgets/data-from-external-source.md
- docs/tutorials/widgets/implementing-a-block-widget.md
- docs/tutorials/widgets/implementing-an-inline-widget.md
- docs/tutorials/widgets/using-react-in-a-widget.md
Docs: license calls in tutorials and Framework.
---
> Docs: license calls in tutorials and Framework.

- docs/getting-started/integrations/react-default-npm.md
Docs: Update the React self-hosted guide.
---
> Docs: Update the React self-hosted guide.

- docs/getting-started/integrations/angular.md
Docs: Update the Angular self-hosted guide.
---
> Docs: Update the Angular self-hosted guide.

- docs/getting-started/integrations/next-js.md
Docs: Update the Next.js self-hosted guide.
---
> Docs: Update the Next.js self-hosted guide.

- docs/getting-started/integrations/quick-start.md
Docs: Update the self-hosted Vanilla JS installation guide.
---
> Docs: Update the self-hosted Vanilla JS installation guide.

- docs/getting-started/integrations/laravel.md
Docs: Update the Laravel self-hosted guide.
---
> Docs: Update the Laravel self-hosted guide.

- docs/getting-started/integrations/dotnet.md
Docs: Update the .NET self-hosted guide.
---
> Docs: Update the .NET self-hosted guide.

- packages/ckeditor5-cloud-services/tests/token/token.js
- packages/ckeditor5-cloud-services/tests/uploadgateway/fileuploader.js
- packages/ckeditor5-cloud-services/tests/uploadgateway/uploadgateway.js
Tests: Ensured all tested Tokens are destroyed correctly to avoid unexpected Token refresh warnings while running tests.
> Tests: Ensured all tested Tokens are destroyed correctly

- docs/getting-started/integrations/vuejs-v2.md
Docs: Update the Vue 2 self-hosted guide.
---
> Docs: Update the Vue 2 self-hosted guide.

- packages/ckeditor5-typing/src/index.ts
Other (typing): Exposed the `TextTransformationConfig` in the index file.
---
See https://github.com/cksource/ckeditor5-commercial/issues/6576.
> Exposed the TextTransformationConfig in the index file

- .circleci/config.yml
- .circleci/template.yml
Internal: Improved the resource class (machine) used on CI. See: #17003.
---
> Improve CI machines (resource class)

- .circleci/config.yml
- .circleci/template.yml
Internal: Improved the resource class (machine) used on CI.
https://github.com/ckeditor/ckeditor5/issues/17003
---
> Increase resources on CI

- docs/_snippets/examples/document-editor.html
Docs: Fixed the color of the heading element in the Document editor sample.
---
> Fixed the color of the heading element in the Document editor sample

- docs/getting-started/integrations-cdn/quick-start.md
Docs: Update the Quick start CDN guide.
---
> Update the Quick start CDN guide.

- docs/getting-started/integrations-cdn/dotnet.md
Docs: Update the .NET CDN guide.
---
> Docs: Update the .NET CDN guide.

- docs/examples/builds/balloon-block-editor.md
- docs/examples/builds/balloon-editor.md
- docs/examples/builds/classic-editor.md
- docs/examples/builds/document-editor.md
- docs/examples/builds/inline-editor.md
- docs/features/index.md
- docs/framework/contributing/package-metadata.md
- docs/getting-started/quick-start.md
- docs/getting-started/setup/configuration.md
- docs/getting-started/setup/editor-types.md
- docs/getting-started/setup/license-key-and-activation.md
- docs/getting-started/setup/toolbar.md
- docs/updating/maintaining.md
- docs/updating/migration-from-ckeditor-4.md
- docs/updating/nim-migration/online-builder.md
- docs/updating/update-to-29.md
- docs/updating/updating-ckeditor-5.md
Docs: updating Builder link.
---
> Docs: updating Builder link.

- packages/ckeditor5-bookmark/src/augmentation.ts
- packages/ckeditor5-bookmark/src/bookmarkediting.ts
- packages/ckeditor5-bookmark/src/index.ts
- packages/ckeditor5-bookmark/tests/bookmarkediting.js
Internal (bookmark): Schema definition for `bookmark`.
---
> Schema definition for `bookmark`.

- docs/getting-started/setup/csp.md
Docs: Fix \`style-src\` entry in the CSP doc. Closes #17074
---
> Fix `style-src` entry in the CSP doc.

- docs/getting-started/legacy-getting-started/predefined-builds.md
- docs/getting-started/legacy-getting-started/quick-start.md
- packages/ckeditor5-utils/src/version.ts
Docs: Update explanation for the `ckeditor-duplicated-modules` error.
---
> Update explanation for the `ckeditor-duplicated-modules` error.

- docs/features/math-equations.md
- docs/features/spelling-and-grammar-checking.md
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
> Docs: infobox update.

- packages/ckeditor5-bookmark/package.json
- packages/ckeditor5-bookmark/src/bookmarkediting.ts
- packages/ckeditor5-bookmark/tests/bookmarkediting.js
- packages/ckeditor5-bookmark/tests/manual/bookmark.html
Internal (bookmark): Data upcast. Closes #000.
---
> [Bookmark] Data upcast.

- docs/getting-started/integrations-cdn/angular.md
- docs/getting-started/integrations-cdn/react-default-cdn.md
Docs: Link the CDN helpers in integrations.
---
I linked to the new CDN helpers guide and I unified integrations with the Vue 3 one.
> Docs: Link the CDN helpers in integrations.

- packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/dropdown/menu/dropdownmenupanel.css
- packages/ckeditor5-ui/theme/components/dropdown/menu/dropdownmenupanel.css
Fix (ui,theme-lark): Increased the specificity of the dropdown menu panel styles to address issues with incorrect `z-index` ordering.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6639.
> Increased the specificity of the dropdown menu panel styles

- docs/getting-started/integrations-cdn/next-js.md
Docs: Add the Next.js CDN guide.
---
> Docs: Add the Next.js CDN guide.

- packages/ckeditor5-engine/src/model/nodelist.ts
- packages/ckeditor5-engine/src/view/domconverter.ts
- packages/ckeditor5-engine/src/view/renderer.ts
- packages/ckeditor5-engine/src/view/stylesmap.ts
Other (engine): Performance improvements. Avoided creating unnecessary arrays. Closes #17143.
---
This PR should not introduce any changes to the editor logic.
> Performance improvements. Avoided creating unnecessary arrays

- CHANGELOG.md
- packages/ckeditor5-clipboard/src/dragdrop.ts
- packages/ckeditor5-clipboard/tests/dragdrop.js
- packages/ckeditor5-engine/src/dataprocessor/htmldataprocessor.ts
- packages/ckeditor5-engine/src/model/schema.ts
- packages/ckeditor5-engine/src/view/styles/utils.ts
- packages/ckeditor5-engine/tests/view/observer/selectionobserver.js
- packages/ckeditor5-engine/tests/view/styles/utils.js
- packages/ckeditor5-html-support/src/htmlpagedataprocessor.ts
- packages/ckeditor5-utils/src/config.ts
Internal: Changelog for v43.1.1.
---
> Changelog for v43.1.1.

- packages/ckeditor5-ui/package.json
Internal: Fixed an invalid merge results by defining a correct version of `ckeditor5-code-block` in `ckeditor5-ui`.
---
> Fixed an invalid merge results (after picking stable to master)

- packages/ckeditor5-bookmark/package.json
- packages/ckeditor5-bookmark/tests/manual/bookmark-with-output.md
- packages/ckeditor5-bookmark/tests/manual/bookmark.md
- packages/ckeditor5-bookmark/tests/manual/multiroot.html
- packages/ckeditor5-bookmark/tests/manual/multiroot.js
- packages/ckeditor5-bookmark/tests/manual/multiroot.md
Internal(bookmark): Manual test with multiroot. Closes #000.
---
_Also updated descriptions in all manual tests._
> [Bookmark] Manual test with multiroot.

- packages/ckeditor5-bookmark/package.json
- packages/ckeditor5-bookmark/tests/bookmarkediting.js
- packages/ckeditor5-bookmark/tests/bookmarkui.js
- packages/ckeditor5-bookmark/tests/insertbookmarkcommand.js
- packages/ckeditor5-bookmark/tests/manual/bookmark-with-output.js
- packages/ckeditor5-bookmark/tests/manual/bookmark.js
- packages/ckeditor5-bookmark/tests/updatebookmarkcommand.js
Internal: Enable drag and drop in manual tests.
---
> [Bookmark] Enable drag and drop in manual tests.

- packages/ckeditor5-ui/src/editorui/poweredby.ts
- packages/ckeditor5-ui/tests/editorui/poweredby.js
Feature (ui): Update powered-by link.
> Update powered by link

- docs/getting-started/integrations-cdn/angular.md
- docs/getting-started/integrations-cdn/dotnet.md
- docs/getting-started/integrations-cdn/laravel.md
- docs/getting-started/integrations-cdn/next-js.md
- docs/getting-started/integrations-cdn/quick-start.md
- docs/getting-started/integrations-cdn/react-default-cdn.md
- docs/getting-started/integrations-cdn/react-multiroot-cdn.md
- docs/getting-started/integrations-cdn/vuejs-v2.md
- docs/getting-started/integrations-cdn/vuejs-v3.md
- docs/getting-started/integrations/vuejs-v3.md
- docs/getting-started/setup/ui-language.md
- docs/updating/migration-to-cdn/angular.md
- docs/updating/migration-to-cdn/react.md
- docs/updating/migration-to-cdn/testing-suite.md
- docs/updating/migration-to-cdn/vanilla-js.md
- docs/updating/migration-to-cdn/vuejs-v3.md
Add banners about a free account and remove properties from guides` snippets.
---
This PR also contains other small fixes.
> Add banners about a free account

- docs/getting-started/index.md
Docs: Update the Quick start guide.
---
> Docs: Update the Quick start guide.

- packages/ckeditor5-bookmark/lang/contexts.json
- packages/ckeditor5-bookmark/src/ui/bookmarkformview.ts
- packages/ckeditor5-bookmark/tests/ui/bookmarkformview.js
Internal: Update the label name in form view.
---
> Bookmark update label

- CHANGELOG.md
Internal: Changelog for v43.2.0.
---
> Changelog for v43.2.0

- CHANGELOG.md
Internal: Updated the changelog file.
---
Context: The changelog for the release was generated before https://github.com/ckeditor/ckeditor5/pull/17174 was closed. This PR addresses a missing changelog entry.
> Updated changelog after additional exports were added to the project

- docs/tutorials/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/tutorials/crash-course/editor.md
- docs/tutorials/creating-simple-plugin-timestamp.md
- docs/tutorials/widgets/data-from-external-source.md
- docs/tutorials/widgets/implementing-a-block-widget.md
- docs/tutorials/widgets/implementing-an-inline-widget.md
- docs/tutorials/widgets/using-react-in-a-widget.md
> Tutorials update

- packages/ckeditor5-bookmark/src/insertbookmarkcommand.ts
- packages/ckeditor5-bookmark/src/updatebookmarkcommand.ts
- packages/ckeditor5-bookmark/src/utils.ts
- packages/ckeditor5-bookmark/tests/insertbookmarkcommand.js
- packages/ckeditor5-bookmark/tests/updatebookmarkcommand.js
Internal: Bookmark id validation in command.
---
> Bookmark id validation

- scripts/ci/check-unit-tests-for-package.mjs
- scripts/ci/generate-circleci-configuration.mjs
Internal: Fix incorrect attempt counts in tests (CI).
> Fix attempts in tests

- packages/ckeditor5-bookmark/src/ui/bookmarkactionsview.ts
- packages/ckeditor5-bookmark/theme/bookmark.css
- packages/ckeditor5-bookmark/theme/bookmarkactions.css
- packages/ckeditor5-bookmark/theme/bookmarkform.css
Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))
Internal: Should bookmark balloons looks good on mobile devices.
---
_We've got a green light 🟢  from @dwandeljanicka _
> [Bookmark] Update mobile look of balloon views in bookmarks.

- packages/ckeditor5-bookmark/lang/contexts.json
Internal: Unified duplicated key of `Bookmark name` into one.
---
> [Bookmark] Unified duplicated key of `Bookmark name` into one.

- packages/ckeditor5-bookmark/lang/contexts.json
- packages/ckeditor5-bookmark/src/ui/bookmarkactionsview.ts
- packages/ckeditor5-bookmark/tests/manual/bookmark.html
- packages/ckeditor5-bookmark/tests/ui/bookmarkactionsview.js
- packages/ckeditor5-bookmark/theme/bookmarkactions.css
Internal: Change preview of bookmark name from UI button to UI label element.
---
> [Bookmark]Change preview of bookmark name from button to label.

- packages/ckeditor5-bookmark/ckeditor5-metadata.json
- packages/ckeditor5-bookmark/docs/features/bookmark.md
> [Bookmark] Feature guide.

- docs/framework/contributing/code-style.md
Docs: Add `ckeditor5-rules/ckeditor-plugin-flags` docs.
---
Caused by https://github.com/ckeditor/ckeditor5-linters-config/pull/45
> Add `ckeditor5-rules/ckeditor-plugin-flags` to docs.

- scripts/release/deploycdn.mjs
- scripts/release/preparepackages.mjs
- scripts/release/publishpackages.mjs
- scripts/release/utils/getcdnversion.mjs
- scripts/release/utils/getreleasedescription.mjs
- scripts/release/utils/isnoncommittablerelease.mjs
- scripts/release/utils/parsearguments.mjs
Internal: Support for internal releases from a feature branch.
---
* Requires: https://github.com/ckeditor/ckeditor5-dev/pull/1026
> Support for internal releases from a feature branch

- docs/api/index.md
- docs/framework/contributing/contributing.md
- docs/framework/deep-dive/localization.md
- docs/getting-started/setup/ui-language.md
- docs/index.md
Docs: Updated CKEditor 5 docs regarding translations in the project.
---
Closes cksource/ckeditor5-internal#3808
> Update CKEditor 5 docs regarding translations in the project

- packages/ckeditor5-link/src/index.ts
Other (link): Exported link and unlink icons from ckeditor5-link package.
Closes #17304
---
> Other (link): Exported link and unlink icons from ckeditor5-link package

- packages/ckeditor5-bookmark/docs/_snippets/features/bookmark.js
- packages/ckeditor5-bookmark/docs/features/bookmarks.md
> Docs: demo fix.

- packages/ckeditor5-bookmark/docs/features/bookmarks.md
- scripts/vale/styles/Vocab/Docs/accept.txt
Docs: bookmark docs fixes.
---
> Docs: bookmark docs fixes.

- packages/ckeditor5-bookmark/docs/api/bookmark.md
Docs: Bookmark API link fix.
---
> Docs: Bookmark API link fix.

- scripts/vale/styles/Vocab/Docs/accept.txt
Docs: updating vale rules.
---
> Docs: updating vale rules.

- CHANGELOG.md
Internal: Changelog for v43.3.0.
---
> Changelog for v43.3.0

- docs/umberto.json
> Docs: updating redirs.

- packages/ckeditor5-bookmark/lang/contexts.json
- packages/ckeditor5-core/lang/contexts.json
- packages/ckeditor5-link/lang/contexts.json
- packages/ckeditor5-link/src/linkcommand.ts
- packages/ckeditor5-link/src/linkui.ts
- packages/ckeditor5-link/src/ui/linkadvancedview.ts
- packages/ckeditor5-link/src/ui/linkformview.ts
- packages/ckeditor5-link/tests/linkui.js
- packages/ckeditor5-link/tests/manual/linkdecorator.js
- packages/ckeditor5-link/tests/ui/linkadvancedview.js
- packages/ckeditor5-link/tests/ui/linkformview.js
- packages/ckeditor5-link/theme/linkform.css
Feature (link): Add the Advanced panel with link decorators to the link UI. See #17230.
> Add the Advanced panel to the link UI

- tsconfig.typedoc.json
Internal: Fixed "yarn docs: API" issue due to hiding the "date-fns" package deeply.
---
> Fixed "yarn docs:api" issue due to hidden deeply the "date-fns" package

- package.json
- tsconfig.typedoc.json
Internal: Downgrade the `date-fns` package in the root repository.
---
> Downgrade "date-fns" in the root repository

- packages/ckeditor5-core/src/editor/editor.ts
Internal: Minor comment clarification.
---
> Internal: Minor comment clarification

- docs/features/feature-digest.md
Docs: Enable ToC in Feature digest.
---
> Docs: Enable ToC in Feature digest.

- docs/getting-started/licensing/managing-ckeditor-logo.md
Internal: Merge `stable` to `master`.
---
> Stable to master tmp

- packages/ckeditor5-cloud-services/src/index.ts
Other (cloud-services): Export `Token` as value, not only as type.
---
:warning: This PR targets the `release` branch :warning:
> Other (cloud-services): Export `Token` as value, not only as type.

- CHANGELOG.md
Internal: Changelog for v43.3.1.
---
> Changelog for v43.3.1

- packages/ckeditor5-core/src/editor/editor.ts
Internal (core): Adjusted function definition order to ensure compatibility with older Webpack versions.
---
More details https://github.com/cksource/ckeditor5-commercial/issues/6754#issuecomment-2456937380
> Fix incorrect compilation of license check key code on Webpack.

- packages/ckeditor5-bookmark/docs/features/bookmarks.md
> Docs: removing switcher.

- packages/ckeditor5-core/src/editor/editor.ts
- packages/ckeditor5-core/tests/editor/licensecheck.js
Internal (core): Adjust editor error codes and associated descriptions.
---
Closes https://github.com/cksource/ckeditor5-commercial/issues/6761#issue-2634762995
> Adjust editor error codes names and descriptions.

- packages/ckeditor5-core/src/editor/editor.ts
Internal (core): Fix UBB docs links.
---
Typo in some links caused CI to fail, this PR fixes that.
> Fix UBB docs links.

- packages/ckeditor5-core/src/editor/editor.ts
Fix (core): Improve error codes linking in docs. 
---
Fix failing CI.
> Fix docs links.

- docs/getting-started/integrations-cdn/angular.md
- docs/getting-started/integrations-cdn/react-default-cdn.md
- docs/getting-started/integrations-cdn/react-multiroot-cdn.md
- docs/getting-started/integrations-cdn/vuejs-v3.md
- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/react-default-npm.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
Docs: Unify the structure of the Installation guides.
---
> Docs: Unify the structure of the Installation guides.

- packages/ckeditor5-media-embed/docs/_snippets/features/media-embed-preview.js
- packages/ckeditor5-media-embed/docs/_snippets/features/media-embed.js
Docs: Fix the tour balloon in the Media embed guide.
---
> Docs: Fix the tour balloon in the Media embed guide.

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/react-default-npm.md
- docs/getting-started/integrations/vuejs-v3.md
Docs: Adjust `jest testing` code snippets in integrations. Closes https://github.com/ckeditor/ckeditor5/issues/17421
---
Based on https://github.com/ckeditor/ckeditor5/pull/17420
> Adjust `jest testing` docs in integrations.

- docs/getting-started/integrations-cdn/angular.md
Docs: Update the versions table of the Angular guide.
---
> Docs: Update the versions table of the Angular guide.

- packages/ckeditor5-core/tests/editor/utils/editorusagedata.js
Tests: OS and Browser agnostic mocking of `env` in editor usage data helper tests.
> OS agnostic mocking of env in editor usage data helper tests.

- docs/getting-started/integrations/angular.md
Docs: Unify the Angular guide.
---
> Docs: Unify the Angular guide.

- .github/ISSUE_TEMPLATE/9-builder-report.yml
Internal: Adjust team label names (s/devops/platform). [skip ci]
---
> Adjust team label names (s/devops/platform)

- scripts/release/assets/zip/index.html
Internal: Add `licenseKey` to CDN index page. Closes https://github.com/cksource/ckeditor5-commercial/issues/6792
> Add `licenseKey` to CDN index page.

- docs/getting-started/integrations/angular.md
> Merging stable to master

- packages/ckeditor5-ui/src/editorui/poweredby.ts
- packages/ckeditor5-ui/theme/globals/_evaluationbadge.css
- packages/ckeditor5-ui/theme/globals/_poweredby.css
Fix(ui): Badges should now scale dynamically based on value of `--ck-font-size-base` CSS variable. Closes #17416.
---
Also while base font size will be changed - CKEditor logo will be also scaled:
<table><tbody><tr><td>Before</td><td><figure class="image"><img src="https://github.com/user-attachments/assets/26fa946e-3fb2-48f1-9369-f935da2ffdc1"></figure></td></tr><tr><td>After</td><td><figure class="image"><img src="https://github.com/user-attachments/assets/4378653e-5159-4a1c-b2f8-27201652c69e"></figure></td></tr></tbody></table>
> Badges improvements.

- docs/getting-started/integrations-cdn/angular.md
- docs/getting-started/integrations-cdn/react-default-cdn.md
Docs: Add the context about TS to the Angular CDN guide.
---
> Docs: Add the context about TS to the Angular CDN guide.

- packages/ckeditor5-engine/src/view/renderer.ts
- packages/ckeditor5-engine/tests/view/renderer.js
Fix (engine): List markers should be visible after changing the list type from multi-level to numbered. Closes #17488.
---
> Fix removing attributes from DOM element.

- docs/getting-started/setup/optimizing-build-size.md
- docs/updating/nim-migration/dll-builds.md
- docs/updating/nim-migration/migration-to-new-installation-methods.md
Docs: Unify license keys in snippets.
---
> Docs: Unify license keys in snippets.

- docs/updating/index.md
> Docs: updating landing.

- packages/ckeditor5-core/src/plugin.ts
Docs: Add internal docs flags `isOfficialPlugin` / `isPremiumPlugin`.
> Add internal docs flags `isOfficialPlugin` / `isPremiumPlugin`.

- packages/ckeditor5-bookmark/docs/features/bookmarks.md
- packages/ckeditor5-link/docs/features/link.md
Docs: Add info about linking in Bookmarks feature. Closes #17497.
---
> Add additional information to bookmarks.

- packages/ckeditor5-bookmark/docs/features/bookmarks.md
> Docs: typo.

- docs/_snippets/features/feature-digest.html
- docs/_snippets/features/feature-digest.js
- docs/features/feature-digest.md
Docs: Feature digest improvements.
---
Closes: https://github.com/ckeditor/ckeditor5/issues/17495
> Feature digest improvements

- docs/getting-started/licensing/usage-based-billing.md
- docs/updating/index.md
Docs: Cross-link to the migration guide.
---
> Fix linking to migration

- package.json
- packages/ckeditor5-clipboard/docs/framework/deep-dive/clipboard.md
Docs: link formatting fix.
---
> Docs: link formatting fix.

- docs/getting-started/licensing/license-and-legal.md
- docs/getting-started/licensing/managing-ckeditor-logo.md
> Docs: fixing typos.

- CHANGELOG.md
- scripts/vale/styles/Vocab/Docs/accept.txt
Internal: Changelog for v44.0.0.
---
> Changelog for v44.0.0

- docs/_snippets/features/feature-digest.html
- docs/features/feature-digest.md
Docs: Add more specificity to styles.
---
> Docs: Add more specificity to styles.

- packages/ckeditor5-cloud-services/src/cloudservicesconfig.ts
> Docs: fixing API link.

- packages/ckeditor5-image/lang/contexts.json
- packages/ckeditor5-image/src/imageinsert/imageinsertviaurlui.ts
- packages/ckeditor5-image/tests/imageinsert/imageinsertviaurlui.js
- packages/ckeditor5-media-embed/lang/contexts.json
- packages/ckeditor5-media-embed/src/mediaembedui.ts
- packages/ckeditor5-media-embed/tests/mediaembedui.js
Internal (image): Unify insert image via URL dialog and CTA title.
Internal (media-embed): Unify insert media embed dialog and CTA title.
---
Part of #17230
> Unify Media Embed and Insert Image via URL dialog titles.

- docs/getting-started/licensing/license-key-and-activation.md
- docs/getting-started/licensing/usage-based-billing.md
- docs/getting-started/setup/csp.md
- docs/updating/update-to-44.md
- packages/ckeditor5-style/docs/_snippets/features/styles.js
Docs: minor tweaks. Closes: cksource/ckeditor5-commercial#6860
---
> Docs: minor tweaks.

- packages/ckeditor5-link/docs/_snippets/features/link.js
- packages/ckeditor5-link/docs/features/link.md
> Docs: Update link docs.

- packages/ckeditor5-ui/docs/framework/deep-dive/focus-tracking.md
Docs: Fix linking in the Focus tracking guide.
---
> Docs: Fix linking in the Focus tracking guide.

- CHANGELOG.md
- scripts/vale/styles/Vocab/Docs/accept.txt
Internal: Changelog for v44.1.0.
---
> Changelog for v44.1.0

- docs/getting-started/licensing/license-key-and-activation.md
> Docs: key update.

- packages/ckeditor5-editor-classic/src/index.ts
Fix (editor-classic): Export `ClassicEditorUIView` from `editor-classic` package.
> Export `ClassicEditorUIView` from `editor-classic` package.

- packages/ckeditor5-emoji/src/emojimention.ts
- packages/ckeditor5-emoji/src/emojipicker.ts
- packages/ckeditor5-emoji/src/ui/emojitoneview.ts
- packages/ckeditor5-emoji/tests/emojimention.js
- packages/ckeditor5-emoji/tests/ui/emojitoneview.js
Internal: Emoji mention will take into account the selected skin tone. Closes #17656.
Internal: Active skin tone in the emoji picker will have checkmark and be selected upon opening the skin tone dropdown. Closes #17660.
---
> Emoji mention will take into account the selected skin tone

- packages/ckeditor5-link/tests/manual/linkproviders.html
- packages/ckeditor5-link/tests/manual/linkproviders.js
- packages/ckeditor5-theme-lark/theme/ckeditor5-link/linkform.css
Fix (link): Should show scroll on link list providers when it contains more than 4 items.
---
> Show scroll on link list providers in certain situations.

- packages/ckeditor5-emoji/src/ui/emojisearchview.ts
- packages/ckeditor5-ui/src/index.ts
Internal: Added a search input to emoji picker. Closes #17659.
---
> Added a search input to emoji picker.

- docs/umberto.json
Docs: adding a redir. Touches: #17677
---
> Docs: adding a redir

- packages/ckeditor5-core/src/editor/editor.ts
- packages/ckeditor5-core/tests/editor/licensecheck.js
- packages/ckeditor5-ui/tests/editorui/evaluationbadge.js
Internal (editor): Improve style of warnings in editor validator checks.
> Improve style of warnings in editor validator checks.

- docs/getting-started/integrations/dotnet.md
Docs: Update the .NET guide. Closes https://github.com/ckeditor/ckeditor5/issues/17705
---
> Docs: Update the .NET guide

- tests/_data/data-sets/ghs.js
Internal: Bumped the year.
---
> Bumped the year

- packages/ckeditor5-emoji/theme/emojicategories.css
- packages/ckeditor5-emoji/theme/emojigrid.css
Internal: Added padding to emoji categories and fixed "Not found" styles. Closes #17661.
---
> Added padding to emoji categories and fixed "Not found" styles.

- docs/updating/nim-migration/migration-to-new-installation-methods.md
Docs: Update the deprecation timelines.
---
> Update the deprecation timelines.

- docs/getting-started/licensing/license-and-legal.md
Docs: Typo fixed in `license-and-legal.md`. Closes #17764.
---
> Typo fixed in license-and-legal.md.

- packages/ckeditor5-emoji/src/emojidatabase.ts
- packages/ckeditor5-emoji/src/emojimention.ts
- packages/ckeditor5-emoji/src/emojipicker.ts
- packages/ckeditor5-emoji/tests/emojidatabase.js
- packages/ckeditor5-emoji/tests/emojimention.js
- packages/ckeditor5-emoji/tests/emojipicker.js
Internal: Do not initialize Emoji plugins if emoji database is not available. Closes #17772.
---
> Do not initialize Emoji plugins if emoji database is not available

- packages/ckeditor5-emoji/src/ui/emojicategoriesview.ts
- packages/ckeditor5-emoji/src/ui/emojigridview.ts
- packages/ckeditor5-emoji/src/ui/emojipickerview.ts
- packages/ckeditor5-emoji/src/ui/emojisearchview.ts
- packages/ckeditor5-emoji/src/ui/emojitoneview.ts
- packages/ckeditor5-emoji/tests/ui/emojicategoriesview.js
- packages/ckeditor5-emoji/tests/ui/emojigridview.js
- packages/ckeditor5-emoji/tests/ui/emojitoneview.js
- packages/ckeditor5-emoji/theme/emojicategories.css
- packages/ckeditor5-emoji/theme/emojigrid.css
- packages/ckeditor5-emoji/theme/emojipicker.css
- packages/ckeditor5-emoji/theme/emojitone.css
Internal: Improved CSS class names. Closes #17792.
> Improved CSS classes (emoji feature)

- packages/ckeditor5-emoji/src/emojidatabase.ts
- packages/ckeditor5-emoji/src/emojimention.ts
- packages/ckeditor5-emoji/src/emojipicker.ts
- packages/ckeditor5-emoji/tests/emojimention.js
Internal: Fixed skin tone in emoji mention to take the default value from emoji config. Closes ckeditor/ckeditor5#17778.
---
> Fixed skin tone in emoji mention to take the default value from emoji config.

- packages/ckeditor5-emoji/src/emojipicker.ts
- packages/ckeditor5-emoji/src/ui/emojipickerview.ts
- packages/ckeditor5-emoji/tests/emojipicker.js
- packages/ckeditor5-emoji/tests/ui/emojipickerview.js
Internal: Updating emoji balloon position when layout is changed. Closes ckeditor/ckeditor5#17774.
---
> Updating emoji balloon position when layout is changed.

- packages/ckeditor5-emoji/docs/features/emoji.md
- packages/ckeditor5-emoji/src/augmentation.ts
- packages/ckeditor5-emoji/src/emojicommand.ts
- packages/ckeditor5-emoji/src/emojidatabase.ts
- packages/ckeditor5-emoji/src/emojipicker.ts
- packages/ckeditor5-emoji/src/index.ts
- packages/ckeditor5-emoji/tests/emojicommand.js
- packages/ckeditor5-emoji/tests/emojipicker.js
Internal: Added the "EmojiCommand" command to open the feature UI using a command only. Closes #17773.
---
> Introduce `EmojiCommand`

- packages/ckeditor5-markdown-gfm/package.json
Other (markdown-gfm): Add `sideEffects` field to allow tree-shaking of external libraries. See #17767.
> Add the `sideEffects` field to `package.json`.

- package.json
Internal: Added Uploadcare as a dev dependency to CKEditor 5.
---
> Add Uploadcare as a dev dependency 

- packages/ckeditor5-engine/src/conversion/mapper.ts
- packages/ckeditor5-engine/src/view/documentfragment.ts
Docs: Fix Mapper API docs.
---
Fixes CI errors related to Mapper API docs.
> Fix API docs

- package.json
Internal: Added `@ckeditor/ckeditor5-source-editing-enhanced` as a project dependency.
---
According to: https://tiugotech.slack.com/archives/CFUAW14R3/p1738135802624959.
> Added ckeditor5-source-editing-enhanced to pkg.json

- docs/features/feature-digest.md
- docs/getting-started/integrations/drupal-real-time-collaboration.md
- packages/ckeditor5-paste-from-office/docs/features/paste-from-google-docs.md
- packages/ckeditor5-paste-from-office/docs/features/paste-from-office.md
Docs: renaming Enhanced paste from Office. 
---
_Merge together with_ cksource/ckeditor5-commercial#7010
> Docs: renaming Enhanced paste from Office.

- docs/_snippets/updating/plugins-mapping/plugins-mapping.html
- docs/features/feature-digest.md
- packages/ckeditor5-emoji/docs/features/emoji.md
- packages/ckeditor5-emoji/src/emojirepository.ts
Docs: updating emojis.
Touches: #17835
---
> Docs: updating emojis.

- packages/ckeditor5-emoji/src/ui/emojipickerview.ts
- packages/ckeditor5-emoji/tests/fixtures/database.json
- packages/ckeditor5-emoji/tests/integration.js
- packages/ckeditor5-emoji/tests/ui/emojipickerview.js
Internal: Fixed scroll position on category change in emoji picker. Closes #17841.
---
> Fixed scroll position on category change in emoji picker

- packages/ckeditor5-emoji/tests/emojimention.js
Tests (emoji): Fixed invalid mocks in Emoji tests.
---
> Fixed invalid mocks in Emoji tests

- packages/ckeditor5-engine/src/conversion/viewconsumable.ts
- packages/ckeditor5-engine/src/view/element.ts
Internal: Fixed invalid links in docs snippets.
---
> Fix links in docs.

- packages/ckeditor5-image/src/imagesizeattributes.ts
- packages/ckeditor5-image/tests/imagesizeattributes.js
Internal (image): Add `loading=lazy` to images with `sources` attribute. Closes #17865.
---
:warning: This PR targets the `release` branch :warning:
> Internal (image): Add `loading=lazy` to images with `sources` attribute.

- packages/ckeditor5-emoji/src/emojirepository.ts
- packages/ckeditor5-emoji/tests/emojirepository.js
Internal: Implemented cache mechanism for Emoji requests.
---
> Implemented cache mechanism for Emoji requests

- packages/ckeditor5-emoji/ckeditor5-metadata.json
Internal: Added missing UI component to the Emoji plugin.
---
> Added missing UI component to the Emoji plugin.

- docs/updating/nim-migration/predefined-builds.md
Docs: updating migration guide. 
---
> Docs: updating migration guide. 

- scripts/release/utils/getcdnversion.mjs
- scripts/release/utils/getreleasedescription.mjs
- scripts/release/utils/isnoncommittablerelease.mjs
- scripts/release/utils/parsearguments.mjs
Internal: Added support in release scripts for publishing the next pre-release version.
---
> Added support in release scripts for publishing the next pre-release version

- scripts/release/utils/getcdnversion.mjs
- scripts/release/utils/getreleasedescription.mjs
- scripts/release/utils/isnoncommittablerelease.mjs
- scripts/release/utils/parsearguments.mjs
Internal: Merge `#master` to `#master-it84`.
---
> Merge `#master` to `#master-it84`

- packages/ckeditor5-html-support/src/augmentation.ts
- packages/ckeditor5-html-support/src/datafilter.ts
- packages/ckeditor5-html-support/src/dataschema.ts
- packages/ckeditor5-html-support/src/generalhtmlsupport.ts
- packages/ckeditor5-html-support/src/index.ts
- packages/ckeditor5-html-support/src/integrations/horizontalline.ts
- packages/ckeditor5-html-support/src/schemadefinitions.ts
- packages/ckeditor5-html-support/tests/datafilter.js
- packages/ckeditor5-html-support/tests/integrations/horizontalline.js
- packages/ckeditor5-html-support/tests/integrations/image.js
- packages/ckeditor5-html-support/tests/manual/ghs-all-features.html
- packages/ckeditor5-html-support/tests/manual/ghs-no-features.html
Feature (html-support): Added support for `<hr>` element. Closes #12973.
---
> Adding support for HR in GHS.

- docs/_snippets/build-balloon-block-source.js
- docs/_snippets/build-balloon-block.js
- docs/_snippets/build-balloon-source.js
- docs/_snippets/build-balloon.js
- docs/_snippets/build-inline-source.js
- docs/_snippets/build-inline.js
- docs/_snippets/build-multi-root-source.js
- docs/_snippets/build-multi-root.js
- docs/_snippets/examples/balloon-block-editor.js
- docs/_snippets/examples/balloon-editor.js
- docs/_snippets/examples/inline-editor.js
- docs/_snippets/examples/multi-root-editor.js
- docs/examples/builds/balloon-block-editor.md
- docs/examples/builds/balloon-editor.md
- docs/examples/builds/inline-editor.md
- docs/examples/builds/multi-root-editor.md
Docs: Ported importing builds in docs to using plain packages imports.
---
> Ported importing builds in docs to using plain packages imports.

- packages/ckeditor5-html-support/docs/features/full-page-html.md
Docs(full-page): Extended guide to `Full page HTML` with a configuration section.
---
> Extended guide to `Full page HTML`.

- packages/ckeditor5-html-support/src/fullpage.ts
Docs(full-page): Fixed error code in `Full page HTML` feature.
---
> Fixed error code in `Full page HTML` feature.

- .circleci/template.yml
- package.json
- packages/ckeditor5-clipboard/package.json
- packages/ckeditor5-core/package.json
- packages/ckeditor5-editor-balloon/package.json
- packages/ckeditor5-editor-classic/package.json
- packages/ckeditor5-editor-decoupled/package.json
- packages/ckeditor5-editor-inline/package.json
- packages/ckeditor5-editor-multi-root/package.json
- packages/ckeditor5-engine/package.json
- packages/ckeditor5-enter/package.json
- packages/ckeditor5-utils/package.json
- packages/ckeditor5-widget/package.json
- scripts/release/validatepackages.mjs
Internal: Re-enable `publint` validation.
> Re-enable `publint` validation

- packages/ckeditor5-email/src/integrations/table.ts
- packages/ckeditor5-email/tests/integrations/table.js
- packages/ckeditor5-table/src/augmentation.ts
- packages/ckeditor5-table/src/index.ts
- packages/ckeditor5-table/src/tablelayout.ts
- packages/ckeditor5-table/tests/tablelayout.js
Internal: Editor should warn about missing `TableLayout` plugin in email integration.
---
> Warn about missing TableLayout in email integration

- packages/ckeditor5-email/docs/features/email.md
Docs: Add `TableLayout` plugin mention in email integration docs.
---
Commercial PR https://github.com/cksource/ckeditor5-commercial/pull/7098
> Add TableLayout plugin mention in email integration docs

- packages/ckeditor5-icons/package.json
- scripts/update-icons-typings.mjs
Internal: Fix icon typings.
---
No issue because everything is already described in the script.
> Fix icons typings

- LICENSE.md
- packages/ckeditor5-emoji/LICENSE.md
- scripts/features/build-emoji-cdn-files.mjs
Internal: Share a script that builds the emoji collection.
---
> Share a script that builds the emoji collection

- LICENSE.md
- packages/ckeditor5-emoji/LICENSE.md
- packages/ckeditor5-emoji/package.json
- packages/ckeditor5-emoji/src/emojirepository.ts
- packages/ckeditor5-emoji/tests/emojirepository.js
Internal (emoji): Changed fuzzy search library from `Fuse.js` to `fuzzysort`.
---
> Swapped fuzzy search library for emoji

- packages/ckeditor5-clipboard/src/index.ts
Other (clipboard): Export `viewToPlainText` function. Closes #17950.
---
> Export `viewToPlainText`.

- docs/updating/update-to-44.md
Docs: adding the update guide for 44.2.0.
---
> Docs: adding the update guide for 44.2.0.

- CHANGELOG.md
Internal: Changelog for v44.2.1.
---
> Changelog for v44.2.1

- docs/updating/update-to-45.md
Docs: Add upgrade docs for refactored linking experience.
---
Part of https://www.notion.so/Linking-experience-Link-UI-release-preparation-174bb9a67232803ca283e584f0e7dac7
Parent PR: https://github.com/ckeditor/ckeditor5/pull/17368
> Add linking experience upgrade docs

- packages/ckeditor5-bookmark/docs/features/bookmarks.md
- packages/ckeditor5-link/docs/features/link.md
Docs: Add feature guides for toolbar configuration of bookmarks and links.
---
Kanban ticket https://www.notion.so/Describe-new-toolbars-in-docs-174bb9a6723280428b13feac7a3e2cad
> Add feature guides for toolbar configuration of bookmarks and links.

- packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md
- packages/ckeditor5-restricted-editing/src/restrictededitingconfig.ts
Docs: adding feature information. Closes #17921
---
> Docs: adding feature information.

- docs/umberto.json
Docs: updating redirects. Closes cksource/ckeditor5-internal#3949
---
> Docs: updating redirects.

- packages/ckeditor5-html-support/ckeditor5-metadata.json
- packages/ckeditor5-html-support/src/emptyblock.ts
Docs: rewording plugin information for `EmptyBlocks`.
---
> Docs: rewording plugin information.

- packages/ckeditor5-emoji/src/utils/isemojisupported.ts
Internal: Do not include 3rd party util in code coverage in Emoji feature. Closes #18004.
---
> Do not include 3rd party util in code coverage in Emoji feature

- packages/ckeditor5-emoji/docs/features/emoji.md
- packages/ckeditor5-emoji/src/emojiconfig.ts
- packages/ckeditor5-emoji/src/emojirepository.ts
- packages/ckeditor5-emoji/tests/emojirepository.js
- packages/ckeditor5-emoji/tests/manual/emoji.html
- packages/ckeditor5-emoji/tests/manual/emoji.js
- packages/ckeditor5-emoji/tests/manual/emoji.md
Other (emoji): Introduced the `emoji.useCustomFont` option to disable the filtering mechanism. Closes #17988.
---
> Introduced the `emoji.useCustomFont` option

- packages/ckeditor5-emoji/src/emojirepository.ts
- packages/ckeditor5-emoji/src/emojiutils.ts
- packages/ckeditor5-emoji/tests/utils/emojiutils.js
Other (emoji): Added support for emoji versions below 15. Closes #18014.
---
> Extended supported emoji versions check

- packages/ckeditor5-emoji/docs/features/emoji.md
Docs: Improved emoji's docs regarding emoji repository versions changing
---
> Improved emoji's docs regarding emoji repository versions changing

- CHANGELOG.md
- docs/updating/update-to-44.md
Internal: Changelog for v44.3.0.
---
> Changelog for v44.3.0

- docs/updating/update-to-43.md
Docs: links in update guide.
---
> Docs: links in update guide.

- scripts/docs/snippetadapter.mjs
Internal: Fix nightly docs build. Closes #18070.
> Internal: Fix nightly docs build.

- packages/ckeditor5-bookmark/docs/_snippets/features/bookmark.html
- packages/ckeditor5-bookmark/docs/features/bookmarks.md
- packages/ckeditor5-link/docs/_snippets/features/link.html
Docs: updating the bookmarks and link guides.
---
> Docs: updating bookmarks and links guides.

- docs/framework/contributing/development-environment.md
- docs/getting-started/advanced/integrating-from-source-vite.md
- package.json
Other: Upgraded the minimal version of Node.js to 20.0.0 due to the end of LTS.
~MAJOR BREAKING CHANGE: Upgraded the minimal version of Node.js to 20.0.0 due to the end of LTS.~
---
> Bumped NodeJS version.

- scripts/docs/snippetadapter.mjs
Docs: Fix tooltip styles. Closes #18107.
> Docs: Fix tooltip styles.

- docs/getting-started/integrations-cdn/next-js.md
- docs/getting-started/integrations/next-js.md
Docs: Update the Next guide to include Next 15 integration. Closes #18061.
---
> Docs: Update the Next guide to include Next 15 integration.

- packages/ckeditor5-media-embed/docs/_snippets/features/media-embed-preview.html
- packages/ckeditor5-media-embed/docs/_snippets/features/media-embed.html
Docs: updating demo content.
---
> Docs: updating demo content.

- package.json
Internal: Merge stable to master.
---
> Merge stable to master

- docs/getting-started/integrations-cdn/dotnet.md
- docs/getting-started/integrations-cdn/laravel.md
- docs/getting-started/integrations-cdn/next-js.md
- docs/getting-started/integrations-cdn/nuxt.md
- docs/getting-started/integrations-cdn/vuejs-v2.md
- docs/getting-started/integrations-cdn/vuejs-v3.md
- docs/getting-started/integrations/dotnet.md
- docs/getting-started/integrations/laravel.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/nuxt.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
Docs: Add Nuxt guides. Closes: #6071.
> Add Nuxt guides

- docs/updating/update-to-44.md
Docs: putting link in the update guide.
---
> Docs: putting link in the update guide.

- docs/getting-started/setup/editor-lifecycle.md
Docs: More precise message about the destroy lifecycle.
---
> Improve the `destroy` docs message.

- docs/tutorials/crash-course/commands.md
- docs/tutorials/crash-course/editor.md
- docs/tutorials/crash-course/keystrokes.md
- docs/tutorials/crash-course/plugin-configuration.md
- docs/tutorials/crash-course/view.md
Docs: Improved the crash course tutorial. Closes https://github.com/cksource/ckeditor5-internal/issues/3966.
---
> Docs: Improved the crash course tutorial

- packages/ckeditor5-table/src/tableconfig.ts
- packages/ckeditor5-table/src/tablelayout/tablelayoutediting.ts
- packages/ckeditor5-table/tests/manual/tablelayout-configurable.html
- packages/ckeditor5-table/tests/manual/tablelayout-configurable.js
- packages/ckeditor5-table/tests/manual/tablelayout-configurable.md
- packages/ckeditor5-table/tests/tablelayout/tablelayoutediting.js
Internal: Introducing the layout table heuristics configuration. See https://github.com/ckeditor/ckeditor5/issues/18131.
---
> Layout table heuristics configuration.

- scripts/docs/snippetadapter.mjs
> Docs: Prevent source leaking.

- COPYING.GPL
- LICENSE.md
Docs: Added `COPYING.GPL` file with the full text of the GPLv2 license and adjusted `LICENSE.md` accordingly.
> Added COPYING.GPL file with the full text of the GPLv2 license

- scripts/release/preparepackages.mjs
- scripts/release/utils/getckeditor5packagejson.mjs
Internal: Added COPYING.GPL to released files.
---
> Added COPYING.GPL to released files

- packages/ckeditor5-icons/src/index.ts
Internal (icons): Fix API docs structure.
> Internal (icons): Fix API docs structure.

- package.json
Internal: Use the latest Umberto
---
> Use the latest Umberto

- packages/ckeditor5-html-support/src/integrations/table.ts
- packages/ckeditor5-html-support/tests/integrations/table.js
- packages/ckeditor5-table/package.json
- packages/ckeditor5-table/tests/manual/tablelayout.js
Fix (html-support): Should load and show floated tables as expected in the editor's view. Closes #18203.
---
> Propagate to `<figure>` selected `<table>` style attributes.

- packages/ckeditor5-engine/src/view/domconverter.ts
- packages/ckeditor5-engine/tests/view/domconverter/domconverter.js
Other (engine): Added readonly `DomConverter#domDocument` property. Closes #18146.
> Other (engine): Added readonly `DomConverter#domDocument` property.

- docs/framework/how-tos.md
Docs: Updated the "how-to" guide on icon customization to point to the dedicated guide. Closes #18178.
---
> Updated icon customization tip

- docs/features/feature-digest.md
- packages/ckeditor5-table/docs/_snippets/features/table-layout.html
- packages/ckeditor5-table/docs/_snippets/features/table-toggling.html
- packages/ckeditor5-table/docs/features/tables-layout.md
Docs: Post merge fixes.
---
There is a commercial version of this PR: https://github.com/cksource/ckeditor5-commercial/pull/7253
Still WIP.
> Docs: Post merge fixes.

- docs/updating/update-to-45.md
- packages/ckeditor5-bookmark/docs/features/bookmarks.md
- packages/ckeditor5-link/docs/features/link.md
- packages/ckeditor5-table/docs/features/tables-layout.md
> Docs: bumping the dates.

- package.json
Internal (fullscreen): Add fullscreen package to the repository `package.json` file.
---
> Add fullscreen feature to package.json

- packages/ckeditor5-table/ckeditor5-metadata.json
Docs: plain table output metadata. Closes https://github.com/ckeditor/ckeditor5/issues/18224
---
> Docs: plain table output metadata.

- packages/ckeditor5-table/docs/features/tables-layout.md
Docs: The layout table guide extended. Closes #18132
---
> The layout table guide extended.

- packages/ckeditor5-fullscreen/docs/features/fullscreen.md
Docs: restoring contribute link. 
---
> Docs: restoring contribute link. 

- docs/getting-started/setup/customizing-icons.md
> Docs: bumping the date.

- CHANGELOG.md
Internal: Changelog for v45.0.0.
---
> Changelog for v45.0.0

- CHANGELOG.md
- docs/features/feature-digest.md
- packages/ckeditor5-fullscreen/docs/features/fullscreen.md
- packages/ckeditor5-table/docs/features/layout-tables.md
> Docs: file renamed.

- packages/ckeditor5-table/src/converters/tableproperties.ts
- packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesediting.ts
- packages/ckeditor5-table/src/tableproperties/tablepropertiesediting.ts
- packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js
Internal (table): Added upcast for tables with `margin-left:auto;margin-right:auto;` inline style set. Closes #18258.
---
> Added upcast for tables with `margin-left:auto;margin-right:auto;` inline style set

- packages/ckeditor5-font/docs/features/font.md
Docs: Add email compatibility section to font docs.
---
Commercial PR https://github.com/cksource/ckeditor5-commercial/pull/7290
> Docs: Add email compatiblity section to font docs

- docs/getting-started/setup/optimizing-build-size.md
- scripts/vale/styles/Vocab/Docs/accept.txt
Docs: Update `The result` section in `Optimizing build size` guide.
> Docs: Update `The result` section in `Optimizing build size` guide.

- docs/getting-started/index.md
> Docs: add Nuxt link.

- packages/ckeditor5-fullscreen/ckeditor5-metadata.json
Internal (fullscreen): Add missing `uiComponents` entry to `ckeditor5-metadata.json` file.
---
> Fill missing fullscreen metadata

- package.json
Internal: Bump Umberto to 6.0.0.
---
> Bump Umberto to 6.0.0.

- packages/ckeditor5-fullscreen/tests/handlers/abstracteditorhandler.js
Internal (fullscreen): Change the assertion to make unit test pass independently from the environment.
---
> Change check in fullscreen unit test

- packages/ckeditor5-table/docs/features/layout-tables.md
Docs: Should present proper code snippets in `Table Layout` feature guide.
---
⚠️  Targeting `release`.
> Code snippets update in `Layout tables` guide.

- packages/ckeditor5-word-count/tests/wordcount.js
Internal (word-count): Increase delay in unstable word-count unit test.
> Increase delay in unstable word-count unit test.

- packages/ckeditor5-fullscreen/lang/contexts.json
- packages/ckeditor5-fullscreen/src/handlers/abstracteditorhandler.ts
Internal (fullscreen): Turn hardcoded strings into translated ones.
---
> Turn hardcoded strings into translated ones in fullscreen

- CHANGELOG.md
- docs/updating/update-to-45.md
Update the release date in CHANGELOG.
---
> Update the release date in CHANGELOG

- docs/updating/update-to-45.md
Docs: update the update guide.
---
> Docs: update the update guide.

- docs/updating/update-to-45.md
Docs: merge stable to master.
---
> Docs: merge stable to master

- packages/ckeditor5-show-blocks/tests/manual/showblocks.html
Internal: Remove flaky external resources in the manual test. Closes #18374.
---
> Remove flaky external resources.

- docs/getting-started/integrations/css.md
- docs/getting-started/integrations/salesforce.md
> Docs: updating CTA.

- packages/ckeditor5-engine/tests/view/domconverter/domconverter.js
- packages/ckeditor5-fullscreen/src/handlers/abstracteditorhandler.ts
Internal (fullscreen): Add type assertion necessary due to TS bug. Closes #18386.
Internal (engine): Fix incorrect property stubbing leaking to other tests and causing some of them to fail.
---
> Fixes for CI

- packages/ckeditor5-fullscreen/tests/handlers/abstracteditorhandler.js
Internal (fullscreen): Fix unit test cleanup.
---
> Properly clean up document after test

- packages/ckeditor5-clipboard/src/index.ts
Feature (clipboard): Export `ClipboardObserver` class from package. Closes #18385.
---
> Export `ClipboardObserver` from clipboard package.

- CHANGELOG.md
- docs/updating/update-to-45.md
Docs: Mention es2022 change in the CHANGELOG and update guides.
---
> Mention es2022 change in the CHANGELOG and update guides.

- packages/ckeditor5-core/tests/editor/licensecheck.js
Tests (core): Fix failing license tests.
---
> Fix failing license tests.

- docs/getting-started/setup/customizing-icons.md
Docs: Improve "Customizing icons" guide. Closes #18367.
> Docs: Improve "Customizing icons" guide.

- packages/ckeditor5-utils/src/language.ts
- packages/ckeditor5-utils/tests/language.js
Feature (utils): Recognize Urdu as an RTL language. Closes #16900.
Thanks to @smtaha512!
---
> Recognize Urdu as an RTL language

- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/react-default-npm.md
- docs/getting-started/integrations/vuejs-v3.md
Docs: Add `TextEncoder` mock to jest testing guide.
---
It prevents CKEditor startup issues with some premium packages.
> Add `TextEncoder` mock to jest testing guide.

- scripts/docs/build-ckeditor-packages.mjs
- scripts/docs/build-docs.mjs
- scripts/docs/parse-arguments.mjs
- scripts/utils/replacekebabcasewithcamelcase.mjs
Internal: Add `dev` flag to docs build and fix existing flags.
Internal: Fix various flags used in docs build process.
---
Merge with cksource/ckeditor5-commercial#7369.
See cksource/ckeditor5-commercial#7347.
> Internal: Add `dev` flag to docs build and fix existing flags.

- scripts/docs/parse-arguments.mjs
Internal: Warn about using the `--dev` docs build.
---
Related to changes made in #18421.
> Internal: Warn about using the `--dev` docs build.

- packages/ckeditor5-html-support/docs/features/general-html-support.md
Docs: layout changes in the GHS guide.
---
> Docs: layout changes.

- docs/getting-started/integrations-cdn/svelte.md
- docs/getting-started/integrations/svelte.md
Docs: Introduced the Svelte integration guides. Closes #18413.
> Docs: Introduced the Svelte integration guides.

- scripts/docs/parse-arguments.mjs
Internal: Fixed `yarn docs --dev` command to handle older versions of node. Closes #18431.
---
> Fixed --dev flag documentation warning to handle older versions of node.

- packages/ckeditor5-fullscreen/docs/features/fullscreen.md
Other: Fix name of one of the fullscreen feature methods mentioned in docs.
---
> Change method name in fullscreen docs

- docs/getting-started/legacy-getting-started/legacy-imports.md
Docs: explaining legacy banner in guide. Closes https://github.com/ckeditor/ckeditor5/issues/17760
---
> Docs: explaining legacy banner in guide.

- docs/getting-started/legacy-getting-started/integrations/overview.md
Docs: removing duplicated keys.
---
> Docs: removing duplicated keys.

- .circleci/template.yml
Internal: Restored tasks on CI for the CKEditor 5 repository from CC.
---
- See https://github.com/cksource/ckeditor5-commercial/issues/7383.
> Restored tasks on CI for the CKEditor 5 repository from CC.

- docs/getting-started/advanced/dll-builds.md
Docs: updating the snippet.
---
> Docs: updating the snippet.

- docs/getting-started/index.md
- docs/getting-started/integrations/svelte.md
Docs: updating integrations list. Part of https://github.com/ckeditor/ckeditor5/issues/18455
---
> Docs: updating integrations list.

- CHANGELOG.md
Docs: Inform about display text in the changelog.
---
> Inform about display text.

- docs/getting-started/setup/menubar.md
Docs: Fix the menu bar config snippet. Closes #18451.
---
> Docs: Fix the menu bar config snippet.

- docs/getting-started/index.md
> Docs: links fix.

- docs/umberto.json
Internal: Updated umberto config.
---
> Updated umberto config

- docs/getting-started/integrations-cdn/salesforce.md
- docs/getting-started/integrations/salesforce.md
- docs/getting-started/integrations/sharepoint.md
Docs: Unify license key string across whole docs.
---
⚠️ `release` is the target branch.
> Unify license key string across whole docs.

- docs/getting-started/integrations-cdn/angular.md
- docs/getting-started/integrations-cdn/dotnet.md
- docs/getting-started/integrations-cdn/laravel.md
- docs/getting-started/integrations-cdn/next-js.md
- docs/getting-started/integrations-cdn/nuxt.md
- docs/getting-started/integrations-cdn/quick-start.md
- docs/getting-started/integrations-cdn/react-default-cdn.md
- docs/getting-started/integrations-cdn/react-multiroot-cdn.md
- docs/getting-started/integrations-cdn/salesforce.md
- docs/getting-started/integrations-cdn/spring-boot.md
- docs/getting-started/integrations-cdn/svelte.md
- docs/getting-started/integrations-cdn/vuejs-v2.md
- docs/getting-started/integrations-cdn/vuejs-v3.md
- docs/getting-started/integrations/angular.md
- docs/getting-started/integrations/dotnet.md
- docs/getting-started/integrations/drupal-real-time-collaboration.md
- docs/getting-started/integrations/laravel.md
- docs/getting-started/integrations/next-js.md
- docs/getting-started/integrations/nuxt.md
- docs/getting-started/integrations/quick-start.md
- docs/getting-started/integrations/react-default-npm.md
- docs/getting-started/integrations/react-multiroot-npm.md
- docs/getting-started/integrations/salesforce.md
- docs/getting-started/integrations/sharepoint.md
- docs/getting-started/integrations/spring-boot.md
- docs/getting-started/integrations/svelte.md
- docs/getting-started/integrations/vuejs-v2.md
- docs/getting-started/integrations/vuejs-v3.md
Docs: Fixing titles and meta-titles for integrations.
Closes: https://github.com/cksource/ckeditor5-commercial/issues/7827
---
_Solution suggested for best SEO gain by Szymon._
> Docs: ZIP + npm integrations.

- docs/umberto.json
Docs: updating redirect. Part of https://github.com/ckeditor/ckeditor5/issues/18510
---
> Docs: updating redirect.

- docs/updating/update-to-45.md
Docs: update to 45.1.0 guide. Closes https://github.com/ckeditor/ckeditor5/issues/18493
---
> Docs: update to 45.1.0 guide.

- packages/ckeditor5-source-editing/package.json
Internal: Use the same CKEditor 5 version packages in the project.
---
> Use the same CKEditor 5 version packages in the project.

- docs/_snippets/features/update-placeholder.html
- docs/_snippets/features/update-placeholder.js
- docs/_snippets/installation/getting-and-setting-data/manualsave.html
- docs/_snippets/installation/getting-and-setting-data/manualsave.js
- docs/features/editor-placeholder.md
- docs/framework/architecture/intro.md
- docs/getting-started/setup/getting-and-setting-data.md
- docs/getting-started/setup/menubar.md
- packages/ckeditor5-fullscreen/docs/_snippets/features/fullscreen-pageless.html
- packages/ckeditor5-fullscreen/docs/_snippets/features/fullscreen-pageless.js
- packages/ckeditor5-heading/docs/_snippets/features/title.html
- packages/ckeditor5-heading/docs/_snippets/features/title.js
- packages/ckeditor5-heading/docs/features/title.md
- packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.html
- packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.js
- packages/ckeditor5-html-embed/docs/features/html-embed.md
- packages/ckeditor5-markdown-gfm/docs/_snippets/features/markdown.html
- packages/ckeditor5-markdown-gfm/docs/_snippets/features/markdown.js
- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
- packages/ckeditor5-minimap/docs/features/minimap.md
- packages/ckeditor5-upload/docs/_snippets/features/base64-upload.html
- packages/ckeditor5-upload/docs/_snippets/features/base64-upload.js
- packages/ckeditor5-upload/docs/features/base64-upload-adapter.md
- scripts/docs/snippetadapter.mjs
Snippets improvements in Gloria
---
Parent PR:
https://github.com/ckeditor/ckeditor5/pull/18435
> Gloria - Snippets refactor

- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
Docs: Fix CKFinder snippet.
---
Closes cksource/ckeditor5-commercial#7842.
> Docs: Fix CKFinder snippet.

- CHANGELOG.md
- docs/updating/update-to-45.md
Internal: Changelog for v45.2.0.
---
> Changelog for v45.2.0

- packages/ckeditor5-ckbox/src/index.ts
Internal (ckbox): Added re-exports in the `ckeditor5-ckbox` package.
---
> Added re-exports in the `ckeditor5-ckbox` package

- packages/ckeditor5-watchdog/src/contextwatchdog.ts
- packages/ckeditor5-watchdog/src/editorwatchdog.ts
- packages/ckeditor5-watchdog/src/index.ts
Internal: Added re-exports and renamed package members for `ckeditor5-watchdog`.
---
> Added re-exports and renamed package members for `ckeditor5-watchdog`.

- packages/ckeditor5-upload/src/index.ts
Internal: Added re-exports and renamed package members for `ckeditor5-upload`.
---
> Added re-exports and renamed package members for `ckeditor5-upload`.

- packages/ckeditor5-undo/src/basecommand.ts
- packages/ckeditor5-undo/src/index.ts
- packages/ckeditor5-undo/src/redocommand.ts
- packages/ckeditor5-undo/src/undocommand.ts
- packages/ckeditor5-undo/tests/basecommand.js
Internal: Added re-exports and renamed package members for `ckeditor5-undo`.
---
> Added re-exports and renamed package members for `ckeditor5-undo`.

- packages/ckeditor5-emoji/src/emojiconfig.ts
- packages/ckeditor5-emoji/src/emojimention.ts
- packages/ckeditor5-emoji/src/emojipicker.ts
- packages/ckeditor5-emoji/src/emojirepository.ts
- packages/ckeditor5-emoji/src/emojiutils.ts
- packages/ckeditor5-emoji/src/index.ts
- packages/ckeditor5-emoji/src/ui/emojigridview.ts
- packages/ckeditor5-emoji/src/ui/emojipickerview.ts
- packages/ckeditor5-emoji/src/ui/emojitoneview.ts
Internal (emoji): Added re-exports and aligned naming in the `ckeditor5-emoji` package.
---
> Added re-exports and aligned naming in the `ckeditor5-emoji` package

- packages/ckeditor5-enter/src/enterobserver.ts
- packages/ckeditor5-enter/src/index.ts
Internal (enter): Added re-exports and aligned naming in the `ckeditor5-enter` package.
---
> Added re-exports and aligned naming in the `ckeditor5-enter` package

- packages/ckeditor5-image/src/imageupload/imageuploadediting.ts
- packages/ckeditor5-image/src/index.ts
Internal (image): Added re-exports and aligned naming in the `ckeditor5-image` package.
---
> Added re-exports and aligned naming in the `ckeditor5-image` package

- packages/ckeditor5-bookmark/src/bookmarkui.ts
- packages/ckeditor5-editor-inline/src/inlineeditoruiview.ts
- packages/ckeditor5-emoji/src/emojipicker.ts
- packages/ckeditor5-image/src/image/ui/utils.ts
- packages/ckeditor5-link/src/linkui.ts
- packages/ckeditor5-mention/src/mentionui.ts
- packages/ckeditor5-table/src/utils/ui/contextualballoon.ts
- packages/ckeditor5-ui/src/badge/badge.ts
- packages/ckeditor5-ui/src/panel/balloon/balloonpanelview.ts
- packages/ckeditor5-ui/src/panel/balloon/contextualballoon.ts
- packages/ckeditor5-utils/src/crc32.ts
- packages/ckeditor5-utils/src/dom/createelement.ts
- packages/ckeditor5-utils/src/dom/global.ts
- packages/ckeditor5-utils/src/dom/position.ts
- packages/ckeditor5-utils/src/dom/rect.ts
- packages/ckeditor5-utils/src/dom/scroll.ts
- packages/ckeditor5-utils/src/index.ts
- packages/ckeditor5-utils/src/observablemixin.ts
Internal: Added re-exports and renamed package members for `ckeditor5-utils`.
---
> Added re-exports and renamed package members for `ckeditor5-utils`.

- packages/ckeditor5-heading/docs/features/title.md
Docs: Pagination + Document Title known issues.
---
> Docs: known issues.

- packages/ckeditor5-minimap/src/index.ts
Internal (minimap): Added re-exports in the `ckeditor5-minimap` package.
---
> Added re-exports in the `ckeditor5-minimap` package

- packages/ckeditor5-ui/src/arialiveannouncer.ts
- packages/ckeditor5-ui/src/button/filedialogbuttonview.ts
- packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
- packages/ckeditor5-ui/src/editableui/inline/inlineeditableuiview.ts
- packages/ckeditor5-ui/src/editorui/poweredby.ts
- packages/ckeditor5-ui/src/index.ts
- packages/ckeditor5-ui/src/template.ts
- packages/ckeditor5-ui/src/toolbar/toolbarview.ts
Internal: Added re-exports and renamed package members for `ckeditor5-ui`.
---
> Added re-exports and renamed package members for `ckeditor5-ui`.

- docs/updating/update-to-46.md
Docs: Create update to 46.x guide placeholder. Closes https://github.com/ckeditor/ckeditor5/issues/18716
---
> Docs: Create update to 46.x guide placeholder.

- CHANGELOG.md
- docs/updating/update-to-45.md
Internal: Changelog for v45.2.1.
---
> Changelog for v45.2.1

- packages/ckeditor5-list/src/augmentation.ts
- packages/ckeditor5-list/src/index.ts
- packages/ckeditor5-list/src/listformatting.ts
- packages/ckeditor5-list/src/listformatting/listitemboldintegration.ts
- packages/ckeditor5-list/tests/list/converters-data-single-block.js
- packages/ckeditor5-list/tests/list/converters-data.js
- packages/ckeditor5-list/tests/list/converters.js
- packages/ckeditor5-list/tests/listformatting.js
- packages/ckeditor5-list/tests/listformatting/listitemboldintegration.js
- packages/ckeditor5-list/theme/listformatting.css
Internal (list): Added upcast and downcast converters for `listItemBold` attribute. Closes #18714.
---
> List item bold upcast and downcast converters

- packages/ckeditor5-font/theme/fontsize.css
- packages/ckeditor5-list/src/listformatting.ts
- packages/ckeditor5-list/src/listformatting/listitemboldintegration.ts
- packages/ckeditor5-list/src/listformatting/listitemfontcolorintegration.ts
- packages/ckeditor5-list/src/listformatting/listitemfontfamilyintegration.ts
- packages/ckeditor5-list/src/listformatting/listitemfontsizeintegration.ts
- packages/ckeditor5-list/src/listformatting/listitemitalicintegration.ts
- packages/ckeditor5-list/tests/list/converters-data-single-block.js
- packages/ckeditor5-list/tests/list/converters-data.js
- packages/ckeditor5-list/tests/list/converters.js
- packages/ckeditor5-list/tests/listformatting.js
- packages/ckeditor5-list/tests/listformatting/listitemboldintegration.js
- packages/ckeditor5-list/tests/listformatting/listitemfontcolorintegration.js
- packages/ckeditor5-list/tests/listformatting/listitemfontfamilyintegration.js
- packages/ckeditor5-list/tests/listformatting/listitemfontsizeintegration.js
- packages/ckeditor5-list/tests/listformatting/listitemitalicintegration.js
- packages/ckeditor5-list/theme/listformatting.css
Internal (list): List markers styled with classes with custom inline CSS property. Closes #18763.
---
> List marker styling

- docs/updating/update-to-46.md
Docs: expanding the Update to 46.x guide.
---
> Docs: expanding the Update to 46.x guide.

- docs/umberto.json
- docs/updating/nim-migration/migrating-exports.md
- packages/ckeditor5-engine/src/index.ts
- packages/ckeditor5-engine/src/view/domconverter.ts
- packages/ckeditor5-html-support/src/schemadefinitions.ts
- packages/ckeditor5-image/src/imagestyle/utils.ts
- packages/ckeditor5-image/src/imageupload/imageuploadediting.ts
- packages/ckeditor5-link/src/index.ts
- packages/ckeditor5-link/src/linkcommand.ts
- packages/ckeditor5-link/src/linkediting.ts
- packages/ckeditor5-link/src/utils.ts
- packages/ckeditor5-link/src/utils/automaticdecorators.ts
- packages/ckeditor5-link/tests/linkcommand.js
- packages/ckeditor5-link/tests/utils/automaticdecorators.js
- packages/ckeditor5-list/src/index.ts
- packages/ckeditor5-list/src/list/converters.ts
- packages/ckeditor5-list/src/list/listediting.ts
- packages/ckeditor5-media-embed/src/converters.ts
- packages/ckeditor5-table/src/utils/ui/contextualballoon.ts
- packages/ckeditor5-watchdog/src/index.ts
- packages/ckeditor5-watchdog/src/watchdog.ts
- scripts/ci/exports/policy/naming.mjs
- scripts/ci/validate-module-re-exports.mjs
*A brief summary of what this PR changes.*
---
* See #18583
* Closes #18786
---
> Added naming rule to the export validator.

- docs/features/feature-digest.md
Docs: updating features digest with line the height feature. 
---
* Closes #000
---
> Docs: updating features digest.

- packages/ckeditor5-list/ckeditor5-metadata.json
Internal (list): Updates list metadata after introducing list item marker formatting. Closes #18774.
---
> Update list metadata.

- .changelog/20250709161613_ck_18831.md
- docs/updating/update-to-46.md
- packages/ckeditor5-list/theme/listformatting.css
Fix the vertical spacing of a single paragraph in the list item with a nested list.
---
* Closes #18831
---
> Fix the list styling.

- packages/ckeditor5-ckbox/src/augmentation.ts
- packages/ckeditor5-core/src/editor/editor.ts
- packages/ckeditor5-utils/src/translation-service.ts
- packages/ckeditor5-utils/src/version.ts
Internal: Fix minor ESLint warnings.
> Fix minor ESLint warnings.

- .circleci/config.yml
While the proposed changes in #18862 can handle API triggers and commits, they fail for CRON (scheduled) tasks.
---
* See https://github.com/cksource/ckeditor5-internal/issues/4073.
---
> Revert: "CircleCI - added a filtering branch for the `push` trigger"

- docs/features/cloud-services-overview.md
Docs: updating CS info.
---
* Closes #000
---
> Docs: updating CS info.

- CHANGELOG.md
Updated release date in changelog.
---
* Closes #000
---
> Updated release date in changelog

- docs/_snippets/getting-started/unlock-feature.html
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
Docs: changing callout wording.
---
* Closes https://github.com/ckeditor/ckeditor5-commercial/issues/8065
---
*Merge with https://github.com/ckeditor/ckeditor5-commercial/pull/8156*
> Docs: changing callout wording.

- docs/updating/update-to-46.md
Bring the Update to 46.x guide up to date with current releases.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/18980
---
> Docs: update to 46.x. 

- scripts/release/utils/getchangelogoptions.mjs
Filter issue links to private repositories in the generated changelog.
---
* See https://github.com/ckeditor/ckeditor5/issues/18936.
---
This PR requires https://github.com/ckeditor/ckeditor5-dev/pull/1196.
> Filter issue links to private repositories in the generated changelog

- packages/ckeditor5-watchdog/tests/actionsrecorder.js
- packages/ckeditor5-watchdog/tests/manual/actionsrecorder-continious.js
- packages/ckeditor5-watchdog/tests/manual/actionsrecorder.js
Fixes imports in tests introduced in https://github.com/ckeditor/ckeditor5/pull/18923.
---
---
> Fixed imports in tests.

- packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.html
- packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.js
- packages/ckeditor5-html-embed/docs/features/html-embed.md
Docs: HMTL embed updates.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/19027
---
> Docs: HMTL embed updates.

- packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.html
- packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.js
Docs: removing content.
---
* Closes #000
---
> Docs: removing content.

- scripts/release/switchlatestnpm.mjs
This PR aims to improve the `release:switch-latest-npm` script by reassigning the `@latest` npm tag to the latest version when we release a non-latest major version.
---
* See #19048.
---
When releasing `v45.2.1`:
```
node scripts/release/switchlatestnpm.mjs
Assigning the `@latest` npm tag for v45.2.1.
Restoring the `@latest` npm tag for v46.0.2.
```
When releasing `v46.0.3`:
```
node scripts/release/switchlatestnpm.mjs
Assigning the `@latest` npm tag for v46.0.3.
The latest published packages and the current release follow the same major version.
```
> Mark as `latest` the latest release when releasing a non-latest version (`#release-v45`)

- scripts/release/switchlatestnpm.mjs
This PR aims to improve the `release:switch-latest-npm` script by reassigning the `@latest` npm tag to the latest version when we release a non-latest major version.
---
* See #19048.
* Merge with: https://github.com/ckeditor/ckeditor5-commercial/pull/8240.
---
When releasing `v45.2.1`:
```
node scripts/release/switchlatestnpm.mjs
Assigning the `@latest` npm tag for v45.2.1.
Restoring the `@latest` npm tag for v46.0.2.
```
When releasing `v46.0.3`:
```
node scripts/release/switchlatestnpm.mjs
Assigning the `@latest` npm tag for v46.0.3.
The latest published packages and the current release follow the same major version.
```
> Mark as `latest` the latest release when releasing a non-latest version (`#release`)

- .changelog/20250912202914_ck_19024.md
- packages/ckeditor5-link/src/linkimageediting.ts
- packages/ckeditor5-link/tests/linkimageediting.js
Fixed downcast of manual decorators of links on block images.
---
* Closes #19024
---
> Fixed downcast of manual decorators of links on block images.

- docs/framework/contributing/development-environment.md
- docs/umberto.json
- docs/updating/update-to-46.md
Docs: update to 46.1.1 guide.
---
* Closes https://github.com/ckeditor/ckeditor5-commercial/issues/8347
---
> Docs: update to 46.1.1 guide.

- .changelog/20250923180810_feat_nextgenai.md
- .changelog/20250923181348_feat_nextgenai.md
- .changelog/20250923182011_feat_nextgenai.md
Updated changelogs related to the AI project
> Updated changelogs related to the AI project

- docs/getting-started/licensing/license-and-legal.md
Docs: update list.
---
* Closes #000
---
> Docs: update list.

- pnpm-lock.yaml
> Update the `pnpm-lock.yaml` file

- pnpm-lock.yaml
> Internal: Update lockfile.
