tests/ckeditor/basepath.js

Fixes #15.
PS. Because of #14 I couldn't run tests, so I haven't checked if they pass :D.

t/15: One it() should contain only one test case

---

ckeditor.js
src/ckeditor-dev.js
tests/ckeditor/ckeditor.js

Added CKEDITOR.isDebug property.

---

dev/tasks/dev/tasks.js
dev/tasks/dev/tasks/install.js
dev/tasks/dev/tasks/update.js
dev/tasks/dev/utils/git.js
dev/tasks/dev/utils/tools.js
dev/tests/dev/git.js
dev/tests/dev/install.js
dev/tests/dev/tools.js
dev/tests/dev/update.js
package.json

This PR contains changes implemented in `gulp update` task according to #93. 
It also adds some changes to `gulp install` task as it is now used in updating when some of the dependencies are not cloned inside workspace directory. Install task is not uninstalling dependencies before cloning them - it is done by modified `tools.linkDirectories` method which now is able to unlink or remove destination directory. This should also resolve #108.

Update development task changes.

---

package.json
tests/_utils-tests/utils.js
tests/_utils/utils.js

Related to https://github.com/ckeditor/ckeditor5-ui-default/issues/12.

t/ckeditor5-ui-default/12: Implement dropdown component

---

dev/tasks/dev/tasks/create-package.js
dev/tasks/dev/utils/git.js
dev/tasks/dev/utils/inquiries.js
dev/tests/dev/create-package.js
dev/tests/dev/git.js

Fixes: #89 
During `gulp create-package`, remote was not created. Now, after init a repository, remote will be added and `git push` shouldn't throw any errors.

Adds remote into created package.

---

dev/tasks/exec/functions/sh.js

Resolves: https://github.com/ckeditor/ckeditor5/issues/235
Example of use:
gulp exec --task sh --cmd "sed 's/find/replace' file.js"

Added task allowing for custom shell commands

---

package.json

Fixes: https://github.com/ckeditor/ckeditor5-typing/issues/17
This PR can be merged after https://github.com/ckeditor/ckeditor5-typing/pull/24

Removed ckeditor5-delete from dependencies.

---

dev/tasks/build/utils.js

Resolves: https://github.com/ckeditor/ckeditor5/issues/191
I went with longer names. They are harder to confuse with built-in methods:
`filter` -> `gulpFilter`
`pipe` -> `multipipe`

Removed duplicated requires

---

dev/tasks/test/tasks.js
dev/tests/test/tasks.js

Fixes https://github.com/ckeditor/ckeditor5/issues/284.
Changed `ckeditor5-dev-utils` submodule name from `build` to `stream`.
**Please close this PR only after following PRs:**
https://github.com/ckeditor/ckeditor5-dev-utils/pull/13
https://github.com/ckeditor/ckeditor5-dev-builder/pull/7

Updated in-node tests with new `ckeditor5-dev-utils`

---

.gitignore
bender.js
build/README.md
gulpfile.js

Creates `build/` directory structure described in #226.
This PR should be closed with:
- https://github.com/ckeditor/ckeditor5-dev-builder/pull/14 - changes in builder configuration
- https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/pull/17 - changes in bundler configuration

Configure bundling and building paths

---

dev/bender/plugins/ckeditor5/static/extensions.js

Resolves: https://github.com/ckeditor/ckeditor5/issues/300.

Added expect( fn ).to.throwCKEditorError() extension to ChaiJS

---

.gitignore
gulpfile.js
package.json

Fixes: #363.
Requires: https://github.com/ckeditor/ckeditor5-dev-tests/pull/28
Also requires changes in **all manual tests**. I prepared shell scripts which will do it.
1. Paste the files in `path-to/ckeditor5/.helpers/`
* `change-css-paths.js` - fixes a path to a stylesheet in HTML files:
```js
#!/usr/bin/env node
/**
* @license Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
* For licensing, see LICENSE.md.
*/
'use strict';
const fs = require( 'fs' );
const path = require( 'path' );
const glob = require( 'glob' );
const testsPath = path.join( process.cwd(), 'tests', '**', 'manual' );
for ( const filePath of glob.sync( path.join( testsPath, '**', '*.html' ) ) ) {
const fileContent = fs.readFileSync( filePath, 'utf-8' )
.replace(
'<link rel="stylesheet" …
```

Introduced task for building and testing manual tests.

---

gulpfile.js
package.json

Fixes #381. Requires: https://github.com/ckeditor/ckeditor5-dev-docs/pull/18.
I was only able to remove editor for samples building, because themes are necessary for documentation building.

Remove unnecessary tasks

---

.gitignore
package.json

Internal: Use a more standard `"directory/"` notation in `.gitignore`. Closes #456.
---
- Requires https://github.com/ckeditor/ckeditor5-dev/pull/225.
- On every repo I've just pushed a branch `t/ckeditor5/456` which contain a new `.gitignore` file.

T/456: Use a more standard directory/ notation in .gitignore.

---

docs/builds/guides/migrate.md

Aligned docs after ranaming ContextualToolbar to BallonToolbar.
---
Other: Rename `ContextualToolbar` to `BalloonToolbar`. Closes #ckeditor/ckeditor5/550.
Updated repositories that uses above mentioned toolbar are:
* https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5/550
* https://github.com/ckeditor/ckeditor5-editor-balloon/tree/t/ckeditor5/550
* https://github.com/ckeditor/ckeditor5-image/tree/t/ckeditor5/550
* https://github.com/ckeditor/ckeditor5-ui/tree/t/ckeditor5/550
Proposed merge message for those branches:
```
Aligned code after ranaming ContextualToolbar to BallonToolbar.
```
but for: https://github.com/ckeditor/ckeditor5-ui/tree/t/ckeditor5/550:
```
Other: Rename `ContextualToolbar` to `BalloonToolbar`.  Closes ckeditor/ckeditor5#550.
BREAKING CHANGE: Renamed …
```

Renamed `contextual/contextualtoolbar~ContextualToolbar` to `balloon/balloontoolbar~BalloonToolbar`.

---

docs/framework/guides/architecture/ui-library.md

Docs: Introduce dropdowns framework guide in architecture/ui-library guide.
---
* This probably got forgot during merging dropdowns API refactoring.

Add missing dropdowns docs.

---

docs/builds/guides/integration/advanced-setup.md
docs/framework/guides/quick-start.md
scripts/docs/snippetadapter.js

It's hard to decide as both are OK:
Docs: Update advanced setup PostCSS files RegExp in webpack example.
Other: Unify `getPostCssConfig()` from @ckeditor/ckeditor5-dev-utils package. Closes #724.
---
* The builds needs and update:
- https://github.com/ckeditor/ckeditor5-build-balloon/tree/t/ckeditor5/724
- https://github.com/ckeditor/ckeditor5-build-classic/tree/t/ckeditor5/724
- https://github.com/ckeditor/ckeditor5-build-inline/tree/t/ckeditor5/724
Proposed merge message:
```
Other: Unify the `getPostCssConfig()` import from `@ckeditor/ckeditor5-dev-utils` package. See ckeditor/ckeditor5#724.
```

T/724: Review PostCSS webpack integration.

---

docs/_snippets/examples/document-editor.html

Docs: Fix nested editable styles in document editor sample. Closes #940.
---
* All editables had styles that should go only for the main document editable.
Also similar bug in sample of decoupled document build: https://github.com/ckeditor/ckeditor5-build-decoupled-document/pull/9.

Docs: Fix nested editable styles in document editor sample.

---

docs/framework/guides/contributing/development-environment.md
scripts/docs/build-docs.js

Internal: Cleaned up how and which params are passed to Umberto.
Changes in `npm run docs`:
* Umberto introduced the `--watch` mode so you can now specify this param to `npm run docs` too.
* `--dev` was removed – docs are by default built in this mode. You can still pass `--production` which enables this mode in the snippets adapter and Umberto itself.
* The `skipApi` option of Umberto that appeared many months ago allowed us to remove the code which cleans the old `builds/docs/output.json` file.

Cleaned up how and which params are passed to Umberto

---

docs/framework/guides/architecture/ui-library.md

Docs: Extended the UI library guide with a section about customizing dropdown icons and labels. Closes #1270.

t/1270: Extended the UI library guide with a section about customizing dropdown icons and labels.

---

docs/builds/guides/frameworks/angular.md

Docs: Removed section about `allowJs` option from the angular integration docs. Closes #000.
---

Remove section about `allowJs` option from the angular integration docs

---

README.md

Internal: Updated ckeditor5 screenshot in README.md. Closes #1311.
---
Screenshots in the builds repo (classic, inline, decoupled, balloon) are updated. 
To keep proper naming (unnecessary spaces in the image name and typo), we will use the same image as `ckeditor5-build-classic` repository.

README.md: updated ckeditor5 screenshot. [skip ci]

---

docs/assets/styles.css

Docs: Content margin should not be overridden for mobile devices. Closes #1350.
---
Side margin should be inherited (umberto default 1em for RWD).

Docs: Reduced content margin for mobile devices [skip ci].

---

docs/api/index.md
docs/assets/styles.css
docs/builds/index.md
docs/examples/index.md
docs/features/index.md
docs/framework/index.md

Docs: The navigation hint in the Examples index should respond to the type of the layout (desktop vs. mobile). Closes #1349.

t/1349: The navigation hint in the Examples index should respond to the type of the layout (desktop vs. mobile)

---

docs/builds/guides/faq.md
docs/builds/guides/migrate.md
docs/umberto.json

Docs: Configured a redirect in the `umberto.json` file to help users navigate straight to the CKFinder documentation after it was moved from ckeditor5-adapter-ckfinder to ckeditor5-ckfinder. Fixed documentation links in the guides (see ckeditor/ckeditor5-ckfinder#7).

t/ckeditor5-ckfinder/7: Configured a redirect after the migration of CKFinder documentation

---

docs/framework/guides/architecture/ui-library.md

Docs: Use class as class-controlling property name in ui guide.
---
* As an outcome of ckeditor/ckeditor5-ui#450.

Use class as class-controlling property name in ui guide.

---

docs/builds/guides/frameworks/vuejs.md
package.json

Other: Update raw-loader dependency. Closes #1420.
---
* AFAICS the `raw-loader`@`1.0.0` is safe to use with CKEditor 5 setup (tested: karma tests, manual tests, builds)
* The Vue guide was either outdated or wrong abut adding rules for `.svg` files. I've udpated the guide which fixes errors like ckeditor/ckeditor5-vue#16
* PR with changes in `ckeditor5-dev`: https://github.com/ckeditor/ckeditor5-dev/pull/462. (dep update)
* Updated dependencies in builds:
* https://github.com/ckeditor/ckeditor5-build-inline/pull/13
* https://github.com/ckeditor/ckeditor5-build-classic/pull/59
* https://github.com/ckeditor/ckeditor5-build-decoupled-document/pull/17
* https://github.com/ckeditor/ckeditor5-build-balloon/pull/22

T/1420: Review SVG raw-loader usage

---

docs/builds/guides/frameworks/overview.md

Docs: Removed obsolete Bootstrap override of `.ck-button`. Closes #1391 .
---
I've updated codepen demo too - https://codepen.io/ckeditor/pen/vzvgOe.

[Docs] Removed obsolete Bootstrap CSS fix.

---

docs/builds/guides/frameworks/vuejs.md

Docs: Added the Document editor section in the Vue.js integration guide. Closes ckeditor/ckeditor5-vue#6.

t/ckeditor5-vue/6: Added the Document editor section in the Vue.js integration guide.

---

docs/builds/guides/frameworks/react.md

Docs: Removed warning about CRA@2. See https://github.com/ckeditor/ckeditor5-react/issues/40#issuecomment-456368847.

Removed warning about CRA@2

---

docs/features/placeholder.md

Docs: Editor placeholder should be created from the "placeholder" attribute only when the source element is `<textarea>`. Closes #1517.
---
Requires changes in other PRs:
* https://github.com/ckeditor/ckeditor5-core/pull/163
* https://github.com/ckeditor/ckeditor5-editor-classic/pull/84
* https://github.com/ckeditor/ckeditor5-editor-decoupled/pull/29
* https://github.com/ckeditor/ckeditor5-editor-balloon/pull/30
* https://github.com/ckeditor/ckeditor5-editor-inline/pull/49

t/1517: Editor placeholder should be created from the "placeholder" attribute only when the source element is `<textarea>`.

---

docs/_snippets/features/placeholder-custom.js
docs/_snippets/features/placeholder.js
docs/features/placeholder.md

Docs: Fixed `CKEDITOR_VERSION` collision error in the editor placeholder guide. Closes #1542.

t/1542: Fixed `CKEDITOR_VERSION` collision error in the editor placeholder guide

---

docs/assets/snippet-styles.css

Docs: Put a border around balloon* editor content in examples to separate it from the example text. Closes #1545.

t/1545: Docs: Put a border around balloon* editor content in examples to separate it from the example text.

---

docs/builds/guides/frameworks/angular.md

Docs: Added section about setting the placeholder to the angular guide. Closes ckeditor/ckeditor5-angular#40.
---
* Fixed code samples

Add section about setting the placeholder to the angular guide

---

docs/framework/guides/architecture/core-editor-architecture.md

Docs: Remove obsolete part from documentation. Closes #1635.

Docs: Remove obsolete part from documentation.

---

docs/builds/guides/frameworks/vuejs.md

There is a missing comma after the separator
---

Fix missing comma in vuejs editorConfig documentation

---

scripts/docs/snippetadapter.js

Internal: Snippet Adapter does not require a full path to match snippets that should be built. Closes #1725.

Snippet Adapter does not require a full path to match snippets that should be built

---

scripts/docs/snippetadapter.js

Internal: Removed an extra space caused by snippet's empty div on top of the feature overview.
---

[Docs] Remove an extra space caused by snippet's empty div on top of the feature overview

---

docs/builds/guides/migrate.md

Docs: Migration table should display `<code>` inside properly. Closes #1718.
---

[Docs] Migration table should display `<code>` inside properly

---

README.md
docs/builds/guides/support/browser-compatibility.md
docs/framework/guides/contributing/testing-environment.md

Docs: Removed BrowserStack from the repository. See #1742.
---
After merging https://github.com/ckeditor/ckeditor5-dev/pull/524 and this PR, we need to merge `t/ckeditor5/1742` branches in other repositories:
```bash
mgit exec "git co master; git fetch;  git co t/ckeditor5/1742; git co -; git merge t/ckeditor5/1742 --no-ff -m 'Docs: Removed BrowserStack from this repository. See ckeditor/ckeditor5#1742.'" 
```

Removed BrowserStack from the repository

---

docs/builds/guides/frameworks/vuejs.md

Goes with https://github.com/ckeditor/ckeditor5-vue/issues/59
Fixes config to play nicer with Vue.

Updated documentation so only CKEditor's CSS is processed

---

docs/umberto.json

Other: Added redirects for docs for removed collaboration pages.

Added redirects for docs for removed collaboration pages

---

docs/framework/guides/quick-start.md

fix the loader limit expression, some theme files are in **deep directories** like `.../theme/dirA/dirB/dirC/file.css`, e.g.: `ckeditor5-ui/theme/components/toolbar/toolbar.css`

doc: fix the framework guide

---

docs/builds/guides/frameworks/react.md

Docs: Fix React integration guide. Closes ckeditor/ckeditor5-react#102.
---
The event callbacks were missing event property and were wrongly documented.
I've re-ordered the properties entry so now it renders like this:

Documented missing component properties in the react integration guide.

---

docs/framework/guides/development-tools.md

Docs: Typo in attach multiple code example

Typo in attach multiple code example

---

docs/builds/guides/integration/advanced-setup.md

Docs: Added docs for building from source in Webpack Encore
---
Hi, today I've had some issues while trying to make [Webpack Encore](https://github.com/symfony/webpack-encore) able to build CKEditor5, but I've finally make it works and I think it will be helpful for other people.
Thanks

doc(advanced-setup): add section for Webpack Encore

---

docs/_snippets/examples/document-editor.html
docs/assets/styles.css
docs/examples/builds/balloon-block-editor.md
docs/examples/builds/balloon-editor.md
docs/examples/builds/classic-editor.md
docs/examples/builds/custom-build.md
docs/examples/builds/document-editor.md
docs/examples/builds/inline-editor.md

Docs: Improved RWD of demos in the Examples section. Closes #5598.
---
1. Enlarged container width of document editor demo
2. Fixed document editor demo for mobiles because ATM it looks like this:
Before:

[Docs] Improved RWD of demos in Examples section

---

docs/builds/guides/integration/content-styles.md
scripts/docs/build-content-styles.js
scripts/docs/content-styles/list-content-styles.js

Internal: Content styles script does not print duplicated styles and handles `at-rule` selectors. Closes #5605. Closes #5604.

Improvements for content styles script

---

yarn.lock

Internal: Updated MathType version. Closes #5613.

Bumped MathType version in the yarn.lock file

---

docs/builds/guides/support/reporting-issues.md

Docs: Fixed a reference to the issue tracker in the docs. Closes #5673.

Fixed a reference to the issue tracker in the docs

---

package.json
scripts/docs/snippetadapter.js
yarn.lock

Internal: Removed a workaround for missing MathType icons. Closes ckeditor/ckeditor5-dev#572.

Removed a workaround for missing MathType icons

---

docs/builds/guides/integration/advanced-setup.md
docs/framework/guides/quick-start.md
package.json
scripts/docs/snippetadapter.js
yarn.lock

Docs: Replaced UglifyJS with Terser. See #1353.
---
More PRs below the mark – https://github.com/ckeditor/ckeditor5/issues/1353#event-2683863323

Replaced UglifyJS with Terser

---

scripts/release/update-utils-version.js

Internal: Fixed a way how to get a new version in the `postchangelog` script. The previous script read the version from `package.json` which is wrong because it will be update later. The version must be taken from `CHANGELOG.md`.

A new version should be taken from CHANGELOG.md instead of package.json

---

README.md
docs/builds/guides/integration/basic-api.md
docs/builds/guides/quick-start.md

Docs: Remove mentions of a `<textarea>` element from guides.. Closes #1806.
---
* I've scanned the whole code base for `<textarea` occurences and only those in this PR might lead to a confusing behavior (#1591)
* the other mentions in the `.md` files were for the usage of CKEditor on forms (which uses `<textarea>` , placeholder usage or were just samples printing out contents of the editor (React sample)

Remove mentions of a <textarea> element from guides.

---

docs/_snippets/framework/tutorials/using-react-in-widget.js
docs/framework/guides/tutorials/using-react-in-a-widget.md

Internal: Fixed a runtime error in the "Using a React component in a block widget" guide. Closes #5850.
---
Decided to put it as "Internal" as it doesn't make sense to put it into changelog, since broken docs were not published in any release.

Fixed a runtime error in the "Using a React component in a block widget" guide

---

docs/framework/guides/tutorials/using-react-in-a-widget.md

Docs: Fixed the way config is accessed in the "Using a React component in a block widget" guide. Closes #5900.

Docs: Fixed the way config is accessed in the "Using a React component in a block widget" guide.

---

tests/manual/wproofreader.html

Test: Remove "unsafe-eval" directive from wproofreader manual test template. Closes #5885 .

i/5885: Remove "unsafe-eval" directive from wproofreader manual test template

---

scripts/release/changelog.js

Internal: Passed a response from `devEnv.generateChangelogForSubRepositories()` task to `devEnv.generateSummaryChangelog()`.
---
Requires https://github.com/ckeditor/ckeditor5-dev/pull/573.

Improved the changelog generator

---

docs/builds/guides/migrate.md

Docs: Fix link to CKEditor 4 `image2_maxSize` config option. Closes #6023.

Fix link to CKEditor 4 image2_maxSize config option

---

docs/framework/guides/custom-editor-creator.md

Docs: Fix misleading references to inline toolbars and decoupled editor in multi-root editor. Closes #1666.

Fix misleading references to inline toolbars and decoupled editor

---

docs/builds/guides/frameworks/react.md

Docs: Added `onError` parameter to list of supported properties. Closes #6050.

Added onError parameter to list of supported properties

---

docs/builds/guides/development/custom-builds.md
docs/builds/guides/integration/installation.md
docs/builds/guides/integration/installing-plugins.md

Docs: Added docs linking to the online builder. Part of #1174.
---
I added the link to the online builder in the `Installation` section. However, I'm not sure if it's the best place to add it. Or if there are better places.
@wwalc suggested the [Custom builds guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html), but to me, the online builder doesn't fit the *development* section of this guide and the guide itself focusing mostly on forking GH's `ckeditor5-build-*` repos.
cc @Reinmar @wwalc

Add docs linking to the online builder

---

tests/manual/performance/_utils/large.txt
tests/manual/performance/_utils/medium.txt
tests/manual/performance/_utils/small.txt
tests/manual/performance/setdata.html
tests/manual/performance/setdata.js
tests/manual/performance/setdata.md

Internal: Added editor setData manual performance test. Part of #5880.
---
In this micro PR I added a manual test for calling setData on the editor.
Fixtures (so the data that we consider small/medium/large) are extracted as separate files to keep it DRY. Fun fact, it couldn't be `.html` file as it would not be served by our Karma/Webpack config so I went with `.txt`. Fixtures contain a dummy placeholder as setting it with proper content will be done in another PR.

Added editor setData manual performance test

---

tests/_utils/utils.js
tests/manual/performance/editorinit.html
tests/manual/performance/editorinit.js
tests/manual/performance/editorinit.md
tests/manual/performance/setdata.js

Tests: Added editor setData manual performance test. Part of #5880.
---
File `utils.js` was placed above of manual test directory, as otherwise it was parsed as a manual test and could not be included at all to the test.

Added editor initialization manual performance test

---

docs/_snippets/framework/tutorials/block-widget.js

Fix: Focus the editor before executing toolbar buttons' command. Closes ckeditor/ckeditor5#353.

i/353: Focus the editor before executing a command

---

scripts/svgo.config.json

Internal: The SVG icons compressed by the clean-up-svg-icons task (svgo) should be editable in graphical editors. Closes #6334.
---
After merging, execute `yarn clean-up-svg-icons packages/**/theme/icons`. 
Then
`mrgit commit -m "Internal: The SVG icons compressed by the clean-up-svg-icons task (svgo) should be editable in graphical editors (see ckeditor/ckeditor5#6334)"`
and push in all repos.

i/6334: The SVG icons compressed by the clean-up-svg-icons task (svgo) should be editable in graphical editors

---

docs/assets/snippet-styles.css
docs/assets/snippet.js

Other: Added a warning notification in demo pages when user tries to paste content from MS Word or Google Docs. Closes #6324.

i/6324: Add a warning notification in demo pages when user tries to paste a content from MS Word or Google Docs

---

package.json
yarn.lock

Internal: Updated `MathType` dependency.
---
7.19.0 is now stable, so we no longer need to use beta release 🎉

MathType dependency bump

---

docs/builds/guides/development/plugins.md

Docs: Updated main plugins guide by adding links to _creating-simple-plugin_ tutorial. Closes #6463.

Docs: Added simple plugin tutorial link to main plugins guide.

---

docs/framework/guides/architecture/ui-library.md
docs/framework/guides/custom-editor-creator.md

Docs: Mentioned the "Deep dive into focus tracking" guide in the "UI library" guide (see ckeditor/ckeditor5#6087).
---
Part of https://github.com/ckeditor/ckeditor5-ui/pull/552.

i/6087: Mentioned the "Deep dive into focus tracking" guide in the "UI library" guide

---

docs/assets/snippet-styles.css

Internal: Fixed stylelint errors related to colors and indentation (see ckeditor/ckeditor5-dev#611).

ckeditor5-dev/i/611: Fixed stylelint errors related to colors and indentation

---

packages/ckeditor5-table/src/tablenavigation.js
packages/ckeditor5-table/tests/tablenavigation.js

Fix (table): Table navigation using keyboard should not alter the native Shift+Arrow behavior inside table cells. Closes ckeditor/ckeditor5#6641.
---

I/6641: Fixed shift + arrow key handling inside table cell.

---

packages/ckeditor5-media-embed/src/mediaembedui.js
packages/ckeditor5-media-embed/tests/mediaembedui.js

Fix (media-embed): Create MediaFormView for each dropdown instance separately. Closes ckeditor/ckeditor5#6333.
MINOR BREAKING CHANGE: `mediaembedui~MediaEmbedUI#form` was removed from the API
---
Moved from https://github.com/ckeditor/ckeditor5-media-embed/pull/98

I/6333: Create MediaFormView for each dropdown instance separately

---

packages/ckeditor-cloud-services-core/tests/token/token.js
packages/ckeditor5-table/src/tablenavigation.js
packages/ckeditor5-table/src/tableselection.js
packages/ckeditor5-table/tests/commands/insertcolumncommand.js
packages/ckeditor5-table/tests/commands/insertrowcommand.js
packages/ckeditor5-table/tests/commands/mergecellscommand.js
packages/ckeditor5-table/tests/commands/removecolumncommand.js
packages/ckeditor5-table/tests/commands/removerowcommand.js
packages/ckeditor5-table/tests/commands/selectcolumncommand.js
packages/ckeditor5-table/tests/commands/selectrowcommand.js
packages/ckeditor5-table/tests/commands/setheadercolumncommand.js
packages/ckeditor5-table/tests/commands/setheaderrowcommand.js
packages/ckeditor5-table/tests/commands/splitcellcommand.js
packages/ckeditor5-table/tests/tableclipboard.js
packages/ckeditor5-table/tests/tablenavigation.js
packages/ckeditor5-table/tests/tableselection-integration.js
packages/ckeditor5-table/tests/tableselection.js
packages/ckeditor5-table/tests/utils.js

Feature (table): Table cells selection with keyboard. Closes #6115. Closes #3203.
---

I/6115: Table cells selection with keyboard.

---

packages/ckeditor5-table/tests/_utils-tests/table-ascii-art.js
packages/ckeditor5-table/tests/_utils/utils.js
packages/ckeditor5-table/tests/manual/tablemocking.html
packages/ckeditor5-table/tests/manual/tablemocking.js

Internal: Updated table mocking tools to preserve cells' content. Closes #6749.
---

#6749: Updated table mocking tools to preserve cells' content.

---

packages/ckeditor5-table/src/commands/insertcolumncommand.js
packages/ckeditor5-table/src/commands/insertrowcommand.js
packages/ckeditor5-table/tests/commands/insertcolumncommand.js
packages/ckeditor5-table/tests/commands/insertrowcommand.js

Fix (table): Fixed insert table row/column commands when a widget is selected inside the table cell. Closes #6607.
---

Fixed insert table row/column commands when a widget is selected inside the table cell

---

packages/ckeditor5-table/src/ui/colorinputview.js
packages/ckeditor5-table/tests/ui/colorinputview.js
packages/ckeditor5-ui/src/colorgrid/colorgridview.js
packages/ckeditor5-ui/src/inputtext/inputtextview.js

Other (table): Display a human readable color label in the text input field. Closes #6241.
---
This also adds docs, for ColorGridView@execute

#6241 Display a defined color label in the text input field.

---

docs/framework/guides/contributing/testing-environment.md

As suggested at https://github.com/ckeditor/ckeditor5-dev/pull/626#issuecomment-620736291
Docs: Document how to use a custom port for the manual test server.
---
This PR requires https://github.com/ckeditor/ckeditor5-dev/pull/626

Document how to use a custom port for the manual test server.

---

packages/ckeditor5-table/src/converters/table-cell-refresh-post-fixer.js
packages/ckeditor5-table/tests/converters/table-cell-refresh-post-fixer.js

Fix (table): Fixed triggering of table cell refreshing when multiple elements added in one differ. Closes #6260.
---

#6260: Fixed triggering of table cell refreshing when multiple elements added in one differ

---

packages/ckeditor5-table/src/converters/table-cell-paragraph-post-fixer.js
packages/ckeditor5-table/src/converters/table-cell-refresh-post-fixer.js
packages/ckeditor5-table/src/converters/table-layout-post-fixer.js
packages/ckeditor5-table/src/converters/upcasttable.js
packages/ckeditor5-table/src/tableediting.js
packages/ckeditor5-table/tests/_utils/utils.js
packages/ckeditor5-table/tests/converters/table-layout-post-fixer.js
packages/ckeditor5-table/tests/converters/upcasttable.js

Fix (table): Table layout post-fixer and upcast converters should properly handle empty rows . Closes #3274.
---

#3274: Updated table layout post-fixer and upcast converters to properly fix empty rows.

---

packages/ckeditor5-table/package.json
packages/ckeditor5-table/src/commands/mergecellcommand.js
packages/ckeditor5-table/src/commands/mergecellscommand.js
packages/ckeditor5-table/src/tableutils.js
packages/ckeditor5-table/tests/_utils/utils.js
packages/ckeditor5-table/tests/commands/mergecellcommand.js
packages/ckeditor5-table/tests/commands/mergecellscommand.js
packages/ckeditor5-table/tests/manual/tablemocking.js

Fix (table): Table heading rows should be properly updated after removing rows as a side effect of merging cells. Closes #6667.
---

#6667: Table heading rows should be properly updated after removing rows as a side effect of merging cells

---

packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesui.js
packages/ckeditor5-table/src/tableproperties/tablepropertiesui.js
packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesui.js
packages/ckeditor5-table/tests/tableproperties/tablepropertiesui.js

Fix (table): The table properties button should not be enabled if all cell properties commands are disabled. Closes #6679.
---

#6679: The table properties button should not be enabled if all cell properties commands are disabled

---

packages/ckeditor5-table/src/tableutils.js
packages/ckeditor5-table/tests/tableutils.js

Fix (table): Editor should not crash when removing column next to row-spanned cells. Closes #6789.
---

#6789: Fixed removing column when there are multiple empty rows to remove.

---

docs/framework/guides/contributing/testing-environment.md

Docs: Document how to use a custom port for the automated test server.
---
This PR requires https://github.com/ckeditor/ckeditor5-dev/pull/638

Document how to use a custom port for the automated test server.

---

packages/ckeditor5-font/tests/ui/colorui.js
packages/ckeditor5-table/src/ui/colorinputview.js
packages/ckeditor5-table/tests/ui/colorinputview.js
packages/ckeditor5-ui/src/colorgrid/utils.js

Fix (table): When the state is restored or the user enters color value manually, color input is able to provide matching color label. Closes #6791.
---
I decided to use more complicated `RegExp` instead of just stripping spaces, I hope it will not affect performance. The main reason was to support, (valid) color definitions, like `rgb(25 50 0)` and not to match them with `rgb(255 0 0)`. (this case is covered in tests)
By the way, I discovered that normalization util uses yet another object type - reported at https://github.com/ckeditor/ckeditor5/issues/6790#issuecomment-627412557/. It's a different type, but function docs refer `ColorDefinition` even though it does not match. It hurts my OCD, but I left it as it was, to minimize the set of changes, and leave the decision up to #6790.

#6791: Stop normalizing color values passed to the UI, relax matching criteria for ColorInputView's text input.

---

packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widgettypearound.css

Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))
Internal (theme-lark): The mouse cursor should not change when mouse is over the insert paragraph buttons in widgets. Closes #6826.

#6826: The mouse cursor should not change when mouse is over the insert paragraph buttons in widgets

---

packages/ckeditor5-table/src/commands/setheadercolumncommand.js
packages/ckeditor5-table/src/commands/setheaderrowcommand.js
packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/src/utils.js
packages/ckeditor5-table/tests/commands/setheadercolumncommand.js
packages/ckeditor5-table/tests/commands/setheaderrowcommand.js
packages/ckeditor5-table/tests/tableclipboard-paste.js
packages/ckeditor5-table/tests/utils.js

Internal (table): Handle spanned table cells in pasting scenarios. Closes #6122.
Fix (table): Setting column as header will now split it col-spaned cells. Closes #6658.
---
This PR:
*   Introduces handling cases of spanned cells (both in selected table and pasted table) that have spans that exceeds rectangular selection.
*   Introduces fix to #6658 as the utils used were also created (they mirrors the logic of setting table header rows).
*   Handles a rectangular selection with cells spanned at the last row or column (like here: https://github.com/ckeditor/ckeditor5/pull/6786#issuecomment-627214164)
*   We also assume that pasted table is either valid or near valid. One case of invalid table structure was moved to a followup.

I/6122: Handling spanned table cells in pasting scenarios

---

packages/ckeditor5-utils/src/dom/position.js
packages/ckeditor5-utils/tests/dom/position.js
packages/ckeditor5-widget/src/utils.js
packages/ckeditor5-widget/tests/utils.js

Internal (widget): The widget toolbar should not use the fallback position for long widgets when there is enough space above or below it in the viewport. Closes #7227.
Internal (utils): getOptimalPosition should allow position to return null to be skipped.
---

The widget toolbar should not use the fallback position for long widgets when there is enough space above or below it in the viewport

---

docs/framework/guides/contributing/git-commit-message-convention.md
scripts/release/changelog.js

Internal: Adjusted the changelog generator script to the new API of `ckeditor5-dev-env`.
---
Requires: https://github.com/ckeditor/ckeditor5-dev/pull/640.

Adjusted the changelog script to the new API

---

packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widgettypearound.css
packages/ckeditor5-widget/theme/widgettypearound.css

Internal (theme-lark): Widget type around buttons should show/hide in sync with the outline of the widget. Closes #7251.
---

#7251: Widget type around buttons should show/hide in sync with the outline of the widget

---

packages/ckeditor5-cloud-services/src/cloudservices.js
packages/ckeditor5-cloud-services/tests/cloudservices.js

Fix (cloud-services): Token instance will be destroyed by the `CloudServices` context plugin. Closes #7248 .
---

7248: Destroy token instance if created by CloudServices plugin

---

packages/ckeditor5-code-block/src/codeblockediting.js
packages/ckeditor5-code-block/src/converters.js
packages/ckeditor5-code-block/tests/codeblockediting.js

as suggested by @oleq at https://github.com/ckeditor/ckeditor5/issues/5901#issuecomment-624605013.
Ignore HTML elements inside `<pre><code>`.
Closes: #5901.
Fix (code-block): Stop rendering `&nbsp;` when restoring the state of an empty code block. Closes #5901.
---
There is still an issue with dom to view conversion
https://github.com/ckeditor/ckeditor5/compare/i/5901-code-blocks?expand=1#diff-82a5336a00edfc515fb87b52fc38eafbR892-R901
as you can see, filler element is not cleared on `getData`
From what I have found, `domConverter` https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/domconverter.js#L1027 uses `getDataWithoutFiller` which strips only **`INLINE_FILLER`**. I tried to change [`_processDataFromDomText`](https://github.com/ckeditor/ckeditor5/blob/ …

#5901: Use text nodes content directly instead of stringifying using data processor in code-block

---

packages/ckeditor5-engine/docs/framework/guides/deep-dive/schema.md
packages/ckeditor5-engine/src/model/schema.js

Docs: Improve the docs for "limit elements" and "object elements". Closes #6829.
---
Travis and Umberto complain about invalid links. However, ``{@link #allowIn `allowIn`}`` looks perfectly fine to me. Using full ``{@link module:engine/model/schema~SchemaItemDefinition#allowIn `allowIn`}`` within `@typeDef module:engine/model/schema~SchemaItemDefinition`looks redundant and confusing to me.
https://github.com/ckeditor/ckeditor5/compare/master...i/6829-isLimit-doc#diff-375a78efc71168f3eacd6055760a3389R1021
Should I change them to full ones, or adapt Umberto check to allow such cases?

#6829: Improve docs for isLimit and isObject

---

packages/ckeditor5-engine/src/model/model.js
packages/ckeditor5-highlight/src/highlightcommand.js
packages/ckeditor5-paragraph/src/insertparagraphcommand.js
packages/ckeditor5-paragraph/src/paragraph.js
packages/ckeditor5-paragraph/tests/insertparagraphcommand.js
packages/ckeditor5-paragraph/tests/paragraph.js
packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widget.css
packages/ckeditor5-widget/src/widgettypearound/widgettypearound.js
packages/ckeditor5-widget/tests/manual/type-around.html
packages/ckeditor5-widget/tests/manual/type-around.js
packages/ckeditor5-widget/tests/widgettypearound/widgettypearound.js
packages/ckeditor5-widget/theme/widgettypearound.css

Internal (widget): Integrated the `WidgetTypeAround` plugin with the read–only mode. Closes #6775.
Internal (widget): Integrated the `WidgetTypeAround` plugin with the `RestrictedEditingMode` plugin (see #6775).
Feature (paragraph): Implemented the `InsertParagraphCommand` registered as `'insertParagraph'` in the editor. Closes #6823. Closes #7229.
Docs (engine): Improved `Model#insertContent` API documentation (see #6775).

#6775: Integrated widget type around feature with read–only, restricted editing and track changes

---

packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widgettypearound.css

Internal (theme-lark): Widget type around buttons should not show up when the ancestor is a selected nested editable. Closes #7263.

#7263: Widget type around buttons should not show up when the ancestor is a selected nested editable

---

.travis.yml

Internal (ckeditor5): Fixed CC upload so that it works when CI job is reset. Closes #7244.
---
In a fascinating twist of reverse engineering and guessing I was able to get it working.
Unfortunately providing _Coveralls token_ (suggested in Coveralls error message) didn't fix the problem.
I noticed a very strange thing, that our env `TRAVIS_JOB_ID` is different than the job id in the Travis link… e.g. for https://travis-ci.org/github/ckeditor/ckeditor5/builds/689606488 `TRAVIS_JOB_ID` will be `689606489`.
I wanted to force an unique job id, by making it e.g. a timestamp - but Coveralls backend was complaining that it could not match corresponding Travis build - so it means it has a special handling for Travis. So I checked the source code of `coveralls` npm package, to see how it …

Internal (ckeditor5): Fixed CC upload so that it works when CI job is reset

---

scripts/release/bump-versions.js
scripts/release/publish.js

Internal (ckeditor5): Use the `release` branch for release. See #7271.
---
Requires https://github.com/ckeditor/ckeditor5-dev/pull/643.

Use "release" branch for releasing

---

packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
packages/ckeditor5-upload/src/adapters/simpleuploadadapter.js
packages/ckeditor5-upload/tests/adapters/simpleuploadadapter.js

Allow to enable [XMLHttpRequest.withCredentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) property.
This is needed when working with cross-domain requests (ex: upload from ckeditor on example.com domain to api.example.com sub-domain).

Feature (upload): Added XMLHttpRequest.withCredentials configuration.

---

packages/ckeditor5-engine/src/model/element.js
packages/ckeditor5-engine/src/model/utils/getselectedcontent.js
packages/ckeditor5-engine/src/model/writer.js
packages/ckeditor5-engine/tests/model/writer.js
packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/src/utils/structure.js

Other (engine): Added `Writer#cloneElement()`. Closes #6819.
Internal (table): Replaced `Element._clone()` usages with `Writer#cloneElement()`.
---

#6819: Added Writer#cloneElement()

---

packages/ckeditor5-build-decoupled-document/tests/ckeditor.js
packages/ckeditor5-font/src/fontfamily.js
packages/ckeditor5-font/src/fontfamily/utils.js
packages/ckeditor5-font/tests/fontfamily/fontfamilyediting.js
packages/ckeditor5-font/tests/fontfamily/fontfamilyui.js
packages/ckeditor5-font/tests/fontfamily/utils.js
packages/ckeditor5-font/tests/integration.js
packages/ckeditor5-font/tests/manual/font-family.md

Fix (font): Font Family should be applied correctly (all values of font families) inside the editor when used with `supportAllValues`. Closes #7285.
---

#7285: Using full list of font-family values as a model attribute value.

---

packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/tests/tableclipboard-paste.js

Other (table): Pasting a table into a table is more tolerant for whitespaces around pasted table. Closes #7379.
---

#7379: Trimming pasted content for table to table pasting.

---

packages/ckeditor5-ui/package.json
packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.js
packages/ckeditor5-ui/tests/toolbar/balloon/balloontoolbar.js

Fix (ui): Table properties balloon should be displayed on cell multi-select in Balloon and Balloon Block editors. Closes #6443.
---

#6443: BalloonToolbar should not be displayed for multi cell table selection.

---

packages/ckeditor5-core/tests/_utils-tests/articlepluginset.js
packages/ckeditor5-font/tests/integration.js
packages/ckeditor5-image/tests/imagetoolbar.js
packages/ckeditor5-image/tests/integration.js
packages/ckeditor5-media-embed/tests/mediaembedtoolbar.js
packages/ckeditor5-widget/src/widgettoolbarrepository.js
packages/ckeditor5-widget/tests/widgetresize.js
packages/ckeditor5-widget/tests/widgetresize/resizer.js
packages/ckeditor5-widget/tests/widgettoolbarrepository.js
packages/ckeditor5-widget/tests/widgettypearound/widgettypearound.js

Fix: The widget toolbar won't be shown if an empty collection of items was specified in the editor's configuration. Closes #5857.

Do not show an empty widget toolbar

---

packages/ckeditor5-link/package.json
packages/ckeditor5-link/src/linkcommand.js
packages/ckeditor5-link/src/unlinkcommand.js
packages/ckeditor5-link/tests/linkcommand.js
packages/ckeditor5-link/tests/unlinkcommand.js

Internal: `#value` and `#isEnabled` properties for `LinkCommand` and `UnlinkCommand` work properly with images. Closes #7429.

(Un)Link command state when an image is selected

---

packages/ckeditor5-engine/src/model/model.js
packages/ckeditor5-engine/src/model/utils/deletecontent.js
packages/ckeditor5-engine/tests/model/model.js
packages/ckeditor5-engine/tests/model/utils/deletecontent.js

Internal (engine): Markers should not be considered as a meaningful content in `Model#deleteContent()` context. Closes #7431.
Other (engine): Added `ignoreMarkers` option for `Model#hasContent()`.
---

#7431: Markers should not be considered as a meaningful content in deleteContent context

---

docs/_snippets/features/mathtype.html
docs/assets/snippet-styles.css

Docs: Do not center math equations and chemical formulas. Closes #2080.
---
http://127.0.0.1:8080/build/docs/ckeditor5/12.4.0/features/math-equations.html

[Docs] Do not center math equations and chemical formulas

---

packages/ckeditor5-link/src/linkcommand.js
packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/src/linkui.js
packages/ckeditor5-link/tests/linkcommand.js
packages/ckeditor5-link/tests/linkediting.js
packages/ckeditor5-link/tests/linkui.js
packages/ckeditor5-link/tests/manual/link.md
packages/ckeditor5-mention/tests/mention-integration.js

Other (link): The selection after inserting a link will land after the inserted element. Thanks to that a user will be able to type directly after the link without extending the link element. Closes #1016.
Other (link): After clicking at the beginning or end of the link element, the selection will land before/after the clicked element. Thanks to that a user will be able to typing before or after the link element as normal text without extending the link. See #1016.

Typing around the link element

---

packages/ckeditor5-widget/src/utils.js
packages/ckeditor5-widget/src/widgettypearound/utils.js
packages/ckeditor5-widget/src/widgettypearound/widgettypearound.js
packages/ckeditor5-widget/tests/utils.js
packages/ckeditor5-widget/tests/widgettypearound/utils.js

Internal (widget): The `findOptimalInsertionPosition()` helper should respect the "fake widget caret" to provide the best UX. Closes #7438.

#7438: The findOptimalInsertionPosition() helper should respect the "fake widget caret"

---

packages/ckeditor5-table/src/converters/downcast.js
packages/ckeditor5-table/src/converters/upcasttable.js
packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/src/tableselection.js
packages/ckeditor5-table/src/utils/structure.js
packages/ckeditor5-table/tests/tableclipboard-copy-cut.js
packages/ckeditor5-table/tests/tableclipboard-paste.js
packages/ckeditor5-table/tests/tableselection.js

Fix (table): Copied and pasted table fragment should maintain proper structure while selection could contain rows that don't have any cells anchored in it. Closes #7245.
---

#7245: Added normalization of pasted table.

---

packages/ckeditor5-horizontal-line/theme/horizontalline.css
packages/ckeditor5-theme-lark/theme/ckeditor5-horizontal-line/horizontalline.css

Other: Improved the look of horizontal lines in the editor content. Closes #7418.
---
To pass WCAG AA for non-text object, the color would need to be much darker (around `#949494`) which does not look good IMO. I checked what GitHub makes of it and they don't comply with the standard. WDYT?

#7418: Improved the look of horizontal lines in the editor content

---

packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/tests/tableclipboard-paste.js

Internal (table): Table pasting integration should not affect inserting text node. Closes #7464.
---

#7464: Table pasting integration should not affect inserting text node.

---

packages/ckeditor5-link/package.json
packages/ckeditor5-link/src/linkcommand.js
packages/ckeditor5-link/src/unlinkcommand.js
packages/ckeditor5-link/tests/linkimage-integration.js

Internal: `LinkCommand` and `UnlinkCommand` should read the state properly when the `LinkImage` plugin is disabled. Closes #7465.

(Un)LinkCommand should read the state properly when LinkImage is disabled

---

packages/ckeditor5-table/src/tablekeyboard.js
packages/ckeditor5-table/tests/tablekeyboard.js

Fix (table): Table multi-cell selection should not be possible with the keystrokes when the TableSelection plugin is disabled. Closes #7483.
---

Table multi-cell selection should not be possible with the keystrokes when the TableSelection plugin is disabled

---

packages/ckeditor5-engine/src/view/downcastwriter.js

Added a comment clarifying the use of createEditableElement in the data view / pipeline.
See https://github.com/ckeditor/ckeditor5/issues/7274#issuecomment-645171865 for more information.
Let me know if this should be rephrased or moved somewhere else.
Docs (patch): Add note about createEditableElement in the data view. Closes #7274.
---
Docs change only, no code changes.

Docs (patch): Add note about createEditableElement in the data view.

---

packages/ckeditor5-core/tests/_utils-tests/assertions/attribute.js
packages/ckeditor5-core/tests/_utils/assertions/attribute.js

The initial step for #7513.
Tests (core): Add attribute chai assertion. Closes #7513.
---
I'm not sure whether it should close the #7513 as it lacks a number of assertions mentioned there.
Also, I have not provided a way to identify an object, as suggested at https://github.com/ckeditor/ckeditor5/issues/7513#issuecomment-651055745 as it seems it would require a full map of all object types, wouldn't it?

Add attribute chai assertion.

---

packages/ckeditor5-engine/src/conversion/mapper.js
packages/ckeditor5-engine/tests/conversion/mapper.js
packages/ckeditor5-list/src/todolistconverters.js
packages/ckeditor5-list/src/todolistediting.js
packages/ckeditor5-list/src/utils.js
packages/ckeditor5-list/tests/manual/todo-list.js
packages/ckeditor5-list/tests/todolistediting.js
packages/ckeditor5-list/theme/todolist.css

Fix (list): Editor should not crash on the enter key press inside a to-do list item containing soft-breaks. Closes #5866. Closes #6585.
Fix (list): Links inside a to-do list item should be properly converted to HTML. Closes #5779.
Feature (engine): Changed visibility scope of `Mapper#findPositionIn()` from `private` to `public`.
---

#5866: To-do lists down-casting refactored

---

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/toolbar/toolbar.css

Internal: Added some vertical margin to toolbar separators. Closes #7493.

#7493: Added some vertical margin to toolbar separators

---

docs/_snippets/examples/document-editor.html
docs/_snippets/framework/tutorials/using-react-in-widget.html
docs/assets/snippet-styles.css
packages/ckeditor5-table/docs/_snippets/features/table.html

 Docs (ckeditor5, table): Added `vertical-align: middle` to table cells in all editors in the docs. Closes #7310.

#7310: Added vertical-align: middle to table cells in all editors in the docs

---

packages/ckeditor5-table/src/commands/mergecellcommand.js
packages/ckeditor5-table/src/commands/mergecellscommand.js
packages/ckeditor5-table/src/commands/removerowcommand.js
packages/ckeditor5-table/src/converters/downcast.js
packages/ckeditor5-table/src/converters/table-heading-rows-refresh-post-fixer.js
packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/src/tableediting.js
packages/ckeditor5-table/src/tableutils.js
packages/ckeditor5-table/src/utils/structure.js
packages/ckeditor5-table/tests/commands/mergecellscommand.js
packages/ckeditor5-table/tests/converters/downcast.js
packages/ckeditor5-table/tests/tableutils.js

Fix (table): Table structure should not be changed while removing heading row. Closes #7454.
Fix (table): Merging multiple cells should not crash editor while removing multiple empty rows and columns that appeared after merge. 
---

#7454: Down-casting whole table on headingRows attribute change

---

packages/ckeditor5-core/tests/_utils-tests/assertions/attribute.js
packages/ckeditor5-core/tests/_utils/assertions/attribute.js

The actual and expected values were switched.
Tests (core): Fix the placement of the actual and expected values in the `attribute` assertion message.
---

Fix the attribute assertion message.

---

packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widgettypearound.css
packages/ckeditor5-widget/package.json
packages/ckeditor5-widget/src/widget.js
packages/ckeditor5-widget/tests/widget-integration.js

Fix (widget): Triple-click inside image caption should not crash editor in Firefox. Closes #7542.
Fix (widget): Triple-click on link inside image caption should not crash editor in Safari. Closes #6021.
---

#7542: Widget type around UI should not be selectable by triple-click.

---

packages/ckeditor5-table/src/commands/inserttablecommand.js
packages/ckeditor5-table/src/tableutils.js
packages/ckeditor5-table/tests/commands/inserttablecommand.js
packages/ckeditor5-table/tests/tableclipboard-paste.js
packages/ckeditor5-table/tests/tableutils.js

Feature (table): Added option to set heading rows/columns for `insertTable` command and `TableUtils#createTable()`. Closes #6768.
---

#6768: Added option to set heading rows/columns for `insertTable` command and TableUtils#createTable()

---

packages/ckeditor5-engine/src/model/element.js
packages/ckeditor5-engine/src/model/position.js
packages/ckeditor5-engine/tests/model/element.js
packages/ckeditor5-engine/tests/model/position.js
packages/ckeditor5-table/src/commands/insertcolumncommand.js
packages/ckeditor5-table/src/commands/insertrowcommand.js
packages/ckeditor5-table/src/commands/mergecellcommand.js
packages/ckeditor5-table/src/commands/mergecellscommand.js
packages/ckeditor5-table/src/commands/removecolumncommand.js
packages/ckeditor5-table/src/commands/removerowcommand.js
packages/ckeditor5-table/src/commands/selectcolumncommand.js
packages/ckeditor5-table/src/commands/selectrowcommand.js
packages/ckeditor5-table/src/commands/setheadercolumncommand.js
packages/ckeditor5-table/src/commands/setheaderrowcommand.js
packages/ckeditor5-table/src/converters/table-layout-post-fixer.js
packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/src/tablekeyboard.js
packages/ckeditor5-table/src/tablemouse.js
packages/ckeditor5-table/src/tableproperties/commands/tablepropertycommand.js
packages/ckeditor5-table/src/tableselection.js
packages/ckeditor5-table/src/utils/common.js
packages/ckeditor5-table/src/utils/selection.js
packages/ckeditor5-table/src/utils/ui/contextualballoon.js
packages/ckeditor5-table/src/utils/ui/widget.js
packages/ckeditor5-table/tests/manual/tablemocking.js
packages/ckeditor5-table/tests/utils/common.js
packages/ckeditor5-table/tests/utils/ui/contextualballoon.js

Feature (engine): Added model `Position#findAncestor()` and `Element#findAncestor()` methods. Closes #3233.
Internal (table): Removed `findAncestor` helper.
MINOR BREAKING CHANGE (table): The `findAncestor()` utility function was removed.
---

#3233: Added model Position#findAncestor() and Element#findAncestor() methods

---

packages/ckeditor5-table/src/tableclipboard.js
packages/ckeditor5-table/tests/tableclipboard-paste.js

Fix (table): Pasting table into table should not set multi-cell selection if TableSelection plugin is disabled. Closes #7486.
---

#7486: Pasting table into table should not set multi-cell selection if TableSelection plugin is disabled

---

packages/ckeditor5-link/package.json
packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/tests/linkediting.js
packages/ckeditor5-typing/src/inputcommand.js
packages/ckeditor5-typing/src/utils/injectunsafekeystrokeshandling.js
packages/ckeditor5-typing/tests/inputcommand.js
packages/ckeditor5-typing/tests/utils/injectunsafekeystrokeshandling.js

Feature (link): Typing over the selected link will not remove the link itself. Instead, the typed text will replace the link text. Closes #4762.

Typing over the link feature

---

packages/ckeditor5-link/src/linkui.js
packages/ckeditor5-link/tests/linkui.js

Fix (link): Fake visual selection should not be added to the editor's data. Closes #7614.

Fake visual selection should not be added to data

---

packages/ckeditor5-font/src/documentcolorcollection.js
packages/ckeditor5-utils/src/collection.js
packages/ckeditor5-utils/tests/collection.js

Feature: Introduced the `Collection.addMany()` method for adding multiple items in a single call. Closes #7627.
Feature: Introduced the `Collection.change` event. See #7627.
---
With this I was also able to simplify `DocumentColorCollection` by using new `change` event.
`clear()` method uses almost the entire `remove()` logic except that it must not fire `change` for each removal. Thus I extracted a private base of `remove()` that can be reused in both cases.

Introduced the Collection.addMany method and Collection.change event

---

packages/ckeditor5-table/tests/tableclipboard-paste.js

Tests (table): Update sample image URI to remove 404 warnings. Closes #7350.
---
I checked all the tests running locally for `404`s.
However, we may also revisit every occurrence of `example.jpg` in our code, to double-check, or to unify it to use `-utils/tests/_assets/sample.png`.

Update sample image URI to remove 404 warnings. Closes #7350.

---

packages/ckeditor5-link/src/linkcommand.js
packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/src/linkimageediting.js
packages/ckeditor5-link/src/unlinkcommand.js
packages/ckeditor5-link/src/utils.js
packages/ckeditor5-link/src/utils/automaticdecorators.js
packages/ckeditor5-link/tests/linkcommand.js
packages/ckeditor5-link/tests/linkediting.js
packages/ckeditor5-link/tests/linkimageediting.js
packages/ckeditor5-link/tests/manual/linkdecorator.js
packages/ckeditor5-link/tests/utils.js
packages/ckeditor5-link/tests/utils/automaticdecorators.js

Fix (link): Manual and automatic decorators will work properly with a link that is labeled by an image. Closes #7519.
Internal (link): An icon that indicates that the image is linked will not be displayed in the editor's data. Closes #7626.
☝️ marking as internal since the icon and the bug was introduced in the same iteration.

Support for decorators when linking images

---

packages/ckeditor5-engine/src/controller/datacontroller.js
packages/ckeditor5-engine/tests/controller/datacontroller.js
packages/ckeditor5-undo/src/basecommand.js
packages/ckeditor5-undo/tests/redocommand.js
packages/ckeditor5-undo/tests/undocommand.js

Fix (undo): Undo/redo stacks should be cleared on `DataController#set()`. Closes #4060.
Feature (engine): `DataController#set()` is now decorated so plugins can listen to `setData()` calls.
MAJOR BREAKING CHANGE: `editor.setData()` clears the undo and redo stacks.
---

#4060: Undo/redo stacks cleared on DataController set().

---

packages/ckeditor5-core/src/command.js
packages/ckeditor5-core/src/commandcollection.js
packages/ckeditor5-core/src/editor/editor.js
packages/ckeditor5-core/src/multicommand.js
packages/ckeditor5-core/tests/commandcollection.js
packages/ckeditor5-core/tests/editor/editor.js
packages/ckeditor5-core/tests/multicommand.js

Other: Editor, CommandCollection and MultiCommand's .execute() method returns the result of the called `command.execute()`. Closes #7647.
---
I considered updating a number of tests, to showcase the purpose of this change. 
But the only `execute`s that return a thing are in the `-internal` repo.
https://github.com/cksource/ckeditor5-internal/blob/master/packages/ckeditor5-export-pdf/src/exportpdfcommand.js#L61
https://github.com/cksource/ckeditor5-internal/blob/master/packages/ckeditor5-export-word/src/exportwordcommand.js#L60
This change allows changing a test like:
https://github.com/cksource/ckeditor5-internal/blob/master/packages/ckeditor5-export-pdf/tests/exportpdfcommmand.js#L143-L154
to
```js
it( 'should pass `options.fileName` to the `_downloadFile` method', async () => {
await …
```

Make Editor, CommandCollection and MultiCommand, .execute() forward the result.

---

packages/ckeditor5-engine/src/model/documentselection.js
packages/ckeditor5-engine/tests/model/documentselection.js
packages/ckeditor5-table/tests/tableselection-integration.js
packages/ckeditor5-typing/tests/inputcommand.js

Fix: Fixed incorrect selection fixing in some multi-cell selection scenarios. Closes #7659.

Fixed incorrect selection fixing in some multi-cell selection scenarios

---

packages/ckeditor5-widget/src/widgetresize/resizer.js
packages/ckeditor5-widget/tests/widgetresize/resizer.js

Fix: `Resizer#redraw()` should not change the editing view unless a different size should be set. Closes #7633.

#7633: Resizer#redraw() should not change the editing view unless a different size should be set

---

packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/tests/linkediting.js

Fix (link): When removing the content after a link element, the selection will not preserve the `linkHref` attribute (and decorators if specified). However, if the selection is placed in the link element (in the middle or at the end), those attributes will be preserved. Closes #7521.

Improved removing content after a link element

---

packages/ckeditor5-image/src/imageresize.js
packages/ckeditor5-image/src/imageresize/imageresizebuttons.js
packages/ckeditor5-image/src/imageresize/imageresizeediting.js
packages/ckeditor5-image/src/imageresize/imageresizehandles.js
packages/ckeditor5-image/tests/imageresize/imageresizebuttons.js
packages/ckeditor5-image/tests/imageresize/imageresizeediting.js

Internal (image): The `config.image.resizeOptions` should have the default value. Closes #7679.

#7679: The config.image.resizeOptions should have the default value.

---

docs/builds/guides/development/custom-builds.md
docs/builds/guides/integration/advanced-setup.md

Previously, the custom builds documentation instructed to clone the ckeditor5-build-classic (and variants) repositories.
Since the inclusion of these repository under the main monorepo, the individual repositories have been marked "archived" and read-only.
This commit modifies the instructions to instruct cloning the main monorepo and working directly out of the subdirectory.

Update individual build locations for custom builds

---

packages/ckeditor5-engine/src/model/documentselection.js
packages/ckeditor5-engine/tests/model/documentselection.js
packages/ckeditor5-enter/package.json
packages/ckeditor5-enter/tests/shiftenter-integration.js

Fix (engine): Selection will not inherit attributes if spotted an inline element while searching for a node from which attributes could be copied. Closes #7459.
Tests (enter): Added an integration test that covers a bug with copying attributes from a node before an inline element. See #7459.

Selection stops searching for attributes when spotted an inline element

---

docs/_snippets/examples/inline-editor.html
docs/_snippets/examples/inline-editor.js
packages/ckeditor5-image/docs/_snippets/features/image-style-presentational.html
packages/ckeditor5-image/docs/_snippets/features/image-style-presentational.js
packages/ckeditor5-image/docs/features/image.md

Docs (image):  Added `ImageResize` plugin to the `Presentational styles` section demo. Closes #7715.
Docs (ckeditor5):  Added`ImageResize` plugin to the `Inline Editor` example demo. See #7715.
Docs (image): Fixed configuration examples for `Using the dropdown` and `Using standalone buttons` sections. Closes #7716.
Docs (image): Added missing mandatory `icon` property to the `Using standalone buttons` configuration example. Closes #7717.

I/7715: Fix demos and docs for the Image feature.

---

packages/ckeditor5-indent/src/indentblock.js
packages/ckeditor5-indent/tests/indentblock.js
packages/ckeditor5-remove-format/src/removeformatcommand.js
packages/ckeditor5-remove-format/tests/removeformatcommand.js

Feature (indent): Block indentation should be recognized as a formatting attribute. Closes #2358.
Other (remove-format): Block formatting should be removed if selection is inside that block. 
---

#2358: Block indentation should be recognized as a formatting attribute

---

packages/ckeditor5-engine/src/conversion/upcasthelpers.js
packages/ckeditor5-engine/tests/conversion/upcasthelpers.js

Internal: Fix for data-to-marker upcast for elements that are not converted. Closes #7732.

Fix for data-to-marker upcast for elements that are not converted

---

packages/ckeditor5-autoformat/docs/features/autoformat.md
packages/ckeditor5-mention/docs/features/mentions.md
packages/ckeditor5-typing/docs/features/text-transformation.md

Adding autolink to productivity features list in mentions, automatic text transformations and autoformatting.

Docs: adding autolink to productivity features. [skip ci]

---

packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.js
packages/ckeditor5-ui/src/toolbar/toolbarview.js
packages/ckeditor5-ui/tests/toolbar/balloon/balloontoolbar.js
packages/ckeditor5-ui/tests/toolbar/toolbarview.js
packages/ckeditor5-utils/src/dom/resizeobserver.js
packages/ckeditor5-utils/tests/dom/resizeobserver.js

Fix: Balloon toolbar should reposition and ungroup items correctly when the window resizes. Closes #6444.
---
This PR is another attempt at https://github.com/ckeditor/ckeditor5/pull/7721/files.  
There are 2 things in this PR (this is hard but here we go):
1.  A reverted `ResizeObserver` optimization (mentioned here https://github.com/ckeditor/ckeditor5/pull/7721#discussion_r461502549).   
Without it (or... actually with it), the `previousWidth !== entry.contentRect.width` in this `ToolbarView` line https://github.com/ckeditor/ckeditor5/blob/i/6444-toolbar-reposition-on-regroup/packages/ckeditor5-ui/src/toolbar/toolbarview.js#L757 does not work.  
The `ToolbarView` optimizes the number of `_updateGrouping()` calls so they only happen when:  
\- it's the first resize in its lifetime …

#6444: Balloon toolbar should reposition and ungroup items correctly when the window resizes

---

packages/ckeditor5-utils/src/dom/emittermixin.js
packages/ckeditor5-utils/tests/dom/emittermixin.js

Feature (utils): DomEmitterMixin should support the `passive` option to `addEventListener`. Closes #7828.
---

#7828: DomEmitterMixin should pass "passive" option for listener

---

packages/ckeditor5-table/src/utils/ui/contextualballoon.js
packages/ckeditor5-utils/src/dom/rect.js
packages/ckeditor5-utils/tests/dom/rect.js

Fix (utils): `Rect` utility returns wrong sizes in case of a sequenced range. Closes #7838. 
Feature (utils): Introduced the `Rect#getBoundingRect()` method that returns a `Rect` instance containing all other rectangles. Closes #7858.
---
Initially I was even tempted to simplify it and use `Range.getBoundingClientRect()` to do the computation for us, but then I saw a plethora of issues that this method not always give reliable results:
*   #4969
*   #4952

Fixed Rect results for a sequenced range

---

packages/ckeditor5-link/src/linkui.js
packages/ckeditor5-link/tests/linkui.js

Fix (link): Fixed a case where link balloon would point invalid place after browser scroll or resize. Closes #7705.
---
Though this PR fixes the source problem, it hits another bug where invalid Rect is returned for a range containing multiple client rects (in this case it's caused by adding extra span for marker, which results with more than 4 client rects for me on Chrome).

Fixed a case where link balloon would point invalid place after browser scroll or resize

---

docs/_snippets/examples/inline-editor.js

Docs (ckeditor5): The header editor in the "Inline editor" example should not enable the `ImageResize` plugin. Closes #7905.

#7905: The header editor in the "Inline editor" example should not enable the ImageResize plugin

---

scripts/continuous-integration-script.js

Internal: Improved the check whether the CC report should be send to Coveralls. The previous solution did not consider normal builds (cron, push). See #7745.

Added one more check whether the CC report should be send to Coveralls

---

packages/ckeditor5-list/src/liststylecommand.js
packages/ckeditor5-list/src/liststyleediting.js
packages/ckeditor5-list/src/utils.js
packages/ckeditor5-list/tests/liststyleediting.js
packages/ckeditor5-list/tests/utils.js

**Two commit messages that depends on the time when we will close the PR.**
---
Internal: Handle removing the content between lists and updating `listStyle` attribute for merged items. Closes #7879.
_☝️ In case when we merge it into the current iteration._
---
_👇  In case when it will be merged somewhen._
Fix (list): When removing the content between two lists items, the lists will be merged into the single list. The second list should adjust its value for the `listStyle` attribute based on the most outer `listItem` in the first list. Closes #7879.

Handle removing the content between lists and updating `listStyle` attribute for merged items

---

scripts/docs/build-docs.js
scripts/docs/buildapi.js

Internal: Moved the `catch()` block to the "main process" while building docs. Support for the `--strict` flag. Closes #7994.
---
Requires: https://github.com/ckeditor/ckeditor5-dev/pull/670

Support for the --strict flag

---

packages/ckeditor5-list/src/liststyleediting.js
packages/ckeditor5-list/tests/liststyleediting.js

Fix (list): The `listStyle` attribute should be inherited when inserting or replacing a `listItem` with the same kind of the list (the `listType` attribute for the inserted/modified item is equal to next/previous sibling list). Closes #7932.

Inheriting the `listStyle` attribute for elements inserted next to the existing list

---

packages/ckeditor5-link/src/autolink.js
packages/ckeditor5-link/tests/autolink.js

Fix (link): Prevented throwing an error on pressing the <kbd>enter</kbd> key when non-collapsed selection is on autolink. Closes #7983.

i/7983: Prevent showing an error on pressing "enter" when autolink is selected.

---

packages/ckeditor5-clipboard/src/utils/viewtoplaintext.js
packages/ckeditor5-clipboard/tests/utils/viewtoplaintext.js

Fix (clipboard): Soft breaks are now properly placed in plain text clipboard data representation by the editor. Closes #8045.

Soft breaks are now properly placed in plain text clipboard data representation by the editor

---

packages/ckeditor5-engine/src/view/observer/inputobserver.js
packages/ckeditor5-engine/src/view/view.js
packages/ckeditor5-engine/tests/view/observer/inputobserver.js
packages/ckeditor5-engine/tests/view/view/view.js

Feature (engine): Improved `InputObserver` with useful input event data properties. Closes #7996.
Other (clipboard): Moved the `DataTransfer` helper class to ckeditor5-engine (see #7996).
Internal (image): Updated import paths and docs since the `DataTransfer` helper class has been moved to [ckeditor5-engine](https://www.npmjs.com/package/@ckeditor/ckeditor5-engine) (see #7996).
MINOR BREAKING CHANGE (clipboard): The `DataTransfer` helper class has been moved to [ckeditor5-engine](https://www.npmjs.com/package/@ckeditor/ckeditor5-engine). Please update the import path in your integrations to `'@ckeditor/ckeditor5-engine/src/view/datatransfer'` (see #7996).
---
\-

#7996: Improved InputObserver with useful input event data properties

---

packages/ckeditor5-clipboard/src/utils/plaintexttohtml.js
packages/ckeditor5-clipboard/tests/clipboard.js
packages/ckeditor5-clipboard/tests/utils/plaintexttohtml.js

Feature (clipboard): Improved line to paragraph/soft break retention when pasting from plain text. Closes #7884.
MINOR BREAKING CHANGE (clipboard): When pasting plain text each double line break is now treated as a paragraph separator, while single line break is converted into a soft break. Formerly every single line break was treated as a paragraph separation.
---
While working on it I found #8045.

Improved line to paragraph/soft break retention when pasting from plain text

---

docs/builds/guides/migrate.md

Docs (ckeditor5): Fixed a link to the export to PDF feature. Closes #8060.

Docs (ckeditor5): Fixed a link to the export to PDF feature

---

packages/ckeditor5-upload/docs/features/simple-upload-adapter.md

A simple commit just to fix typo of `CSFR-Token` to `CSRF-Token`
---

Fixed Typo: CSFR-Token -> CSRF-Token

---

.github/workflows/merge-stable.yml

Internal: The slack notification should be sent if failed while merging. Closes #7839.
---

The slack notification should be sent if failed while merging

---

packages/ckeditor-cloud-services-core/package.json
packages/ckeditor-cloud-services-core/src/token/token.js
packages/ckeditor-cloud-services-core/tests/token/token.js
packages/ckeditor-cloud-services-core/tests/uploadgateway/fileuploader.js
packages/ckeditor-cloud-services-core/tests/uploadgateway/uploadgateway.js

Other (cloud-services-core): Change tokens refreshing mechanism to depend on the token expiration time. 
---
Closes cksource/ckeditor5-internal#316.
_Do not paste it in the commit merge message!_
---
After these changes token should be refreshed after half of a difference between the token expiration time and the actual time.

Change token refresh mechanism to depend on the token expiration time

---

packages/ckeditor5-list/src/liststyleediting.js
packages/ckeditor5-list/tests/liststyleediting.js

Fix (list): The editor will not crash when indenting a list item that is the last element in the editor. Closes #8072.
Fix (list): Undo will restore the proper value of the `list-style-type` attribute in the [`View`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_containerelement-ContainerElement.html) element after undoing merging different lists. Closes #7930. 
Fix (list): Fixed a bug that blocked using the same value of the [List style](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html#list-styles) feature for nested lists. Closes #8081.
Internal (list): The mechanism that merges two lists and inherits their list styles will not crash while deleting content (lists with different values of the `listIndent` attribute) in a nested list. Closes #8073. …

Fixed ugly crashes when playing with List style feature

---

packages/ckeditor5-image/docs/_snippets/features/image-insert-via-url.js
packages/ckeditor5-image/docs/features/image.md
packages/ckeditor5-image/src/imageinsert.js
packages/ckeditor5-image/src/imageinsert/utils.js
packages/ckeditor5-image/tests/imageinsert/imageinsertui.js
packages/ckeditor5-image/tests/imageinsert/utils.js
packages/ckeditor5-image/tests/manual/imageinsertviaurl.js
tests/manual/all-features.js

BREAKING CHANGE (image): Changed the integration API for the `ImageInsert` plugin. Closes #8034.
Docs (image): Changed the feature and API docs for the `ImageInsert` plugin. See #8034.

i/8034: Change the API and docs for ImageInsert plugin.

---

packages/ckeditor-cloud-services-core/src/token/token.js
packages/ckeditor-cloud-services-core/tests/token/token.js

Other (cloud-services-core): Fix the token refresh timeout time calculations. 
---
Closes cksource/ckeditor5-internal#329.
_Do not paste it in the commit merge message!_
---
After these changes token should be properly refreshed after the default time (1 hour) if the token payload doesn't contain the `exp` property and refresh timeout time calculations should respect the fact that the `exp` property in the token payload is always in seconds.

Fix the token refresh timeout time calculations

---

packages/ckeditor5-link/src/linkimageediting.js
packages/ckeditor5-link/tests/linkimageediting.js
tests/manual/all-features.html
tests/manual/all-features.js
tests/manual/all-features.md

Fix (link): Manual decorators will be handled properly for linked images and linked text. Closes #7975.

Manual link decorators for images will not crash decorators for linked text

---

packages/ckeditor5-core/src/plugincollection.js
packages/ckeditor5-engine/src/conversion/upcasthelpers.js
packages/ckeditor5-image/src/imagestyle/utils.js
packages/ckeditor5-media-embed/src/mediaregistry.js
packages/ckeditor5-media-embed/tests/mediaembedediting.js
packages/ckeditor5-media-embed/tests/mediaembedtoolbar.js
packages/ckeditor5-mention/src/mentionui.js
packages/ckeditor5-mention/tests/mentionui.js
packages/ckeditor5-table/src/tablewalker.js
packages/ckeditor5-ui/src/toolbar/toolbarview.js
packages/ckeditor5-upload/src/adapters/simpleuploadadapter.js
packages/ckeditor5-upload/src/filerepository.js
packages/ckeditor5-upload/tests/adapters/simpleuploadadapter.js
packages/ckeditor5-upload/tests/filerepository.js
packages/ckeditor5-utils/src/ckeditorerror.js
packages/ckeditor5-utils/tests/ckeditorerror.js
packages/ckeditor5-watchdog/tests/editorwatchdog.js
packages/ckeditor5-widget/src/widgettoolbarrepository.js
packages/ckeditor5-widget/tests/widgettoolbarrepository.js

Internal: Use same format for error name in attachLinkToDocumentation as in CKEditorError. Closes #8097.
---
*   I've added this to ESLint rule as well: ckeditor/eslint-plugin-ckeditor5-rules#1.

Use same format for error name in attachLinkToDocumentation as in CKEditorError

---

packages/ckeditor5-engine/src/model/utils/deletecontent.js
packages/ckeditor5-engine/tests/model/utils/deletecontent.js

Fix (engine): `Model#deleteContent()` should properly remove blocks when the selection is spanning multiple blocks. Closes #8145.
---

#8145 : Fixed handling of multiple selected blocks in Model#deleteContent().

---

docs/_snippets/features/mathtype.html
docs/_snippets/features/mathtype.js
package.json

Docs (ckeditor5): Reintroduce the latest MathType version. Closes #8198.
---
To reintroduce latest MathType version in the docs not only commit `3997ba3a` has to be reverted (merged previously in #7944), but additionally also `@wiris/mathtype-ckeditor5` package has to be updated to at least version `7.24.0`, becaue only from this version this package contain the fix (in the internal MathType dependency `@wiris/mathtype-html-integration-devkit@1.4.1`).

Docs: Reintroduce latest MathType version

---

packages/ckeditor5-link/src/linkui.js
packages/ckeditor5-link/tests/linkui.js

Fix: Do not show up Link UI on Ctrl+K when LinkCommand is disabled. Closes #7919.
---

Link UI should not show up on Ctrl+K when LinkCommand is disabled

---

packages/ckeditor5-block-quote/docs/_snippets/features/block-quote.html
packages/ckeditor5-block-quote/docs/_snippets/features/block-quote.js
packages/ckeditor5-block-quote/docs/api/block-quote.md
packages/ckeditor5-block-quote/docs/features/block-quote.md

Closes #8129
Also closes cksource/content-documentation-proofread#321
This is not a from-scratch job but made by repainting another feature. Please pay attention to the API and install sections during the review.

Docs: Block quote documentation. [skip ci]

---

packages/ckeditor5-block-quote/docs/features/block-quote.md
packages/ckeditor5-page-break/docs/features/page-break.md

"Related" section moved to a new position. No other changes made.

Docs: structure updated. [skip ci]

---

packages/ckeditor5-media-embed/src/mediaembedcommand.js
packages/ckeditor5-media-embed/src/mediaembedediting.js
packages/ckeditor5-media-embed/tests/insertmediacommand.js

Fix (media-embed): Enable media embed command when selected media is in a table cell. Closes #7604.
---

Media embed command is disabled when selected media is in a table cell

---

packages/ckeditor5-paste-from-office/tests/_data/image/adjacent-groups/model.edge.word2016.html
packages/ckeditor5-paste-from-office/tests/_data/image/adjacent-groups/model.safari.word2016.html
packages/ckeditor5-paste-from-office/tests/_data/image/adjacent-groups/model.word2016.html
packages/ckeditor5-table/src/converters/upcasttable.js
packages/ckeditor5-table/src/tableediting.js
packages/ckeditor5-table/tests/converters/upcasttable.js
packages/ckeditor5-table/tests/tableclipboard-paste.js

Fix (table): Pasting nested tables with unsupported by the editor elements will not blow up. Closes #8098.
MINOR BREAKING CHANGES (table): Removed the `ensureParagraphInTableCell()` converter that ensures that the model state after the conversion process will be correct. Now the model will be fixed (if needed) by the post-fixer (`injectTableCellParagraphPostFixer()`).

Pasting nested tables with unsupported by the editor elements will not blow up

---

packages/ckeditor5-media-embed/src/automediaembed.js
packages/ckeditor5-media-embed/tests/automediaembed.js

Fix (media-embed): Allow URL with '%'-symbols for Media Object transformation. Closes #7488.
---

Inserted URL with '%'-symbols is not transformed to Media Object

---

packages/ckeditor5-ckfinder/docs/features/ckfinder.md

Type: Fix link on documentation
---
The link doesn't redirect on the good information.

Docs: Fix link in CKFinder page

---

packages/ckeditor5-engine/src/view/observer/fakeselectionobserver.js

Internal (engine): Use `isArrowKeyCode` from `ckeditor5-utils` package. Closes #6648.
---
`isArrowKeyCode` method is available since https://github.com/ckeditor/ckeditor5/commit/eb8dd9f0e616cd5d15c3dc673508679d3061f547#diff-e6250bd96c3f473fa2ca5e514f412797R138 and there was only 1 place where it wasn't used. Unit tests are already created for it.

Use isArrowKeyCode from ckeditor5-utils package

---

docs/features/image-upload.md

Closes cksource/content-documentation-proofread#337
Adding a link to a blog post: https://ckeditor.com/blog/managing-images-with-ckeditor-5/ to image upload feature guide: https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html

Docs: adding image blog post to image upload guide.

---

packages/ckeditor5-image/src/imageinsert/imageinsertui.js
packages/ckeditor5-image/tests/imageinsert/imageinsertui.js

Fix (image): Focusing the URL input when the image upload panel shows up. Closes #7896.
---

Focusing the URL input when the image upload panel shows up

---

docs/builds/guides/integration/advanced-setup.md

Docs: Use npm in favor of yarn in the advanced setup for consistency 
---
Assumed that you want to use npm instead of yarn given that in most places you are using npm.

Use npm in favor of yarn for consistency

---

packages/ckeditor5-list/src/liststyleediting.js
packages/ckeditor5-list/tests/liststyleediting.js

Fix (list): The list conversion will not throw an error if the list element is being surrounded by the non-tagged elements (text nodes). Closes #8262.

Non-tagged elements will not blow up the list style feature

---

docs/builds/guides/frameworks/angular.md

Docs: Added information about supported Angular versions in the Angular guide. Closes ckeditor/ckeditor5-angular#227.
---

Add information about supported Angular versions in the Angular guide

---

packages/ckeditor5-utils/docs/framework/guides/deep-dive/observables.md
packages/ckeditor5-utils/src/observablemixin.js

Docs (utils): Add information about using callback with a single property.
---
I added this example as it was not stated directly that you can use this for one property. The docs say only about merging multiple properties. You can also process the property value for bound property.the

Docs (utils): Add information about using callback with a single property.

---

packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/responsive-form/responsiveform.css

Internal (theme-lark): Fixing showing button separators in inappropriate places. Closes #8296.
---
Follow-up of [#7704](https://github.com/ckeditor/ckeditor5/issues/7704).

Fixing showing button separators in inappropriate places

---

packages/ckeditor5-image/theme/imageinsertformrowview.css
packages/ckeditor5-theme-lark/theme/ckeditor5-table/form.css
packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/responsive-form/responsiveform.css

Fix (image): Removing focus outline in "insert image via URL" form.. Closes #7973.
---

Removing focus outline in "insert image via URL" form.

---

packages/ckeditor5-code-block/docs/_snippets/features/code-block-custom-languages.html

Docs (code-block): Removed warnings about unsupported code block languages in the docs. Closes #7925.
---
As mentioned in https://github.com/cksource/umberto/issues/838#issuecomment-559036170, this is a workaround for a bug in Umberto.

Remove warnings about unsupported code block languages in the docs

---

packages/ckeditor5-link/src/autolink.js
packages/ckeditor5-link/src/linkui.js
packages/ckeditor5-link/src/utils.js
packages/ckeditor5-link/tests/autolink.js
packages/ckeditor5-link/tests/linkui.js
packages/ckeditor5-link/tests/utils.js

add mailto to email link when there is no defaultProtocol
Fix (link): Use \`link.defaultProtocol\` when auto-linking an URL. Closes #8079.
---

Use `link.defaultProtocol` when auto-linking an URL,

---

packages/ckeditor5-engine/tests/common.js

Tests (engine): Added the detection for infinite selection rendering loop. See #8263.
---
This is the first step that might show us what is wrong with the test. The trick is to proxy `console.warn` so that it fails if infinite selection loop message is detected (see https://github.com/ckeditor/ckeditor5/issues/8263#issuecomment-708964548).
It's acceptable that it will cause the entire test run to fail - we get a fail from CI anyway (due to lacking CC if infinite rendering is happening).

Added a code that will help identify the source of infinite selection loop

---

packages/ckeditor5-html-embed/src/htmlembedediting.js
packages/ckeditor5-html-embed/tests/htmlembedediting.js
packages/ckeditor5-html-embed/theme/htmlembed.css
packages/ckeditor5-theme-lark/theme/ckeditor5-html-embed/htmlembed.css

Internal: Added a label and an outline to the HTML embed widget to improve contrast. Closes #8321.
---
There's a problem with the widget type around button. I moved if by some offset to avoid collisions but it could be that in some languages "HTML snippet" will translate to some long string and it will overlap with the button. I don't see any easy way to anticipate this, though.

#8321: Added a label and and outline to the html embed widgets to improve contrast.

---

packages/ckeditor5-engine/src/conversion/downcastdispatcher.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js

Fix (engine): The old view element should be properly unbound after reconversion is done. Closes #8358.

The old view element should be properly unbound after reconversion is done

---

packages/ckeditor5-list/package.json
packages/ckeditor5-list/src/liststyleediting.js
packages/ckeditor5-list/tests/liststylecommand.js
packages/ckeditor5-list/tests/liststyleediting.js

#7959 # Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))
Fix (list): List styles will be inherited correctly when pasting a list into another list. Closes #8160.
---
_I know, I used the best solution for detecting that content comes from pasting… How could we improve that?_

Pasting a list into another list (fix list-style attr)

---

package.json
scripts/docs/buildapi.js
scripts/docs/snippetadapter.js

Fix: Fixed building documentation on Windows. Closes #7212.
---
This PR is the 1 of 2 PRs that are needed to fix building documentation on Windows - the second one is https://github.com/cksource/umberto/pull/884.
It works on Linux and on Windows now! 🎉 
The main problem was with mixed `/` and `\`, which were used in HTML links and paths on filesystem. After some investigation it turned out, that:
- we can't use methods from built-in `path` module, because they always produce paths with native separator,
- we can't use POSIX versions of methods from built-in `path` module (e.g. `path.posix.<methodName>`), [because of their unreliability and inconsistency](https://github.com/nodejs/node/issues/13683).
A lot of parts of code implicitly expect that the one and only valid path separator is …

Fix building documentation on Windows

---

packages/ckeditor5-html-embed/src/htmlembedediting.js
packages/ckeditor5-html-embed/tests/htmlembedediting.js

Fix (html-embed): The editing root should remain focused when saving changes in the embed. Closes #8318.
---

The editing root should remain focused when saving changes in the embed

---

packages/ckeditor5-undo/src/basecommand.js
packages/ckeditor5-undo/tests/undoediting-integration.js

Internal (undo): Fixed restoring selection on undoing for cases when transformed ranges are interleaved by ranges in the graveyard.
---

Fixed restoring selection on undoing for cases when transformed ranges are interleaved by ranges in the graveyard

---

tests/manual/all-features.html
tests/manual/all-features.js
tests/manual/all-features.md

Tests: Added missing plugins to the `all-features` manual test: `HtmlEmbed`, `ListStyle` and `PasteFromOffice`. Closes #8317.

Added missing plugins to the `all-features` manual test

---

packages/ckeditor5-font/src/fontsize/fontsizeediting.js
packages/ckeditor5-font/tests/fontfamily/fontfamilyediting.js
packages/ckeditor5-font/tests/fontsize/fontsizeediting.js
packages/ckeditor5-font/tests/manual/tickets/8233/1.html
packages/ckeditor5-font/tests/manual/tickets/8233/1.js
packages/ckeditor5-font/tests/manual/tickets/8233/1.md

Fix (font): Fixed the `supportAllValues` configuration for `font-size` to work with nested elements. Closes #8233.

The `supportAllValues` for `font-size` doesn't work with nested elements

---

packages/ckeditor5-typing/docs/_snippets/features/text-transformation-extended.html
packages/ckeditor5-typing/docs/_snippets/features/text-transformation-extended.js
packages/ckeditor5-typing/docs/_snippets/features/text-transformation.html
packages/ckeditor5-typing/docs/_snippets/features/text-transformation.js

Solid encouragement text inside the demos was replaced with editor placeholders for a better experience in the automatic text transformations guide.

Docs: editor text replaced with an editor placeholder.

---

docs/_snippets/framework/tutorials/using-react-in-widget.html
docs/_snippets/framework/tutorials/using-react-in-widget.js
docs/framework/guides/tutorials/using-react-in-a-widget.md
package.json

Internal: Adjusted the "Using React in widget" guide to the latest changes in the `@ckeditor/ckeditor5-react` package.
---
It should be merged after releasing the new version of the react integration package.

Adjusted "Using React in widget" guide to changes in <CKEditor> component

---

packages/ckeditor5-indent/src/indentblock.js
packages/ckeditor5-indent/tests/indentblock-integration.js
packages/ckeditor5-indent/tests/manual/indent-block.html
packages/ckeditor5-indent/tests/manual/indent-block.js

Fix (indent): blockIndent now works with custom headings. Closes #8177.
---
Please let me know if you want me to change anything.

Fix (indent): blockIndent now works with custom headings. Closes #8177.

---

packages/ckeditor5-engine/src/conversion/conversion.js
packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/src/view/element.js
packages/ckeditor5-engine/tests/conversion/upcasthelpers.js
packages/ckeditor5-image/src/image/imageinsertcommand.js
packages/ckeditor5-image/src/imageupload/imageuploadcommand.js
packages/ckeditor5-media-embed/src/mediaregistry.js
packages/ckeditor5-table/package.json
packages/ckeditor5-table/src/converters/downcast.js
packages/ckeditor5-typing/tests/twostepcaretmovement.js
packages/ckeditor5-ui/src/template.js
packages/ckeditor5-undo/tests/redocommand.js
packages/ckeditor5-undo/tests/undocommand.js
packages/ckeditor5-utils/src/locale.js
packages/ckeditor5-utils/src/toarray.js
packages/ckeditor5-utils/tests/toarray.js
packages/ckeditor5-watchdog/package.json
packages/ckeditor5-watchdog/src/contextwatchdog.js
packages/ckeditor5-widget/src/utils.js
packages/ckeditor5-widget/tests/widget.js

Internal: Added `toArray()` helper to cast any value to an array. Closes #7401.
---
All occurrences of `Array.isArray( value ) ? value : [ value ]` and `[].concat( value )` have been replaced by this new `toArray( value )` helper.

Added `toArray()` helper to cast any value to an array

---

docs/umberto.json

Docs: Added a redirect for the old Vue.js guide. Closes #8489.

Added a redirect for the old Vue.js guide

---

packages/ckeditor5-utils/src/emittermixin.js

`listenTo()` stores the callback under both the `_events` key and the `_listeningTo` key, but when invoked with a specific callback, `stopListening()` was only removing the entry under the `_events` key, holding the callback in memory.

Fix (utils): Fix memory leak in EventEmitterMixin

---

docs/framework/guides/architecture/editing-engine.md

Docs: Fixed incorrect snippet in the editing engine guide. Closes #8477.

Docs: Fixed incorrect snippet in the editing engine guide

---

packages/ckeditor5-clipboard/docs/framework/guides/deep-dive/clipboard.md

Docs: Fix UpcastWriter example in Clipboard Deep Dive. Closes #8470.
---
Small docs fix.

Docs: Fix UpcastWriter example in Clipboard Deep Dive

---

packages/ckeditor5-link/src/linkcommand.js
packages/ckeditor5-link/tests/linkcommand.js

Fix (link): Editor should not crash after inserting a link with the same href just after the link. Closes #8210.
---

Fixed crash after text nodes got merged in insertContent while inserting a link

---

docs/builds/guides/frameworks/react.md

Docs: Refreshed the React integration guide. Removed unsupported version of `create-react-app` (`1.x` and `2.x`). Added a section about importing build produced by Online Builder. Closes #8062. Closes #8105.
---
Do not paste it to commit merge:
Closes https://github.com/cksource/ckeditor5-internal/issues/190.
---

Refreshed the React integration guide

---

packages/ckeditor5-engine/src/model/utils/deletecontent.js
packages/ckeditor5-engine/src/model/utils/selection-post-fixer.js
packages/ckeditor5-engine/tests/model/utils/deletecontent.js
packages/ckeditor5-engine/tests/model/utils/selection-post-fixer.js

Fix (engine): The select all command should include all selectable elements in the content. Closes #7978.
Fix (engine): Editor should not crash on content deletion while one of the ends of the selection is inside the common ancestor of the selection range.
---

Fixed selection post-fixer for the case of selectable element at the end of the selection

---

packages/ckeditor5-markdown-gfm/docs/features/markdown.md

Closes: #8540
Rewriting the Markdown output plugin guide to be more user-oriented.
A step toward this: #5721

Docs: rewriting the guide intro.

---

packages/ckeditor5-cloud-services/package.json
packages/ckeditor5-cloud-services/src/cloudservices.js
packages/ckeditor5-cloud-services/tests/cloudservices.js

Internal (cloud-services): CloudServices Plugin should allow for registering multiple token endpoints. 
---

CloudServices Plugin should allow for registering multiple token endpoints

---

packages/ckeditor5-engine/src/dataprocessor/dataprocessor.jsdoc
packages/ckeditor5-engine/src/dataprocessor/htmldataprocessor.js
packages/ckeditor5-engine/src/dataprocessor/xmldataprocessor.js
packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/tests/dataprocessor/htmldataprocessor.js
packages/ckeditor5-engine/tests/dataprocessor/xmldataprocessor.js
packages/ckeditor5-engine/tests/view/domconverter/dom-to-view.js
packages/ckeditor5-engine/tests/view/domconverter/rawcontent.js
packages/ckeditor5-html-embed/src/htmlembedediting.js
packages/ckeditor5-html-embed/tests/htmlembedediting.js
packages/ckeditor5-html-embed/tests/manual/htmlembed.html
packages/ckeditor5-markdown-gfm/src/gfmdataprocessor.js
packages/ckeditor5-markdown-gfm/tests/_utils/utils.js
packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/code.js

Feature (engine): Introducing `DataProcessor#registerRawContentMatcher()`. 
Fix (html-embed): Editor should not crash after inserting a broken HTML. Closes #8323.
Fix (engine): `DomConverter` should not trim whitespaces in nodes that are siblings to inline raw content elements (e.g. MathML). Closes #5870.
---

Introducing DataProcessor#registerRawContentElementMatcher()

---

packages/ckeditor5-theme-lark/docs/_snippets/examples/custom.css
packages/ckeditor5-theme-lark/docs/framework/guides/theme-customization.md
packages/ckeditor5-theme-lark/tests/manual/inverted.html
packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/labeledfield/labeledfieldview.css

Internal (theme-lark): Inverted theme should properly display labeled fields. Closes #8275.
---

Updated inverted theme.

---

docs/framework/guides/contributing/contributing.md

Updating in-documentation links for code style guide form GitHub wiki to internal documents.
Type: Message. Closes #8565.

Docs: updating link to docs.

---

packages/ckeditor5-html-embed/src/htmlembedediting.js
packages/ckeditor5-html-embed/tests/htmlembedediting.js

Fix (html-embed): Save button should close editor even if there is no changes. Closes #8560.
---

Save button should close editor even if there is no changes.

---

packages/ckeditor5-autoformat/docs/features/autoformat.md
packages/ckeditor5-code-block/docs/features/code-blocks.md
packages/ckeditor5-markdown-gfm/docs/_snippets/features/markdown.html
packages/ckeditor5-markdown-gfm/docs/_snippets/features/markdown.js
packages/ckeditor5-markdown-gfm/docs/features/markdown.md

Adding known issues to the Markdown output guide and the Autoformatting (input) guide.
Closes: #8520 
May also close: #5721 (this is the final instalment in a series of improvements to Markdown-related guides).

Docs: markdown editor known issues

---

docs/builds/guides/development/dll-builds.md
sample/index.html
scripts/dll/dll-loader.js
webpack.config.dll.js

Internal: DLL modules will be added to the global scope. Closes #8521.

Add DLL modules to the global scope

---

packages/ckeditor5-engine/docs/framework/guides/deep-dive/element-reconversion.md

---
change from
`<sideCardSection cardType="info" cardURL="https://ckeditor.com/">...</sideCard>`
to
`<sideCard cardType="info" cardURL="https://ckeditor.com/">...</sideCard>`

Docs: edit incorrect tag name

---

packages/ckeditor5-autoformat/src/autoformat.js
packages/ckeditor5-autoformat/tests/autoformat.js

Fix (autoformat): Formatting will not be applied to snake_case anymore. Closes #2388.

Expect autoformat delimiters to have a space character preceding them.

---

packages/ckeditor5-ui/src/toolbar/toolbarview.js
packages/ckeditor5-ui/tests/toolbar/toolbarview.js

Fix (ui): A `'-'` divider will not be rendered when grouping is enabled. Closes #8582.

ToolbarLineBreakView should not be rendered when grouping is enabled.

---

packages/ckeditor5-mention/docs/_snippets/examples/chat-with-mentions.html
packages/ckeditor5-mention/docs/_snippets/examples/chat-with-mentions.js
packages/ckeditor5-mention/docs/examples/chat-with-mentions.md
packages/ckeditor5-ui/src/toolbar/toolbarview.js

Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))
Docs (mention): Clearing up and focusing the editor after sending a message, preventing the empty message from being sent. Closes #8147.

Improvements in chat with mentions

---

docs/_snippets/examples/multi-root-editor.js
docs/builds/guides/integration/configuration.md
docs/features/toolbar.md
docs/framework/guides/custom-editor-creator.md
packages/ckeditor5-build-classic/tests/ckeditor.js
packages/ckeditor5-editor-classic/src/classiceditorui.js
packages/ckeditor5-editor-classic/tests/classiceditorui.js
packages/ckeditor5-editor-decoupled/src/decouplededitorui.js
packages/ckeditor5-editor-decoupled/tests/decouplededitorui.js
packages/ckeditor5-editor-inline/src/inlineeditorui.js
packages/ckeditor5-editor-inline/tests/inlineeditorui.js
packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.js
packages/ckeditor5-ui/src/toolbar/block/blocktoolbar.js
packages/ckeditor5-ui/src/toolbar/normalizetoolbarconfig.js
packages/ckeditor5-ui/src/toolbar/toolbarview.js
packages/ckeditor5-ui/tests/toolbar/normalizetoolbarconfig.js
packages/ckeditor5-ui/tests/toolbar/toolbarview.js

Feature (ui): Items baked into editor bundles can be removed from the toolbar now. Closes #7945.
Docs: Updated docs/builds/guides/integration/configuration.md with new configuration setting.
MINOR BREAKING CHANGE (ui): Configuration passed to `ToolbarView.fillFromConfig()` will be stripped off of leading, trailing, and duplicated separators (`'|'` and `'-'`).
---
The `ToolbarView.fillFromConfig()` should accept two types of parameters, an array, and an object. This is done to prevent breaking changes in the public API.

Items baked into editor build can be removed from the toolbar now.

---

docs/features/toolbar.md

Updated to toolbar guide example code snippets to reflect the presented demos.
Added a link to the Block toolbar guide.
Closes: #8636

Toolbar guide code snippets

---

docs/features/math-equations.md

Closes #6054.
Adding install informations for Java, PHP, .NET and RoR services to the MathType guide.

Docs: adding services to MathType guide.

---

packages/ckeditor5-mention/src/mentionediting.js
packages/ckeditor5-mention/tests/mentionediting.js

Other (mention): Conversion API reference is no longer passed down to attribute props. Closes #8370.

Do not pass conversionAPI to the `_toMentionAttribute()`.

---

packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js
packages/ckeditor5-image/tests/imagecaption/imagecaptionediting.js

Fix (image): An empty image caption should be hidden if an editor is in the read-only mode. Closes #5168.

Not showing empty image caption if editor is in readOnly mode.

---

scripts/dll/build-dlls.js

Other: Fixed `yarn build:dll` on Windows. Closes #8746.
---
As noted in a very old Node issue https://github.com/nodejs/node-v0.x-archive/issues/2318, we need the `shell: true` option for `spawn()` or `spawnSync()` methods to make them work on Windows.

The spawnSync() method needs shell to work on Win

---

packages/ckeditor5-html-embed/src/htmlembed.js
packages/ckeditor5-html-embed/tests/htmlembed.js

Fix (html-embed): HTML embed should be selectable if no other widget plugins are installed. Closes #8720.

Widget required in html-embed plugin.

---

packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widgetresize.css
packages/ckeditor5-widget/theme/widget.css
packages/ckeditor5-widget/theme/widgetresize.css

Fix (widget): The visual styles of widget-resize should be placed in the theme package. Closes #6744.

Widget resize visual styles moved to the theme package.

---

packages/ckeditor5-image/src/imageresize/imageresizehandles.js
packages/ckeditor5-image/tests/imageresize/imageresizehandles.js

Fix (image): Fixed image resizer for images with links. Closes #8749.

Fixed image resizer for images with links

---

packages/ckeditor5-image/src/imageupload/imageuploadediting.js
packages/ckeditor5-image/src/imageupload/utils.js
packages/ckeditor5-image/tests/imageupload/imageuploadediting.js
packages/ckeditor5-paste-from-office/tests/manual/tickets/7957/1.html
packages/ckeditor5-paste-from-office/tests/manual/tickets/7957/1.js
packages/ckeditor5-paste-from-office/tests/manual/tickets/7957/1.md

Fix (image): Allow pasting an image with data URL scheme in src, if strict CSP rules are defined. Closes #7957.

Allow pasting an image with data URL scheme in src, if strict CSP rules are defined

---

packages/ckeditor5-engine/src/dev-utils/model.js
packages/ckeditor5-engine/tests/dev-utils/model.js

Fix (engine): The setData method in dev-utils/model should support the batchType option. Closes #7947.

Supporting batchType option in the setData method.

---

packages/ckeditor5-clipboard/src/clipboard.js
packages/ckeditor5-clipboard/tests/clipboard.js
packages/ckeditor5-editor-balloon/src/ballooneditor.js
packages/ckeditor5-editor-classic/src/classiceditor.js
packages/ckeditor5-editor-decoupled/src/decouplededitor.js
packages/ckeditor5-editor-inline/src/inlineeditor.js
packages/ckeditor5-engine/src/controller/datacontroller.js
packages/ckeditor5-engine/tests/controller/datacontroller.js
packages/ckeditor5-html-embed/package.json
packages/ckeditor5-html-embed/src/htmlembedediting.js
packages/ckeditor5-html-embed/tests/htmlembedediting.js

Fix (html-embed): Pasting HTML embed widget from the clipboard will not clear its content anymore. Closes #8789.
Feature (engine): New property `DataController#htmlProcessor` is initialized with `HtmlDataProcessor` and assigned to `DataController#processor` by default.
Internal (clipboard): Plugin now uses `HtmlDataProcessor` instance from the `DataController`.
Internal (editor-balloon, editor-classic, editor-inline, editor-decoupled): The `editor.processor` property does is automatically initialized with `HtmlDataProcessor` now.
---
The `DataController` will always keep `HtmlDataProcessor` instance under `editor.data.htmlProcessor` for reuse. The editor can be processed in many ways, but the clipboard plugin always uses `HtmlDataProcessor`. 
The method …

The raw content matchers can be updated through `DataProcessor`

---

packages/ckeditor5-horizontal-line/src/horizontalline.js
packages/ckeditor5-horizontal-line/tests/horizontalline.js
packages/ckeditor5-page-break/src/pagebreak.js
packages/ckeditor5-page-break/tests/pagebreak.js

Fix (horizontal-line): Horizontal line can be selected when no other package uses Widget. Closes #8825.
Fix (page-break): Page break can be selected when no other package uses Widget. Closes #8825.

Horizontal line/Page break can be selected without other plugins using Widget plugin

---

packages/ckeditor5-image/src/imagestyle/converters.js
packages/ckeditor5-image/tests/imagestyle/imagestyleediting.js

Fix (image): Image plugins can be loaded in any order without causing an error. Closes #8270.

Stop upcast conversion early when a model element is not available

---

packages/ckeditor5-theme-lark/theme/ckeditor5-html-embed/htmlembed.css

Fix (html-embed): The raw HTML text in disabled input in iOS Safari should be the same color as in other browsers. Closes #8320.
---
I also slightly increased the contrast, so it meets the WCAG AA requirements.

Overriding Safari's disabled input opacity.

---

docs/_snippets/examples/multi-root-editor.js
docs/framework/guides/custom-editor-creator.md
packages/ckeditor5-core/tests/_utils/classictesteditor.js
packages/ckeditor5-core/tests/_utils/modeltesteditor.js
packages/ckeditor5-core/tests/_utils/virtualtesteditor.js
packages/ckeditor5-core/tests/editor/utils/attachtoform.js
packages/ckeditor5-core/tests/editor/utils/dataapimixin.js
packages/ckeditor5-core/tests/editor/utils/elementapimixin.js
packages/ckeditor5-ui/docs/_snippets/examples/bootstrap-ui-inner.js
packages/ckeditor5-ui/docs/framework/guides/external-ui.md
packages/ckeditor5-watchdog/tests/editorwatchdog.js

Tests: Remove unnecessary processor initialization. Closes #8834.
Docs: Remove unnecessary processor initialization in examples and snippets. Closes #8834.

Remove unnecessary processor initialization in editor

---

packages/ckeditor5-link/src/linkui.js

Other (link): Fake selection marker for collapsed and non-collapsed selections for link UI should be converted separately. Closes #8092.
---
The problem with downcasting `link-ui` marker was that two separate converters were defined for the same marker:
*   `markerToHighlight` - for the non collapsed selection.
*   `markerToElement` - for the collapsed selection (but this converter also works correctly for non collapsed selection - it inserts elements at both ends of the marker range).

Fake selection marker for collapsed and non-collapsed selections for link UI should be converted separately

---

package.json
packages/ckeditor5-alignment/package.json
packages/ckeditor5-autoformat/package.json
packages/ckeditor5-basic-styles/package.json
packages/ckeditor5-build-balloon-block/package.json
packages/ckeditor5-build-balloon/package.json
packages/ckeditor5-build-classic/package.json
packages/ckeditor5-build-decoupled-document/package.json
packages/ckeditor5-build-inline/package.json
packages/ckeditor5-ckfinder/package.json
packages/ckeditor5-code-block/package.json
packages/ckeditor5-core/package.json
packages/ckeditor5-font/package.json
packages/ckeditor5-heading/package.json
packages/ckeditor5-horizontal-line/package.json
packages/ckeditor5-html-embed/package.json
packages/ckeditor5-image/package.json
packages/ckeditor5-indent/package.json
packages/ckeditor5-markdown-gfm/package.json
packages/ckeditor5-media-embed/package.json
packages/ckeditor5-page-break/package.json
packages/ckeditor5-restricted-editing/package.json
packages/ckeditor5-table/package.json
packages/ckeditor5-theme-lark/package.json
packages/ckeditor5-watchdog/package.json
packages/ckeditor5-word-count/package.json

Internal: Fixed unused or misplaced dependencies and added dependency checker to Husky. See: #8817.
---
Fixes and improvements in dependency checker are done in https://github.com/ckeditor/ckeditor5-dev/pull/687. This PR only contains fixes found by improved dependency checker.
**Important note**: as this PR adds dependency checker to Husky in `pre-commit` hook, before merging this PR new version of `ckeditor5-dev` (containing improved dependency checker) must be released and used in `ckeditor5` repo. Otherwise, the old dependency checker will not be able to handle absolute paths provided by `lint-staged` and will crash.

Fixed unused or misplaced dependencies and added dependency checker to Husky

---

packages/ckeditor5-page-break/src/pagebreakediting.js
packages/ckeditor5-page-break/tests/pagebreakediting.js

Fix (page-break): Drag and dropping image on Page Break divider is no longer crashing the editor. Closes #8788.
⚠️ Merge this, then related PRs! ⚠️

Render page break label as an UI element

---

package.json

Internal: Dependency checker logs are limited to show only errors and warnings in `pre-commit` hook. See #8862.
---
The `--quiet` flag, which is now used in the `pre-commit` hook, has been added in https://github.com/ckeditor/ckeditor5-dev/pull/688.
**Important note**: this PR requires changes from `ckeditor5-dev` ☝🏻.

Dependency checker improvements

---

packages/ckeditor5-core/src/plugincollection.js
packages/ckeditor5-core/tests/plugincollection.js

Internal: Do not log plugin errors thrown in initialization phase twice. Closes #8680.

Do not log plugin errors thrown in initialization phase twice

---

packages/ckeditor5-engine/docs/framework/guides/deep-dive/schema.md

Docs (engine): Fixed missing bracket.

Fixed missing bracket in docs.

---

docs/_snippets/assets.js
packages/ckeditor5-block-quote/docs/_snippets/features/block-quote.js
packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.js

Fix (docs): Hide a toolbar tooltip when focusing the editable. Closes #8883.
---

Hide a toolbar tooltip when focusing the editable.

---

docs/builds/guides/frameworks/angular.md

Closes: ckeditor/ckeditor5-angular#243
Updated information about old Angular integration versions support dropped.

Docs: Angular integration update.

---

packages/ckeditor5-list/docs/_snippets/features/todo-list.html

A pretty image of a delicious waffle has been restored in the documentation after it got accidentally unlinked during some unrelated operations.

Docs: the restoration of the waffle.

---

scripts/release/changelog.js

Internal: Parse `external/ckeditor5-internal` repository while generating the changelog.
---
Requires https://github.com/ckeditor/ckeditor5-dev/pull/689.

Parse `external/ckeditor5-internal` repository while generating the changelog

---

packages/ckeditor5-engine/src/view/placeholder.js
packages/ckeditor5-engine/tests/view/placeholder.js
packages/ckeditor5-engine/theme/placeholder.css

Improve the Placeholder behavior to keep shown when focused.

---

packages/ckeditor5-watchdog/package.json

Internal: Fixed docs due to invalid dependency versions in `ckeditor5-watchdog`. Closes #8980.

Fixed docs due to invalid dependency versions in `ckeditor5-watchdog`

---

packages/ckeditor5-image/src/autoimage.js
packages/ckeditor5-image/tests/autoimage.js

Other autoimage.js: Adds WEBP support to the inline pasting of images from source URLs.

Add WEBP support to autoimage

---

packages/ckeditor5-table/src/converters/downcast.js

Previously, it was possible for table cells to be entirely empty.
However, a recent change introduced in 93dbbf99 changed the evaluation order for table cell children.
This led to calling `hasAnyAttribute` on a null reference, which is not supported.
Move `isSingleParagraph` check prior to `hasAnyAttribute`. `isSingleParagraph` is correctly calculated because it relies on the `childCount` for the table cell.
Fixes #8941
Fixes #8917

Fix (table): Support cells without children

---

packages/ckeditor5-engine/src/view/placeholder.js
packages/ckeditor5-engine/tests/view/placeholder.js

Internal (placeholder): Placeholder should not be visible if there are multiple elements in the root. Closes #9009.
---

Placeholder should not be visible if there are multiple elements in the root

---

packages/ckeditor5-engine/src/view/placeholder.js
packages/ckeditor5-engine/tests/view/placeholder.js

Internal (engine): Direct placeholder should precede indirect one. Closes #9046.
---

Direct placeholder should precede indirect one

---

packages/ckeditor5-engine/theme/placeholder.css

Internal (engine): Placeholder should render properly in text elements aligned to the right. Closes #9048.
---

Fix for placeholder inside node aligned to the right

---

packages/ckeditor5-font/docs/features/font.md
packages/ckeditor5-font/src/fontcolor/fontcolorediting.js
packages/ckeditor5-font/src/fontfamily/fontfamilyediting.js
packages/ckeditor5-font/src/fontsize/fontsizeediting.js
packages/ckeditor5-font/tests/fontcolor/fontcolorediting.js
packages/ckeditor5-font/tests/fontfamily/fontfamilyediting.js
packages/ckeditor5-font/tests/fontsize/fontsizeediting.js

Feature (font): Add `<font>` styling compatibility. Closes #8621.
---

Allow loading `<font>` tag styling

---

packages/ckeditor5-page-break/src/pagebreakediting.js
packages/ckeditor5-page-break/tests/pagebreakediting.js

Fix (page-break): Fixed rendering editor placeholder inside page break widget. Closes #8880.
---

Fixed rendering editor placeholder inside page break widget.

---

packages/ckeditor5-alignment/docs/features/text-alignment.md
packages/ckeditor5-alignment/src/alignment.js
packages/ckeditor5-alignment/src/alignmentediting.js
packages/ckeditor5-alignment/src/alignmentui.js
packages/ckeditor5-alignment/src/utils.js
packages/ckeditor5-alignment/tests/alignmentediting.js
packages/ckeditor5-alignment/tests/manual/alignment.js
packages/ckeditor5-alignment/tests/utils.js
packages/ckeditor5-engine/src/conversion/conversion.js

Feature (alignment): Add option to use classes instead of inline styles. Closes #8516.
---

Handle alignment with classes

---

packages/ckeditor5-editor-balloon/README.md

Closes #9126
Typo in `BalloonEditor` in `packages/ckeditor5-editor-balloon/README.md`

Docs (editor-balloon): Fix package name / url

---

packages/ckeditor5-upload/src/filerepository.js

Closes #9127
Fix typo in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-filerepository-no-upload-adapter

chore(ckeditor5-upload): Fix typo

---

docs/builds/guides/migration/migration-from-ckeditor-4.md
docs/builds/guides/migration/migration-to-26.0.0.md
docs/umberto.json
packages/ckeditor5-core/src/plugincollection.js
packages/ckeditor5-core/tests/plugincollection.js
packages/ckeditor5-utils/src/keyboard.js

Docs: Introduced "Migration" section and the guide regarding migration to 26.0.0. Reviewed `plugincollection-soft-required`. Closes #8902.

Migration guide for 26.0.0 + plugincollection-soft-required docs improved

---

scripts/web-crawler/index.js
scripts/web-crawler/spinner.js
scripts/web-crawler/utils.js

Other: Decreased the size of output log from web crawler. Closes #9062.
Feature: New CLI switch `--quit` (`-q`) to terminate the web crawler scan as soon as the first error is found.
---
From now on, only the first line of the error message will be displayed. My observations shows, that it is completely sufficient and it helps to quickly find out the cause of the error, especially if the log contains a lot of entries.
I chose **not to add** a "verbose" CLI switch, which would display the entire call stack with an error, as I found it of little use. It is certainly not needed to integrate the web crawler with CI, which we are focusing on now.
Instead, I added a new switch `--quit` (`-q`) so that we can finish scanning as soon as the first error is detected. This CLI switch will shorten the …

Decreased the size of output log from web crawler

---

docs/framework/guides/contributing/development-environment.md
package.json
scripts/web-crawler/index.js

Docs: Updated docs for web crawler. Closes #9171.
Internal: Better navigation detection in web crawler.
Internal: Bumped `puppeteer` version to `^8.0.0`.

Updated docs for web crawler and better navigation detection

---

docs/assets/snippet-styles.css

Docs (ckeditor5): Got rid of the heading style overrides in favor of less inclusive heading styles in Umberto. Closes #9091.
---
Requires cksource/umberto#900.

#9091: Got rid of the heading style overrides in favor of less inclusive heading styles in Umberto

---

packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js
packages/ckeditor5-widget/src/utils.js
packages/ckeditor5-widget/tests/utils.js

Feature (widget): Added attributes support in default markers highlight downcast conversion for widgets. Closes #8362.

Added attributes support in default markers highlight downcast conversion for widgets

---

packages/ckeditor5-engine/src/controller/datacontroller.js
packages/ckeditor5-engine/tests/controller/datacontroller.js

Fix (engine): `DataController#toView()` should have a default value for the `options` parameter. Closes #9293.

`DataController#toView()` should have a default value for the `options` parameter

---

packages/ckeditor5-autoformat/docs/features/autoformat.md
packages/ckeditor5-list/docs/features/todo-lists.md
packages/ckeditor5-markdown-gfm/docs/features/markdown.md

Docs (list). Adding Markdown marker information. Closes #9281 
Docs (autoformat).  Adding Markdown marker information.
Docs (markdown-gfm). Removing known issues information. Closes #9283
---
New marker `[x]` information added to the guides. Removed outdated horizontal line information from guide.

Docs: markdown update.

---

packages/ckeditor5-clipboard/src/dragdrop.js
packages/ckeditor5-clipboard/tests/dragdrop.js
packages/ckeditor5-widget/src/widget.js
packages/ckeditor5-widget/tests/widget.js

Internal (clipboard): Drag and drop is disabled on Android. Closes #9287.
Internal (clipboard): Fixed setting drop effect while dragging in non-Gecko browsers. Closes #9270.
Internal (clipboard): Fixed crash while dragging removed element.
Internal (widget): Fixed selection jumping to the first table cell on selection handle click on Android.
---

Fixed Drag & Drop issues

---

docs/_snippets/builds/frameworks/framework-integration.js
docs/builds/guides/frameworks/angular.md
docs/builds/guides/frameworks/react.md
docs/builds/guides/frameworks/vuejs-v2.md
docs/builds/guides/frameworks/vuejs-v3.md
scripts/web-crawler/constants.js
scripts/web-crawler/index.js
scripts/web-crawler/spinner.js

Internal: Added retries in crawler in case of an error. Closes https://github.com/cksource/ckeditor5-internal/issues/687.
---
From now on, the crawler will try to open the page up to 3 times when it encounters an error to eliminate various random causes of these errors.
All NPM badges in the documentation (except the API, which is not scanned by default by the crawler) have been converted to `<img src="..." alt="..." loading="lazy">` tags. The `loading="lazy"` attribute has been added, so these resources do not delay the `load` event anymore.
Additionally, request failures from `badge.fury.io` domain are now ignored.

Added retries in crawler in case of an error

---

packages/ckeditor5-editor-balloon/src/ballooneditor.js
packages/ckeditor5-editor-balloon/tests/ballooneditor.js
packages/ckeditor5-editor-classic/src/classiceditor.js
packages/ckeditor5-editor-classic/tests/classiceditor.js
packages/ckeditor5-editor-decoupled/src/decouplededitor.js
packages/ckeditor5-editor-decoupled/tests/decouplededitor.js
packages/ckeditor5-editor-inline/src/inlineeditor.js
packages/ckeditor5-editor-inline/tests/inlineeditor.js

Fixed: `config.initialData` was skipped when set to an empty string and DOM data was used instead. Closes #8974.
---
Alternative commit message:
Fixed: Editor was not initialized with empty data for `config.initialData` set to an empty string.

config.initialData was skipped when set to an empty string and DOM data was used instead

---

packages/ckeditor5-list/src/listcommand.js
packages/ckeditor5-list/tests/listcommand.js

Internal: Introduced the `config.forceValue` option to `ListCommand` that allows overriding the default toggle-like behavior to allow more predictable state changes during applying track changes suggestions.
---

Add support for the `config.forceValue` option in `ListCommand`

---

packages/ckeditor5-image/src/imagestyle/imagestylecommand.js
packages/ckeditor5-image/tests/imagestyle/imagestylecommand.js

Fix (image): The whole action of the `imageStyle` command (changing the image type and its style) should be undone in one step. Closes #9322.

Executing the imageType command from the model.change callback.

---

packages/ckeditor5-page-break/src/pagebreakediting.js
packages/ckeditor5-page-break/tests/pagebreakediting.js

Internal (page-break): Upcast converter will be less strict when checking if a view element should be converted to the model. Closes #9385.

Page break: make upcast converter less strict

---

packages/ckeditor5-image/docs/framework/guides/deep-dive/upload-adapter.md
packages/ckeditor5-image/src/imageupload/imageuploadediting.js
packages/ckeditor5-image/tests/imageupload/imageuploadediting.js
packages/ckeditor5-upload/src/adapters/simpleuploadadapter.js
packages/ckeditor5-upload/src/filerepository.js
packages/ckeditor5-upload/tests/adapters/simpleuploadadapter.js

Feature (image): Introduced the `uploadComplete` event in `ImageUploadEditing` that allows customizing the image element (e.g. setting custom attributes) based on data retrieved from the upload adapter. Closes #5204.
Feature (upload): Upload adapters' `upload` method can now return a promise that resolves to an object with additional properties along with the `urls` array. See more in #5204.
MINOR BREAKING CHANGE (upload): The `SimpleUploadAdapter#upload()` returns now a promise that resolves to an object with normalized data including the `urls` array, which was only returned before. This may affect all integrations depending on the `SimpleUploadAdapter` uploading mechanism.
---

Introduce the uploadComplete event in ImageUploadEditing

---

packages/ckeditor5-alignment/docs/features/text-alignment.md
packages/ckeditor5-alignment/src/alignmentediting.js
packages/ckeditor5-alignment/tests/alignmentediting.js

Feature (alignment): Added support for deprecated `align` attribute. Closes #9193.

Added support for deprecated `align` attribute

---

packages/ckeditor5-clipboard/src/dragdrop.js
packages/ckeditor5-clipboard/tests/dragdrop.js

Fix (clipboard): Fixed changing selection in read-only mode. Closes #9372.
Fix (clipboard): Nested editable should not be dragged. Closes #9370.
---

Fixed dragging text in read-only mode. Fixed dragging nested editable.

---

packages/ckeditor5-restricted-editing/docs/_snippets/features/restricted-editing.js

Docs. Closes #9280.
---
Moving the toolbar tooltip to stay in place when switching between modes in restricted editing demo.

Docs: fixing toolbar tooltip for restricted editing.

---

packages/ckeditor5-alignment/tests/integration.js
packages/ckeditor5-engine/src/conversion/upcasthelpers.js
packages/ckeditor5-engine/tests/conversion/upcasthelpers.js
packages/ckeditor5-font/tests/fontcolor/fontcolorediting.js
packages/ckeditor5-highlight/tests/highlightediting.js
packages/ckeditor5-language/tests/textpartlanguageediting.js

Fix (engine): While setting attributes upon upcast conversion, don't override attributes that were already set. The correct behavior is to keep the "information" applied by the deepest nodes in the view tree as, in most cases, the deepest node will have precedence (e.g. inline style applied by the deepest node). Closes #8921.
---
Calling:
```js
editor.setData(`<span style="font-family:'helvetica';"> <span style="color:#0000ff;"> <span style="font-size:16px;font-family:'arial';color:#000000;"> aaa </span> </span> </span>`)
```
in the [all features manual test](http://localhost:8125/ckeditor5/tests/manual/all-features.html) with the following changes:
```diff
diff --git a/tests/manual/all-features.js b/tests/manual/all-features.js
index d40a704ce3..c1b8a76565 100644
--- …
```

Conversion:elementToAttribute: do not overwrite an attribute that is already specified

---

packages/ckeditor5-core/src/multicommand.js

`_getFirstEnabledCommand` may return `undefined`, but `execute` does not check if returned value is defined.
Not encountered as a bug, but found will creating Typescript typings.

Fix (ckeditor5-core): check that command exists in multicommand execute

---

packages/ckeditor5-table/tests/manual/table.md
packages/ckeditor5-theme-lark/theme/ckeditor5-widget/widget.css
packages/ckeditor5-widget/tests/widget.js
packages/ckeditor5-widget/theme/widget.css

Fix (widget): Hide selection handle in nested widget, if outer widget is hovered or selected. Closes #9453.
---
I wasn't sure, if this change should only apply to nested tables, or be global. I chose the latter option and now all nested widgets will look the same.
https://user-images.githubusercontent.com/56868128/114510908-839a6480-9c37-11eb-8102-9061b04328a4.mp4

Hide selection handle in nested widget, if outer widget is hovered or selected

---

.travis.yml
scripts/ci/check-packages-code-coverage.js
scripts/ci/travis-check.js
scripts/docs/build-and-publish-nightly.js

Internal: Split Travis jobs into two machines (parallel tasks). Closes cksource/ckeditor5-internal#706.
---

Split Travis jobs into two machines (parallel tasks)

---

packages/ckeditor5-engine/src/controller/datacontroller.js
packages/ckeditor5-engine/src/conversion/downcastdispatcher.js
packages/ckeditor5-engine/src/model/model.js
packages/ckeditor5-engine/src/model/schema.js
packages/ckeditor5-engine/tests/controller/datacontroller.js
packages/ckeditor5-engine/tests/conversion/downcastdispatcher.js
packages/ckeditor5-engine/tests/model/model.js
packages/ckeditor5-engine/tests/model/schema.js

Feature (engine): Enable marker downcast for document fragments. Closes #9460.

Enable marker downcast for document fragments

---

packages/ckeditor5-engine/src/dataprocessor/dataprocessor.jsdoc
packages/ckeditor5-engine/src/dataprocessor/htmldataprocessor.js
packages/ckeditor5-engine/src/dataprocessor/xmldataprocessor.js
packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/src/view/filler.js
packages/ckeditor5-engine/tests/dataprocessor/htmldataprocessor.js
packages/ckeditor5-engine/tests/dataprocessor/xmldataprocessor.js
packages/ckeditor5-engine/tests/view/domconverter/domconverter.js
packages/ckeditor5-engine/tests/view/domconverter/view-to-dom.js
packages/ckeditor5-markdown-gfm/src/gfmdataprocessor.js
packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/gfmdataprocessor.js

Feature (engine): Introduced new block filler mode "markedNbsp" in `DomConverter`, in which `<span data-cke-filler="true">&nbsp;</span>` are inserted, to prevent leaking extra space characters into the data.
Feature (engine): Introduced `useFillerType()` in `HtmlDataProcessor` and `XmlDataProcessor` to switch between using marked and regular nbsp block fillers. Closes #9345.
MINOR BREAKING CHANGE (engine): Added new method `useFillerType()` in `DataProcessor` interface. Classes that base on this interface should implement `useFillerType()` to avoid errors.

Introduced "markedNbsp" block filler mode

---

packages/ckeditor5-engine/docs/_snippets/framework/extending-content-custom-element-converter.js
packages/ckeditor5-engine/docs/framework/guides/deep-dive/custom-element-conversion.md

Docs (engine): The widget type around feature should work in the "Custom element conversion guide". Closes [#9444](https://github.com/ckeditor/ckeditor5/issues/9444).
---
Extracted from #9445 to be merged directly to `stable`.

The widget type around feature should work in the "Custom element conversion guide"

---

packages/ckeditor5-widget/src/widgettypearound/widgettypearound.js
packages/ckeditor5-widget/tests/widgettypearound/widgettypearound.js

Fix (widget): Pasting plain text while the widget fake caret is active should not remove the widget. Closes #9477.
---

Pasting plain text while the widget fake caret is active should not remove the widget

---

packages/ckeditor5-markdown-gfm/docs/_snippets/features/markdown.html

Docs (markdown-gfm): Fixed demo display error. Closes #9487.

Docs: fixed code block in Markdown output demo.

---

packages/ckeditor5-engine/src/view/stylesmap.js

This error is triggering an empty value in docs.
https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_stylesmap-StylesMap.html

Fix jsdoc isEmpty getter

---

packages/ckeditor5-engine/src/view/stylesmap.js

This error is triggering a duplicate value in docs.
https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_stylesmap-StylesProcessor.html

stylesmap.js Remove duplicate jsdoc getReducedForm

---

packages/ckeditor5-block-quote/docs/_snippets/features/nested-block-quote.html
packages/ckeditor5-block-quote/docs/features/block-quote.md
packages/ckeditor5-engine/docs/framework/guides/deep-dive/schema.md

Docs (block-quote): nested block quotes functionality description.

Docs nested blockquotes fix

---

packages/ckeditor5-engine/src/view/styles/border.js
packages/ckeditor5-engine/src/view/styles/utils.js
packages/ckeditor5-engine/tests/view/styles/border.js
packages/ckeditor5-paste-from-office/tests/_data/table/tablecellproperties/model.html
packages/ckeditor5-table/src/converters/tableproperties.js
packages/ckeditor5-table/src/tablecellproperties/tablecellpropertiesediting.js
packages/ckeditor5-table/src/tableproperties/tablepropertiesediting.js
packages/ckeditor5-table/tests/tablecellproperties/commands/tablecellbordercolorcommand.js
packages/ckeditor5-table/tests/tablecellproperties/commands/tablecellborderstylecommand.js
packages/ckeditor5-table/tests/tablecellproperties/commands/tablecellborderwidthcommand.js
packages/ckeditor5-table/tests/tablecellproperties/tablecellpropertiesediting.js
packages/ckeditor5-table/tests/tableclipboard-paste.js
packages/ckeditor5-table/tests/tableproperties/commands/tablebordercolorcommand.js
packages/ckeditor5-table/tests/tableproperties/commands/tableborderstylecommand.js
packages/ckeditor5-table/tests/tableproperties/commands/tableborderwidthcommand.js
packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js

Other (table): Border definitions produced by the `TableProperties` and `TableCellProperties` features will be merged into a group if possible. Instead of producing `border-(top|right|bottom|left):*` selectors, the `border:*` definition will be returned. See #9490.
Fix (engine): The `view.Element#getNormalizedStyle()` will return the merged `border` definition produced if all its properties (width, style, and color) are specified. Otherwise, `border-(width|style|color)` definition should be returned. Closes #9490.
MINOR BREAKING CHANGE (table): Values for the `borderColor`, `borderStyle`, and `borderWidth` attributes are unified (to values produced by the editor itself) while upcasting the table or table cells if all borders (top, right, bottom, and left) have the same values. Previously, …

Border properties will be merged into the single group if possible

---

packages/ckeditor5-image/src/imageutils.js
packages/ckeditor5-image/tests/imageutils.js
packages/ckeditor5-link/tests/linkimageui.js
packages/ckeditor5-widget/src/widget.js
packages/ckeditor5-widget/tests/widget-integration.js
packages/ckeditor5-widget/tests/widget.js
packages/ckeditor5-widget/tests/widgetresize.js

Fix (widget): Selected inline widgets wrapped in an attribute in the view should create a fake selection. Closes #9524. Closes #9521.

#9524: Selected inline widgets wrapped in an attribute in the view should create a fake selection

---

packages/ckeditor5-engine/src/view/renderer.js
packages/ckeditor5-engine/tests/view/renderer.js

This loop was doing unsafe removals of DOM nodes while iterating over indices that point into a live `NodeList`, and was causing a crash in certain cases.
The error is:
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at Function.from (<anonymous>)
at Renderer._updateAttrs (webpack:///./packages/ckeditor5-engine/src/view/renderer.js?:19:11593)
at Renderer.render (webpack:///./packages/ckeditor5-engine/src/view/renderer.js?:19:2390)
```
and it can happen when this loop ends up setting up an incorrect mapping from a view element to a text node, and then `_updateAttrs()` is called on that text node.
The factors that I've identified that will cause this to reproduce are:
* Enough nodes to make `_diffNodeLists()` use the fastDiff implementation
* A render …

Fix crash in renderer

---

packages/ckeditor5-image/src/image/utils.js
packages/ckeditor5-image/tests/image/imageinlineediting.js
packages/ckeditor5-image/tests/image/utils.js

Other (image): When inserting an image in an empty list item, the `inlineImage` element will be used as the default type of image. Closes #9391.

Inserting the inline image in the empty list item

---

packages/ckeditor5-image/src/imagestyle/converters.js
packages/ckeditor5-image/tests/imagestyle/imagestyleediting.js

Fix (image): Pasting an image without the source attribute will not break the editor. Closes #9563.

Pasting an image without the source attribute will not break the editor

---

packages/ckeditor5-code-block/package.json
packages/ckeditor5-code-block/src/codeblockcommand.js
packages/ckeditor5-code-block/src/codeblockediting.js
packages/ckeditor5-code-block/tests/codeblock-integration.js
packages/ckeditor5-code-block/tests/codeblockcommand.js
packages/ckeditor5-code-block/tests/codeblockediting.js

Fix (code-block): The code block feature will not allow for inserting inline images as its content. Closes #9567.

Do not insert inline images inside code blocks

---

packages/ckeditor5-link/src/linkimageui.js
packages/ckeditor5-link/src/linkui.js
packages/ckeditor5-link/tests/linkimageui.js
packages/ckeditor5-link/tests/linkui.js
packages/ckeditor5-widget/tests/manual/inline-widget.js

Fix (link): The link UI should be shown when clicking a linked inline widget. Closes #9607.

Link UI should be shown when clicking a linked inline widget

---

packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/src/model/treewalker.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js

Other (engine): In marker-to-data conversion, attributes for marker boundaries will be used every time the marker starts or ends before or after a model element, instead only where text is not allowed by model schema. Closes #9622.

Change marker-to-data logic to improve conversion inside document fragment

---

packages/ckeditor5-autoformat/docs/features/autoformat.md
packages/ckeditor5-markdown-gfm/docs/features/markdown.md

Docs (autoformat): Linking to Markdown blog post.
Docs (markdown-gfm): Linking to Markdown blog post.
Also crosslinking the guides for better discoverability.

Docs: linking Markdown blogpost to docs.

---

packages/ckeditor5-list/docs/features/lists.md
packages/ckeditor5-list/docs/features/todo-lists.md

Docs: linking lists blog post in the documentation.
---
Part of the feature discoverability improvement epic. Includes expanded introduction and links to the dedicated blog post.

Docs: linking list blog post to docs.

---

packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md

Docs: linking blog post in the documentation.
---
Part of the feature discoverability improvement epic. Linking the Pagination blogpost showcasing usage of restricted editing to create user-interactive tmeplates.

Docs: linking blog post to docs.

---

docs/framework/guides/contributing/testing-environment.md

Docs: Cleaning up option names in Testing environment docs.  
Added the aliases as well to unify this section of the documentation. Closes #8885
---

Cleaning up option names in Testing environment docs I/8885

---

docs/builds/guides/integration/features-html-output-overview.md
scripts/docs/features-html-output/build-features-html-output.js

Internal: Fixed source files links in features HTML output script. See #9414.
---
The source file can be:
- a link to the `ckeditor5-metadata.json` on GitHub:
- just a text for external or third-party packages:
- a text *"not published yet"* for third-party packages, when the `ckeditor5-metadata.json` file is not available in locally installed package in `node_modules`:

Fixed source files links in features HTML output script

---

packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/tests/linkediting.js

Fix (link): All text attributes starting their names with `link` will be removed when typing over a link or clicking at the end of the link. Closes #8462.

Remove all link* attributes when interacting with link boundaries

---

packages/ckeditor5-list/src/liststyleediting.js
packages/ckeditor5-list/tests/liststyleediting.js

Fix (list): Fixed a crash when spelling a word inside the list item. Closes #9325.

Spelling a word inside list item will not crash

---

packages/ckeditor5-html-embed/src/htmlembedediting.js
packages/ckeditor5-html-embed/tests/htmlembedediting.js
packages/ckeditor5-html-embed/tests/manual/htmlembed.html
packages/ckeditor5-html-embed/tests/manual/htmlembed.js

Fix (html-embed): Allows rendering the `<script>` element inside the HTML preview. Closes #8326.

Allows rendering the <script> element inside the HTML preview

---

packages/ckeditor5-watchdog/src/contextwatchdog.js

Replace with WatchdogItemConfiguration that is used as a param for the
`add` method.

Remove redundant/unused EditorWatchdogConfiguration

---

docs/builds/guides/migration/migration-from-ckeditor-4.md
docs/builds/guides/migration/migration-to-25.md
docs/builds/guides/migration/migration-to-26.md
docs/builds/guides/migration/migration-to-27.md
docs/builds/index.md

Docs: Reversing migration guides order in TOC. Closes #9550.
Docs: Extending the build landing page just a tiny little bit. Partially addresses cksource/docs#368

Docs: migration guides order

---

packages/ckeditor5-engine/src/conversion/upcasthelpers.js
packages/ckeditor5-engine/tests/conversion/upcasthelpers.js
packages/ckeditor5-table/tests/table-integration.js

Fix (engine): Added checks for the upcast attribute to marker converter before changing the data and consuming view elements. Part of the #9779.
---

Added checks for the upcast attribute to marker converter before the view consumption

---

docs/builds/guides/migration/migration-to-28.md

Internal: Added the migration guide to v28.0.0. Closes #9759.

Migration to 28.0.0

---

docs/builds/guides/integration/features-html-output-overview.md
packages/ckeditor5-table/ckeditor5-metadata.json

Internal: Added metadata and HTML output for the TableCaption. Closes #9806.
---

Add metadata and HTML output for the TableCaption

---

packages/ckeditor5-engine/src/model/utils/insertcontent.js
packages/ckeditor5-engine/tests/model/utils/insertcontent.js
packages/ckeditor5-image/src/image/imageinlineediting.js
packages/ckeditor5-image/tests/image/imageinlineediting.js

Fix (engine,image): Disallowed inline images in `caption` elements. Closes #9794.
---
Adding the schema check in `ImageInlineEditing` revealed a bug in `insertContent` resulting in infinite loops. When an inline image was disallowed in the caption (a limit), the algorithm attempted to autoparagraph it in that caption on a (wrong) assumption that the paragraph is allowed there. Then, since that failed, the algorithm decomposed that paragraph, reached the inline image inside, and autoparagraphed it again on a wrong assumption... This PR also addresses this issue.

#9794: Disallow inline images in captions

---

packages/ckeditor5-image/src/imageresize/imageresizehandles.js
packages/ckeditor5-image/tests/imageresize/imageresizehandles.js

Fix (image): The image should not resize to 100% if the resize command was overridden (canceled). 
---

CF/3390: The image should not resize to 100% if the resize command was overridden

---

packages/ckeditor5-code-block/src/codeblockcommand.js
packages/ckeditor5-code-block/src/codeblockui.js
packages/ckeditor5-code-block/tests/codeblock-integration.js
packages/ckeditor5-code-block/tests/codeblockcommand.js
packages/ckeditor5-code-block/tests/codeblockui.js

Feature (code-block): When inserting a new code block, instead of applying the default language (the first in the dropdown view), the feature re-use the previously inserted language. Closes #8722.

Added the option to remember the language when creating a new code block.

---

docs/builds/guides/frameworks/react.md

Docs: Added a note about resolving the heap out of memory error in the React integration guide. See #9808.

Resolving "heap out of memory" error when building React app

---

packages/ckeditor5-engine/src/view/element.js
packages/ckeditor5-engine/src/view/matcher.js
packages/ckeditor5-engine/src/view/styles/background.js
packages/ckeditor5-engine/src/view/stylesmap.js
packages/ckeditor5-engine/tests/view/element.js
packages/ckeditor5-engine/tests/view/matcher.js
packages/ckeditor5-engine/tests/view/stylesmap.js

Feature (engine): Improved engine view matcher with new pattern syntax allowing to match attribute keys using regular expressions. Unified pattern syntax between attributes, styles, and classes. Closes #9872.
Feature (engine): Added special `expand` option to `StylesMap.getStyleNames()` and view `Element.getStyleNames()` methods allowing to expand shorthand style properties.
---
* Adding missing test suite to `StylesProcessor` will be handled in the follow-up: https://github.com/ckeditor/ckeditor5/issues/9811.
* Exclusion of `style` and `class` attributes is reverted back to original form. There is a follow-up, where we'll decide how to approach this: https://github.com/ckeditor/ckeditor5/issues/9813.

Improve engine view matcher with new pattern syntax

---

packages/ckeditor5-restricted-editing/src/restrictededitingmode/converters.js
packages/ckeditor5-restricted-editing/tests/restrictededitingmodeediting.js

Fix (restricted-editing): Editor will not crash when restircted area marker is removed. Closes #9650.

Editor will not crash when restircted area marker is removed

---

docs/builds/guides/migration/migration-to-29.md

Docs: The migration guide should link properly to the image feature page. Closes #9915.
---

Fixed missing links in the migration guide.

---

docs/assets/snippet-styles.css
packages/ckeditor5-html-embed/theme/htmlembed.css
packages/ckeditor5-image/theme/image.css
packages/ckeditor5-media-embed/theme/mediaembed.css
packages/ckeditor5-table/theme/table.css
packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/editorui/editorui.css

Docs (image): The last element of the editor content should not have the forced `margin: 0` CSS rule. Closes #9825.
---

Removed the unnecessary resetting of the last element's bottom margin.

---

docs/umberto.json

Docs: adding redirect from the removed "What's new?" guide to the features landing page.
Closes: cksource/ckeditor5-internal#789

Docs: redirecting removed guide.

---

packages/ckeditor5-code-block/tests/codeblockediting.js
packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/tests/view/domconverter/domconverter.js
packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/blockquotes.js

Fix (engine): `DomConverter.blockElements` is missing some of the HTML block element names. Closes #9801. Closes #7863.

Expand DomConverter.blockElements with missing elements

---

packages/ckeditor5-engine/src/dataprocessor/htmldataprocessor.js
packages/ckeditor5-engine/tests/dataprocessor/htmldataprocessor.js

Other (engine): Fixed parsing leading HTML comments by `HtmlDataProcessor.toView()`. Closes #9861.

Move leading comment nodes into the document fragment

---

packages/ckeditor5-html-support/src/datafilter.js
packages/ckeditor5-html-support/tests/datafilter.js

Fix (html-support): Existing features no longer breaks GHS attributes filtering.

[GHS] Existing features shouldn't break attribute filtration

---

docs/_snippets/builds/saving-data/autosave.html
docs/_snippets/builds/saving-data/manualsave.html

Docs: fixed broken fake consoles in 'Getting and saving data' demos.
Closes https://github.com/ckeditor/ckeditor5/issues/9938.

Docs: fixed broken fake consoles in demos

---

packages/ckeditor5-find-and-replace/src/findandreplaceediting.js
packages/ckeditor5-find-and-replace/tests/findandreplace.js
packages/ckeditor5-find-and-replace/tests/findcommand.js

Internal (find-and-replace): Fixed the issue with restoring highlight artifacts after the undo. Closes #9974.

Fixed the issue with restoring highlight artifacts after the undo

---

packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.js
packages/ckeditor5-find-and-replace/theme/findandreplaceform.css

Fix (find-and-replace): Added CSS styles for RTL editor support for the `find-and-replace` feature. Closes #9981.
---

i/9981: CSS for RTL editor in find and replace feature added

---

packages/ckeditor5-core/lang/contexts.json
packages/ckeditor5-ui/lang/contexts.json

Internal: Moved the context for the `Show more items` message to `ckeditor5-core`. Closes #9991.
---

Move the context for the 'Show more items' message to 'ckeditor5-core'.

---

packages/ckeditor5-source-editing/src/utils/formathtml.js

Internal (source-editing): Removed unnecessary lookbehind and lookahead from regex, which are not supported in Safari. Closes #10033.
---
Marked as `Internal`, because source editing is not yet released.

Removed unnecessary lookbehind and lookahead from regex in source editing

---

README.md
docs/builds/guides/integration/features-html-output-overview.md
packages/ckeditor5-html-support/CHANGELOG.md
packages/ckeditor5-html-support/CONTRIBUTING.md
packages/ckeditor5-html-support/LICENSE.md
packages/ckeditor5-html-support/README.md
packages/ckeditor5-html-support/ckeditor5-metadata.json
packages/ckeditor5-html-support/docs/api/html-support.md
packages/ckeditor5-html-support/package.json
packages/ckeditor5-html-support/webpack.config.js

Internal (html-support): Added missing package files. Closes #10034.
---
* I'm not totally sure how OB works, so I didn't verify if `ckeditor5-metadata.json` works correctly
* I'm not sure if we want to publish API docs of GHS right now as it's in beta stage, but it's required to publish `config.htmlSupport` option

Added missing html-support package files

---

packages/ckeditor5-find-and-replace/src/utils.js

Internal (find-and-replace): Fixed whole word matching for Safari. Closes #10031.

Fixed whole word matching for Safari in find and replace

---

packages/ckeditor5-basic-styles/docs/features/basic-styles.md
packages/ckeditor5-block-quote/docs/features/block-quote.md
packages/ckeditor5-code-block/docs/features/code-blocks.md
packages/ckeditor5-html-embed/docs/features/html-embed.md
packages/ckeditor5-indent/docs/features/indent.md
packages/ckeditor5-table/docs/features/table.md

Docs: Adding toolbar items icons to user guides.
Part of: #10048   
This PR covers the following guides:
*   basic text styles
*   block indentation
*   block quote
*   code blocks
*   HTML embed
*   tables
---
This is a test PR for toolbar items icons adding them in selected few guides.
However, one reviewer should be enough from the technical point of view, so the first one is the winner and we merge.

Add editor icons to guides #01

---

docs/builds/guides/integration/features-html-output-overview.md
packages/ckeditor5-html-support/ckeditor5-metadata.json

Internal (html-support): Added missing metadata files for exposed plugins. Closes #10069.

Add metadata files to html-support

---

packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md
packages/ckeditor5-font/docs/features/font.md
packages/ckeditor5-highlight/docs/features/highlight.md
packages/ckeditor5-horizontal-line/docs/features/horizontal-line.md
packages/ckeditor5-remove-format/docs/features/remove-format.md

Docs: Adding toolbar items icons to user guides.
Part of: [#10048](https://github.com/ckeditor/ckeditor5/issues/10048) 
This PR covers the following guides:
*   font
*   find and replace
*   highlight
*   horizontal line
*   remove formatting
---
One reviewer should be enough from the technical point of view, so the first one is the winner and we merge, but:
*   please read the font guide carefully, as an intro section has been added.

Add editor icons to guides #03

---

packages/ckeditor5-image/src/image/imagetypecommand.js
packages/ckeditor5-image/src/imageupload/imageuploadediting.js
packages/ckeditor5-image/tests/image/imagetypecommand.js
packages/ckeditor5-image/tests/imageupload/imageuploadediting.js

Internal (image): Changing the image type during the upload should not crash the editor. Closes #10013.

Changing the image type during the upload should not crash the editor

---

docs/_snippets/features/mathtype.html
docs/features/math-equations.md
packages/ckeditor5-link/docs/features/link.md
packages/ckeditor5-list/docs/features/lists.md
packages/ckeditor5-list/docs/features/todo-lists.md
packages/ckeditor5-media-embed/docs/features/media-embed.md
packages/ckeditor5-page-break/docs/features/page-break.md

Docs: Adding toolbar items icons to user guides.
Part of: [#10048](https://github.com/ckeditor/ckeditor5/issues/10048) 
This PR covers the following guides:
*   link
*   media embed
*   page break
*   math / chem formulas
*   lists (all 3 of these)
---
One reviewer should be enough from the technical point of view, so the first one is the winner and we merge, but the math/chem icons need more love before merging.

Add editor icons to guides #04

---

packages/ckeditor5-autoformat/src/autoformat.js
packages/ckeditor5-autoformat/tests/autoformat.js

Fix (autoformat): Autoformat will apply the previous language choice for the code block feature. Closes #10005.

Fixed autoformat not remembering previous language choice for codeblock

---

docs/features/spelling-and-grammar-checking.md
packages/ckeditor5-alignment/docs/features/text-alignment.md
packages/ckeditor5-language/docs/features/language.md
packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md
packages/ckeditor5-select-all/docs/features/select-all.md
packages/ckeditor5-special-characters/docs/features/special-characters.md

Docs: Adding toolbar items icons to user guides.
Part of: [#10048](https://github.com/ckeditor/ckeditor5/issues/10048) 
This PR covers the following guides:
*   restricted editing
*   select all
*   special characters
*   text part language (only reworded, no icon)
*   spelling / grammar checking
*   text alignment
---
You know the rules, and so do I.

Add editor icons to guides #05

---

packages/ckeditor5-find-and-replace/package.json
packages/ckeditor5-find-and-replace/src/findandreplaceui.js
packages/ckeditor5-find-and-replace/tests/findandreplaceui.js
packages/ckeditor5-find-and-replace/tests/manual/findandreplace.js
packages/ckeditor5-find-and-replace/tests/manual/findandreplace.md

Fix (find-and-replace): The dropdown button should now be disabled when the source mode is active. Closes #10001.

Find and replace: Source mode integration added, manual test updated

---

.travis.yml

Internal: Limited CI to building only for the following branches: `#master`, `#stable`, and `#release`.

Preventing CI from running twice per PR

---

packages/ckeditor5-find-and-replace/src/findandreplaceui.js
packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.js
packages/ckeditor5-find-and-replace/tests/findandreplaceui.js
packages/ckeditor5-find-and-replace/tests/ui/findandreplaceformview.js

Fix (find-and-replace):  Label animation on view opening has been removed. Closes #10008.
Tests (find-and-replace): Added missing tests for the dropdown's button.

Find and replace: Label won't animate on view opening

---

docs/_snippets/examples/document-editor.html
docs/builds/guides/migration/migration-to-29.md
packages/ckeditor5-image/docs/features/images-linking.md

Docs: The image in the document editor demo should have a proper path for the large size. Closes #10125.
Docs (image): The code snippet in the image linking guide should have a proper indentation. See #10125.
Docs: The UI components' names should be properly named in the code snippet in the v.29 migration guide. See #10125.
---

Various issues related to the documentation discovered after changing images docs.

---

packages/ckeditor5-link/docs/features/link.md

Docs: fixing the `autolink` feature description. Closes #10098.

Docs: autolink feature description fix.

---

packages/ckeditor5-find-and-replace/src/findandreplaceui.js
packages/ckeditor5-find-and-replace/tests/findandreplace.js

Fix (find-and-replace): Find and replace toolbar button now uses `DropdownButtonView`. Closes #10007.

Find and replace: toolbar button is now using DropdownButtonView

---

packages/ckeditor5-theme-lark/package.json

Tests: Changed most theme-lark dependencies into dev-dependencies. Closes #9998.
---
ckeditor5-ui is still marked as regular dependency - see [this](https://github.com/ckeditor/ckeditor5/issues/9998#issuecomment-879026870).

Changed most theme-lark dependencies into dev-dependencies

---

packages/ckeditor5-html-support/package.json
packages/ckeditor5-html-support/src/generalhtmlsupport.js
packages/ckeditor5-html-support/src/integrations/table.js
packages/ckeditor5-html-support/src/schemadefinitions.js
packages/ckeditor5-html-support/tests/manual/pfo-table.html
packages/ckeditor5-html-support/tests/manual/pfo-table.js
packages/ckeditor5-html-support/tests/manual/pfo-table.md
packages/ckeditor5-html-support/tests/manual/table.html
packages/ckeditor5-html-support/tests/manual/table.js
packages/ckeditor5-html-support/tests/manual/table.md
packages/ckeditor5-html-support/tests/table.js

Feature (html-support): Added General HTML Support integration for Tables feature. Closes #9914.
---
No support for `tfooter` as it's not supported by Table feature itself. `caption`/`figcaption` elements are supported by default GHS itself and don't require any additional integration.
The class name for integration (`TableElementSupport`) doesn't follow the same naming pattern as `CodeBlockHtmlSupport` because it's something we are currently changing in https://github.com/ckeditor/ckeditor5/pull/9891 - although I have some small doubts if actually `*HtmlSupport` is not a better name as we are not providing simple element support (which is already done by GHS) but existing feature integration.

[GHS] Table feature integration

---

docs/builds/guides/migration/migration-to-30.md
packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion-extending-output.md
packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion-preserving-custom-content.md
packages/ckeditor5-engine/tests/view/matcher.js
packages/ckeditor5-link/src/link.js
packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/src/linkimageediting.js
packages/ckeditor5-link/src/utils/automaticdecorators.js
packages/ckeditor5-link/src/utils/manualdecorator.js
packages/ckeditor5-link/tests/linkediting.js
packages/ckeditor5-link/tests/linkimageediting.js

Fix (link): Link decorators should use `classes` and `styles` properties instead of directly matching `style` and `class` HTML attributes . Closes #9813.
---
TBC

Link decorators should use `classes` and `styles` properties

---

packages/ckeditor5-widget/src/widgetresize.js
packages/ckeditor5-widget/tests/widgetresize.js

Fix (widget): Remove references to and destroy resizers of widgets no longer in the document. Closes #10156.

Remove references to and destroy resizers of widgets no longer in the document

---

packages/ckeditor5-find-and-replace/src/findandreplaceui.js
packages/ckeditor5-find-and-replace/tests/findandreplaceui.js

Fix (find-and-replace): Fixed the regression caused by changing the split button to a regular dropdown button. Closes #10184.

Find and replace: keyboard shortcut error

---

packages/ckeditor5-table/src/tableediting.js
packages/ckeditor5-table/tests/manual/tickets/10042.html
packages/ckeditor5-table/tests/manual/tickets/10042.js
packages/ckeditor5-table/tests/manual/tickets/10042.md
packages/ckeditor5-table/tests/tableediting.js

Fix (table): Fixed editor freezing when providing non-integer colspan or rowspan attributes values. Closes #10042.
---
Can be tested by running `yarn manual --files=table` and checking `tickets/10042.html` test case.

Fixed editor freezing when providing non-integer colspan or rowspan attributes values

---

docs/builds/guides/migration/migration-to-30.md
packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion-extending-output.md
packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion-preserving-custom-content.md
packages/ckeditor5-engine/src/view/matcher.js
packages/ckeditor5-engine/tests/view/matcher.js
packages/ckeditor5-html-support/tests/datafilter.js
packages/ckeditor5-link/src/link.js
packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/src/linkimageediting.js
packages/ckeditor5-link/src/utils/automaticdecorators.js
packages/ckeditor5-link/src/utils/manualdecorator.js
packages/ckeditor5-link/tests/linkediting.js
packages/ckeditor5-link/tests/linkimageediting.js

Fix (engine): Matcher shouldn't match style and class attributes with object "attributes" pattern. Closes #9813.
Fix (link): Link decorators should use `classes` and `styles` properties instead of directly matching `style` and `class` HTML attributes . Closes #9813.

Remove `style` and `class` attributes from Matcher `attributes` match

---

packages/ckeditor5-table/src/tableediting.js
packages/ckeditor5-table/tests/table-integration.js

Internal (table): Fixed model mappings in table cell if paragraph is bound to its parent. Closes #10116.

HTML comments: compatibility with empty table cell

---

packages/ckeditor5-html-support/src/htmlcomment.js

Internal (html-support): Fixed JSDoc typedef for HTML comments interface. See #9661.

Fixed JSDoc typedef for HTML comments interface

---

docs/builds/guides/migration/migration-from-ckeditor-4.md
packages/ckeditor5-html-support/docs/features/general-html-support.md

Docs: updating migration fromCKE4 guide.
Docs: mentioning Advanced Content Filtering in the General HTML Support feature guide.
---
This is an MVP solution for cksource/ckeditor5-internal#851 and we do not close it yet, as some more work is introduced in #10168.
Please make sure the automatic link from CKE5 to CKE4 docs does render on production. Might be checked by building docs and testing preview. If it fails, replace it with a regular URL.

Docs: updating migration fromCKE4 guide; mentioning ACF in GHS.

---

packages/ckeditor5-html-support/src/htmlcomment.js
packages/ckeditor5-html-support/tests/htmlcomment-integration.js
packages/ckeditor5-html-support/tests/htmlcomment.js

Internal: Introduced removing HTML comments at the document boundaries when the document content is removed with `editor.data.set()` or `model.removeContent()` . Closes #10117.
---

Introduce removing HTML comments at the document boundaries when the content is removed

---

packages/ckeditor5-utils/src/dom/position.js
packages/ckeditor5-utils/src/dom/rect.js

The constructor for `Rect` shows this example:
```js
document.body.getClientRects().item( 0 )
```
The return type in every browser but IE is [`DOMRect`](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) so I'm adding it to
the possible values of the `Rect` constructor. I'm also adding `Window`
cause `Rect` can handle it.
For the `target` property of `Options` interface, I'm adding the same
types cause that property is used to create a new `Rect`.

JSDoc: Add DOMRect to getOptimalPosition and Rect

---

packages/ckeditor5-table/src/commands/inserttablecommand.js
packages/ckeditor5-table/src/table.js
packages/ckeditor5-table/src/tableediting.js
packages/ckeditor5-table/src/tableutils.js
packages/ckeditor5-table/tests/commands/inserttablecommand.js
packages/ckeditor5-table/tests/manual/tableautoheadings.html
packages/ckeditor5-table/tests/manual/tableautoheadings.js
packages/ckeditor5-table/tests/manual/tableautoheadings.md
packages/ckeditor5-table/tests/tableutils.js

Feature (table): Option in table config to set rows/columns as headings by default. Closes #10039.
---
To test run `yarn manual --files=table/manual/tableautoheadings.js`

Feature (table): Option in table config to set rows/columns as headings by default

---

packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/tests/view/domconverter/dom-to-view.js
packages/ckeditor5-paste-from-office/src/filters/parse.js
packages/ckeditor5-paste-from-office/src/normalizers/googledocsnormalizer.js
packages/ckeditor5-paste-from-office/src/normalizers/mswordnormalizer.js
packages/ckeditor5-paste-from-office/src/pastefromoffice.js
packages/ckeditor5-paste-from-office/tests/_utils/utils.js
packages/ckeditor5-paste-from-office/tests/filters/parse.js
packages/ckeditor5-paste-from-office/tests/pastefromoffice.js
packages/ckeditor5-utils/tests/_utils/normalizehtml.js

Internal (html-support): Fixed compatibility issues with Paste from Office by skipping all comments. Closes #10155.

Fixed compatibility issues with Paste from Office by skipping all comments

---

packages/ckeditor5-autosave/src/autosave.js
packages/ckeditor5-autosave/tests/autosave.js
packages/ckeditor5-autosave/tests/manual/autosave.js

Fix (autosave): Autosave callback should not be called while the editor is initialized. Closes #10214.
Feature (autosave): Introduced \`Autosave#save()\`. Closes #10215.

Autosave improvements

---

packages/ckeditor5-html-support/docs/_snippets/features/general-html-support-source.js
packages/ckeditor5-html-support/docs/_snippets/features/general-html-support.js
packages/ckeditor5-html-support/docs/_snippets/features/html-comment.html
packages/ckeditor5-html-support/docs/_snippets/features/html-comment.js
packages/ckeditor5-html-support/docs/api/html-comment.md
packages/ckeditor5-html-support/docs/features/general-html-support.md
packages/ckeditor5-html-support/docs/features/html-comment.md
packages/ckeditor5-html-support/src/htmlcomment.js

Internal (html-support): Added docs guide for HTML comment feature. Closes #10159.

Added docs guide for HTML comment feature

---

docs/builds/guides/integration/features-html-output-overview.md
packages/ckeditor5-html-support/ckeditor5-metadata.json

Internal (html-support): Added `HtmlComment` plugin to package metadata. Closes #10234.

Added HtmlComment plugin to package metadata

---

packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/src/conversion/upcasthelpers.js
packages/ckeditor5-engine/tests/conversion/upcasthelpers.js

Internal: Undeprecated the `elementToMarker` upcast helper. Improved API docs for `elementToMarker` and `markerToElement` helpers. Closes #10128.
---

Undeprecate the elementToMarker upcast helper and improve API docs

---

packages/ckeditor5-link/src/linkimageediting.js
packages/ckeditor5-link/tests/linkimageediting.js

Internal (link): Linked block image should not trigger `linkHref` `attributeToElement` conversion. Closes #10231.
---

Linked block image should not trigger linkHref attributeToElement conversion

---

packages/ckeditor5-html-support/tests/htmlcomment-integration.js

Internal (html-support): Fixed integration tests in HtmlComment plugin.
---
Changes in whitespace handling caused that 2 integration tests started failing.

Fixed integration tests in HtmlComment plugin

---

packages/ckeditor5-engine/src/model/selection.js

Given that `selectable` existence is checked at the end of the constructor, the argument is optional

jsdoc: Engine>Model>Selection: optional arg in constructor

---

packages/ckeditor5-source-editing/docs/features/source-editing.md
packages/ckeditor5-source-editing/src/sourceediting.js
packages/ckeditor5-source-editing/tests/sourceediting.js

Fix (source-editing): Source Editing plugin will send a warning to the console when Restricted Editing is loaded. Closes #10228.

Warn user if Source Editing is loaded together with Restricted Editing

---

packages/ckeditor5-widget/src/widgetresize.js
packages/ckeditor5-widget/tests/widgetresize.js

Fix (widget): The editor should not crash when a widget with a resizer is moved in the model document. Closes #10266.
---
@ckeditor/qa-team Can you check this out, please?

The editor should not crash when a widget with a resizer is moved in the model document

---

packages/ckeditor5-html-support/src/htmlcomment.js
packages/ckeditor5-html-support/tests/htmlcomment.js

Fix (html-support): Extended schema definition for `$root` to allow storing comment's content as the `$root` attribute. Closes #10274.

Allow storing comment's content as the $root attribute

---

packages/ckeditor5-clipboard/src/utils/normalizeclipboarddata.js
packages/ckeditor5-clipboard/tests/utils/normalizeclipboarddata.js

Fix (html-support): Filtered out all pasted HTML comments. Closes #10213.
---
I chose to use simple regular expression filtering instead of the recently added `skipComments` option in `DomConverter#domToView()`, because:
* to use `skipComments` option in the `ckeditor5-clipboard` package, I would have to make a few more changes: options that are now passed to `DomConverter#domToView()` would have to be additionally passed to `HtmlDataProcessor#toView()` and `XmlDataProcessor#toView()`. Alternatively, the two `toView()` methods could now only accept one `skipComments` option, but a single option would look silly.
* the existing `normalizeClipboardHtml()` function fits perfectly to the initial cleanup of the input data.

Filtered out all pasted HTML comments

---

packages/ckeditor5-source-editing/src/sourceediting.js
packages/ckeditor5-source-editing/tests/sourceediting.js

Fix (source-editing): Selection is now set at the beginning of the source editing view. Closes #10180.
---

Move the selection of source editing textarea to the beginning

---

packages/ckeditor5-minimap/docs/features/minimap.md

Docs: Fixed wrong imports in minimap documentation page. Closes https://github.com/ckeditor/ckeditor5/issues/10320.
---

Docs: fixed wrong minimap imports

---

docs/builds/guides/migration/migration-to-29.md

Docs: Fixed typo in 29.1.0 migration guide. Closes https://github.com/ckeditor/ckeditor5/issues/10347.
---

Docs: fixed typo in 29.1.0 migration guide

---

packages/ckeditor5-highlight/src/highlightcommand.js
packages/ckeditor5-highlight/tests/highlightcommand.js

Other (highlight): Toggling highlight doesn't remove it when the caret is at the end of highlighted range. Closes #2616.

Fixing "Can't use highlight while typing"

---

docs/_snippets/assets.js
package.json

Internal: Added a script for replacing all relative paths to absolute in the documentation executed on each page where live demos are available.
---
Closes cksource/ckeditor5-internal#852.

Replace relative paths to absolute in the live demos

---

packages/ckeditor5-find-and-replace/src/utils.js
packages/ckeditor5-find-and-replace/tests/findcommand.js

Fix (find-and-replace): Allows search term to contain trailing/leading space when searching 'whole word only'. Closes #10131.
---

Ck/10131 Whole word search with spaces

---

packages/ckeditor5-find-and-replace/src/utils.js
packages/ckeditor5-find-and-replace/tests/findcommand.js

Other (find-and-replace): Moves model.change() outside the loop in updateFindResultFromRange(). Closes #10302.
---

Move model.change() outside the loop

---

docs/framework/guides/contributing/git-commit-message-convention.md

Docs (contributing): git commit message convention update.
---
_Closes: cksource/ckeditor5-internal#970_

Docs: git commit message convention update.

---

packages/ckeditor5-engine/src/model/markercollection.js
packages/ckeditor5-engine/tests/model/markercollection.js

Other (engine): The `MarkerCollection#has()` method now also accepts an instance of a marker. Closes #9985.
---

MarkerCollection has() method accept instance of marker

---

packages/ckeditor5-engine/src/view/styles/utils.js
packages/ckeditor5-engine/tests/view/styles/utils.js

Fix (engine): Adds System Colors names from CSS Color Module Level 3 so that pasting tables from MS Word works correctly. Closes #10383.
---

Adds System Colors names

---

packages/ckeditor5-image/src/autoimage.js
packages/ckeditor5-image/tests/autoimage.js
packages/ckeditor5-link/src/autolink.js
packages/ckeditor5-link/tests/autolink.js
packages/ckeditor5-media-embed/src/automediaembed.js
packages/ckeditor5-media-embed/tests/automediaembed.js
packages/ckeditor5-typing/src/delete.js
packages/ckeditor5-typing/src/deleteobserver.js
packages/ckeditor5-typing/src/texttransformation.js
packages/ckeditor5-typing/tests/delete.js
packages/ckeditor5-typing/tests/texttransformation.js

Feature: Allows using backspace to undo certain operations. Closes #10413.
---
_Features that allows undo by backspace:_
*   _Text transformation_
*   _Auto linking_
*   _Auto media embed_
*   _Auto image_

Implementing undo in Delete plugin & TextTransformation & others

---

packages/ckeditor5-ui/src/button/buttonview.js
packages/ckeditor5-ui/tests/button/buttonview.js
packages/ckeditor5-ui/tests/manual/tickets/9412/1.html
packages/ckeditor5-ui/tests/manual/tickets/9412/1.js
packages/ckeditor5-ui/tests/manual/tickets/9412/1.md

Fix (ui): Editor no longer crashes when a button has `withKeystroke` set to `true` but no `keystroke` property is provided. Closes #9412.
---

ButtonView - editor crashed with withKeystroke set to true and keystroke undefined.

---

docs/framework/guides/contributing/git-commit-message-convention.md

Docs: correcting the method name syntax in commit message convention guide. Closes #10503.
---

Method name syntax

---

packages/ckeditor5-table/src/tablecellproperties/ui/tablecellpropertiesview.js
packages/ckeditor5-table/src/tableproperties/ui/tablepropertiesview.js
packages/ckeditor5-table/tests/tablecellproperties/ui/tablecellpropertiesview.js
packages/ckeditor5-table/tests/tableproperties/ui/tablepropertiesview.js

Fix (table): Cancelling the table cell properties UI no longer results with a warning in the console. Closes #6266.
---
As the same console warn occurred for canceling table cell properties, both cases (table and table cell properties) have been fixed

Table - console warning on cancel table and table cell properties

---

packages/ckeditor5-find-and-replace/src/findandreplaceui.js
packages/ckeditor5-find-and-replace/tests/findandreplaceui.js

Fix (find-and-replace): The toolbar should not lose focus after escaping from the find and replace dropdown. Closes #10420.
---

Fixing focus after escaping find and replace dropdown

---

packages/ckeditor5-editor-inline/src/inlineeditoruiview.js
packages/ckeditor5-editor-inline/tests/inlineeditoruiview.js
packages/ckeditor5-ui/tests/panel/balloon/balloonpanelview.js

Fix (editor-inline): Set `withArrow` to `false` in inline editor toolbar balloon. Closes #10529.

Fix inline editor withArrow property.

---

packages/ckeditor5-mention/tests/mentionui.js

Tests (mention): UI tests execution speed has been greatly increased by replacing `setTimeout` with Sinon `fakeTimer`. Closes #6619.
---
One of the `setTimeout` functions remain untouched:  
https://github.com/ckeditor/ckeditor5/blob/7d5848d5e43bb856042933bacc8852999fc28b2c/packages/ckeditor5-mention/tests/mentionui.js#L940-L947
Updating this would require a lot of additional effort, and the possible tests time decrease would be minor.  
Overall this change results in decreasing (on average):  
\- total time from `~28 secs` to `~5.5 secs`  
\- net time from `~24 secs` to `~2.3 secs`

Improving mention feature ui tests speed.

---

packages/ckeditor5-typing/src/texttransformation.js
packages/ckeditor5-typing/tests/texttransformation.js

Fix (typing): Restricts mathematical text transformation, so it requires no alphanumeric character before and after the fraction. Closes #9170.
---

Restrict mathematical text transformation not to interfere with dates

---

packages/ckeditor5-utils/src/keyboard.js
packages/ckeditor5-utils/tests/keyboard.js

Fix(utils): Adds more known key codes. For instance, to allow `CTRL-]`. Closes #10439.
---

Add more known key codes

---

docs/framework/guides/contributing/development-environment.md
package.json
scripts/docs/build-docs.js

Docs: Added new options that allow filtering guides to build in the "Generating documentation" section in the "Development environment" guide.
---
It targets the `#stable` branch. We need to bump the Umberto version after releasing new changes.
PR: https://github.com/cksource/umberto/pull/948

Introduce "yarn docs [--skip-guides] [--guides=...]"

---

docs/framework/guides/architecture/editing-engine.md

Text read
> ...  events fired by observes check
Change to:
> ...  events fired by observers check
Type (Docs): Fix typo. observes to observers.
---

Fix typo. `observes` to `observers`

---

packages/ckeditor5-source-editing/theme/sourceediting.css

Fix (source-editing): Safari browser use monospace font for text in source editing mode. Closes #10585.
---

SourceEditing - monospace font on Safari browser

---

packages/ckeditor5-engine/src/model/utils/selection-post-fixer.js
packages/ckeditor5-engine/tests/model/utils/selection-post-fixer.js
packages/ckeditor5-table/tests/tabletoolbar.js

Fix (engine): Fixes bug in selection postfixer (when the selection stuck in a limit element that can't contain text). Closes #10487.
---

Fixes bug in selection postfixer

---

packages/ckeditor5-upload/docs/features/base64-upload-adapter.md

Docs: added svg file upload type in Base64UploadAdapter docs. Closes https://github.com/ckeditor/ckeditor5/issues/10624.
---

Docs: add svg file upload type in Base64UploadAdapter docs

---

packages/ckeditor5-clipboard/tests/pasteplaintext.js
packages/ckeditor5-engine/src/conversion/downcastdispatcher.js
packages/ckeditor5-engine/src/conversion/modelconsumable.js
packages/ckeditor5-engine/src/model/differ.js
packages/ckeditor5-engine/tests/conversion/downcastdispatcher.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js
packages/ckeditor5-engine/tests/conversion/modelconsumable.js
packages/ckeditor5-heading/src/title.js
packages/ckeditor5-image/tests/imagecaption/imagecaptionediting.js

Feature (engine): The `DowncastDispatcher` will throw an error if any of the model items were not consumed while converting. Closes #10377.
Tests (clipboard): Added missing downcast conversion.
Internal (heading): Added missing consuming converter.
Tests (image): Tests updated to properly handle non-consumed errors fired by the `DowncastDispatcher`.
---

Downcast conversion should throw an error if some items were not consumed

---

packages/ckeditor5-code-block/docs/features/code-blocks.md
packages/ckeditor5-code-block/src/codeblockediting.js
packages/ckeditor5-code-block/tests/codeblockediting.js
packages/ckeditor5-code-block/tests/manual/codeblock.md

Improvement of the `CodeBlock` feature, described in https://github.com/ckeditor/ckeditor5/issues/6682.
Closes https://github.com/ckeditor/ckeditor5/issues/6682.

Make three Enter clicks necessary at the end of a code block to escape it

---

packages/ckeditor5-find-and-replace/src/utils.js
packages/ckeditor5-find-and-replace/tests/findcommand.js

Fix (find-and-replace): Fixed adjacent whole words being missed by find and replace. Closes #10719.

Fixed adjacent whole words being missed by find and replace

---

packages/ckeditor5-core/src/editor/editor.js
packages/ckeditor5-core/tests/editor/editor.js

Fix (core): Support language configuration passed in `defaultConfig` option through editor's constructor. Closes #8510.

Support language configuration passed in `defaultConfig` option through editor's constructor

---

packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/tests/view/domconverter/domconverter.js

Internal (engine): Always allow `contenteditable` attribute to be rendered.
---

Always allow `contenteditable` to be rendered.

---

packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/src/view/renderer.js
packages/ckeditor5-engine/tests/view/domconverter/domconverter.js
packages/ckeditor5-engine/tests/view/domconverter/view-to-dom.js
packages/ckeditor5-engine/tests/view/renderer.js
packages/ckeditor5-engine/theme/renderer.css
packages/ckeditor5-html-support/tests/datafilter.js
packages/ckeditor5-media-embed/tests/mediaembedediting.js

Internal (engine): Unsafe attributes should be prefixed with `data-ck-unsafe-attribute-` in the editing pipeline instead of being removed. Closes #10801.
---
I wanted to write a few words in some guide for anyone who debugs their integration, noticed their attribute got removed, and decided to google it but I don't know where would it make the most sense.

Prefixed unsafe attributes in the editing pipeline

---

packages/ckeditor5-html-support/tests/integrations/image.js
packages/ckeditor5-html-support/tests/integrations/mediaembed.js
packages/ckeditor5-html-support/tests/integrations/table.js
packages/ckeditor5-image/src/image/converters.js
packages/ckeditor5-image/tests/image/converters.js
packages/ckeditor5-media-embed/src/mediaembedediting.js
packages/ckeditor5-media-embed/tests/mediaembedediting.js
packages/ckeditor5-table/src/converters/upcasttable.js
packages/ckeditor5-table/tests/converters/upcasttable.js

Fix (image, media-embed, table): The `<figure>` element should not get replicated while GHS is enabled. Closes #10279.
Tests (html-support): Added tests for double converted `<figure>` elements. See #10279.
---

The `<figure>` element should not get replicated while GHS is enabled

---

packages/ckeditor5-image/src/image/imageinlineediting.js
packages/ckeditor5-image/tests/image/insertimagecommand.js
packages/ckeditor5-image/tests/imageupload/uploadimagecommand.js
packages/ckeditor5-link/src/linkimageediting.js
packages/ckeditor5-link/tests/linkimageediting.js

Fix (link, image): Manual decorators on the linked inline images should be preserved while loading editor content. Closes #10828.

Manual link decorators of block images should not break decorators for links on the inline images

---

packages/ckeditor5-engine/src/model/utils/selection-post-fixer.js
packages/ckeditor5-engine/tests/model/utils/selection-post-fixer.js

Fix (engine): Merge intersecting ranges that aren't adjacent to each other on ranges array. Closes #10628.
---

Fix (engine): selection postfixer - merge intersecting ranges

---

package.json

Internal: Removed workspaces from `external/*/external` after extracting collaboration samples and cloud services outside CF.
---
See https://github.com/cksource/collaboration-features/issues/4316.

Removed workspaces from `external/*/external` after extracting collaboration samples and cloud services outside CF

---

docs/features/math-equations.md

Docs: Added information about full MathML mode to MathType guide. Closes #10831.

Docs: Added information about full MathML mode to MathType guide

---

packages/ckeditor5-watchdog/src/editorwatchdog.js
packages/ckeditor5-watchdog/tests/editorwatchdog.js

Fix (watchdog): Prevented `EditorWatchdog` from crashing during the editor destruction process when one of the plugins tries to change data at this moment. Closes #10643.
---

Improved the EditorWatchdog's editor destruction phase by removing a `change:data` listener before destroying the editor

---

docs/assets/snippet-styles.css

Docs: Allows to add/remove bold to H3 heading in editors. Closes #9761

Docs: Allows to add/remove bold to H3 heading in editors. Closes #9761

---

packages/ckeditor5-build-decoupled-document/sample/index.html

Fix (build-decoupled-document): Fix image caption being stretched down. Closes: #10940

Fix (build-decoupled-document): Fix image caption being stretched down. Closes: #10940

---

docs/builds/guides/migration/migration-to-32.md

Docs: Added migration guide to 32.0.0 covering the bump of Node.js version to 14. Closes #10984.

Covered bump of Node.js version in the migration to 32.0.0 guide

---

packages/ckeditor5-mention/src/mentionui.js
packages/ckeditor5-mention/tests/manual/mention.html
packages/ckeditor5-mention/tests/manual/mention.js
packages/ckeditor5-mention/tests/manual/mention.md
packages/ckeditor5-mention/tests/mentionui.js

Fix (mention): Mention plugin now allows searching mentions that include space character. Closes #9741.
---
Mention plugin allowed user to search for feeds only using single words and as soon as it encountered a space it closed items list with results even if there were matches including a space e.g. 'Barry Thompson'. It happened because of regexp for matching mentions in currently edited text that only allowed visible characters to occur after a mention mark.
At first it seemed as an easy improvement of regexp to just allow a space but a scenario with multiple registered markes complicated it a lot.
Take this case:
> aaa @fooo #bar
Regexp allowing space would match @foo as well as #bar. After playing a little bit with regexp to handle that case it quickly got overcomplicated and still …

Handle spaces in feeds for mention plugin

---

packages/ckeditor5-engine/src/dataprocessor/htmldataprocessor.js
packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/src/view/renderer.js
packages/ckeditor5-engine/tests/view/domconverter/domconverter.js
packages/ckeditor5-utils/src/dom/iscomment.js
packages/ckeditor5-utils/tests/dom/iscomment.js

Internal (utils, engine): Extracted `isComment()` function from engine to utils. Closes #7428.

Extract isComment() to utils

---

packages/ckeditor5-build-decoupled-document/src/ckeditor.js

Other (build-decoupled-document): Enables `startIndex` and `reversed` list properties in document build. Closes #11037.
---

Adds all list properties to decoupled document build config

---

packages/ckeditor5-find-and-replace/tests/findandreplaceediting.js
packages/ckeditor5-html-support/tests/integrations/image.js
packages/ckeditor5-html-support/tests/integrations/mediaembed.js
packages/ckeditor5-html-support/tests/integrations/table.js
packages/ckeditor5-html-support/tests/manual/htmlcomment.js
packages/ckeditor5-html-support/tests/manual/mediaembed.js
packages/ckeditor5-table/src/tablecaption/tablecaptionui.js
packages/ckeditor5-table/src/tablecaption/toggletablecaptioncommand.js
packages/ckeditor5-typing/tests/spellchecking.js
scripts/bump-year.js

Internal: Replaced the existing script for bumping a year in license headers with the common one from the `ckeditor5-dev`. Closes #10909.

Replaced bump-year logic with execution of an external function

---

packages/ckeditor5-autosave/src/autosave.js
packages/ckeditor5-autosave/tests/autosave.js

Feature (autosave): \`Autosave#save()\` will now return a promise that is resolved when the autosave callback has finished.
Other (autosave): Autosave plugin will now ignore changes coming from remote clients during real-time collaboration. Closes #9233.
---
Requires #11009.

Autosave plugin should ignore remote changes

---

packages/ckeditor5-paste-from-office/src/filters/list.js
packages/ckeditor5-paste-from-office/tests/filters/list.js
packages/ckeditor5-paste-from-office/tests/manual/integration.js

Feature (paste-from-office): Adds support for start index in ordered lists. Closes #11043.
---

Pasting from office: startIndex support

---

packages/ckeditor5-list/src/documentlist/documentlistediting.js
packages/ckeditor5-list/src/documentlist/documentlistindentcommand.js
packages/ckeditor5-list/src/documentlist/documentlistsplitcommand.js
packages/ckeditor5-list/tests/documentlist/documentlistediting-integrations.js
packages/ckeditor5-list/tests/documentlist/documentlistediting.js
packages/ckeditor5-list/tests/documentlist/documentlistsplitcommand.js

Internal (list): Improved enter handling in document lists by allowing to split the list item when the collapsed selection is anchored in the first (but not only) empty block of a list item (see [#10879](https://github.com/ckeditor/ckeditor5/issues/10879), [#10976](https://github.com/ckeditor/ckeditor5/issues/10976)).

Improved enter handling in document lists

---

packages/ckeditor5-list/src/listpropertiesediting.js
packages/ckeditor5-list/tests/listpropertiesediting.js

Fix (list): The list properties feature will no longer crash when removing content from the last list item which is next to a non-list element. Closes #8642.

List properties should not crash when removing a last list item from the list next to non-list element

---

docs/builds/guides/frameworks/react.md

Docs: Updated the React component guide. Closes #11160.

Updated the guide that was using outdated API.

---

packages/ckeditor5-mention/docs/_snippets/features/custom-mention-colors-variables.js
packages/ckeditor5-mention/docs/_snippets/features/mention-customization.js
packages/ckeditor5-mention/docs/_snippets/features/mention.js
packages/ckeditor5-mention/docs/features/mentions.md

Docs: Added name with a space to the mentions guide demo. Closes #11182 
Changed all examples in the mentions docs page to include a new person with two names. Now all three demos are consequent and include the person with space in its ID. 
Also added `minimumCharacters` limit to demo snippet code to make it aligned with the code which is in the docs presented as a source of this example.

Docs: Added name with a space to the mentions guide demo

---

package.json

Internal: Specified an exact version to the `karma-coverage` package due to [karma-coverage@v2.1.1](https://github.com/karma-runner/karma-coverage/releases/tag/v2.1.1) which breaks the testing environment. Closes #11221.
---

WIP: Travis coverage fix

---

packages/ckeditor5-html-support/docs/features/general-html-support.md

Docs: missing comma in an example configuration. Closes #11209.
---

Docs: missing comma in example configuration

---

packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector-structure.js
packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/downcast.md
packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/helpers/downcast.md
packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/src/view/downcastwriter.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js
packages/ckeditor5-engine/tests/manual/slot-conversion.js
packages/ckeditor5-engine/tests/view/downcastwriter/writer.js
packages/ckeditor5-image/src/image/imageblockediting.js
packages/ckeditor5-image/tests/image/converters.js
packages/ckeditor5-media-embed/src/utils.js
packages/ckeditor5-table/src/converters/downcast.js
packages/ckeditor5-widget/tests/widget.js
packages/ckeditor5-widget/tests/widgettypearound/widgettypearound.js

Internal (engine): The `elementToStructure` `conversionApi.slotFor()` replaced with `writer.createSlot()`. Closes #11179.
---

Changed slotFor() API into writer.createSlot()

---

packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js

Internal (engine): `elementToStructure()` should throw when invoked for an element that allows `$text`. Closes #11163.
---
The original issue was about throwing an error when `slotFor()` is used but it turns out this configuration error can be captured way earlier.

elementToStructure() should throw when invoked for an element that allows $text

---

packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js

Revert (engine): Reverted #11229 due to concerns in `Widget` tests.

Revert "elementToStructure() should throw when invoked for an element that allows $text"

---

packages/ckeditor5-engine/src/conversion/downcasthelpers.js
packages/ckeditor5-engine/tests/conversion/downcasthelpers.js
packages/ckeditor5-widget/tests/widget-events.js
packages/ckeditor5-widget/tests/widget.js
packages/ckeditor5-widget/tests/widgetresize.js
packages/ckeditor5-widget/tests/widgettypearound/widgettypearound.js

Internal (engine): `elementToStructure()` should throw when invoked for an element that allows `$text`. Closes #11163.
---
For the record, we decided to bring back the error thrown by `elementToStructure()` when downcasting an element that allows `$text` but at the same time, we got rid of the warning (validation) in `elementToElement()` which now works as a workaround for people who cannot use `elementToStructure` due to the error. This is not perfect but OTOH it is hard to predict how many integrations downcast model elements to structures with text so let's give them some error&warning-free solution.

Brought back previously reverted changes to elementToStructure() throwing when invoked for an element that allows $text""

---

packages/ckeditor5-list/src/documentlist/documentlistcommand.js
packages/ckeditor5-list/src/documentlist/documentlistediting.js
packages/ckeditor5-list/src/documentlist/utils/listwalker.js
packages/ckeditor5-list/src/documentlist/utils/model.js
packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesediting.js
packages/ckeditor5-list/src/documentlistproperties/documentliststylecommand.js
packages/ckeditor5-list/src/documentlistproperties/utils/style.js
packages/ckeditor5-list/src/listproperties/listreversedcommand.js
packages/ckeditor5-list/src/listproperties/liststartcommand.js
packages/ckeditor5-list/src/listproperties/liststylecommand.js
packages/ckeditor5-list/tests/documentlist/_utils-tests/utils.js
packages/ckeditor5-list/tests/documentlist/_utils/uid.js
packages/ckeditor5-list/tests/documentlist/_utils/utils.js
packages/ckeditor5-list/tests/documentlist/documentlistcommand.js
packages/ckeditor5-list/tests/documentlist/utils/listwalker.js
packages/ckeditor5-list/tests/documentlist/utils/model.js
packages/ckeditor5-list/tests/documentlistproperties/documentliststylecommand.js
packages/ckeditor5-list/tests/documentlistproperties/utils/style.js
packages/ckeditor5-list/tests/listproperties/liststylecommand.js

Internal (list): Adds `DocumentListStyleCommand`. See #11166.
---

Added DocumentListStyle command

---

packages/ckeditor5-image/src/image/imageblockediting.js
packages/ckeditor5-image/src/image/utils.js
packages/ckeditor5-image/tests/image/converters.js
packages/ckeditor5-image/tests/image/utils.js

Internal (image): Refactor `createBlockImageViewElement()` helper function.
________________
Why: Recently we changed the `slotFor()` API by moving it into the writer and renaming the function. This PR aims to do a small refactoring by removing second parameter `slotElement` which is created using `writer` since we already pass the whole `writer` into the `createBlockImageViewElement()`.
It's documented in another PR review and acts as a follow up to it: https://github.com/ckeditor/ckeditor5/pull/11211#pullrequestreview-875583814

Refactor createBlockImageViewElement() helper function.

---

packages/ckeditor5-markdown-gfm/docs/_snippets/features/markdown.js
packages/ckeditor5-markdown-gfm/docs/features/markdown.md

Docs: adding source editing to Markdown demo. Closes #11231.
---

Docs: adding source editing to Markdown demo

---

packages/ckeditor5-list/docs/features/lists.md

Type: Adding links to lists guide for examples with all list properties enabled.

Docs: linking from lists to examples.

---

packages/ckeditor5-image/package.json
packages/ckeditor5-image/src/imagestyle/utils.js
packages/ckeditor5-image/tests/imagestyle/imagestyle-integration.js
packages/ckeditor5-image/tests/imagestyle/utils.js

Fix (image): Always create new instances of the default options for the `ImageStyle` plugin. Closes #11328.
---

The default configuration options for `ImageStyle` plugin are not properly cloned

---

packages/ckeditor5-engine/src/model/differ.js
packages/ckeditor5-engine/tests/model/document.js

Fix: Markers that do not change their range will not trigger the `change:data` event. Closes #9901.
---

Markers that do not change their range will not trigger the change:data event.

---

docs/_snippets/examples/multi-root-editor.js
docs/framework/guides/custom-editor-creator.md
packages/ckeditor5-core/src/editor/editorconfig.jsdoc
packages/ckeditor5-editor-balloon/src/ballooneditor.js
packages/ckeditor5-editor-balloon/tests/ballooneditor.js
packages/ckeditor5-editor-classic/src/classiceditor.js
packages/ckeditor5-editor-classic/tests/classiceditor.js
packages/ckeditor5-editor-decoupled/src/decouplededitor.js
packages/ckeditor5-editor-decoupled/tests/decouplededitor.js
packages/ckeditor5-editor-inline/src/inlineeditor.js
packages/ckeditor5-editor-inline/tests/inlineeditor.js

Other: `Editor.create()` will now set `config.initialData` value based on the first parameter, if `initialData` has not been set in the editor config. As a result, plugins can now easily read and modify the editor initial data.
MINOR BREAKING CHANGE: `config.initialData` now will be always set, even if it was not passed in the editor config.
---

Editor.create() will set config.initialData

---

packages/ckeditor5-html-support/src/datafilter.js
packages/ckeditor5-html-support/tests/datafilter.js

Internal (html-support): `DataFilter` should hook into `DataController#init` before anything else to prevent errors if other features start downcasting the model. Closes #11356.

DataFilter should hook into DataController#init before anything else

---

packages/ckeditor5-html-support/src/integrations/script.js
packages/ckeditor5-html-support/src/integrations/style.js
packages/ckeditor5-html-support/tests/integrations/script.js
packages/ckeditor5-html-support/tests/integrations/style.js

Fix (html-support): Prevent `<script>` and `<style>` tags removal if they are the only content in the editor. Closes #11247.

GHS: Prevent <script> and <style> tags removal

---

packages/ckeditor5-engine/src/model/differ.js
packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesediting.js
packages/ckeditor5-list/tests/documentlistproperties/documentlistpropertiesediting.js

Internal (list): Reset document list properties after indent. Closes #11357.
---

Reset document list properties after indent

---

packages/ckeditor5-core/src/editor/editor.js
packages/ckeditor5-core/src/editor/editorconfig.jsdoc
packages/ckeditor5-core/src/plugincollection.js
packages/ckeditor5-editor-balloon/src/ballooneditor.js
packages/ckeditor5-editor-classic/src/classiceditor.js
packages/ckeditor5-editor-decoupled/src/decouplededitor.js
packages/ckeditor5-editor-inline/src/inlineeditor.js
packages/ckeditor5-utils/src/version.js

Docs: fixing invalid absolute URLs in installation API docs. Closes cksource/ckeditor5-internal#1554.
---

Fixing absolute internal URLs in installation docs

---

packages/ckeditor5-table/src/plaintableoutput.js
packages/ckeditor5-table/tests/plaintableoutput.js

Fix (table): Prevent plain table output converter from interfering with other features caption converters. Closes #11394.
---
After some testing we noticed that the new `PlainTableOutput` plugin converter for downcasting captions was doing a bit too much. For tables it was correctly changing the output from `<figcaption>` to `<caption>` element, but for all the other elements it was falling back to the `<figcaption>` element. This was preventing other converters to alter this behaviour on their own. Hence this change.

Prevent `PlainTableOutput` from interfering with other features caption downcast converters

---

packages/ckeditor5-html-support/src/integrations/image.js
packages/ckeditor5-html-support/tests/integrations/image.js

Fix (html-support): Skip inline image upcast conversion inside not supported element. Closes #10703.

Certain markup breaks the Source Editing mode

---

docs/installation/advanced/dll-builds-collaboration-features.md
docs/installation/advanced/dll-builds.md

Docs: Integrating changes from https://github.com/ckeditor/ckeditor5/pull/11097/files. Closes cksource/ckeditor5-internal#1495.
---
DO NOT merge if revamp is dropped on production before 33.x release.

Docs: integrating changes from  #11097.

---

docs/installation/getting-started/configuration.md

Docs: Fix of removing features guide with additional examples. Closes #11455.

Docs: Fix of removing features guide with additional examples

---

packages/ckeditor5-html-support/src/conversionutils.js
packages/ckeditor5-html-support/tests/datafilter.js

Fix (html-support): Prevents `TypeError` in `mergeViewElementAttributes`. Closes #10657. Closes #11450. Closes #11477.
---

GHS: fix mergeViewElementAttributes

---

packages/ckeditor5-engine/src/model/differ.js
packages/ckeditor5-engine/tests/model/differ.js

Fix (engine): Marker changes sometimes did not trigger `change:data` event which resulted in errors in features using markers (for example, annotations not showing up in the sidebar).

Marker changes did not trigger `change:data`

---

packages/ckeditor5-watchdog/src/utils/getsubnodes.js

Other: Improved performance of the `getSubNodes()` utility.
---
This function is a bottleneck when it comes to the watchdog restarting mechanism - watchdog traverses the whole editor structure to find the context of the thrown error. After this change, the `getSubNodes` function will be ~100 times faster for large documents.

Improved performance of the 'getSubNodes()' utility

---

packages/ckeditor5-engine/src/model/treewalker.js

Other (engine): Improved \`model.TreeWalker#next()\` efficiency.
---
No tests because the change does not change any logic.

Improved `model.TreeWalker#next()` efficiency

---

packages/ckeditor5-theme-lark/tests/manual/reset.html
packages/ckeditor5-theme-lark/tests/manual/reset.js
packages/ckeditor5-theme-lark/tests/manual/reset.md
packages/ckeditor5-theme-lark/theme/ckeditor5-ui/globals/_reset.css
packages/ckeditor5-ui/theme/globals/_reset.css

Feature (theme-lark): Implemented a `.ck-reset_all-excluded` CSS class that excludes certain elements from CSS reset. Closes #11451.
---
Demo in the manual test in the `theme-lark` package.

Allowed excluding certain elements from CSS reset

---

packages/ckeditor5-style/src/ui/stylegridbuttonview.js
packages/ckeditor5-style/tests/ui/stylegridbuttonview.js

Internal (style): Excluded the style preview from CSS UI reset making it easier to integrate the feature. Closes #11520. See #11462.
---
For the record: This is not a silver bullet and does not replace web components in 100%. It's an improvement over what we had, though. Some styles will trickle down from parents because this is how inheritance works in CSS, there's no way to seal this up.

Excluded the style preview from CSS UI reset

---

packages/ckeditor5-list/src/documentlist/documentlistediting.js
packages/ckeditor5-list/tests/documentlist/integrations/enter.js

Fix (list): Soft enter (`Shift+Enter`) is no longer captured by document list `enter` key listener allowing to insert soft breaks in empty list's items. Closes #11539.
---

Allow soft break in an empty document lists' items.

---

packages/ckeditor5-language/src/textpartlanguageediting.js
packages/ckeditor5-language/tests/textpartlanguageediting.js

Fix (language): Fixes interference between `TextPartLanguage` and `CodeBlock`. Closes #11538. Closes #11563.
---

Fixes interference between TextPartLanguage and CodeBlock

---

packages/ckeditor5-clipboard/tests/manual/dragdrop.js
packages/ckeditor5-core/src/editor/editor.js
packages/ckeditor5-core/tests/editor/editor.js
packages/ckeditor5-core/tests/manual/readonly.js
packages/ckeditor5-find-and-replace/tests/manual/findandreplace.js
packages/ckeditor5-find-and-replace/tests/manual/scrolling.js
packages/ckeditor5-widget/tests/manual/type-around.js
tests/manual/all-features.js
tests/manual/memory/memory.js

Internal (core): Removed the second parameter from `Editor#enableReadOnlyMode()`. Closes #11599.
---

Remove the second parameter from Editor#enableReadOnlyMode()

---

docs/features/read-only.md

Internal: Fix docs for the editor's read-only mode management. Closes #11572.
---

Fix docs for the editor's read-only mode management

---

packages/ckeditor5-table-resize/src/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table-resize/src/tablecolumnresize/utils.js
packages/ckeditor5-table-resize/tests/tablecolumnresizer/tablecolumnresizeediting.js

Fix (table-resize): Nested tables should no longer reset its width when resizing.
---
Replaced the `rootWidth` with  `viewFigureParentWidth` as it is more useful because of the nested tables possibility.

Fixed table column resize width reset for nested tables

---

packages/ckeditor5-table-resize/src/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table-resize/tests/manual/tablecolumnresizewithoutproperties.html
packages/ckeditor5-table-resize/tests/manual/tablecolumnresizewithoutproperties.js
packages/ckeditor5-table-resize/tests/manual/tablecolumnresizewithoutproperties.md
packages/ckeditor5-table-resize/tests/tablecolumnresizer/tablecolumnresizeediting.js

Fix (table-resize): Resolved issue when resizing columns with fixed width was leading the table to increase the size and go out of the editor.
Fix (table-resize): Resolved issue where the table width was not reflected in table properties after the resize.
---

Fixes table column resize 'tableWidth' related issues

---

packages/ckeditor5-table-resize/src/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table-resize/tests/tablecolumnresizer/tablecolumnresizeediting.js

Fix (table-resize): Editor will no longer crash when adding caption for the table.
---

Fixed table column resize editor crash when adding caption

---

packages/ckeditor5-list/ckeditor5-metadata.json

Internal (list): Adds `DocumentList` and `DocumentListProperties` to `ckeditor5-metadata.json`. Closes #11613.
---

Add DocumentLists to ckeditor5-metadata.json

---

packages/ckeditor5-html-support/src/integrations/dualcontent.js
packages/ckeditor5-html-support/tests/integrations/dualcontent.js

Fix (html-support): `DualContentModelElementSupport` should upcast inline elements as block when they contain block inside. Closes #11513.
---

GHS: DualContent should search for block in all nested elements

---

packages/ckeditor5-list/src/documentlist/documentlistediting.js
packages/ckeditor5-list/tests/documentlist/integrations/clipboard.js
packages/ckeditor5-list/tests/documentlistproperties/converters.js

Other (list): The editor should strip list attributes from solo blocks to enhance UX on paste or drop in document lists. Closes #11608.

[Document lists] The editor should strip list attributes from solo blocks to enhance UX on paste or drop

---

packages/ckeditor5-list/ckeditor5-metadata.json
packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesediting.js
packages/ckeditor5-list/src/documentlistproperties/documentliststylecommand.js
packages/ckeditor5-list/src/documentlistproperties/utils/style.js
packages/ckeditor5-list/src/listproperties.js
packages/ckeditor5-list/src/listproperties/listpropertiesui.js
packages/ckeditor5-list/tests/documentlistproperties/documentlistpropertiesediting.js
packages/ckeditor5-list/tests/documentlistproperties/documentliststylecommand.js
packages/ckeditor5-list/tests/documentlistproperties/utils/style.js
packages/ckeditor5-list/tests/listproperties/listpropertiesui.js
packages/ckeditor5-list/tests/manual/documentlist-properties.html
packages/ckeditor5-list/tests/manual/documentlist-properties.js

Feature (list): Adds support for `type` attribute of `<ul>` and `<ol>` elements in addition to `list-style-type` style. Closes #11615.
---

<ul type> & <ol type>

---

packages/ckeditor5-engine/src/conversion/upcasthelpers.js
packages/ckeditor5-engine/tests/conversion/upcasthelpers.js
packages/ckeditor5-html-support/src/converters.js
packages/ckeditor5-html-support/tests/datafilter.js
packages/ckeditor5-html-support/tests/integrations/table.js
packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js

Fix (html-support,engine): Attributes should not be set if parent was converted into a collapsed range. Closes #11000.

Alignment feature should not clash with GHS

---

packages/ckeditor5-table-resize/src/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table-resize/src/tablecolumnresize/utils.js
packages/ckeditor5-table-resize/tests/tablecolumnresizer/tablecolumnresizeediting.js
packages/ckeditor5-table-resize/tests/tablecolumnresizer/utils.js

Fix (table-resize): Resolved issue with nested tables not being resizable after paste.
---

Column resize nested tables can be resized correctly after paste

---

packages/ckeditor5-mention/package.json
packages/ckeditor5-mention/src/mentionui.js
packages/ckeditor5-mention/tests/manual/tickets/11400.html
packages/ckeditor5-mention/tests/manual/tickets/11400.js
packages/ckeditor5-mention/tests/manual/tickets/11400.md
packages/ckeditor5-mention/tests/mentionui.js

Fix (mention): The mention UI should not show up when matching an existing mention after a white space. Closes #11400.

The mention UI should not show up when matching an existing mention

---

package.json

Internal: Removed the `#resolutions` definitions from `package.json`.
---
Perhaps the `karma-coverage` package must be specified (see: https://github.com/ckeditor/ckeditor5/pull/11225). Let's see what CI thinks about these changes.

Removed the `#resolutions` definitions from `package.json`

---

packages/ckeditor5-engine/src/model/document.js
packages/ckeditor5-engine/tests/model/document.js

Internal (engine): Brought back setter for \`model.Document#version\`.
---
The setter was removed when working on #11226. However, it was a breaking change for cloud services.

Brought back setter for model.Document#version

---

packages/ckeditor5-core/src/editor/editor.js

Docs (core): Improved an error message when trying to set the editor in read-only mode by using `Editor#isReadOnly` setter. Closes #11695.
---
How it looks now

Improve editor-is-readonly-has-no-setter error message.

---

packages/ckeditor5-ui/docs/_snippets/examples/bootstrap-ui-inner.js

Docs: update custom UI read-only demo to reflect API changes from the 34.0.0 release. Closes #11791.

Docs: update custom UI read-only demo to reflect API changes from the 34.0.0 release

---

docs/installation/frameworks/overview.md
docs/installation/frameworks/react.md
docs/installation/frameworks/vuejs-v2.md
docs/installation/frameworks/vuejs-v3.md
docs/support/faq.md

Docs: changing the ready-to-use to predefined builds in docs. Closes #11827
---

Docs: unifying predefined builds naming.

---

scripts/translations/download.js
scripts/translations/upload.js
scripts/translations/utils.js

Internal: Added support for handling specified packages when downloading or uploading translations by providing the `--packages` argument. Closes #11570.
---
The `--packages` support has been added for downloading and uploading translations.

Added support for handling specified packages when downloading or uploading translations

---

scripts/docs/get-latest-changelogs.js

Internal: Show paragraph with the link to the blog post for changelog entries. Closes #11643.
---

The "get-latest-changelogs" script removes links to blogposts

---

packages/ckeditor5-source-editing/src/utils/formathtml.js
packages/ckeditor5-source-editing/tests/utils/formathtml.js

Fix (source-editing): The `formatHtml()` helper should not crash when a pathological iframe content is passed. Closes #10698.
---
Whys in https://github.com/ckeditor/ckeditor5/issues/10698#issuecomment-1138643844.

The formatHtml() helper should not crash

---

packages/ckeditor5-table/docs/features/table.md

Docs: Fix typos in Table Feature.
---
I noticed some typos while reading through the docs.

Docs: Fix typos in Table Feature

---

packages/ckeditor5-editor-balloon/README.md
packages/ckeditor5-editor-classic/README.md
packages/ckeditor5-editor-decoupled/README.md
packages/ckeditor5-editor-inline/README.md

Docs: rewriting the predefined builds info in readmes. Closes: #10632
---

Docs: rewriting the predefined builds info in readmes.

---

packages/ckeditor5-engine/src/view/element.js
packages/ckeditor5-engine/tests/view/renderer.js

Fix (engine): The view element `renderUnsafeAttributes` option should not be lost for an `AttributeElement`s. Closes #11879.
---

renderUnsafeAttributes should not be lost for an AttributeElement

---

packages/ckeditor5-engine/src/view/renderer.js
packages/ckeditor5-engine/tests/view/renderer.js

Fix (engine): Inline filler should not be removed while updating a text node. Closes #11472 .
---

Fixed inline filler handling while isSelecting = true

---

packages/ckeditor5-clipboard/tests/clipboardpipeline.js
packages/ckeditor5-engine/src/view/domconverter.js
packages/ckeditor5-engine/tests/view/domconverter/dom-to-view.js
packages/ckeditor5-html-support/tests/datafilter.js
packages/ckeditor5-html-support/tests/integrations/mediaembed.js
packages/ckeditor5-html-support/tests/integrations/table.js
packages/ckeditor5-image/tests/image/imageblockediting.js
packages/ckeditor5-image/tests/image/imageediting.js
packages/ckeditor5-image/tests/image/imageinlineediting.js
packages/ckeditor5-link/tests/linkimageediting.js
packages/ckeditor5-list/tests/documentlist/converters.js
packages/ckeditor5-list/tests/listproperties/listpropertiesediting.js
packages/ckeditor5-table/tests/converters/downcast.js

Fix (engine): The order of attributes should not get reversed while loading editor data. Closes #11850.
Tests (html-support, clipboard, image, link, list, table): The order of attributes should not get reversed while loading editor data.
---

DomConverter should not reverse order of attributes while converting from DOM to view

---

packages/ckeditor5-table/src/ui/colorinputview.js
packages/ckeditor5-table/tests/ui/colorinputview.js

Fix (table): Added label for the Table properties color grid dropdown. Closes #11895.
---

Table properties color picker label updated

---

.gitignore

Internal: Cleanup in gitignore. Closes ckeditor/ckeditor5#11985.

Cleanup in gitignore.

---

scripts/translations/utils.js

Internal: Support for TypeScript when collecting translation entries. Closes #12029.
---

Support for TypeScript when collecting translation entries

---

packages/ckeditor5-image/src/imageutils.js
packages/ckeditor5-image/tests/imageutils.js
packages/ckeditor5-table/src/utils/ui/widget.js
packages/ckeditor5-table/tests/utils/ui/widget.js

Internal (image): Prevent `getClosestSelectedImageWidget()` from throwing when view selection is empty. Closes #11972.
Internal (table): Prevent `getTableWidgetAncestor()` from throwing when view selection is empty. Closes #11972.
---
Internal in the commit message instead of Fix because I am not sure if this ever happens when normal editor scenarios.

Validate view selection position in image and table helpers

---

scripts/translations/utils.js

Internal: Translation utils allow specifying packages that should not be processed.

Translation utils - support for skipping packages

---

packages/ckeditor5-link/src/linkediting.js
packages/ckeditor5-link/tests/linkediting.js

Fix (link): Link manual decorators should be properly down-casted on the document selection. Closes #12046.
---

Link manual decorator attribute should be down-casted on selection

---

packages/ckeditor5-table/theme/tablecolumnresize.css

Other (table): Exclude table column resizer styles from content styles. Closes #11922.
---
I really like that the content styles builder only includes those CSS variables that are actually necessary.

Exclude table column resizer styles from content styles

---

packages/ckeditor5-ui/tests/button/buttonview.js
packages/ckeditor5-ui/theme/components/button/button.css

Fix (toolbar): Reverted changes introduced by https://github.com/ckeditor/ckeditor5/pull/11869 PR. Closes #12068.
---

Revert patch for displaying tooltips for focused buttons

---

packages/ckeditor5-utils/src/dom/emittermixin.ts
packages/ckeditor5-utils/src/emittermixin.ts
scripts/translations/collect.js

Internal: Restored the ckeditor5-utils package in the `translations:collect` script.
---
Changes from ckeditor/ckeditor5-dev#780 are required.

Restored the ckeditor5-utils package in the `translations:collect` script

---

packages/ckeditor5-style/README.md
packages/ckeditor5-style/ckeditor5-metadata.json
packages/ckeditor5-style/docs/_snippets/features/styles.html
packages/ckeditor5-style/docs/_snippets/features/styles.js
packages/ckeditor5-style/docs/features/style.md

Docs: Styles feature guide. See #11311.
---
In https://github.com/ckeditor/ckeditor5/pull/11562 we incorrectly merged it to `master`. I reverted that in #12135. 
This PR should contain all the commits from the original PR but correctly rebased onto the latest `release`.

Resurrected the styles feature guide

---

docs/api/index.md
docs/examples/index.md
docs/features/overview.md
docs/features/toolbar.md
docs/features/ui-language.md
docs/installation/advanced/content-styles.md
docs/installation/advanced/plugins.md
docs/installation/getting-started/installing-plugins.md
docs/installation/getting-started/migration-from-ckeditor-4.md
docs/installation/getting-started/predefined-builds.md
docs/installation/getting-started/quick-start.md
docs/installation/overview.md
docs/support/faq.md
docs/updating/updating.md
packages/ckeditor5-editor-balloon/docs/api/editor-balloon.md
packages/ckeditor5-editor-classic/docs/api/editor-classic.md
packages/ckeditor5-editor-decoupled/docs/api/editor-decoupled.md
packages/ckeditor5-editor-inline/docs/api/editor-inline.md
packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/helpers/intro.md
packages/ckeditor5-remove-format/docs/features/remove-format.md
packages/ckeditor5-utils/docs/framework/guides/deep-dive/observables.md

Docs: relinking landing pages to overviews globally for CKE5 docs.
Follow up to https://github.com/ckeditor/ckeditor5/pull/12091
Part of https://github.com/ckeditor/ckeditor5/issues/12081
---

Docs: relinking landing pages to overviews globally for CKE5 docs.

---

packages/ckeditor5-table/src/tablecolumnresize/utils.js
packages/ckeditor5-table/tests/manual/tablecolumnresize.html
packages/ckeditor5-table/tests/tablecolumnresize/_utils/utils.js
packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js

Fix (table): Fixed column resize for tables containing only table headers. Closes #11878.
---
Tested also with a table pasted from CKE4 containing only `<thead>` element - see https://github.com/ckeditor/ckeditor5/issues/11975#issue-1285829256 for details.

Fix column resizing in table with only heading rows

---

packages/ckeditor5-paste-from-office/src/filters/space.js
packages/ckeditor5-paste-from-office/tests/filters/space.js

Fix (paste-from-office): Use innerText instead of innerHTML in filters/space
---
This PR fixes one of the issues mentioned in #10845 .

Fix (paste-from-office): Use innerText instead of innerHTML in filters/space

---

packages/ckeditor5-ui/src/icon/iconview.js
packages/ckeditor5-ui/tests/icon/iconview.js

Fix (ui): Use removeChild instead of innerHTML in icon/iconview
---
This PR fixes one of the issues mentioned in #10845 .

Fix (ui): Use removeChild instead of innerHTML in icon/iconview

---

packages/ckeditor5-clipboard/src/dragdrop.js

Fix (clipboard): Use Element.append instead of innerHTML in dragdrop.js
---
This PR fixes one of the issues mentioned in #10845 .

Fix (clipboard): Use Element.append instead of innerHTML in dragdrop.js

---

packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table/tests/manual/tablecolumnresize.html
packages/ckeditor5-table/tests/manual/tablecolumnresize.js
packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table/theme/tablecolumnresize.css

Fix (table): Table column resizers should be hidden when resizing commands are disabled. Closes #11886.
---

Hide resizers when resizing commands are disabled (e.g. in comments-only mode)

---

packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table/src/tablecolumnresize/utils.js
packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table/tests/tablecolumnresize/utils.js

Internal (table): Fixed removing tables from the editor. Closes #12201.
---
As described in the issue, previously this was handled by the `if` statement located in https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-table/src/tablecolumnresize/utils.js#L60. Writing the unit tests revealed though that this solution works because of a coincidence.
When a table is removed, the table plugin immediately inserts a paragraph instead. That means that (fortunately) there is always a paragraph as a `position.nodeAfter`, so the removed table is not classified as "affected" by change. However, if that behaviour is altered (i.e. a paragraph won't be inserted) and there will be another table right after a removed one, the code will classify that second table as affected - which is not …

Fix removing tables

---

packages/ckeditor5-image/src/imageupload/imageuploadui.js
packages/ckeditor5-image/tests/imageupload/imageuploadui.js

Fix (image): Fixed the focus after inserting an image - it is now moved moved to editable. Closes #12229.
---

Move focus to editable after inserting image

---

packages/ckeditor5-html-support/src/schemadefinitions.js
packages/ckeditor5-html-support/tests/manual/ghs-all-features.html
packages/ckeditor5-html-support/tests/manual/ghs-all-features.js
packages/ckeditor5-table/src/tablecolumnresize/converters.js
packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js
packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js

Fix (table,html-support): Fixed table column resize integration with General HTML Support. Closes #12191.
---
It's a two-parts fix:
1.  On the GHS side, it adds the `colgroup` and `col` elements schema. It resolves the issue where these elements were filtered out as `unsafe`. Please note that it only happened after using `editor.setData()` - if you just open a demo and insert a table, it can be resized normally.
2.  On the table column resize feature the `ck-table-resized` CSS class handling had to be improved as it was not always present when it should be. It was causing incorrect table rendering during the upcast in some cases (e.g. for a resized table with a lot of text in cell). Also it didn't work well for a table with `<colgroup>` element but without `width` attribute in the editor …

Enable table column resize feature in GHS

---

packages/ckeditor5-ckbox/docs/_snippets/features/ckbox.js

Docs: CKBox demo resize options changed to % instead of px. Closes #12192.

Docs: CKBox demo resize options changed to % instead of px

---

docs/framework/guides/creating-simple-plugin-timestamp.md
docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-1.md
docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-2.md
docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-3.md

Docs: Removed unnecessary links to API. Closes internal #[1889](https://github.com/cksource/ckeditor5-internal/issues/1889).
---

Docs: Removed unnecessary links to API from timestamp and abbreviation tutorials. 

---

packages/ckeditor5-ui/src/dropdown/button/dropdownbuttonview.js
packages/ckeditor5-ui/tests/dropdown/button/dropdownbuttonview.js

Fix (ui): Added aria-expanded attribute for the dropdownbuttonview. Closes #12258.
---
Tested briefly with VoiceOver and it seems that the screen reader will now properly announce if the button has a popup.  
You can check this behavior with all-features manual tests and insertImageViaUrl.

Added aria-expanded for dropdownbuttonview

---

packages/ckeditor5-font/src/ui/colortableview.js
packages/ckeditor5-font/tests/ui/colortableview.js

Fix (font): Removed an unnecessary color button tooltip. Closes #12277.
---

Remove color button tooltip

---

packages/ckeditor5-core/src/editor/editorui.js
packages/ckeditor5-core/tests/editor/editorui.js

Internal (core): Pressing Alt+F10 in a toolbar focused by mouse should not throw an error. Closes #12339.
---
QA needed.

Pressing Alt+F10 in a toolbar focused by mouse should not throw an error

---

packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js
packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js

Internal (list): The list style grid should ba navigable using the keyboard regardless of the geometry of the grid. Closes #12340.
---
Best place to test: http://fake.ckeditor.com:8125/ckeditor5-list/tests/manual/list-properties.html.
P.S. Don't mind https://github.com/ckeditor/ckeditor5/issues/12337 there.

The list style grid should ba navigable using the keyboard regardless of the geometry of the grid.

---

packages/ckeditor5-ui/src/list/listitemview.js
packages/ckeditor5-ui/tests/list/listitemview.js

Feature (ui): Introduced the observable `#isVisible` property to `ListItemView` class instances. Closes #12357.
---
A requirement of cksource/collaboration-features#4731.
See cksource/collaboration-features#4719 to learn more.

Introduced ListItemView#isVisible

---

packages/ckeditor5-table/src/tablecolumnresize/utils.js
packages/ckeditor5-table/tests/tablecolumnresize/utils.js

Internal(table): Calculate the table parent width properly in various scenarios. Closes #12335.
---
There is a [comment in the original issue](https://github.com/ckeditor/ckeditor5/issues/12335#issuecomment-1230389708) where I've explained the reasoning behind this change.

Adjust the table element width calculations during resizing

---

packages/ckeditor5-style/src/ui/stylegridbuttonview.js
packages/ckeditor5-style/src/ui/stylegridview.js
packages/ckeditor5-style/src/ui/stylepanelview.js
packages/ckeditor5-style/tests/ui/stylegridbuttonview.js
packages/ckeditor5-style/tests/ui/stylegridview.js
packages/ckeditor5-style/tests/ui/stylepanelview.js

Fix (style): Improves keyboard navigation for style feature. Closes #12250.
---
Now `(shift) tab` keystroke navigates between the two sections in style dropdown whilst `arrow keys` navigate between grid items within a single grid.

Keyboard navigation for styles grids

---

docs/features/index.md
docs/framework/index.md
docs/installation/index.md

Docs: changing menu titles for overview sections.
Assumption:
Overviews (index.md) are not indexed in algolia so naming them the same way just for UX purposes is okay

Docs: changing menu titles for overview sections

---

docs/updating/migration-to-35.md

Docs (ckeditor5): Created a migration guide entry for changes to the tooltip system made in CKEditor v35.1.0. Closes #12384.

Migration guide entry for changes to the tooltip system

---

package.json

Internal: Removed unnecessary `popper` package from the dependencies. Closes #12408.
Internal: Added missing `assert` package.
---

Removed unnecessary `popper` package from the dependencies

---

packages/ckeditor5-list/src/list/utils.js
packages/ckeditor5-list/tests/list/utils.js

Fix (list): Ordering problem when block quote was being inserted into the middle of the list. Closes #11082.
---
This issue was caused by by incorrectly ignoring closing tags when searching for list items.

Fix list ordering when block quote was inserted

---

packages/ckeditor5-paste-from-office/tests/manual/integration.js
packages/ckeditor5-paste-from-office/tests/manual/tickets/7957/1.js
tests/manual/all-features-dll.js
tests/manual/all-features.js
tests/manual/memory/memory-semi-automated.js
tests/manual/memory/memory.js
tests/manual/performance/richeditor.js

Tests: Added table column resize to the manual tests with all features. Closes #12255.
---
That's actually part of the ticket, there are two more related PRs in different repos. 
The list of updated manual tests is a bit arbitrary (e.g. I decided it can be useful to update PfO test, but not document lists). I'm open for discussion about the choice.

Add table column resize to the all-features manual tests.

---

packages/ckeditor5-special-characters/docs/_snippets/features/special-characters-extended-category.html
packages/ckeditor5-special-characters/docs/_snippets/features/special-characters-extended-category.js
packages/ckeditor5-special-characters/docs/features/special-characters.md
packages/ckeditor5-special-characters/lang/contexts.json
packages/ckeditor5-special-characters/src/specialcharactersarrows.js
packages/ckeditor5-special-characters/tests/specialcharacters.js

Other (special-characters): Added missing arrow characters (↑, →, ↓, ←). Closes #6167.
---
The example from user guide has been updated.

Added common arrows in the special characters package

---

packages/ckeditor5-link/src/autolink.js
packages/ckeditor5-link/src/utils.js
packages/ckeditor5-link/tests/autolink.js

Fix (link): Corrected autolinking URLs without protocol. Closes #11040.
---

Corrected autolinking urls without protocol

---

packages/ckeditor5-list/src/todolist/todolistconverters.js
packages/ckeditor5-list/tests/todolist/todolistediting.js

Fix (list): To-do list items should not interrupt the Tab key navigation across the editor content. Closes #6535 .
---

Set tabindex to -1 to prevent focusing the checkbox element with Tab key

---

packages/ckeditor5-html-support/src/schemadefinitions.js
packages/ckeditor5-html-support/tests/integrations/heading.js

Fix (html-support): Redefine most GHS-elements as not blocks in schema. Closes #12430.

Fix (html-support): Redefine most GHS-elements as not blocks in schema.

---

packages/ckeditor5-link/src/autolink.js
packages/ckeditor5-link/tests/autolink.js

Fix (link): Don't undo autolinking when any other change has been made. Closes #12447 .

Fix (link): Don't undo autolinking when any other change has been made.

---

docs/framework/guides/contributing/testing-environment.md

Docs: Added description for the new `--dll` and `--no-dll` flags, that are available for manual tests.
---
This is part of ckeditor/ckeditor5-dev#787.

Added description for new `--dll` flag for manual tests

---

packages/ckeditor5-engine/src/model/nodelist.ts
packages/ckeditor5-engine/tests/model/nodelist.js
packages/ckeditor5-utils/src/splicearray.ts
packages/ckeditor5-utils/tests/splicearray.js

Fix (engine): Fixed editor throwing `Maximum call stack size exceeded` error when huge number of nodes were inserted at once into an element. Closes #12428.
---
Generally, the editor crashes with error _"Maximum call stack size exceeded"_ when there are at least 200 000 elements in one paragraph and someone opens the revision history feature. This issue has been solved, however, there is still situation when browser crashes because of large content (like 1-2 mln of chars in one paragraph) and this issue cannot be fix on our side.

Created custom splice method to deal with very big number of elements

---

packages/ckeditor5-html-support/src/datafilter.js
packages/ckeditor5-html-support/tests/datafilter.js
packages/ckeditor5-html-support/tests/integrations/image.js
packages/ckeditor5-html-support/tests/integrations/mediaembed.js
packages/ckeditor5-html-support/tests/integrations/table.js

Feature (html-support): GHS can exclude elements from the allowed list of elements.
---
This PR is modifying the flow of registering filtering rules for elements. Previously GHS was firing the `register` event on `DataController#init` event to defer the registration to the last possible moment before data load (to make sure that all plugins registered their schemas and converters). After the initial editor `init`, all GHS `register` events were fired immediately but this caused a problem with being able to exclude some elements from the allow rule (in most cases we pass the allow list and then the disallow list). To be able to defer registering only the difference between those sets of rules there is another delay in firing the `register` event after the initial data load so that those …

Introducing `DataFilter#disallowElement()`.

---

packages/ckeditor5-image/tests/imageresize/imageresizehandles.js
packages/ckeditor5-widget/src/widgetresize.js
packages/ckeditor5-widget/src/widgetresize/resizer.js
packages/ckeditor5-widget/tests/widgetresize.js
packages/ckeditor5-widget/tests/widgetresize/resizer.js

Fix (widget): Don't show image resizer handle when resizer is not enabled (commentsOnly mode). Closes #11891.
---
Main issue was, probably race condition between change of visibleResizer attribute(https://github.com/ckeditor/ckeditor5/blob/e51d6c564261889433c04fb8b2bcaa24a38bf0a5/packages/ckeditor5-widget/src/widgetresize.js#L90) and change of isEnabled attribute (https://github.com/ckeditor/ckeditor5/blob/e51d6c564261889433c04fb8b2bcaa24a38bf0a5/packages/ckeditor5-widget/src/widgetresize/resizer.js#L115).

Fix (widget): Don't show image resizer handle when resizer is not enabled (commentsOnly mode)

---

packages/ckeditor5-theme-lark/tests/manual/theme.js
packages/ckeditor5-theme-lark/theme/ckeditor5-list/collapsible.css
packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/button/switchbutton.css

Fix (theme-lark): SwitchButtonView should no longer change color when it is on. Closes #12519 .
---
The structure of the code for `find & replace` / `link decorators` differs from the one used for `listproperties` and because of that we need to add additional css rule for `.ck.ck-list__item.ck-switchbutton.ck-on` selector adding the missing `color: inherit`.  
Otherwise we would most likely have to update the `listproperties` implementation so it's not a single \<button> but a button placed inside of the list (similarly to the structure mentioned below).
For `find & replace` and `link decorators` it is added by the `.ck.ck-list__item .ck-switchbutton.ck-on` selector because the structure is:
```
<ul class="ck ck-reset ck-list"><li class="ck ck-list__item"><button>...
```

Updated css styles for switchbutton

---

docs/updating/migration-to-35.md

Docs: adding information about moved icons to the migration to 35.2.0 guide. Closes: #12586
---

Docs: adding moved icons to migration guide.

---

docs/framework/guides/contributing/testing-environment.md

Docs: Added description for the `--disable-watch` option in manual tests section. See #12189.

Docs: Add disable watch option description in running manual tests section

---

scripts/ci/check-packages-code-coverage.js

Internal: Improved error messages for code coverage script on CI. Now the output from `stdout` and `stderr` is piped to the parent process. Closes #12412.
---
Decided to stay with execSync, because:
1.  Some parts would be risky to rewrite `childProcess.execSync( 'npx coveralls < .out/combined_lcov.info' )`
2. spawnSync does not throw an error, so each time it is called, the response code would have to be checked, and script stopped manually in case of error

Fix (scripts): Improve error messages for code coverage ci script

---

packages/ckeditor5-engine/src/view/placeholder.ts
packages/ckeditor5-engine/tests/view/placeholder.js

Fix (engine): The placeholder should not be visible while composing. Closes #12389.
---

Placeholder should be hidden while composing.

---

packages/ckeditor5-list/src/list/converters.js
packages/ckeditor5-list/tests/list/listediting.js
packages/ckeditor5-table/src/tablecaption/toggletablecaptioncommand.js
packages/ckeditor5-table/tests/tablecaption/toggletablecaptioncommand.js

Internal (table): Use insertContent in table caption instead of using writer directly.
---
This is needed / going to help with track changes integration

Internal (table, list): Use insertContent in table caption instead of using writer directly

---

packages/ckeditor5-utils/src/index.ts

Internal (utils): Export `insertToPriority()` as default from index file.
---

Export insertToPriorityArray as default from index

---

packages/ckeditor5-engine/src/model/utils/modifyselection.ts
packages/ckeditor5-engine/tests/model/utils/modifyselection.js

Fix (engine): ModifySelection with word unit should not stop at the attribute boundary. Closes #12673. Closes #12657.
---

ModifySelection with word unit should not stop at the attribute boundary

---

packages/ckeditor5-image/ckeditor5-metadata.json

Internal (image): Added the `toggleImageCaption` button to the image toolbar.
---

Added toggleImageCaption that was missing from the metadata of ckeditor5-image

---

packages/ckeditor5-typing/src/input.ts
packages/ckeditor5-typing/tests/input.js

Internal (typing): Content should not get removed on the composition start if the input is disabled. Closes #12739.
---

Content should not get removed on the composition start if input is disabled

---

packages/ckeditor5-engine/src/view/observer/mutationobserver.ts
packages/ckeditor5-engine/tests/view/observer/mutationobserver.js

Internal (engine): MutationObserver is no longer watching attribute changes. Closes #12759.
---

MutationObserver is no longer watching attribute changes.

---

packages/ckeditor5-typing/src/deleteobserver.ts
packages/ckeditor5-typing/tests/tickets/11904.js

Internal (typing): Delete event should not be fired on backspace keyup if delete event was stopped. Closes #12776.
---
The problem was that workaround for missing `beforeInput` events (https://github.com/ckeditor/ckeditor5/issues/11904) was checking whether the `beforeInput` was fired on `normal` priority and in case of custom widget delete handling, the `delete` event was stopped and as a result the `beforeInput` was stopped before it got noticed by the workaround code.

Delete event should not be fired on backspace keyup if delete event was stopped

---

.eslintrc.js
docs/framework/guides/contributing/code-style.md
packages/ckeditor5-minimap/src/minimap.js
packages/ckeditor5-table/src/tablewalker.js
packages/ckeditor5-utils/_src/dom/position.js
packages/ckeditor5-utils/src/dom/position.ts

Docs: Added the new rule (`ckeditor5-rules/use-require-for-debug-mode-imports`) in the "Code style" guide. See #12479.
Internal: Fixed errors reported by `eslint` after introducing the new rule.

Added new eslint rule to use require in debug imports and updated docs

---

docs/installation/frameworks/react.md

Type: Adding a missing export statement to a code snippet in the docs. Closes #12761.

Docs: add missing export statement to code snippet

---

packages/ckeditor5-ui/src/formheader/formheaderview.ts
packages/ckeditor5-ui/tests/formheader/formheaderview.js

Fix (Special Characters): Special characters form header should use a heading markup. Closes #12464.
---
In this pull request I also provided little changes of neighbouring unit test, I mean "should set the template". First reason is better to getting to property through template not through DOM. Second reason is to increase the readability of test in case it failed. 
_For example – It will no display "**expect false to be true**", however it will display "**expect [ 'ck', 'ck-form__header'] should include  'wrong data'** "_

Special characters form header should use a heading markup

---

packages/ckeditor5-engine/src/view/observer/selectionobserver.ts
packages/ckeditor5-engine/tests/view/observer/selectionobserver.js

Other (engine): Add a mechanism for detecting which tests fail because of too many selection changed events. Closes #12103.

Change selection observer behavior

---

packages/ckeditor5-enter/_src/entercommand.js
packages/ckeditor5-enter/src/entercommand.ts
packages/ckeditor5-enter/tests/entercommand.js
packages/ckeditor5-paragraph/src/paragraphbuttonui.ts

Other (enter): Made `enterBlock()` helper publicly accessible through `EnterCommand#enterBlock()`. Closes #12885.
---
I am not sure whether I should add JSDoc to `_src/entercommand.js` as well.

Made `enterBlock()` helper publicly accessible through `EnterCommand#enterBlock()`

---

packages/ckeditor5-image/src/image/utils.js
packages/ckeditor5-image/tests/image/imageediting.js
packages/ckeditor5-image/tests/image/utils.js

Feature (image): Upcasts `img` with `display:block` style as block image. Closes #12811.
---

Upcasts img with display:block as block image

---

packages/ckeditor5-html-support/src/integrations/mediaembed.js
packages/ckeditor5-html-support/src/integrations/table.js
packages/ckeditor5-html-support/tests/integrations/image.js
packages/ckeditor5-html-support/tests/integrations/mediaembed.js
packages/ckeditor5-html-support/tests/integrations/table.js

Fix (html-support): Markers should not be lost while upcasting a plain table (without a `<figure>` element).
---

Markers should not be lost while upcasting a plain table (without a <figure> element).

---

packages/ckeditor5-list/src/documentlist/utils/postfixers.js

Internal: Fixed infinite loop after transpilation to ES5. Closes ckeditor/ckeditor5-react#345.
---
The description how to reproduce this issue is in ckeditor/ckeditor5-react#345.
In short, `create-react-app` uses by default very loose `browserslist` rules for production environment, that cause the generated (minified) code of the application targets the ES5. This in turn causes that the Babel (probably) does not handle properly the inline destructuring inside a `for of` loop with a generator.

Fixed infinite loop after transpilation to ES5

---

packages/ckeditor5-list/src/index.js
packages/ckeditor5-list/src/list/listediting.js
packages/ckeditor5-list/src/list/listutils.js
packages/ckeditor5-list/tests/list/listutils.js

Other (list): Added access to list-related utils functions through new \`ListUtils\` plugin to make it possible to use them in other packages.

Task (list): Provide list utils plugin so that list utils functions can be accessed externally
