ckeditor/ckeditor5

- tests/ckeditor/basepath.js
> t/17: CKEDITOR._getBasePath() has insufficient tests

- dev/bender/plugins/ckeditor5/lib/index.js
- dev/bender/plugins/ckeditor5/static/tools.js
- tests/bender/createsinonsandbox.js
Fixes #31.
Introduces the namespace, docs and one tool method with tests.
> Introduced bender.tools.

- bender.js
- dev/bender/plugins/ckeditor5/lib/index.js
> Add pagebuilder before the includes pagebuilder.

- .jshintrc
- bender.js
- ckeditor.js
- dev/.jshintrc
- dev/bender/plugins/ckeditor5/lib/index.js
- dev/bender/plugins/ckeditor5/static/extensions.js
- dev/bender/plugins/ckeditor5/static/tools.js
- dev/tasks/build.js
- dev/tasks/build/builder.js
- dev/tasks/jscs.js
- dev/tasks/jshint.js
- dev/tasks/utils/tools.js
- gruntfile.js
- src/ckeditor-dev.js
- src/plugin.js
- tests/.jshintrc
- tests/amd/amd.js
- tests/bender/createsinonsandbox.js
- tests/ckeditor/basepath.js
- tests/ckeditor/ckeditor.js
- tests/plugin/plugin.js
> ES6-y the code

- dev/tasks/utils/git.js
- dev/tests/git.js
> t/48 - Task dev-install clones repositories using wrong Git URLs

- dev/tasks/gulp/build/utils.js
- dev/tests/build/tasks.js
- dev/tests/build/utils.js
- package.json
> T/25 - Tests for the builder

- dev/tasks/gulp/build/utils.js
- dev/tests/build/utils.js
> Do not try to process null files.

- dev/tasks/dev/templates/package.json
- dev/tasks/lint/tasks.js
- package.json
> gulp lint-staged does not exclude src/lib/** #71

- dev/tasks/build/utils.js
- dev/tests/build/utils.js
> Remove unused version of files when building

- dev/tasks/build/tasks.js
- dev/tests/build/tasks.js
> Parse shell args inside specific tasks.

- package.json
> Added utils as a dep

- src/editablecollection.js
> Changed: EditableCollection prepared for changed ObservableMixin.

- src/command/attributecommand.js
- tests/command/attributecommand.js
Prepare AttributeCommand for changes in Schema. Fixes #129
> Prepare AttributeCommand for changes in Schema.

- dev/tasks/build/utils.js
- dev/tests/build/utils.js
> t/133: Builder fails on Windows

- dev/tasks/build/utils.js
- package.json
> t/146: Fix istanbul coverage

- ckeditor.js
- src/command/command.js
- src/editable.js
- src/editablecollection.js
- src/editor.js
- src/plugin.js
https://github.com/ckeditor/ckeditor5-ui/pull/23 -> clkeditor5-utils#12
Connected to https://github.com/ckeditor/ckeditor5-utils/pull/29
> Use of utils object refactor

- dev/tasks/dev/utils/git.js
- dev/tests/dev/git.js
> Extended fetch form one specified branch to all branches on each remote in git.checkout task

- tests/plugincollection.js
> Extended test case for loading plugins in PluginCollection.

- dev/tasks/dev/tasks/update.js
- dev/tasks/dev/utils/git.js
- dev/tests/dev/git.js
- dev/tests/dev/update.js
- package.json
> Added fetching of branches from main repository during update task.

- dev/tasks/build/utils.js
- tests/.jshintrc
- tests/_utils-tests/benderglobals.js
This PR adds view and model utilities to bender namespace as described in #144.
> Added view and model utilities to bender namespace.

- tests/.jshintrc
Fixes #163.
Fixes in other repositories are already on master.
> Set bender global to read only in test jshint file.

- src/creator/standardcreator.js
- tests/creator/standardcreator.js
Partially resolves #173 issue, by adding default parameter to `StandardCreator` constructor.
> Added default parameter to StadardCreator constructor.

- tests/creator/manual/_utils/creator/inlinecreator.js
- tests/creator/manual/_utils/creator/legacycreator.js
- tests/creator/manual/_utils/creator/multicreator.js
- tests/editor/baseeditor.js
Fixes #179.
Complementary change in the classic creator https://github.com/ckeditor/ckeditor5-creator-classic/pull/6.
> Fixed unit tests and addded integrational tests.

- src/creator/standardcreator.js
- src/editor.js
- src/keystrokehandler.js
- tests/creator/standardcreator.js
- tests/keystrokehandler.js
> Implemented keystroke handler

- dev/tasks/dev/utils/inquiries.js
- dev/tasks/dev/utils/sanitize.js
- dev/tests/dev/sanitize.js
Resolves https://github.com/ckeditor/ckeditor5/issues/122
> Forcing period at the end of package description.

- src/editor/editor.js
Dependent on https://github.com/ckeditor/ckeditor5-utils/pull/36
> Changed config class getter.

- package.json
> Updated gulp-watch version to ^4.3.7.

- tests/_utils-tests/modeltesteditor.js
- tests/editor/standardeditor.js
Fixes https://github.com/ckeditor/ckeditor5-engine/issues/390
Depends on https://github.com/ckeditor/ckeditor5-engine/pull/477
> Changed parameters order of model.document.createRoot() method.

- dev/tasks/build/utils.js
- dev/tests/build/utils.js
- package.json
Fixes #190 
Related: https://github.com/ckeditor/ckeditor5-engine/pull/497
> Improved compatibility with code coverage.

- dev/tasks/dev/tasks.js
See: https://github.com/ckeditor/ckeditor5/commit/a8411f98ac3e9591744b1736b21a87a768e39ca2
Fixes: #220
> Removed invalid returning from create-package task.

- tests/command/attributecommand.js
Changes required by https://github.com/ckeditor/ckeditor5-engine/issues/480 and it's related PR: https://github.com/ckeditor/ckeditor5-engine/pull/537
> Fixed: changes required by ckeditor5-engine#480.

- src/command/attributecommand.js
> Changed name and order of arguments when using Batch methods

- tests/editor/standardeditor.js
> Fixes for tests using setData

- gulpfile.js
Fixes: #275 
**Depends on:** https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/pull/11
> Adjusted gulp bundle tasks to new API

- dev/bundles/build-config-standard.js
> Updated default bundle config - added missing parameters.

- gulpfile.js
- package.json
> Using compiler instead of builder

- gulpfile.js
> Renamed gulp bundle task to gulp build

- gulpfile.js
> Introduced configuration for bundler - BUNDLE_DEFAULT_CONFIG.

- gulpfile.js
Fixes: #316 
Requires: https://github.com/ckeditor/ckeditor5-dev-compiler/pull/27
> Integrated sample tests with the default compile task and small jsDocs fixes.

- gulpfile.js
- package.json
> Removed code which was moved to dev-tests.

- gulpfile.js
Fixes: #336.
Needs: https://github.com/ckeditor/ckeditor5-dev-docs/issues/8
> Clean up Gulpfile.

- gulpfile.js
- package.json
Fixes: #343 
Requires: https://github.com/ckeditor/ckeditor5-dev-compiler/pull/43 and https://github.com/ckeditor/ckeditor5-dev-docs/pull/12
> Adjust tasks to the `dev-compiler`'s changes

- .travis.yml
- README.md
> Travis configuration

- lerna.json
- package.json
Fixes #395.
---
Message:
```
Internal: Updated Lerna and started using hoisting on CI. Resolves #395.
```
> Update Lerna and use hoisting

- gulpfile.js
- package.json
- scripts/fix-src-imports.js
- scripts/switch-to-dev-dev.sh
Resolves ckeditor5-part of the https://github.com/ckeditor/ckeditor5/issues/387.
> Add translation tasks to gulpfile.

- gulpfile.js
Internal: Added gulp task for generating JSDoc output only. Closes #442 .
> Added gulp task for generating JSDoc output.

- .travis.yml
- gulpfile.js
Feature: Added validation JSDoc on CI. Closes #444.
---
Requires: https://github.com/ckeditor/ckeditor5-dev/pull/222.
> T/444: Verify API docs on CI

- mgit.json
- package.json
Feature: Introduced `BalloonToolbarEditor`. Closes #450. Closes #402.
---
* Requires https://github.com/ckeditor/ckeditor5-editor-balloon-toolbar/pull/2
> t/450: Introduced BalloonToolbarEditor

- .travis.yml
- package.json
Feature: Added documentation build script to `.travis.yml`. Closes #460.
It will be triggered by Travis's CRON.
> T/460: Nightly documentation builds

- docs/builds/guides/overview.md
> 'rich text editor' - for consistency

- docs/builds/guides/reporting-issues.md
> Update reporting-issues.md - added 5

- docs/umberto.json
Docs: Updated umberto.json with methods important for search. Closes #595.
> Updated umberto.json with methods important for search

- .github/ISSUE_TEMPLATE.md
> Create Issue template

- docs/umberto.json
Docs: Added custom search ranking to umberto.json. Closes #632.
> Added custom search ranking to umberto.json. Closes #632

- docs/framework/guides/support/getting-support.md
Type: Message. Closes #695 .
---
> Added a paragraph about commercial support.

- docs/builds/guides/integration/advanced-setup.md
> Fix copy-paste typo

- docs/features/ui-language.md
Docs: Aligned docs to renamed translations output directory. See ckeditor/ckeditor5-dev#354.
> Aligned docs to renamed translations output directory.

- docs/_snippets/examples/classic-editor-short.js
- docs/_snippets/features/read-only.js
- docs/_snippets/features/ui-language.js
Docs: Enabled EasyImage in all code snippets. Closes #789.
> Docs - EasyImage is enabled in all snippets

- docs/builds/guides/development/installing-plugins.md
> Docs: Fix typo

- .travis.yml
- scripts/docs/build-and-publish-nightly.js
- scripts/docs/build-and-publish.js
Internal: Scripts that build the documentation start working again. CI marks the build as failed if something goes wrong. Closes #1076.
> Fixed scripts that build the docs

- docs/builds/guides/support/browser-compatibility.md
Docs: Added Android and iOS WebViews to the compatibility page.
> Docs: Added Android and iOS WebViews to the compatibility page

- docs/builds/guides/frameworks/angular.md
- docs/builds/guides/frameworks/overview.md
- docs/builds/guides/frameworks/react.md
- docs/builds/guides/integration/basic-api.md
- docs/umberto.json
Docs: Introduced the "Frameworks" section. Closes #1213.
> [Docs] Introduced the "Frameworks" section

- docs/framework/guides/architecture/ui-library.md
- mgit.json
Docs: Fixed outdated examples in the dropdown section of the UI library guide (see ckeditor/ckeditor5-ui#123).
> t/ckeditor5-ui/123: Docs: Fixed outdated examples in the dropdown section of the UI library

- docs/builds/guides/frameworks/react.md
Docs: Added a warning about lack of support for `create-react-app@2`. See ckeditor/ckeditor5-react#40.
> Added a warning about lack of support for CRA@2

- docs/builds/guides/integration/configuration.md
Docs: Documented a possible use–case of `config.extraPlugins` (see ckeditor/ckeditor5-core#146).
---
A part of https://github.com/ckeditor/ckeditor5-core/pull/149.
> t/ckeditor5-core/146: Documented a possible use–case of config.extraPlugins.

- docs/features/image-upload.md
- docs/umberto.json
Docs: Add image upload category.
---
* Changes in other repos:
- https://github.com/ckeditor/ckeditor5-adapter-ckfinder/pull/12
- https://github.com/ckeditor/ckeditor5-ckfinder/pull/33
- https://github.com/ckeditor/ckeditor5-easy-image/pull/23
- https://github.com/ckeditor/ckeditor5-image/pull/259
- https://github.com/ckeditor/ckeditor5-upload/pull/89
> Add image upload category in the documentation.

- docs/builds/guides/frameworks/css.md
- docs/builds/guides/frameworks/overview.md
Docs: Introduced CSS Frameworks compatibility section. Closes #1421.
> [Docs] Introduced CSS Frameworks compatibility. [skip ci]

- .travis.yml
Internal: Before calling `yarn install` on CI, all dependencies that were installed before will be removed. Closes #1465.
> Reset pkg.json and yarn.lock before install deps

- docs/builds/guides/frameworks/angular.md
- docs/builds/guides/frameworks/react.md
- docs/builds/guides/frameworks/vuejs.md
- docs/builds/guides/migrate.md
- docs/framework/guides/architecture/ui-library.md
Docs: Aligned docs with changes in editor UI classes.
---
See https://github.com/ckeditor/ckeditor5-core/pull/154 and #1449.
> Docs: Adjusted to recent UI refactor

- package.json
- yarn.lock
Internal: `Husky` has been upgraded and the `precommit` hook will be installed correctly. Closes #1492.
---
With this PR, we need to merge `t/ckeditor5/1492` branch across the entire project. See the changes: https://github.com/ckeditor/ckeditor5-engine/compare/t/ckeditor5/1492.
An instruction for merging everything after closing the PR.
```bash
mgit fetch
mgit co t/ckeditor5/1492
mgit co master
mgit exec 'git merge --no-ff t/ckeditor5/1492 -m "Merge branch t/ckeditor5/1492" -m "Internal: Upgraded the `husky` dependency. See: ckeditor/ckeditor#1492."'
mgit push
mgit exec 'git br -D t/ckeditor5/1492'
mgit exec 'git push origin :t/ckeditor5/1492'
```
After merging, I recommend to execute: `yarn run reset`.
> Husky has been upgraded and will be installed correctly

- docs/builds/guides/frameworks/overview.md
Docs: Added Ionic and Cordova compatibility information. Closes #701
> [Docs] Added Ionic and Cordova compatibility information

- .travis.yml
- scripts/notify-travis-status.js
Internal: Replaced an integration with Slack provided by Travis with a custom script that sends a notification for specified branches. Closes #1493.
---
Unfortunately, it does not detect a change of status between two builds. But the notification will be sent only for `push` builds and only for `master` and `master-revisions` branches. I guess it won't create a huge mess.
> Slack integration

- scripts/notify-travis-status.js
Internal: Added a missing `CRON` type of a build to the script which sends notifications to our Slack. Closes #1526.
> CRON builds will send a notification on Slack

- docs/builds/guides/frameworks/css.md
Docs: Extended Bootstrap overrides. Closes https://github.com/ckeditor/ckeditor5-table/issues/154.
> [Docs] Extended Bootstrap overrides.

- docs/builds/guides/integration/advanced-setup.md
Docs: Updated Babel's packages in Advanced setup guide. Closes #1553.
> Updated Babel's packages in Advanced setup guide

- docs/framework/guides/tutorials/implementing-a-block-widget.md
Docs: Correct link to widget's guide in CKEditor4. Closes: #1598.
---
> Docs. Correct link to widget guide in CKEditor4.

- docs/builds/guides/frameworks/vuejs.md
Docs: Add information about SVG loader in CKEditor 5. Closes ckeditor/ckeditor5-vue#32.
---
> Add information about SVG loader in CKEditor 5.

- docs/builds/guides/integration/saving-data.md
Docs: Improved saving data guide. Part of the ckeditor/ckeditor5-autosave#24.
---
> Improved saving data guide

- docs/builds/guides/frameworks/vuejs.md
Docs: Remove duplicated package from a snippet on Vue integration page. Closes #1751
> Docs: Remove duplicated package from a snippet on Vue integration page

- docs/features/image-upload.md
Docs: Added a short note about `Base64UploadAdapter` plugin.
---
Requires: https://github.com/ckeditor/ckeditor5-upload/pull/93.
> Docs - mention about Base64 Upload Adapter

- README.md
- package.json
Feature: Introduced watchdog feature.
---
> Introduced watchdog feature

- yarn.lock
Other: Upgraded dependencies in `yarn.lock`.
> Upgraded dependencies in yarn.lock

- yarn.lock
Internal: Upgraded dependencies in the `yarn.lock` file once again.
> Upgraded dependencies in lock file once again

- scripts/docs/snippetadapter.js
Docs: Snippet Adapter works with additional languages. Closes #1932.
> Snippet Adapter works with additional languages

- docs/framework/guides/contributing/testing-environment.md
Docs: Aligned docs to changes in the testing environment. Part of #383.
---
> Align docs to changes in the testing environment

- docs/builds/guides/frameworks/react.md
- docs/builds/guides/frameworks/vuejs.md
- docs/builds/guides/integration/advanced-setup.md
- docs/framework/guides/quick-start.md
- docs/framework/guides/tutorials/implementing-a-block-widget.md
- docs/framework/guides/tutorials/implementing-an-inline-widget.md
Docs: Set depenency versions, to avoid installing their new major versions automatically. See #1945.
> Set depenency versions, to avoid installing their new major versions

- docs/_snippets/features/wproofreader.html
- docs/_snippets/features/wproofreader.js
- docs/features/spell-checker.md
Docs: Improved the WProofreader demo. Closes #1982.
> Improved the WProofreader demo

- docs/builds/guides/frameworks/react.md
- docs/builds/guides/integration/advanced-setup.md
- docs/framework/guides/quick-start.md
- docs/framework/guides/tutorials/implementing-a-block-widget.md
- docs/framework/guides/tutorials/implementing-an-inline-widget.md
Docs: Unify the asset regexps. Closes #1046.
> Unify the asset regexps

- .travis.yml
Internal: Increased Travis build time for documentation. Closes #5570.
> Increased Travis build time for documentation

- docs/builds/guides/integration/content-styles.md
Docs: Updated the styles listing in the "Content styles" guide (see ckeditor/ckeditor5#5677).
---
To be merged after https://github.com/ckeditor/ckeditor5-highlight/pull/46.
> i/5677: Updated the styles listing in the "Content styles" guide

- docs/builds/guides/frameworks/angular.md
Docs: Added a section about integrating collaboration plugins in the angular app. Closes ckeditor/ckeditor5-angular#6.
---
> Add a section about integrating collaboration plugins in the angular app

- docs/builds/guides/frameworks/react.md
Docs: Added section about integrating collaboration plugins in React apps. Closes #5809.
---
> Added section about integrating collaboration plugins in React apps.

- package.json
- scripts/release/update-utils-version.js
Internal: Added a script that updates the version of CKEditor 5 in `@ckeditor/ckeditor5-utils` package. Closes #5660.
> Script for updating the version in utils/version.js file after generating changelogs

- docs/_snippets/features/mathtype.js
Feature: Added more plugin to the Math and chemical formulas feature guide. Message. Closes #5789.
> Added more plugin to the Math and chemical formulas feature guide

- docs/builds/guides/frameworks/angular.md
Docs: Fixed Angular quick start guide. Closes ckeditor/ckeditor5-angular#74.
---
> Docs: Fixed Angular quick start guide

- yarn.lock
Internal: Updated dependencies in `yarn.lock`. Closes #5926.
> Updated dependencies in yarn.lock

- docs/_snippets/framework/tutorials/inline-widget.js
- docs/framework/guides/tutorials/implementing-an-inline-widget.md
Docs: Add button to command binding in inline widget sample. Closes #5955.
---
> Add button to command binding in inline widget sample.

- docs/framework/guides/contributing/testing-environment.md
Docs: Enhanced `--files` option part in development environment documentation. Closes #5949.
> i/5949: Enhance `--files` option part in developer env. docs

- docs/builds/guides/support/browser-compatibility.md
Docs: Update number of tests in the browser compatibility guide.
---
> Those are rookie numbers

- docs/builds/guides/frameworks/react.md
Docs: Updated React integration guide. Closes #6275.
> Docs: Updated React integration guide

- tests/manual/performance/richeditor.js
Tests: Added essential special characters set to the rich editor performance test. Closes #6255.
---
Note, it's for iteration 30 - so it shouldn't be merged it till `master` is unlocked.
> Added essential special characters set to the rich editor performance test

- yarn.lock
Internal: Upgraded dependencies.
> Upgraded dependencies

- package.json
- yarn.lock
Docs: Updated the version of `MathType` plugin.
> Updated the version of MathType plugin

- scripts/docs/snippetadapter.js
Internal: Aligned snippet adapter to changes in CKEditorWebpackPlugin. Part of #6526.
---
> Aligned snippet adapter to changes in CKEditorWebpackPlugin.

- docs/umberto.json
Docs: Added a new category in features documentation.
> Added a new category in features documentation

- docs/features/keyboard-support.md
Docs: Updated keyboard support documentation - added table navigation and widget keystrokes. Closes #6663.
---
> I/6663: Updated keyboard support documentation - added table navigation and widget keystrokes.

- package.json
Internal: Fixed the `release:stable-branches` package command. Closes #6703.
> Fixed the release:stable-branches package command

- .travis.yml
Internal (ckeditor5): Added a missing line for travis status notify.
---
As suggested in https://github.com/ckeditor/ckeditor5/commit/23e5152252bbddb6c31b46bc7b20ad28fe2a4d6d#r38909145.
> Added a missing line for travis status notify

- packages/ckeditor5-table/src/tableui.js
- packages/ckeditor5-table/tests/tableui.js
Other (table): Insert row above/below in reasonable order in the menu. Closes #6702.
---
> Insert row above/below in reasonable order in the menu.

- docs/features/ui-language.md
- docs/framework/guides/architecture/ui-library.md
- docs/framework/guides/creating-simple-plugin.md
- docs/framework/guides/deep-dive/localization.md
Docs: Introduced the localization guide featuring the translation API . Closes #6646.
> Introduce the localization guide featuring the translation API 

- packages/ckeditor5-table/src/tableclipboard.js
- packages/ckeditor5-table/tests/tableclipboard-paste.js
Other (table): Added support for pasting table when only one table cell is selected. Closes #6121.
---
> Added support for pasting table when only one table cell is selected.

- .github/workflows/merge-stable.yml
Internal (ckeditor5): GH action to merge the stable to the master branch automatically. Closes #6316.
---
Notes can be found in this comment: https://github.com/ckeditor/ckeditor5/issues/6316#issuecomment-630112493
> GH action to merge the stable to the master branch automatically

- packages/ckeditor5-media-embed/package.json
- packages/ckeditor5-media-embed/src/automediaembed.js
- packages/ckeditor5-media-embed/tests/automediaembed.js
Internal (media-embed): AutoMediaEmbed should detach LiveRange. Closes #6806.
---
> AutoMediaEmbed should detach LiveRange

- packages/ckeditor5-table/src/tableclipboard.js
- packages/ckeditor5-table/src/tableselection/croptable.js
- packages/ckeditor5-table/tests/manual/tablemocking.js
- packages/ckeditor5-table/tests/tableclipboard-paste.js
Internal (table): Pasting smaller table into bigger table part selected. Closes #6769.
---
> #6769: Pasting smaller table into bigger table area selected

- scripts/release/bump-versions.js
- scripts/release/publish.js
Internal (ckeditor5): Use the "release" branch for publishing changes. See #7300.
---
Requires https://github.com/ckeditor/ckeditor5-dev/pull/645.
> Use "release" branch for publishing changes

- packages/ckeditor5-table/src/tableclipboard.js
Internal (table): Refactored pasting table into table. Closes #7294.
---
> Refactored pasting table into table (content table preparations extracted to helper function, simplified local variables to be more consistent).

- docs/builds/guides/integration/content-styles.md
Docs: Updated content styles. Closes #7407.
> Updated content styles

- docs/framework/guides/contributing/code-style.md
Docs: Code style suggests to use sinon-chai and named spies. Closes #7456.
---
> Add note about named spies and sinon-chai to the code style guide. 

- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
Fix: Updated the link to the moved GFM package source code.
---
> Updated the link to the GFM package source code

- packages/ckeditor5-widget/src/utils.js
You use the `toWidget` function in "editingDowncast", not in "dataDowncast".
> Fix error in function documentation

- docs/builds/guides/migrate.md
- packages/ckeditor5-link/docs/_snippets/features/autolink.html
- packages/ckeditor5-link/docs/features/link.md
- packages/ckeditor5-link/src/autolink.js
Edited and amended: API docs; snippet content; plugin instructions; migration guide.
> Docs: Autolink guide and API docs corrected. [skip ci]

- packages/ckeditor5-table/package.json
- packages/ckeditor5-widget/package.json
Internal: Removed duplicated packages in `package.json` in `table` and `widget` packages. See #7706.
> Removed duplicated packages in pkg.json

- docs/builds/guides/frameworks/vuejs.md
- docs/features/ui-language.md
Other: Improved Vue.js localization docs. Part of #7688.
---
> Improve Vue.js localization docs

- packages/ckeditor5-table/src/tablekeyboard.js
- packages/ckeditor5-table/tests/tablekeyboard.js
Other (table): The whole table should be selected on the <kbd>Shift</kbd>+<kbd>Tab</kbd> press in the first table cell. Closes #7535.
---
> The whole table should be selected on Shift+Tab press in the first table cell

- docs/builds/guides/development/custom-builds.md
- docs/builds/guides/integration/advanced-setup.md
- docs/builds/guides/integration/installing-plugins.md
- docs/framework/guides/contributing/development-environment.md
- docs/framework/guides/quick-start.md
The required Node.js version was updated to 12.0.0+; the required npm version was updated to 5.7.1+
> Docs: Node and npm version update. [skip ci]

- packages/ckeditor5-image/docs/_snippets/features/image-caption.html
- packages/ckeditor5-image/docs/_snippets/features/image-link.html
- packages/ckeditor5-image/docs/_snippets/features/image-resize-buttons-dropdown.html
- packages/ckeditor5-image/docs/_snippets/features/image-resize-buttons.html
- packages/ckeditor5-image/docs/_snippets/features/image-resize-px.html
- packages/ckeditor5-image/docs/_snippets/features/image-resize.html
- packages/ckeditor5-image/docs/_snippets/features/image-style-presentational.html
- packages/ckeditor5-image/docs/_snippets/features/image-style.html
- packages/ckeditor5-image/docs/_snippets/features/image-toolbar.html
- packages/ckeditor5-image/docs/features/image.md
- packages/ckeditor5-image/src/imageresize/imageresizebuttons.js
- packages/ckeditor5-image/src/imageresize/imageresizecommand.js
- packages/ckeditor5-image/src/imageresize/imageresizeediting.js
- packages/ckeditor5-image/src/imageresize/imageresizehandles.js
- packages/ckeditor5-image/tests/imageresize/imageresizebuttons.js
- yarn.lock
CKEditor 5 image feature and image alignment docs - fixes and minor changes. Scope: guide, snippets.  
Still missing: live example for defining custom styles.
> Docs: Fixes to image guide. [skip ci]

- docs/builds/guides/integration/advanced-setup.md
> Docs: broken link in integration guide. [skip ci]

- packages/ckeditor5-engine/docs/_snippets/framework/extending-content-custom-element-converter.html
Docs (engine): Updated styling for the custom element converter demo. Closes #7781.
> i/7781: Update styling for the custom element converter demo

- docs/_snippets/features/wproofreader.html
- docs/_snippets/features/wproofreader.js
- docs/features/spelling-and-grammar-checking.md
- package.json
Docs: Updated WProofreader guide.
> Docs: Updated Wproofreader guide

- packages/ckeditor5-image/tests/imagetoolbar.js
- packages/ckeditor5-media-embed/tests/mediaembedtoolbar.js
- packages/ckeditor5-table/tests/tabletoolbar.js
Tests: Use custom matcher to match balloon add call arguments. Closes #7851.
> Use custom matcher to match balloon add call arguments.

- packages/ckeditor5-engine/src/model/utils/insertcontent.js
- packages/ckeditor5-engine/src/view/downcastwriter.js
- packages/ckeditor5-table/src/tablewalker.js
- packages/ckeditor5-table/tests/tablewalker.js
- packages/ckeditor5-utils/src/collection.js
- packages/ckeditor5-utils/src/focustracker.js
Docs: Corrected errors without messages. Closes #5643.
---
I also corrected some of the messages.
> Corrected errors without messages

- scripts/continuous-integration-script.js
Internal: Community PRs will not break the Travis process. Closes #7745.
> Community PRs will not break the Travis process

- packages/ckeditor5-markdown-gfm/LICENSE.md
Internal (markdown-gfm): Update LICENSE.md. Closes #7865 .
---
Just to double-check this entry. I've used similar algorithm to create those entries as ~Lo-Dash~ Lodash ones were created.
> Update markdown-gfm LICENSE.md.

- docs/_snippets/framework/tutorials/block-widget.js
- docs/_snippets/framework/tutorials/inline-widget.js
- docs/_snippets/framework/tutorials/using-react-in-widget.js
- docs/framework/guides/tutorials/implementing-a-block-widget.md
- docs/framework/guides/tutorials/implementing-an-inline-widget.md
- docs/framework/guides/tutorials/using-react-in-a-widget.md
- packages/ckeditor5-engine/docs/_snippets/framework/extending-content-allow-div-attributes.js
- packages/ckeditor5-engine/docs/_snippets/framework/extending-content-allow-link-target.js
- packages/ckeditor5-engine/docs/_snippets/framework/extending-content-arbitrary-attribute-values.js
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion-preserving-custom-content.md
- packages/ckeditor5-engine/src/conversion/downcasthelpers.js
- packages/ckeditor5-engine/tests/manual/highlight.js
- packages/ckeditor5-engine/tests/manual/nestededitable.js
- packages/ckeditor5-engine/tests/manual/selection.js
- packages/ckeditor5-engine/tests/manual/tickets/475/1.js
- packages/ckeditor5-engine/tests/manual/tickets/ckeditor5-721/1.js
- packages/ckeditor5-mention/tests/manual/mention.js
- packages/ckeditor5-widget/tests/manual/inline-widget.js
- packages/ckeditor5-widget/tests/manual/keyboard.js
- packages/ckeditor5-widget/tests/widgettoolbarrepository.js
Docs: Framework guides updated to latest conversion API changes. Closes #7910.
---
> #7910: Framework guides updated to latest conversion API changes

- packages/ckeditor5-utils/src/env.js
- packages/ckeditor5-utils/tests/env.js
Internal (utils): Added user-agent check for Blink. 
---
> Added user agent check for Blink

- packages/ckeditor5-utils/src/env.js
- packages/ckeditor5-utils/tests/env.js
Feature (utils): Implemented the Input Events Level 1 support detection. Closes [#7995](https://github.com/ckeditor/ckeditor5/issues/7995).
> #7995: Implemented the Input Events Level 1 support detection.

- packages/ckeditor5-page-break/docs/features/page-break.md
Merge after Pagination deployment.
> Docs: mention Pagination in Page break. [skip ci]

- packages/ckeditor5-utils/src/observablemixin.js
> Docs: API fixes. [skip ci]

- packages/ckeditor5-page-break/docs/features/page-break.md
Docs: Fix the CI by using absolute URLs to cross-repo docs. Closes #8122.
---
> Unfortunately, we need to use absolute URLs to workaround the CI problem

- package.json
Internal: Added support for linking nested external packages. Closes #8141.
---
> Add support for linking nested external packages

- docs/index.md
- packages/ckeditor5-alignment/docs/features/text-alignment.md
- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
- packages/ckeditor5-block-quote/docs/features/block-quote.md
- packages/ckeditor5-code-block/docs/features/code-blocks.md
- packages/ckeditor5-font/docs/features/font.md
- packages/ckeditor5-heading/docs/_snippets/features/default-headings.html
- packages/ckeditor5-heading/docs/_snippets/features/default-headings.js
- packages/ckeditor5-heading/docs/features/headings.md
- packages/ckeditor5-heading/docs/features/title.md
- packages/ckeditor5-highlight/docs/features/highlight.md
- packages/ckeditor5-indent/docs/features/indent.md
- packages/ckeditor5-list/docs/_snippets/features/lists-style.html
- packages/ckeditor5-list/docs/features/lists.md
- packages/ckeditor5-remove-format/docs/features/remove-format.md
Closes: cksource/content-documentation-proofread#335  
Closes: cksource/content-documentation-proofread#336
Adding "Related features" section to selected CKEditor 5 features documentation. Updating demos. Fixes.
> Docs: related block; new demos; minor fixes and expansions

- docs/features/index.md
- packages/ckeditor5-list/docs/features/lists.md
Formatting fix.
Online Builder link.
> Docs: features quickfix.

- packages/ckeditor5-utils/src/version.js
> Fixes typo in docs

- packages/ckeditor5-media-embed/docs/features/media-embed.md
Update doc with the good command to execute CF: https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembedcommand-MediaEmbedCommand.html
---
> Wrong command parameters

- packages/ckeditor5-basic-styles/docs/_snippets/features/basic-styles.html
A new, better demo to demonstrate all the basic style we have.
> Docs: new basic styles demo.

- packages/ckeditor5-html-embed/theme/htmlembed.css
Fix (html-embed): Fixing html embed covering image inserted above with align. Closes #8324.
---
> Fixing html embed covering image inserted above with align.

- scripts/continuous-integration-script.js
Internal: Improved the visibility of errors in CI build. Closes #8111.
---
One new improvement has been reported: https://github.com/ckeditor/ckeditor5/issues/8344.
> Improve the visibility of errors in CI build

- packages/ckeditor5-heading/docs/_snippets/features/title.html
- packages/ckeditor5-heading/docs/features/title.md
Closes #5625
Part of feature description was removed from the demo snippet and moved to the document itself.
> Docs title demo

- packages/ckeditor5-html-embed/theme/htmlembed.css
Fix (html-embed): Revisit HTML embed styles around floated elements. Closes #8332.
---
> Revisit HTML embed styles around floated elements

- packages/ckeditor5-basic-styles/src/code/codeediting.js
- packages/ckeditor5-basic-styles/tests/code/codeediting.js
Fix (basic-styles): Code should not be copied to a new line on Enter. Closes #8144.
---
> Code should not be copied to a new line on Enter

- packages/ckeditor5-paste-from-office/docs/_snippets/features/build-paste-from-office-source.js
- packages/ckeditor5-paste-from-office/docs/_snippets/features/paste-from-office.js
Adding list styles to paste from office demos.
Closes: #8181
> Docs: list styles in paste from office.

- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
Adding the autoformatting feature's information to the basic text styles guide.
> Docs: adding autoformatting to basic styles.

- packages/ckeditor5-list/docs/features/lists.md
Adding autoformatting information to the lists feature guide.
> Docs: autoformatting feature for lists.

- packages/ckeditor5-block-quote/docs/features/block-quote.md
Adding information about the autoformatting feature to the blockquote guide.
> Docs: autoformatting in block quote.

- packages/ckeditor5-code-block/docs/features/code-blocks.md
Adding information about the autoformatting feature to the code block guide.
> Docs: adding autoformatting to code blocks.

- packages/ckeditor5-select-all/docs/features/select-all.md
Expanding the select all guide intro.
Adding keyboard shortcuts to Related features block.
> Docs: expanding select all guide.

- docs/features/keyboard-support.md
Making guide intro human-friendly.
Adding related productivity features.
> Docs: keyboard shortcuts.

- packages/ckeditor5-autoformat/docs/features/autoformat.md
Adding Markdown-oriented information to the autoformatting feature.
> Docs: adding Markdown info to autoformatting.

- packages/ckeditor5-horizontal-line/docs/_snippets/features/horizontal-line.html
- packages/ckeditor5-horizontal-line/docs/features/horizontal-line.md
Extending the feature intro with usage description.
Adding a related feature to the guide.
Replacing demo.
This is part of the revamp epic: cksource/content-documentation-proofread#332
> Docs: horizontal rule

- docs/builds/guides/frameworks/vuejs-v3.md
Docs: Fixed integration guide for Vue 3. Closes #8497 and closes https://github.com/ckeditor/ckeditor5-vue/issues/169.
> Fix integration guide for Vue 3

- packages/ckeditor5-html-embed/src/htmlembedediting.js
- packages/ckeditor5-html-embed/tests/htmlembedediting.js
- packages/ckeditor5-html-embed/tests/manual/tickets/8328/1.html
- packages/ckeditor5-html-embed/tests/manual/tickets/8328/1.js
- packages/ckeditor5-html-embed/tests/manual/tickets/8328/1.md
Fix (html-embed): Fixed saving in HTML embed after it lost selection. Closes #8328.
> Fixed saving in HTML embed after it lost selection

- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
Changing info about the experimental nature of Markdown output.
> Docs: markdown output info.

- packages/ckeditor5-block-quote/docs/features/block-quote.md
- packages/ckeditor5-heading/docs/features/title.md
- packages/ckeditor5-horizontal-line/docs/api/horizontal-line.md
- packages/ckeditor5-horizontal-line/docs/features/horizontal-line.md
- packages/ckeditor5-html-embed/docs/api/html-embed.md
- packages/ckeditor5-html-embed/docs/features/html-embed.md
- packages/ckeditor5-image/docs/features/image.md
- packages/ckeditor5-link/docs/api/link.md
- packages/ckeditor5-page-break/docs/api/page-break.md
- packages/ckeditor5-page-break/docs/features/page-break.md
- packages/ckeditor5-restricted-editing/docs/api/restricted-editing.md
- packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md
- packages/ckeditor5-special-characters/docs/api/special-characters.md
- packages/ckeditor5-special-characters/docs/features/special-characters.md
- packages/ckeditor5-upload/docs/features/base64-upload-adapter.md
- packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
- packages/ckeditor5-widget/docs/api/widget.md
Docs: Aligned code snippets syntax to Highlight.js@10.
> Aligned code snippets syntax to Highlight.js@10 [stable]

- packages/ckeditor5-block-quote/docs/features/block-quote.md
- packages/ckeditor5-heading/docs/features/title.md
- packages/ckeditor5-horizontal-line/docs/api/horizontal-line.md
- packages/ckeditor5-horizontal-line/docs/features/horizontal-line.md
- packages/ckeditor5-html-embed/docs/api/html-embed.md
- packages/ckeditor5-html-embed/docs/features/html-embed.md
- packages/ckeditor5-image/docs/features/image.md
- packages/ckeditor5-link/docs/api/link.md
- packages/ckeditor5-page-break/docs/api/page-break.md
- packages/ckeditor5-page-break/docs/features/page-break.md
- packages/ckeditor5-restricted-editing/docs/api/restricted-editing.md
- packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md
- packages/ckeditor5-special-characters/docs/api/special-characters.md
- packages/ckeditor5-special-characters/docs/features/special-characters.md
- packages/ckeditor5-upload/docs/features/base64-upload-adapter.md
- packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
- packages/ckeditor5-widget/docs/api/widget.md
Internal: Reverted changes related to Highlight.js.
> Reverted changes related to Highlight.js

- packages/ckeditor5-heading/src/title.js
- packages/ckeditor5-heading/tests/title.js
Internal (heading): Conversion options should be passed to the downcast converters.
---
> Fixed conversion options in the Title plugin

- docs/_snippets/features/wproofreader.js
Closes: #8598
Updating web spell checker language.
Additional: multiline wrap option.
> Docs: changing spellcheck language.

- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
Removing an issue that was solved.
> Docs: removing outdated issue.

- packages/ckeditor5-engine/src/model/differ.js
Other (engine): Improved performance of `Differ#getChanges()`. Closes #8188.
---
> Improved performance of Differ#getChanges().

- docs/builds/guides/development/dll-builds.md
- packages/ckeditor5-adapter-ckfinder/dll-sample/index.html
- packages/ckeditor5-alignment/dll-sample/index.html
- packages/ckeditor5-autoformat/dll-sample/index.html
- packages/ckeditor5-autosave/dll-sample/index.html
- packages/ckeditor5-block-quote/dll-sample/index.html
- packages/ckeditor5-ckfinder/dll-sample/index.html
- packages/ckeditor5-cloud-services/dll-sample/index.html
- packages/ckeditor5-code-block/dll-sample/index.html
- packages/ckeditor5-easy-image/dll-sample/index.html
- packages/ckeditor5-font/dll-sample/index.html
- packages/ckeditor5-heading/dll-sample/index.html
- packages/ckeditor5-highlight/dll-sample/index.html
- packages/ckeditor5-horizontal-line/dll-sample/index.html
- packages/ckeditor5-indent/dll-sample/index.html
- packages/ckeditor5-link/dll-sample/index.html
- packages/ckeditor5-list/dll-sample/index.html
- packages/ckeditor5-markdown-gfm/dll-sample/index.html
- packages/ckeditor5-media-embed/dll-sample/index.html
- packages/ckeditor5-mention/dll-sample/index.html
- packages/ckeditor5-page-break/dll-sample/index.html
- packages/ckeditor5-paste-from-office/dll-sample/index.html
- packages/ckeditor5-remove-format/dll-sample/index.html
- packages/ckeditor5-restricted-editing/dll-sample/index.html
- sample/index.html
- sample/plugin/webpack.config.js
- scripts/dll/dll-loader.js
- webpack.config.dll.js
Internal: Export and read DLL from the scoped variable. Closes #8575.
---
Should be merged together with https://github.com/ckeditor/ckeditor5-dev/pull/681.
> Export and read DLL from the scoped variable

- packages/ckeditor5-engine/docs/framework/guides/deep-dive/element-reconversion.md
I follow the example and find out that the code in the example is incorrect.
> Docs: Update element-reconversion.md - correct code in _defineUI() function

- docs/features/toolbar.md
- packages/ckeditor5-ui/docs/_snippets/features/blocktoolbar.html
> Docs: links fixed.

- docs/builds/guides/frameworks/angular.md
Docs: Documenting common issue with zone.js when upgrading to a new Angular version.
---
Related issue: ckeditor/ckeditor5-angular#235
> Documenting common issue with zone.js when upgrading to a new Angular version.

- packages/ckeditor5-word-count/package.json
- packages/ckeditor5-word-count/src/wordcount.js
- packages/ckeditor5-word-count/tests/manual/wordcount.md
- packages/ckeditor5-word-count/tests/wordcount.js
Fix (word-count): A string of characters with a single special character inside should be counted as a single word. Closes #8078.
> Counting properly the words with spacial characters inside.

- packages/ckeditor5-table/src/converters/tableproperties.js
- packages/ckeditor5-table/tests/tableclipboard-paste.js
- packages/ckeditor5-table/tests/tableproperties/tablepropertiesediting.js
Fix (table): The contents of nested tables are no longer going through upcasting. Closes #8393.
---
> Do not upcast contents of inner table

- packages/ckeditor5-engine/src/model/schema.js
Docs (engine): Fix a typo in model/schema.js.
---
> Fix a typo in model/schema.js

- packages/ckeditor5-engine/src/view/downcastwriter.js
Docs (engine): Added missing API docs for the return value of `DowncastWriter#rename`.
> Added missing API docs for the return value of DowncastWriter#rename

- scripts/docs/build-content-styles.js
Internal: The version for content styles will be read from the changelog file.
> The version for content styles will be read from the changelog file

- packages/ckeditor5-clipboard/docs/framework/guides/deep-dive/clipboard.md
Docs (Clipboard): Update documentation for Clipboard Plugin. Closes #8920.
---
Community PR: #8967
> Docs: adjust clipboard-plugin code example

- packages/ckeditor5-ckfinder/src/index.js
- packages/ckeditor5-clipboard/src/index.js
- packages/ckeditor5-heading/src/index.js
- packages/ckeditor5-image/src/index.js
- packages/ckeditor5-select-all/src/index.js
- packages/ckeditor5-table/src/index.js
- packages/ckeditor5-upload/src/index.js
Internal: Added missing plugins to index files. Closes #8639.
---
Commit type is `Internal`, because the DLL feature was introduced in the current iteration.
> Added missing plugins to index files

- tests/manual/all-features-dll.js
Tests (ckeditor5): DLL manual test "imports" all packages from the `window` object. Closes #9039.
---
Requires https://github.com/ckeditor/ckeditor5-dev/pull/691.
> DLL manual test "imports" all packages from the window object

- packages/ckeditor5-link/src/autolink.js
- packages/ckeditor5-link/tests/autolink.js
Fix (link): Improved validation of autolink. Closes #8050.
---
> Improved validation of autolink

- packages/ckeditor5-basic-styles/tests/bold/boldediting.js
- packages/ckeditor5-basic-styles/tests/italic/italicui.js
- packages/ckeditor5-basic-styles/tests/strikethrough/strikethroughui.js
- packages/ckeditor5-basic-styles/tests/underline/underlineui.js
- packages/ckeditor5-core/tests/editingkeystrokehandler.js
- packages/ckeditor5-link/tests/linkui.js
- packages/ckeditor5-restricted-editing/tests/restrictededitingmodeediting.js
- packages/ckeditor5-select-all/tests/selectallediting.js
- packages/ckeditor5-undo/tests/undoediting.js
Tests (core, basic-styles, link, restricted-editing, select-all, undo): Tests should not fail on macOS after changes in the keystrokes handling. Closes #9083.
---
> Tests updated to the changed keystroke handling.

- packages/ckeditor5-table/tests/tablekeyboard.js
- packages/ckeditor5-widget/tests/verticalnavigation.js
Tests (widget, table): Vertical navigation tests updated to changes in Chrome.. Closes #9151.
---
> Vertical navigation tests updated to changes in Chrome.

- docs/framework/guides/tutorials/implementing-an-inline-widget.md
Docs: Fixed snippet in Implementing an inline widget guide. Closes #9215.
> Docs: Fixed snippet in Implementing an inline widget guide

- scripts/check-manual-tests.sh
Internal: Small improvements for the manual tests checker. See #9224.
---
Requires https://github.com/ckeditor/ckeditor5-dev/pull/694 to be released.
> Small improvements for the manual tests checker

- packages/ckeditor5-paste-from-office/docs/features/paste-from-word.md
Docs (image): known issues. Closes #8855
---
Adding "known issue" information about specific cases where content with styled text and images does not paste properly.
> Docs: adding known issues section in paste from Office.

- scripts/release/changelog.js
Other: Include Collaboration Features packages in the changelog.
> Include Collaboration Features while generating the changelog

- packages/ckeditor5-restricted-editing/docs/_snippets/features/restricted-editing.js
Docs (restricted-editing). Toolbar tooltip corrected. Closes #9284
> Docs: updating restricted editing toolbar tooltip.

- packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md
Docs (restricted-editing).
---
Additional information about the usage of toolbar button.
> Docs: feature usage expalantion extended.

- packages/ckeditor5-restricted-editing/src/restrictededitingmode/converters.js
- packages/ckeditor5-restricted-editing/src/restrictededitingmodeediting.js
- packages/ckeditor5-restricted-editing/tests/restrictededitingmode.js
- packages/ckeditor5-restricted-editing/tests/restrictededitingmodeediting-commands.js
- packages/ckeditor5-restricted-editing/tests/restrictededitingmodeediting.js
- packages/ckeditor5-restricted-editing/tests/restrictededitingmodeui.js
Internal (restricted-editing): Fixed restricted editing mode integration with drag and drop. Closes #9286. Closes #9279.
---
> Fixed restricted editing mode integration with drag and drop.

- packages/ckeditor5-watchdog/package.json
- packages/ckeditor5-watchdog/src/contextwatchdog.js
Fix (watchdog): Removed import from the `ckeditor5` package. Closes #9315.
---
> Removed `ckeditor5` dep from ckeditor5-watchdog

- packages/ckeditor5-clipboard/docs/_snippets/features/drag-drop.js
Internal (clipboard): Drag drop docs snippet configuration fix. Closes #9266.
---
> Drag drop docs snippet configuration fix.

- packages/ckeditor5-clipboard/src/clipboard.js
- packages/ckeditor5-clipboard/src/clipboardobserver.js
- packages/ckeditor5-clipboard/src/clipboardpipeline.js
- packages/ckeditor5-clipboard/src/datatransfer.js
- packages/ckeditor5-clipboard/src/dragdrop.js
- packages/ckeditor5-clipboard/src/pasteplaintext.js
- packages/ckeditor5-code-block/src/utils.js
- packages/ckeditor5-core/src/editor/editor.js
- packages/ckeditor5-engine/src/view/observer/mouseobserver.js
Docs: drag and drop API docs review.
> Docs: drag-n-drop API review.

- .editorconfig
See also:
- https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/code-style.html#strings
Type: Other. Closes #9203
---
This assures quotes in CKEditor5's style aren't rewritten accidentally
> editorconfig: Use single quotes

- tests/manual/all-features-dll.js
- tests/manual/all-features.html
- tests/manual/all-features.js
- tests/manual/all-features.md
Internal: Added language feature to all-features and all-features-dll manual tests. Closes #9269.
> Added language feature to all-features and all-features-dll manual tests

- packages/ckeditor5-code-block/src/codeblockediting.js
- packages/ckeditor5-code-block/src/converters.js
- packages/ckeditor5-code-block/src/utils.js
- packages/ckeditor5-code-block/tests/codeblockediting.js
Fix (code-block): Markers are now preserved on the upcast. Closes #9402.
---
> Preserve markers on upcast.

- packages/ckeditor5-language/docs/_snippets/features/textpartlanguage.html
- packages/ckeditor5-language/docs/features/language.md
> Docs: text part language demo fix.

- packages/ckeditor5-editor-classic/src/classiceditoruiview.js
- packages/ckeditor5-editor-decoupled/src/decouplededitoruiview.js
Type: Message. Closes #9527.
---
https://github.com/ckeditor/ckeditor5/search?q=%22fo+the%22
- packages/ckeditor5-editor-decoupled/src/decouplededitoruiview.js
- packages/ckeditor5-editor-classic/src/classiceditoruiview.js
> chore: Fix typos

- packages/ckeditor5-engine/src/model/schema.js
Docs (engine): Corrected invalid model schema guide links.
> Corrected model schema guide links

- packages/ckeditor5-image/src/image/imagetypecommand.js
- packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js
- packages/ckeditor5-image/src/imagecaption/imagecaptionui.js
- packages/ckeditor5-image/tests/image/imagetypecommand.js
- packages/ckeditor5-image/tests/imagecaption/imagecaptionediting.js
Fix (image): Preserving markers on image type conversion.
---
> Preserving markers on image type conversion

- docs/_snippets/tour-balloon.css
Docs: Changed default cursor to pointer one in docs tooltip. Closes #9419.
---
> Changed default cursor to pointer one in docs tooltip.

- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
Docs: adding known issue to Markdown output.
---
Information about improper rendering of nested tables in the output.
> Docs: adding known issue to Markdown output.

- packages/ckeditor5-media-embed/tests/manual/mediaembed.html
- packages/ckeditor5-media-embed/tests/manual/semanticmediaembed.html
Internal: Added Spotify exception to exclusions in manual tests. Closes #9678.
> Added Spotify exception to exclusions in manual tests

- packages/ckeditor5-alignment/ckeditor5-metadata.json
- packages/ckeditor5-basic-styles/ckeditor5-metadata.json
- packages/ckeditor5-font/ckeditor5-metadata.json
- packages/ckeditor5-heading/ckeditor5-metadata.json
- packages/ckeditor5-html-embed/ckeditor5-metadata.json
- packages/ckeditor5-media-embed/ckeditor5-metadata.json
- scripts/docs/features-html-output/third-party-packages/mathtype-ckeditor5/ckeditor5-metadata.json
Docs: Minor corrections for features' HTML output. Closes #9702.
> Minor corrections for features' HTML output

- tests/_data/large.html
Internal: Fixed missing images in `editorinit` manual test. Closes #9747.
> Fixed missing images in `editorinit` manual test

- README.md
- package.json
- packages/ckeditor5-source-editing/LICENSE.md
- packages/ckeditor5-source-editing/README.md
- packages/ckeditor5-source-editing/package.json
Internal (source-editing): Bootstrap the package. Closes #9803.
> Source-editing: bootstrap the package

- packages/ckeditor5-heading/docs/_snippets/features/title.html
- packages/ckeditor5-heading/docs/_snippets/features/title.js
Internal: Aligned the code after replacing the Highlight.js with Prism.js.
---
Requires a new version of Umberto.
> Aligned the code after replacing the Highlight.js with Prism.js

- packages/ckeditor5-link/docs/_snippets/features/linkdecorators.html
- packages/ckeditor5-link/docs/_snippets/features/linkdecorators.js
Docs: Removed highlight.js worker from the code snippet. Closes #9834.
---
> Removed highlight.js worker from the code snippet

- scripts/ci/check-packages-code-coverage.js
Tests: Enabled executing tests from the `ckeditor5` package on CI. Closes #9838.
> Enabled tests from the ckeditor5 package.

- docs/umberto.json
Docs: Revision history documentation TOC.
Merge with cksource/collaboration-features#4090
> Docs: revision history TOC.

- .github/ISSUE_TEMPLATE/1-bug-report.md
Internal: Added the 'Possible solution' section to the bug report template.
> Added the 'Possible solution' section to the bug report template.

- packages/ckeditor5-easy-image/docs/features/easy-image.md
- packages/ckeditor5-image/docs/_snippets/features/image-style-presentational.js
- packages/ckeditor5-image/docs/features/images-installation.md
- packages/ckeditor5-image/docs/features/images-resizing.md
- packages/ckeditor5-image/docs/features/images-styles.md
Multiple fixes to `master` nightly docs, as listed in closing tickets below:
Closes: #9907 
Closes: #9908 
Closes: #9910 
Closes: #9912
Closes: #9913 
Closes: #9919
> Docs: nightly master fixes.

- packages/ckeditor5-image/docs/features/images-styles.md
Docs (image): The sample editor in the image styles guide should be properly described. Closes #9911.
---
> Fixed the editor sample description.

- docs/builds/guides/integration/features-html-output-overview.md
- packages/ckeditor5-adapter-ckfinder/ckeditor5-metadata.json
- packages/ckeditor5-alignment/ckeditor5-metadata.json
- packages/ckeditor5-ckfinder/ckeditor5-metadata.json
- packages/ckeditor5-code-block/ckeditor5-metadata.json
- packages/ckeditor5-easy-image/ckeditor5-metadata.json
- packages/ckeditor5-font/ckeditor5-metadata.json
- packages/ckeditor5-heading/ckeditor5-metadata.json
- packages/ckeditor5-image/ckeditor5-metadata.json
- packages/ckeditor5-link/ckeditor5-metadata.json
- packages/ckeditor5-paragraph/ckeditor5-metadata.json
- packages/ckeditor5-upload/ckeditor5-metadata.json
Docs: Moving fixes in the features' output guide to proper package metadata files. Closes #9965.
> Docs: moving fixes to package files.

- docs/builds/guides/migration/migration-to-29.md
- packages/ckeditor5-image/docs/features/images-inserting.md
- packages/ckeditor5-image/docs/features/images-overview.md
- packages/ckeditor5-image/src/imageutils.js
Docs: Migration to v29.0.0 user guide.
Language review as requested in https://github.com/ckeditor/ckeditor5/issues/9339#issuecomment-868324817
> Docs: migration to 29 language review.

- packages/ckeditor5-find-and-replace/src/findandreplace.js
- packages/ckeditor5-find-and-replace/src/findcommand.js
- packages/ckeditor5-find-and-replace/src/findnextcommand.js
- packages/ckeditor5-find-and-replace/tests/findcommand.js
- packages/ckeditor5-find-and-replace/tests/findnextcommand.js
- packages/ckeditor5-find-and-replace/tests/findpreviouscommand.js
- packages/ckeditor5-find-and-replace/tests/manual/findandreplace.html
- packages/ckeditor5-find-and-replace/tests/manual/findandreplace.js
- packages/ckeditor5-find-and-replace/tests/manual/scrolling.html
- packages/ckeditor5-find-and-replace/tests/manual/scrolling.js
- packages/ckeditor5-find-and-replace/tests/replacecommand.js
Internal (find-and-replace): Fixed find and replace commands integration with readonly editor. Closes #9975.
> Fixed find and replace commands integration with readonly editor

- packages/ckeditor5-find-and-replace/src/findandreplaceui.js
- packages/ckeditor5-find-and-replace/theme/findandreplaceform.css
Fix (find-and-replace): As per issue #9959, I've applied various changes to the code to fix UI/UX problems with the find-and-replace feature.  
As of this moment, checkboxes styling (point 7) and the position of the prev/next arrows (point 6) are still missing. Closes #9959.
> I/9959: UI/UX improvements to find and replace feature

- packages/ckeditor5-find-and-replace/README.md
Fix (find-and-replace): Added missing badges for Readme.md file. Closes #10040.
> Added missing badges for Readme.md.

- packages/ckeditor5-html-support/docs/features/general-html-support.md
Docs: Fixed incorrect brackets in GHS docs. Closes https://github.com/ckeditor/ckeditor5/issues/10133.
> Docs: Fixed wrong brackets in GHS docs.

- docs/features/editor-placeholder.md
- docs/features/ui-language.md
- packages/ckeditor5-ui/docs/features/blocktoolbar.md
Docs demo section fixes.
---
Support PR for #9781
> Docs: additional demo section fixes.

- docs/builds/guides/migration/migration-to-29.md
Docs: Adding CKFinder information to v29.0.0 migration guide.
> Docs: CKFinder in Migration docs.

- packages/ckeditor5-minimap/README.md
- packages/ckeditor5-minimap/ckeditor5-metadata.json
- packages/ckeditor5-minimap/docs/api/minimap.md
- packages/ckeditor5-minimap/docs/features/minimap.md
- packages/ckeditor5-minimap/src/minimap.js
- packages/ckeditor5-minimap/src/minimapiframeview.js
- packages/ckeditor5-minimap/src/minimapview.js
- packages/ckeditor5-minimap/src/utils.js
Docs: Content minimap docs + API docs review.
> Content minimap documentation review.

- packages/ckeditor5-source-editing/docs/features/source-editing.md
Dos: clarifying Markdown source editing mode.
> Docs: source view MD info.

- packages/ckeditor5-build-decoupled-document/sample/index.html
Fix (build-decoupled-document): Fixed style of decoupled document build sample. Closes https://github.com/ckeditor/ckeditor5/issues/10095.
> Fixed style of decoupled document build sample

- docs/builds/guides/integration/features-html-output-overview.md
- packages/ckeditor5-html-support/src/htmlcomment.js
- packages/ckeditor5-html-support/tests/htmlcomment.js
Internal (html-support): Implemented API for the HTML Comments plugin . Closes #9661.
---
> Implement API for the HTML Comments plugin 

- packages/ckeditor5-html-support/package.json
- packages/ckeditor5-html-support/tests/htmlcomment-integration.js
- packages/ckeditor5-html-support/tests/htmlcomment.js
Internal (html-support): Added integration tests for `HtmlComment` plugin. Closes #9667.
> HTML comments: Added integration tests

- packages/ckeditor5-html-support/package.json
- packages/ckeditor5-html-support/src/index.js
- packages/ckeditor5-html-support/tests/manual/htmlcomment.html
- packages/ckeditor5-html-support/tests/manual/htmlcomment.js
- packages/ckeditor5-html-support/tests/manual/htmlcomment.md
- tests/manual/all-features-dll.js
- tests/manual/all-features.html
- tests/manual/all-features.js
- tests/manual/all-features.md
Internal (html-support): Improved manual test in `HtmlComment` plugin and added plugin to both all-features tests. Closes #10154.
> Improved manual test in `HtmlComment` plugin and added to both all-features tests

- packages/ckeditor5-html-support/docs/_snippets/features/general-html-support.html
- packages/ckeditor5-html-support/docs/_snippets/features/general-html-support.js
- packages/ckeditor5-html-support/docs/features/general-html-support.md
Docs: Enabled all HTML features in the GHS demo. Closes #9987.
> Docs: Enabled all HTML features in the GHS demo

- packages/ckeditor5-table/docs/_snippets/features/table-default-headings.html
- packages/ckeditor5-table/docs/_snippets/features/table-default-headings.js
- packages/ckeditor5-table/docs/features/table.md
Docs (table): Document table default headings feature. Closes #10292.
> Document table default headings feature

- packages/ckeditor5-html-support/docs/_snippets/features/general-html-support.html
- packages/ckeditor5-html-support/docs/_snippets/features/general-html-support.js
- packages/ckeditor5-html-support/docs/features/general-html-support.md
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing-with-markdown.html
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing-with-markdown.js
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing.html
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing.js
- packages/ckeditor5-source-editing/docs/features/source-editing.md
Docs: minor fixes to source editing and GHS demos.
> Docs: minor fixes to source editing demos.

- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing-imports.js
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing-with-markdown.js
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing.js
Docs: Added linkImage plugin to source editing docs demos. Closes https://github.com/ckeditor/ckeditor5/issues/10349.
---
> Docs: added linkImage plugin to source editing docs demos.

- packages/ckeditor5-clipboard/src/datatransfer.js
- packages/ckeditor5-clipboard/tests/datatransfer.js
Other (clipboard). Makes sure that DataTransfer.file property is not evaluated more than once. Closes #10287.
> Paste performance for large images

- packages/ckeditor5-source-editing/docs/features/source-editing.md
**Docs (source editing): relinking between repos.**
---
> Docs: relinking between repos.

- packages/ckeditor5-language/src/textpartlanguageui.js
- packages/ckeditor5-language/tests/textpartlanguageui.js
Other (language): 'Remove language' option is the first in the list. Closes #10338.
---
> 'Remove language' option should be the first

- docs/features/image-upload.md
- packages/ckeditor5-upload/docs/features/base64-upload-adapter.md
Docs(upload): Base64 efficiency information.
Closes: cksource/ckeditor5-internal#875
> Docs: Base64 efficiency information.

- packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.js
- packages/ckeditor5-find-and-replace/tests/ui/findandreplaceformview.js
Feature (find-and-replace): Made it possible to cycle find results by using <kbd>Enter</kbd> and <kbd>Shift</kbd>+<kbd>Enter</kbd> keystrokes. Closes #10012.
---
> Hit Enter to find next and Shift+Enter to find previous

- docs/features/index.md
> Docs: landing page fixes.

- docs/builds/guides/development/dll-builds.md
- packages/ckeditor5-clipboard/src/utils/normalizeclipboarddata.js
- packages/ckeditor5-core/lang/contexts.json
- packages/ckeditor5-find-and-replace/src/findandreplaceui.js
- packages/ckeditor5-html-support/docs/features/general-html-support.md
- scripts/docs/features-html-output/build-features-html-output.js
Docs: CKEditor 5 v29.2.0 post-release documentation review.
Touches: cksource/ckeditor5-internal#960
---
> Docs: v29.2 review.

- packages/ckeditor5-utils/src/dom/position.js
This is just an experiment/proposition for simplifying #10373
> Remove getBestConstrainedPosition in favour of unified getBestPosition

- docs/framework/guides/contributing/code-style.md
Docs: Mention imports between DLLs packages. See #10375.
---
Requires: https://github.com/ckeditor/eslint-plugin-ckeditor5-rules/pull/7.
> The Code style guide - mention imports between DLLs packages

- scripts/ci/check-packages-code-coverage.js
Internal (find-and-replace): Enables CI code coverage check for find-and-replace. Closes #9996.
---
> Enable code coverage check for find-and-replace

- .eslintrc.js
Internal: Removed list of DLL core packages from ESLint configuration file.
> Simplified ESLint configuration.

- packages/ckeditor5-engine/tests/controller/datacontroller.js
Tests (engine): Add tests for nested upcast and downcast conversion.
---
> Add tests for nested conversion

- docs/builds/guides/migration/migration-to-25.md
- docs/builds/guides/migration/migration-to-26.md
- docs/builds/guides/migration/migration-to-27.md
- docs/builds/guides/migration/migration-to-28.md
- docs/builds/guides/migration/migration-to-29.md
Docs: additional migration info.
---
The idea carried over from customer support.
> Docs: additional migration info.

- docs/builds/guides/migration/migration-to-30.md
- docs/index.md
- packages/ckeditor5-core/src/editor/editorconfig.jsdoc
Docs (core): Create a migration guide for the toolbar.viewportTopOffset config.. Closes #10401.
> Create a migration guide for the toolbar.viewportTopOffset config.

- packages/ckeditor5-engine/docs/framework/guides/deep-dive/schema.md
Docs: updating deep-dive guide schema info for `image`. Closes #10419
---
The guide needs more work on `$documentFragment` so no closing the original issue, yet.
> Docs: updating schema infor for image.

- packages/ckeditor5-find-and-replace/src/findandreplaceediting.js
- packages/ckeditor5-find-and-replace/src/findandreplacestate.js
- packages/ckeditor5-find-and-replace/src/findandreplaceui.js
- packages/ckeditor5-find-and-replace/src/findcommand.js
- packages/ckeditor5-find-and-replace/src/findnextcommand.js
- packages/ckeditor5-find-and-replace/src/findpreviouscommand.js
- packages/ckeditor5-find-and-replace/src/replaceallcommand.js
- packages/ckeditor5-find-and-replace/src/replacecommand.js
- packages/ckeditor5-find-and-replace/src/utils.js
- packages/ckeditor5-find-and-replace/tests/findcommand.js
Docs (find-and-replace): Adds missing API documentation for F&R. Closes #10415.
---
> Find & replace: Add missing API documentation

- packages/ckeditor5-html-support/docs/features/general-html-support.md
> Add documentation section to GHS Configuration.

- docs/features/keyboard-support.md
- packages/ckeditor5-autoformat/docs/features/autoformat.md
Docs: Release v30.0.0 documentation review. Touches #10602
---
> Docs: 30.0.0 post-release review.

- docs/framework/guides/quick-start.md
Docs: Adding info about package generator to the framework quickstart. Closes #10641
---
> Docs: adding package generator info.

- packages/ckeditor5-restricted-editing/docs/_snippets/features/restricted-editing.js
Docs: Cleaned up the toolbar code clutter. Closes #10779.
> Docs: Cleaned up the toolbar code clutter. 

- packages/ckeditor5-engine/src/view/matcher.js
Other (engine): Update `MatcherPattern` API documentation. Closes #10720.
---
> Update MatcherPattern API documentation

- docs/_snippets/examples/balloon-block-editor.js
- docs/_snippets/examples/balloon-editor.js
- docs/_snippets/examples/custom-build.js
- docs/_snippets/examples/document-editor.js
- docs/_snippets/examples/multi-root-editor.js
- docs/_snippets/features/placeholder-custom.js
- docs/_snippets/features/placeholder.js
- docs/_snippets/features/toolbar-basic.js
- docs/_snippets/features/toolbar-separator.js
- docs/_snippets/framework/tutorials/inline-widget.js
- packages/ckeditor5-heading/docs/_snippets/features/custom-heading-buttons.js
- packages/ckeditor5-heading/docs/_snippets/features/heading-buttons.js
- packages/ckeditor5-heading/docs/_snippets/features/title.js
- packages/ckeditor5-html-support/docs/_snippets/features/html-comment.js
- packages/ckeditor5-image/docs/_snippets/features/image-insert-via-pasting-url-into-editor.js
- packages/ckeditor5-markdown-gfm/docs/_snippets/features/markdown.js
- packages/ckeditor5-minimap/docs/_snippets/features/minimap.js
- packages/ckeditor5-restricted-editing/docs/_snippets/features/restricted-editing.js
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing-with-markdown.js
- packages/ckeditor5-source-editing/docs/_snippets/features/source-editing.js
- packages/ckeditor5-table/docs/_snippets/features/table-caption.js
- packages/ckeditor5-table/docs/_snippets/features/table-default-headings.js
- packages/ckeditor5-table/docs/_snippets/features/table-default-properties.js
- packages/ckeditor5-table/docs/_snippets/features/table-nesting.js
- packages/ckeditor5-table/docs/_snippets/features/table-styling-colors.js
- packages/ckeditor5-table/docs/_snippets/features/table-styling.js
- packages/ckeditor5-table/docs/_snippets/features/table.js
- packages/ckeditor5-ui/docs/_snippets/examples/bootstrap-ui-inner.js
Docs: adding \`ViewportTopOffset\` to demos. Closes #10729
---
Merge with: [https://github.com/cksource/ckeditor5-internal/pull/new/ci/10729](https://github.com/cksource/ckeditor5-internal/pull/new/ci/10729)
and with: cksource/collaboration-features#4295
> Adding `ViewportTopOffset` to demos.

- packages/ckeditor5-engine/src/view/domconverter.js
- packages/ckeditor5-engine/tests/view/domconverter/domconverter.js
Other (engine): Improve rendering mode filtering rules.
---
> Improve rendering mode filtering rules

- docs/builds/index.md
Docs: adding online builder to installation index.
Touches: #10681
---
Online builder would preferable need a guide on itself, too.
> Docs: adding online builder to installation index.

- docs/_snippets/features/read-only-build.js
- docs/_snippets/features/read-only-hide-toolbar.html
- docs/_snippets/features/read-only-hide-toolbar.js
- docs/_snippets/features/read-only.js
- docs/assets/read-only-export-pdf.css
- docs/features/read-only.md
Docs: Adding exports and f&r to read-only mode demo. Closes #10751
---
> Docs: adding exports to read-only.

- docs/umberto.json
**Docs: Remove premium feature icon for annotations guide in docs TOC.**
**Closes:** cksource/ckeditor5-internal#1174
---
> Docs: removing PF icon for annotations.

- docs/features/index.md
Docs: Adding Premium Features icon to features' index page.
---
Do not merge before 10:00 CET on 2021-11-16
> Docs: adding PF icon to index.

- docs/framework/guides/contributing/testing-environment.md
Docs: Documented custom assertion we use in tests. Closes #10872.
> Documented custom assertion we use in tests.

- docs/framework/guides/creating-simple-plugin.md
- docs/framework/guides/package-generator.md
- docs/umberto.json
Docs: adding interim TOC section for plugins-related guides. Closes: cksource/ckeditor5-internal#1186
---
> Docs: adding interim TOC section for plugins-related guides.

- package.json
Internal: Simplified the workspaces definition (cf/4280).
> Simplified the workspaces definition

- docs/builds/guides/frameworks/react.md
Docs: clarification of customizing information. Closes #10925
---
> Docs: claricication of customization guide.

- docs/builds/guides/frameworks/react.md
Docs: update links after collaboration samples rename. Closes https://github.com/cksource/collaboration-features/issues/4270.
---
> Update links after collaboration samples rename.

- packages/ckeditor5-font/src/fontsize.js
- packages/ckeditor5-font/tests/fontsize/fontsizeediting.js
Tests (font): Add tests for correct downcast of font-size values. Closes #9253.
Docs (font): Add missing closing paragraphs.
> Add tests for correct downcast of font-size values

- packages/ckeditor5-image/docs/features/images-resizing.md
Docs: Add missing array separator in code example
---
> Add missing array separator

- docs/builds/index.md
Fixed the typo in the first sentence.
---
> updated index.md

- docs/installation/advanced/predefined-builds.md
- docs/installation/getting-started/quick-start.md
- packages/ckeditor5-core/src/plugincollection.js
- packages/ckeditor5-editor-decoupled/docs/framework/guides/document-editor.md
- packages/ckeditor5-upload/src/filerepository.js
Type: Managing the predefined builds guide. 
Closes: [cksource/ckeditor5-internal#1272](https://github.com/cksource/ckeditor5-internal/issues/1272)
Alternative approach for #11069.
---
> Docs: predefined builds guide

- packages/ckeditor5-html-support/src/generalhtmlsupport.js
- packages/ckeditor5-html-support/src/integrations/script.js
- packages/ckeditor5-html-support/src/schemadefinitions.js
- packages/ckeditor5-html-support/tests/integrations/script.js
- packages/ckeditor5-html-support/tests/manual/generalhtmlsupport.js
Feature (html-support): Adds support for \<script> elements. Closes #10891.
---
> Adds support for <script> elements in GHS

- packages/ckeditor5-html-support/docs/_snippets/features/html-comment.html
Docs: fix html comment wrapped in p tags in demo. Closes https://github.com/ckeditor/ckeditor5/issues/11108.
> Docs: fix html comments demo.

- docs/installation/getting-started/basic-api.md
- docs/installation/getting-started/configuration.md
- docs/installation/getting-started/installing-plugins.md
- docs/installation/getting-started/maintenance.md
- docs/installation/getting-started/migration-from-ckeditor-4.md
- docs/installation/getting-started/quick-start.md
Docs: Added Quick recap and What's next? sections to Getting started articles. Closes cksource/ckeditor5-internal#1271.
> Docs: Added Quick recap and What's next? sections to Getting started articles

- packages/ckeditor5-clipboard/docs/framework/guides/deep-dive/clipboard.md
Docs: updating code snippet.
Closes cksource/ckeditor5-internal#1333.
---
> Updating code snippet

- docs/installation/getting-started/maintenance.md
Docs: CKEditor 5 maintenance guide.
Closes https://github.com/cksource/ckeditor5-internal/issues/1265#event-5941693062
---
> Docs: maintenance guide draft.

- docs/builds/guides/frameworks/angular.md
Docs: Added info box to the Angular integration guide. Closes #11156
> Docs: Added info box to the Angular integration guide

- docs/examples/index.md
- docs/framework/index.md
- docs/installation/index.md
- docs/support/index.md
- docs/updating/index.md
Docs: updates to documentation sections landing pages. Closes cksource/ckeditor5-internal#1419.
---
> Docs: minor changes to landing pages.

- packages/ckeditor5-engine/docs/_snippets/framework/mini-inspector-upcast-attribute.html
Internal (engine): Update upcast attribute mini-inspector snippet to use real image url.
> Update upcast attribute mini-inspector snippet to use real image url

- docs/builds/guides/frameworks/angular.md
- docs/builds/guides/frameworks/vuejs-v2.md
- docs/builds/guides/frameworks/vuejs-v3.md
Docs: guides on Vue and Angular integrations with editor from Online Builder. Closes https://github.com/ckeditor/ckeditor5/issues/11256.
> Docs: online builder integration in Vue and Angular

- docs/features/editor-placeholder.md
- docs/features/keyboard-support.md
- docs/features/math-equations.md
- docs/features/read-only.md
- docs/features/spelling-and-grammar-checking.md
- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-clipboard/docs/features/drag-drop.md
- packages/ckeditor5-clipboard/docs/features/paste-plain-text.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
- packages/ckeditor5-heading/docs/features/headings.md
- packages/ckeditor5-image/docs/features/images-inserting.md
- packages/ckeditor5-list/docs/features/lists.md
- packages/ckeditor5-media-embed/docs/features/media-embed.md
- packages/ckeditor5-select-all/docs/features/select-all.md
- packages/ckeditor5-table/docs/features/table.md
- packages/ckeditor5-typing/docs/features/text-transformation.md
Docs: reviewing sub/features installation sections. Closes cksource/ckeditor5-internal#1366
---
Especially check the installation instructions for `AutoImage`.  
Add installation instructions for `read-only` mode.
> Docs: installation sections review.

- packages/ckeditor5-autoformat/docs/features/autoformat.md
- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
Docs: adding online markdown editor links to documentation. Closes #11319.
---
> Docs: adding online markdown editor links to docs.

- docs/framework/guides/contributing/testing-environment.md
Docs: Added `--identity-file` (`-i`) option for automated tests.
---
> Docs: Added `--identity-file` (`-i`) option for automated tests

- packages/ckeditor5-markdown-gfm/package.json
- packages/ckeditor5-markdown-gfm/src/markdown2html/markdown2html.js
- packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/lists.js
- packages/ckeditor5-markdown-gfm/tests/gfmdataprocessor/strong-emphasis.js
Internal (markdown-gfm): Bumped marked to 4.x to prevent a security issue. Closes #11124. Closes #8314.
> Bumped marked to 4.x.

- packages/ckeditor5-engine/src/model/differ.js
- packages/ckeditor5-engine/src/model/document.js
- packages/ckeditor5-engine/src/model/markercollection.js
- packages/ckeditor5-engine/tests/model/differ.js
- packages/ckeditor5-engine/tests/model/document.js
- packages/ckeditor5-engine/tests/model/markercollection.js
Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))
Other: Introduced `Marker#getData()`. Improved marker-related change detection in Differ. Closes https://github.com/ckeditor/ckeditor5/issues/11389
---
> Introduced Marker#getData(). Improved marker-related change detection in Differ.

- docs/installation/getting-started/quick-start.md
Docs: Updated dependencies in the Quick start guide. Closes cksource/ckeditor5-internal#1443.
> Docs: Updated dependencies in the Quick start guide

- packages/ckeditor5-list/src/listproperties/listpropertiesediting.js
- packages/ckeditor5-list/tests/listproperties/listpropertiesediting.js
- packages/ckeditor5-list/tests/manual/list-properties.js
Fix (list): Fixes list properties after a paragraph following a list is toggled into list item. Closes #11408.
---
> Fix ListPropertiesEditing postfixer

- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/downcast.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/helpers/downcast.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/helpers/upcast.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/upcast.md
Docs (engine): Misc polishing in conversion guides. Closes #11173.
> Misc polishing in conversion guides

- docs/builds/guides/development/dll-builds-collaboration-features.md
- docs/builds/guides/development/dll-builds.md
- docs/builds/guides/frameworks/angular.md
- docs/builds/guides/frameworks/vuejs-v2.md
- docs/builds/guides/frameworks/vuejs-v3.md
- docs/builds/guides/migration/migration-to-33.md
- docs/framework/guides/tutorials/implementing-a-block-widget.md
Docs: post-release additional documentation review.
Part of #11364
---
> Docs: additional docs review for 33.0.0

- docs/updating/migration-to-33.md
Cross linking to summary of changes from the migration guide.
> Add info-box with link to summary of changes in the migration guide

- packages/ckeditor5-core/src/editor/editorconfig.jsdoc
- packages/ckeditor5-core/src/plugincollection.js
Docs: removing trailing slashes from docs.
> Docs: removing trailing slashes.

- packages/ckeditor5-html-embed/docs/_snippets/features/html-embed.js
Docs: replacing outdated code snippet in the HTML embed demo. Closes #11481.
---
> Docs: replacing outdated code snippet in the HTML embed demo.

- docs/framework/guides/architecture/intro.md
- docs/framework/guides/overview.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/downcast.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/helpers/downcast.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/helpers/intro.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/helpers/upcast.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/intro.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/conversion/upcast.md
Docs: making conversion guide titles SEO friendly.
Part of cksource/ckeditor5-internal#1591
---
> Docs: making conversion guide titles SEO friendly

- packages/ckeditor5-image/src/image/utils.js
- packages/ckeditor5-image/tests/image/imageblockediting.js
- packages/ckeditor5-image/tests/image/imageinlineediting.js
- packages/ckeditor5-image/tests/image/utils.js
Fix (image): The image upcast converter should consume the src attribute. Closes #11530.
> The image upcast converter should consume the src attribute

- packages/ckeditor5-style/CHANGELOG.md
- packages/ckeditor5-style/CONTRIBUTING.md
- packages/ckeditor5-style/LICENSE.md
- packages/ckeditor5-style/README.md
- packages/ckeditor5-style/ckeditor5-metadata.json
- packages/ckeditor5-style/docs/api/style.md
- packages/ckeditor5-style/docs/features/style.md
- packages/ckeditor5-style/package.json
- packages/ckeditor5-style/src/index.js
- packages/ckeditor5-style/webpack.config.js
Internal (style): Added meta files for the package. Closes #11332.
> Added meta files for the ckeditor5-style package

- docs/support/getting-support.md
- docs/support/license-and-legal.md
Docs: changes in the Getting support section. Closes cksource/ckeditor5-internal#1623.
---
> Docs: changes in the Getting support section.

- docs/updating/migration-to-33.md
- docs/updating/migration-to-34.md
Docs: migration to v34.x guide review.
---
Part of cksource/ckeditor5-internal#1635
> Docs: migration to v34.x guide review.

- packages/ckeditor5-style/src/stylecommand.js
- packages/ckeditor5-style/tests/stylecommand.js
Internal (style): The `StyleCommand` should be able to detect multiple inline styles applied. Closes #11588. Closes #11586.
---
> Fixed collecting active inline styles.

- docs/installation/getting-started/migration-from-ckeditor-4.md
- docs/support/faq.md
Docs: Adding a way to set editor height to the FAQ. Closes cksource/ckeditor5-internal#1606.
---
> Docs: adding editor height setting to FAQ.

- scripts/docs/get-latest-changelogs.js
Internal: Changed the way how to get all the latest releases.
> Changed the way how to get all the latest releases

- docs/updating/migration-to-31.md
Docs: updating the Migration to v31.x guide. Closes #11632.
---
> Docs: updating the Migration to v31.x guide.

- packages/ckeditor5-table-resize/package.json
- packages/ckeditor5-table-resize/src/tablecolumnresize/utils.js
- packages/ckeditor5-table-resize/tests/tablecolumnresizer/tablecolumnresizeediting.js
- packages/ckeditor5-table-resize/tests/tablecolumnresizer/utils.js
Fix (table-resize): Resolves issue when adding & removing text formatting was leading to an error.
---
> Table column resize text formatting error fix

- packages/ckeditor5-engine/src/index.js
Other (engine): Exported some `engine.View` classes in `index.js`.
> Exported some `engine.View` classes in `index.js`

- packages/ckeditor5-html-support/src/converters.js
- packages/ckeditor5-html-support/src/datafilter.js
- packages/ckeditor5-html-support/src/integrations/codeblock.js
- packages/ckeditor5-html-support/src/integrations/documentlist.js
- packages/ckeditor5-html-support/src/integrations/image.js
- packages/ckeditor5-html-support/src/integrations/mediaembed.js
- packages/ckeditor5-html-support/src/integrations/table.js
Other (html-support): Exposes internal `DataFilter` method as `processViewAttributes`. Closes #10827.
---
> GHS: DataFilter._consumeAllowedAttributes() made public

- packages/ckeditor5-list/src/index.js
Other (list): Exports `DocumentList` related plugins. Closes #11610.
---
> Export DocumentList{,Properties}{,Editing}

- packages/ckeditor5-watchdog/src/contextwatchdog.js
- packages/ckeditor5-watchdog/tests/contextwatchdog.js
Other (watchdog): Improved `ContextWatchdog` queueing mechanism. Closes #11664.
---
> Improved ContextWatchdog queueing mechanism.

- docs/_snippets/examples/bottom-toolbar-editor.js
- docs/examples/custom/bottom-toolbar-editor.md
Docs: Add code snippets for full-featured and bottom toolbar editor examples
---
Part of: #11622
Merge together with: https://github.com/cksource/ckeditor5-internal/pull/1691
> Add code snippets for editor examples

- packages/ckeditor5-table-resize/tests/tablecolumnresizer/tablecolumnresizeediting.js
Fix (table-resize): fixes 6 failing tests.
---
> Table column resize: fixes 6 failing tests

- .github/ISSUE_TEMPLATE/7-docs-issue-community.yml
- docs/umberto.json
Docs: Enabled the "report issue" widget in Umberto. Added a new (semi-automated) documentation issue template.
---
Requires the latest Umberto (which is not published yet).
> Enabled the "Report issue" widget in docs

- docs/support/browser-compatibility.md
Docs: Updating browser compatibility guide. 
---
Closes cksource/ckeditor5-internal#1714.
> Docs: updating browser compatibility guide.

- docs/installation/frameworks/angular.md
- docs/installation/frameworks/react.md
- docs/installation/frameworks/vuejs-v2.md
- docs/installation/frameworks/vuejs-v3.md
Docs: Rewriting framework components guide titles to boos SEO. Closes: #11759
---
> Docs: updating framework components guide titles.

- docs/updating/updating.md
Docs: Add links to flush method in the Updating guide. Closes #11817.
---
> Docs: Add links to flush method in the Updating guide

- packages/ckeditor5-font/docs/_snippets/features/font.html
Type: New font demo content. Closes #11733.
---
Part of: #9995
> Docs: new font demo content.

- docs/framework/guides/custom-editor-creator.md
Docs: code listing fix in the Creating custom editor guide. Closes cksource/ckeditor5-internal#1743.
---
> Docs: code listing fix.

- .github/ISSUE_TEMPLATE/7-docs-issue-community.yml
Docs: Added project version to the issue template for the "Report issue" widget.
---
Requires the latest Umberto.
> Added project version to the issue template for the "Report issue" widget

- docs/installation/frameworks/css.md
- docs/installation/frameworks/overview.md
- docs/installation/getting-started/basic-api.md
Docs: adding the recap and what's next sections around the frameworks integration guides. Closes cksource/ckeditor5-internal#1444
---
> Docs: adding bracket sections to framework guides; updating links.

- docs/framework/guides/tutorials/implementing-a-block-widget.md
- docs/framework/guides/tutorials/implementing-an-inline-widget.md
- docs/framework/guides/tutorials/using-react-in-a-widget.md
- packages/ckeditor5-mention/docs/examples/chat-with-mentions.md
Docs: rewriting headers for searchability
---
Part of cksource/ckeditor5-internal#1267
> Docs: rewriting headers for searchability

- packages/ckeditor5-ckbox/docs/_snippets/features/ckbox.js
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckbox/src/ckbox.js
- packages/ckeditor5-ckbox/src/ckboxcommand.js
- packages/ckeditor5-ckbox/src/ckboxediting.js
- packages/ckeditor5-ckbox/src/ckboxuploadadapter.js
- packages/ckeditor5-ckbox/tests/_utils/ckbox-config.js
- packages/ckeditor5-ckbox/tests/ckboxcommand.js
- packages/ckeditor5-ckbox/tests/ckboxediting.js
- packages/ckeditor5-ckbox/tests/ckboxuploadadapter.js
- packages/ckeditor5-ckbox/tests/manual/ckbox.js
Internal (ckbox): Support for `ckbox.assetsOrigin`.
> Support for `ckbox.assetsOrigin`

- packages/ckeditor5-ckbox/src/ckbox.js
- packages/ckeditor5-ckbox/src/ckboxcommand.js
- packages/ckeditor5-ckbox/tests/ckboxcommand.js
Internal (ckbox): Pass the `ckbox.assetsOrigin` to CKBox dialog.
> Pass the `ckbox.assetsOrigin` to CKBox dialog

- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: Improved the description for the special handling of the `defaultUploadCategories` option for CKBox.
---
> Improved the description for the special handling of the `defaultUploadCategories` option for CKBox

- packages/ckeditor5-ckbox/docs/_snippets/features/build-ckbox-source.js
- packages/ckeditor5-ckbox/docs/_snippets/features/ckbox.js
- packages/ckeditor5-ckfinder/docs/_snippets/features/build-ckfinder-source.js
- packages/ckeditor5-ckfinder/docs/_snippets/features/ckfinder-upload-only.js
- packages/ckeditor5-ckfinder/docs/_snippets/features/ckfinder.js
Docs: adding image options to CKBox+CKFinder.
---
Part of cksource/ckeditor5-internal#1814
> Docs: adding image options to CKBox+CKFinder.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckbox/src/ckbox.js
Docs: Added the `config.ckbox.language` configuration option to the CKBox feature guide.
> Added the `config.ckbox.language` configuration option to the CKBox feature guide

- docs/framework/guides/tutorials/implementing-an-inline-widget.md
Docs: fix typos in docs/framework/guides/tutorials/implementing-an-inline-widget.md
---
Q: Why isn't this branch name called `GITHUB-ISSUE-NUMBER`  ?
A: I have found the information in the [contributing guidelines](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/contributing.html). 
> Make sure to open a ticket in https://github.com/ckeditor/ckeditor5 describing the issue, feature or problem that you want to solve in your pull request. This can be skipped in case of obvious and trivial changes (typos, documentation, etc.).
This is my first time opening a pull request in this project , please let me know if my submission method is wrong.
> Docs: fix typos.

- packages/ckeditor5-image/src/imageinsert.js
- packages/ckeditor5-image/src/imageinsert/imageinsertui.js
- packages/ckeditor5-image/src/imageinsert/ui/imageinsertpanelview.js
- packages/ckeditor5-image/src/imageinsertviaurl.js
- packages/ckeditor5-image/tests/imageinsert.js
- packages/ckeditor5-image/tests/imageinsert/imageinsertui.js
- packages/ckeditor5-image/tests/imageinsert/ui/imageinsertpanelview.js
- packages/ckeditor5-image/tests/imageinsertviaurl.js
- packages/ckeditor5-image/tests/manual/imageinsert.html
- packages/ckeditor5-image/tests/manual/imageinsert.js
- packages/ckeditor5-image/tests/manual/imageinsert.md
Other (image): Introducing the `ImageInsertViaUrl` plugin enabling insertion of images via URL without the requirement of the `UploadPlugin`. Closes #11654.
MINOR BREAKING CHANGE (image): `ImageInsertPanelView#dropdownView` property is no longer accessible. Use `editor.plugins.get( 'ImageInsertUI' ).dropdownView` instead to access the image insert dropdown instance. See #11654.
---
It's a replacement for the `ImageInsert` plugin which does not require `ImageUpload`.
> Introducing the ImageInsertViaUrl plugin enabling insertion of images via URL without the requirement of the UploadPlugin

- docs/examples/builds/balloon-editor.md
- docs/installation/frameworks/overview.md
- docs/installation/getting-started/basic-api.md
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckbox/src/utils.js
- packages/ckeditor5-editor-inline/README.md
Docs: post-release review.
Part of https://github.com/cksource/ckeditor5-internal/issues/1818
---
> Docs: post-release review.

- LICENSE.md
- packages/ckeditor5-autosave/LICENSE.md
- packages/ckeditor5-build-balloon-block/LICENSE.md
- packages/ckeditor5-build-balloon/LICENSE.md
- packages/ckeditor5-build-classic/LICENSE.md
- packages/ckeditor5-build-decoupled-document/LICENSE.md
- packages/ckeditor5-build-inline/LICENSE.md
- packages/ckeditor5-clipboard/LICENSE.md
- packages/ckeditor5-code-block/LICENSE.md
- packages/ckeditor5-core/LICENSE.md
- packages/ckeditor5-editor-balloon/LICENSE.md
- packages/ckeditor5-editor-classic/LICENSE.md
- packages/ckeditor5-editor-decoupled/LICENSE.md
- packages/ckeditor5-editor-inline/LICENSE.md
- packages/ckeditor5-engine/LICENSE.md
- packages/ckeditor5-find-and-replace/LICENSE.md
- packages/ckeditor5-html-support/LICENSE.md
- packages/ckeditor5-image/LICENSE.md
- packages/ckeditor5-link/LICENSE.md
- packages/ckeditor5-markdown-gfm/LICENSE.md
- packages/ckeditor5-mention/LICENSE.md
- packages/ckeditor5-restricted-editing/LICENSE.md
- packages/ckeditor5-table/LICENSE.md
- packages/ckeditor5-typing/LICENSE.md
- packages/ckeditor5-ui/LICENSE.md
- packages/ckeditor5-utils/LICENSE.md
- packages/ckeditor5-watchdog/LICENSE.md
- packages/ckeditor5-widget/LICENSE.md
- packages/ckeditor5-word-count/LICENSE.md
Other: Updated license files in packages. Closes https://github.com/ckeditor/ckeditor5/issues/11754.
---
> Update license files

- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
Docs: adding premium badges to selected guides. Closes https://github.com/ckeditor/ckeditor5/issues/12010
---
> Docs: adding premium badges to selected guides.

- docs/framework/guides/creating-simple-plugin-timestamp.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-2.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-3.md
Docs: Fixing comments formatting. Closes #12101
---
> Docs: formatting comments.

- docs/features/ui-language.md
Docs: adding a list of professional translations to the UI language guide.
Part of https://github.com/cksource/ckeditor5-internal/issues/1847
---
> Docs: list professional translations in docs.

- packages/ckeditor5-utils/src/collection.ts
- packages/ckeditor5-utils/src/dom/emittermixin.ts
- packages/ckeditor5-utils/src/emittermixin.ts
- packages/ckeditor5-utils/src/eventinfo.ts
- packages/ckeditor5-utils/src/observablemixin.ts
Other (utils): Adds support for typed events in `EmitterMixin`. Closes #12076.
---
> TypeScript: Added support for typed events

- packages/ckeditor5-style/docs/_snippets/features/styles.html
Docs: trimming the styles dropdown demo. Closes: https://github.com/ckeditor/ckeditor5/issues/12137
---
> Docs: trimming the styles dropdown demo.

- packages/ckeditor5-restricted-editing/docs/_snippets/features/restricted-editing.js
- packages/ckeditor5-restricted-editing/tests/manual/restrictedediting.js
Internal: Updated Restricted editing manual test and documentation demo. Closes #12120.
> Updated Restricted editing manual test and documentation demo

- docs/features/index.md
- docs/framework/index.md
- docs/installation/index.md
- docs/support/index.md
- docs/umberto.json
- docs/updating/index.md
Docs: reverting and replacing unfortunate redirects for indexes.
A follow-up to: https://github.com/ckeditor/ckeditor5/pull/12091
---
> Docs: reverting and replacing unfortunate redirs for indexes.

- docs/framework/guides/creating-simple-plugin-timestamp.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-2.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-3.md
Docs: Fixed links to the tutorials repository after changing directory names there. Closes [#12100](https://github.com/ckeditor/ckeditor5/issues/12100).
---
> Docs: Fixed repo directory names and links.

- docs/_snippets/framework/abbreviation-level-1.js
- docs/_snippets/framework/abbreviation-level-2.js
- docs/_snippets/framework/abbreviation-level-3.js
- docs/_snippets/framework/abbreviationView-level-2.js
- docs/_snippets/framework/abbreviationView-level-3.js
- docs/framework/guides/creating-simple-plugin-timestamp.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/framework/guides/simple-plugin-tutorial/abbreviation-plugin-level-2.md
Docs: Removed localization from the Abbreviation and Timestamp tutorials. Closes #12102 .
---
> Docs: Removed localization from the Abbreviation and Timestamp tutorials.

- packages/ckeditor5-ckbox/docs/_snippets/features/ckbox.html
- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: removing the predefined image from the demo. Closes https://github.com/cksource/ckeditor5-internal/issues/1887
---
> Docs: removing predefined image from demo.

- packages/ckeditor5-table/src/tablecolumnresize/constants.js
- packages/ckeditor5-table/src/tablecolumnresize/converters.js
- packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js
- packages/ckeditor5-table/src/tablecolumnresize/utils.js
- packages/ckeditor5-table/tests/tablecolumnresize/tablecolumnresizeediting.js
- packages/ckeditor5-table/tests/tablecolumnresize/utils.js
Type: Message. Closes #11990 .
---
> Bump `TableColumnResize` plugin code coverage to 100%

- docs/framework/guides/development-tools.md
Docs: Added bookmarklet method to import CKEditor 5 inspector. Closes #12032.
---
> Docs: Added bookmarklet method to import CKEditor 5 inspector

- packages/ckeditor5-mention/docs/features/mentions.md
Docs: Information in Mentions guide how to use them with Comments. Closes https://github.com/cksource/collaboration-features/issues/4632.
---
> Docs: Information in Mentions guide how to use them with Comments

- docs/updating/migration-to-35.md
Docs: Added a note about TS being used now.
> [Migration guide] Added a note about TS being used now

- packages/ckeditor5-ui/src/toolbar/balloon/balloontoolbar.js
Docs (ui): Fixed `balloonToolbar` item separator example
> Docs (ui): Fixed `balloonToolbar` item separator example

- packages/ckeditor5-table/docs/api/table.md
- packages/ckeditor5-table/src/tablecolumnresize.js
- packages/ckeditor5-table/src/tablecolumnresize/converters.js
- packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js
- packages/ckeditor5-table/src/tablecolumnresize/tablecolumnwidthscommand.js
- packages/ckeditor5-table/src/tablecolumnresize/tablewidthresizecommand.js
- packages/ckeditor5-table/src/tablecolumnresize/utils.js
- packages/ckeditor5-table/tests/tablecolumnresize/utils.js
Fix (table): Improved the API documentation of table column resize feature. Closes #12059.
---
This PR is build on top of #12049 ([ck/11990-table-column-resize-code-coverage](https://github.com/ckeditor/ckeditor5/tree/ck/11990-table-column-resize-code-coverage) branch), so that one should be merged first.
> Revisited table column resize API docs.

- docs/installation/index.md
Docs: Correcting an erroneous call in the installation choice quiz script.
Closes:  https://github.com/cksource/ckeditor5-internal/issues/18651
---
> Docs: repairing the installation quiz.

- packages/ckeditor5-engine/src/model/documentselection.ts
- packages/ckeditor5-engine/src/model/model.ts
- packages/ckeditor5-engine/src/model/selection.ts
- packages/ckeditor5-engine/tests/model/model.js
- packages/ckeditor5-engine/tests/tickets/11925.js
Fix (engine). Fixes calling `writer.setSelection()` so that it does not break the editor. Closes #11925.
---
> Fix (engine). Fixes calling writer.setSelection() so that it does not break the editor.

- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
- packages/ckeditor5-font/docs/features/font.md
- packages/ckeditor5-highlight/docs/features/highlight.md
Docs: adding styles feature to the related section in other guides. Closes #12310
---
> Docs: adding styles to related in other guides.

- packages/ckeditor5-code-block/docs/features/code-blocks.md
> code-blocks.md: Fix typos

- docs/_snippets/examples/document-editor.js
Docs: add table column resize feature to document editor example demo.
Part of cksource/ckeditor5-internal#1740
---
> Docs: table resize in document example.

- scripts/release/publish.js
Internal: Allow defining optional files and directories per package in release config.
---
> Allow defining optional files and directories per package

- .travis.yml
- package.json
- scripts/ci/ansi-colors.js
- scripts/ci/check-packages-code-coverage.js
- scripts/ci/travis-check.js
- scripts/ci/travis-folder.js
- scripts/dll/webpack.config.dll.js
Internal: Improved CI performance.
---
> Improved CI performance

- docs/features/math-equations.md
- docs/features/spelling-and-grammar-checking.md
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
Docs: Update Premium Features infoboxes.
Touches: cksource/ckeditor5-internal#1946
---
> Docs: updating premium features infobox.

- docs/support/faq.md
Docs: Added information about the superbuild to the FAQ. Closes #12433.
---
> Docs: Added information about the superbuild to the FAQ

- packages/ckeditor5-special-characters/docs/_snippets/features/special-characters-extended-category.js
- packages/ckeditor5-special-characters/docs/features/special-characters.md
Docs (special-characters): Minor fixes in special characters dropdown guide.
---
> Minor fixes in styles dropdown guide

- docs/updating/migration-to-35.md
Docs (ckeditor5): Added a migration entry about bringing back the previous look of the editor. Closes #12437.
> Added a migration entry about bringing back the previous look of the editor

- packages/ckeditor5-list/theme/liststyles.css
Fix (list): Improved styles for indented lists. Closes #12179.
---
Styles were created for both unordered and ordered lists.
> Created styles for indented lists (unordered and ordered)

- docs/installation/getting-started/migration-from-ckeditor-4.md
- docs/support/faq.md
Docs: Migrated CKEditor 4 related questions to the migration guide. Closes #12434.
---
> Docs: Migrated CKEditor 4 related questions to the migration guide

- docs/support/faq.md
Docs: corrected source mode question in the FAQ. Closes #12487.
---
> Docs: corrected source mode question in the FAQ

- packages/ckeditor5-style/tests/stylecommand.js
Tests (style): Check if styles are enabled for paragraphs inside html sections. Closes #12417.
---
> Tests (style): Check if styles are enabled for paragraphs inside html sections.

- packages/ckeditor5-engine/src/model/position.ts
- packages/ckeditor5-engine/tests/model/position.js
- packages/ckeditor5-utils/src/dom/rect.ts
Other (utils): Dropped using lodash `isElement()` to achieve better performance in `Rect` class.
Other (engine): Reimplemented `Position#isTouching()` to achieve better performance.
---
@oleq could you check changes in `Rect`?
@arkflpc could you check this PR from TS point of view?
> Performance improvements in CKE5

- packages/ckeditor5-ui/src/toolbar/toolbarview.js
- packages/ckeditor5-ui/tests/toolbar/toolbarview.js
Internal (ui): Brought support for `config.toolbar.removeItems` to declarative nested toolbar dropdowns. Closes #12529.
---
I refactored the code of `ToolbarView` just a little bit for clarity. `fillFromConfig()` got too long.
> Brought support for config.toolbar.removeItems to declarative nested toolbar dropdowns.

- docs/features/math-equations.md
- docs/features/spelling-and-grammar-checking.md
Docs: update premium features infobox. 
Part of cksource/ckeditor5-internal#2031
---
> Docs: update premium features infobox.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
Docs: rewording premium feature infoboxes.
---
> Docs: rewording premium feature infoboxes.

- packages/ckeditor5-widget/src/widgetresize.js
- packages/ckeditor5-widget/src/widgetresize/resizer.js
- packages/ckeditor5-widget/tests/widgetresize.js
- packages/ckeditor5-widget/tests/widgetresize/resizer.js
Fix (widget): Update code coverage. Closes #12538.
> Fix (widget): Update code coverage.

- packages/ckeditor5-engine/src/view/domconverter.ts
- packages/ckeditor5-engine/src/view/observer/selectionobserver.ts
- packages/ckeditor5-engine/src/view/renderer.ts
- packages/ckeditor5-engine/tests/view/domconverter/dom-to-view.js
Fix (engine). Fixes \`IndexSizeError\` when the background color is applied on Safari. Closes #12375. Closes #12294.
---
> Fixes IndexSizeError when the background color is applied on Safari.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
Docs: Updating the premium features license contact info box.
Part of cksource/ckeditor5-internal#2069
---
> Docs: premium features info box update.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: rewording premium features info box.
---
> Docs: rewording premium features info box.

- docs/features/spelling-and-grammar-checking.md
- docs/installation/getting-started/predefined-builds.md
Changing webspellcker feature title + minor changes to content and installation guide
Docs: Changing webspellcker feature title + minor changes to content
---
> Docs: Changing webspellcker feature title + minor changes to content.

- docs/installation/getting-started/quick-start.md
Docs: fixing typos. Closes #12483
---
> Docs: fixing typos. Closes #12483

- packages/ckeditor5-core/tsconfig.json
- packages/ckeditor5-engine/tsconfig.json
- packages/ckeditor5-ui/tsconfig.json
- packages/ckeditor5-utils/tsconfig.json
Internal: Fixes `tsconfig.json` handling in VSCode.
---
> Fix include in tsconfig.json

- package.json
Other: Updates `eslint-config-ckeditor5` to 4.0.2. Closes #12547.
---
> Bump up eslint-config-ckeditor5 version to 4.0.2

- package.json
Internal: Downgraded the eslint configuration to hide array errors.
---
> Internal: Downgraded the eslint configuration to hide array errors.

- docs/installation/getting-started/predefined-builds.md
Docs: updating the builds feature list.
---
Keep branch after the merge, this is a two-step task, part of cksource/ckeditor5-internal#2116
> Docs: updating the builds feature list.

- docs/features/spelling-and-grammar-checking.md
Docs: Added modified webpack config with instructions for WProofreader guide. Closes #12533.
---
> Docs: Added modified webpack config with instructions for WProofreader guide

- docs/features/spelling-and-grammar-checking.md
Doc (webspellchecker): Replace sentence in "web spell checker" documentation. Closes [#2165](https://github.com/cksource/ckeditor5-internal/issues/2165).
---
> Replace sentence in "web spell checker" documentation

- docs/framework/guides/contributing/development-environment.md
- docs/installation/getting-started/migration-from-ckeditor-4.md
- docs/installation/getting-started/quick-start.md
- docs/umberto.json
- packages/ckeditor5-build-classic/README.md
- packages/ckeditor5-clipboard/src/clipboard.ts
- packages/ckeditor5-clipboard/src/clipboardpipeline.ts
- packages/ckeditor5-clipboard/src/dragdrop.ts
- packages/ckeditor5-core/src/command.ts
- packages/ckeditor5-core/src/context.ts
- packages/ckeditor5-core/src/multicommand.ts
- packages/ckeditor5-core/src/pendingactions.ts
- packages/ckeditor5-engine/src/model/schema.ts
- packages/ckeditor5-enter/src/enter.ts
- packages/ckeditor5-enter/src/entercommand.ts
- packages/ckeditor5-enter/src/enterobserver.ts
- packages/ckeditor5-enter/src/utils.ts
- packages/ckeditor5-ui/src/componentfactory.ts
- packages/ckeditor5-undo/src/basecommand.ts
- packages/ckeditor5-undo/src/undo.ts
- packages/ckeditor5-undo/src/undocommand.ts
- packages/ckeditor5-undo/src/undoediting.ts
- packages/ckeditor5-upload/src/filerepository.ts
- packages/ckeditor5-utils/src/emittermixin.ts
- packages/ckeditor5-utils/src/observablemixin.ts
- packages/ckeditor5-widget/src/highlightstack.ts
Docs: v35.3.0 review.
Part of cksource/ckeditor5-internal#2163
---
> Docs: v35.3.0 review.

- packages/ckeditor5-table/tests/manual/tablemocking.js
> `tablemocking` manual test is broken

- docs/framework/guides/architecture/core-editor-architecture.md
Docs: Fixed simple plugin link in the core guide. Closes #12787.
---
> Docs: Fixed simple plugin link in the core guide

- docs/features/toolbar.md
Docs: toolbar custom icons update. Closes #12804
---
> Docs: toolbar custom icons update.

- packages/ckeditor5-engine/tests/controller/datacontroller.js
Tests (engine): Fixed `data-caption` nested conversion with inline elements. Closes #12797.
---
> Fixed test for data-caption nested conversion.

- docs/features/ui-language.md
Docs: translation table update. Closes cksource/ckeditor5-internal#2224
---
> Docs: translation table update.

- packages/ckeditor5-ckbox/docs/_snippets/features/build-ckbox-source.html
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-undo/docs/_snippets/features/undo-redo.html
Docs: bump CKBox version.
Part of #12855
---
> Docs: bump CKBox version.

- docs/framework/guides/tutorials/data-from-external-source.md
- docs/framework/guides/tutorials/implementing-an-inline-widget.md
- docs/framework/guides/tutorials/using-react-in-a-widget.md
Docs: Changed order of items in submenu "Advanced tutorials" and add a `new` badge to the newest guide. Closes https://github.com/ckeditor/ckeditor5/issues/12859.
---
> Set proper order of guides and add 'new' badge to the new guide

- packages/ckeditor5-image/src/imageblock.js
Fix copypasta from inline file
---
> Tiny typo in image block docs

- packages/ckeditor5-special-characters/docs/features/special-characters.md
Type (special-characters.md) : Bolden the text to make it faster to read
> enhance special-characters.md

- docs/_snippets/framework/tutorials/external-data-widget.html
Internal: Removed stray "the".
---
> Fixed a typo in the "Data from external source" tutorial content

- package.json
- scripts/release/clean.js
Internal: Adds script for `yarn run release:clean`. Closes #12820.
---
> Add script for 'release:clean'

- packages/ckeditor5-list/src/documentlist/documentlistediting.js
- packages/ckeditor5-list/src/documentlist/documentlistutils.js
- packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesediting.js
- packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesutils.js
- packages/ckeditor5-list/src/index.js
- packages/ckeditor5-list/tests/documentlist.js
- packages/ckeditor5-list/tests/documentlist/documentlistutils.js
- packages/ckeditor5-list/tests/documentlistproperties.js
- packages/ckeditor5-list/tests/documentlistproperties/documentlistpropertiesutils.js
Internal (list): Bulk document list utils into plugin. Closes #12851.
> Internal (list): Bulk document list utils into plugin.

- docs/features/spelling-and-grammar-checking.md
Type: changing just one sentence. See [ci/2190](https://github.com/cksource/ckeditor5-internal/issues/2190).
---
Rest of the changes to be introduced in CKE4 Docs
> Docs: changing just one sentence

- docs/_snippets/features/toolbar-nested-simple.html
- docs/_snippets/features/toolbar-nested-simple.js
- docs/features/toolbar.md
Docs: adding more toolbar dropdowns. Closes cksource/ckeditor5-internal#2245
---
> Docs: adding more toolbar dropdowns.

- docs/_snippets/framework/tutorials/external-data-widget.html
- docs/_snippets/framework/tutorials/external-data-widget.js
- docs/framework/guides/tutorials/data-from-external-source.md
Docs: widget fixes. Closes #12869
---
> Docs: widget fixes.

- package.json
- scripts/external-postinstall.js
- scripts/postinstall.js
Internal: Fixed husky installation script.
> Fixed husky installation script

- docs/updating/migration-to-35.md
Docs: adding missing info to guide. Closes #12918
---
> Docs: adding missing info to guide.

- packages/ckeditor5-ckbox/docs/_snippets/features/build-ckbox-source.html
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-undo/docs/_snippets/features/undo-redo.html
Docs: updating CKBox call. 
Part of cksource/ckeditor5-internal#2261
---
> Docs: updating CKBox call.

- docs/features/keyboard-support.md
Docs: adding keystroke information. Closes #12345
---
> Docs: adding keystroke info.

- docs/_snippets/framework/tutorials/external-data-widget.html
Docs: Exclusion for crawler on "Data from external source" file. Closes #12959.
---
> Defining exclusions for web crawler

- docs/_snippets/framework/tutorials/external-data-widget.html
Docs: Exclusion for crawler on "Data from external source" file. Closes #12959.
---
> Add wildcard to ignore all errors

- packages/ckeditor5-engine/_src/view/document.js
- packages/ckeditor5-engine/_src/view/renderer.js
- packages/ckeditor5-engine/src/view/document.ts
- packages/ckeditor5-engine/src/view/observer/focusobserver.ts
- packages/ckeditor5-engine/src/view/observer/selectionobserver.ts
- packages/ckeditor5-engine/src/view/renderer.ts
- packages/ckeditor5-engine/src/view/view.ts
- packages/ckeditor5-engine/tests/view/document.js
- packages/ckeditor5-engine/tests/view/observer/focusobserver.js
- packages/ckeditor5-engine/tests/view/observer/selectionobserver.js
- packages/ckeditor5-engine/tests/view/renderer.js
- packages/ckeditor5-engine/tests/view/view/view.js
Fix (engine): Introducing a new flag to prevent rendering on Chrome before changing the selection. Closes #12967.
---
> Focus issue

- docs/_snippets/framework/tutorials/external-data-widget.html
Docs: Exclusion for crawler on "Data from external source" file. Closes https://github.com/ckeditor/ckeditor5/issues/12959.
---
> Add content-security-policy header to pass the binance.com request

- docs/framework/guides/tutorials/implementing-a-block-widget.md
- docs/framework/guides/tutorials/implementing-an-inline-widget.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/schema.md
Docs: Updated tutorials and schema deep dive guide to reflect new generic items. Closes #12810.
---
> Updated tutorials and schema deep dive guide to reflect new generic items

- docs/framework/guides/creating-simple-plugin-timestamp.md
Multiple improvements in the basic plugin guide including more detailed instructions for the DIY version.
Docs: Create basic plugin guide improvements. Closes https://github.com/cksource/ckeditor5-internal/issues/2191.
> Docs: Create basic plugin guide improvements

- docs/installation/advanced/features-html-output-overview.md
- packages/ckeditor5-heading/ckeditor5-metadata.json
- packages/ckeditor5-paragraph/ckeditor5-metadata.json
Docs: adding $block info. Closes #9698
---
> Docs: adding $block info.

- docs/installation/getting-started/predefined-builds.md
Docs: Rephrased a sentence in the predefined builds guide. Closes [#2293](https://github.com/cksource/ckeditor5-internal/issues/2293).
---
Rephrased a sentence in the [predefined builds](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html) guide to clarify its meaning.
From:
> However, CDN only offers ready-to-use, predefined packages – the builds – and as does not offer much customization capabilities.
To:
> However, CDN only offers ready-to-use, predefined packages (the builds). This limits its customization capabilities.
> Docs: Rephrased a sentence in the predefined builds guide.

- docs/examples/framework/data-from-external-source.md
Docs: Exposed "Data from external source" demo on examples page. Closes https://github.com/cksource/ckeditor5-internal/issues/2257.
---
> Docs: Exposed "Data from external source" demo on examples page

- docs/installation/getting-started/installing-plugins.md
Docs: Added meaningful comments to ellipses in installing plugins guide. Closes [#13039](https://github.com/ckeditor/ckeditor5/issues/13039).
---
Added explanatory comments to ellipses in a code snippet in the installing plugins guide.
> Docs: Added meaningful comments to ellipses in installing plugins guide.

- packages/ckeditor5-utils/src/collection.ts
- packages/ckeditor5-utils/src/focustracker.ts
- packages/ckeditor5-utils/src/mapsequal.ts
- packages/ckeditor5-utils/src/observablemixin.ts
Docs (utils): Fixed warnings reported by TypeDoc.
---
> Fixed warnings reported by TypeDoc

- docs/updating/migration-from-ckeditor-4.md
Docs: updating links to installation overview from migration guide. Closes cksource/ckeditor5-internal#2343
---
> Docs: updating links.

- docs/_snippets/framework/tutorials/using-react-in-widget.html
- docs/examples/framework/using-react-in-a-widget.md
Docs: Expose "Using a React component in a block widget" demo on examples page.
Closes https://github.com/cksource/ckeditor5-internal/issues/2309
---
> Docs: Expose "Using a React component in a block widget" demo on examples page

- CHANGELOG.md
- docs/examples/framework/data-from-external-source.md
- docs/umberto.json
Feature (engine): Selection hooks added. Closes #6837
---
> Feature (engine): Selection hooks added.

- docs/framework/guides/contributing/git-commit-message-convention.md
Docs: update image. Closes #6837
---
> Docs: update image.

- docs/examples/framework/inline-widget.md
Docs: Exposed "Implementing an inline widget" demo on examples page. Closes [#2258](https://github.com/cksource/ckeditor5-internal/issues/2258).
---
Created a new example on the examples page containing the "Implementing an inline widget" demo.
> Docs: Exposed "Implementing an inline widget" demo on examples page.

- docs/_snippets/framework/tutorials/inline-widget.js
- docs/examples/framework/content-placeholder.md
- docs/examples/framework/using-react-in-a-widget.md
- docs/umberto.json
Docs: renaming examples. Closes cksource/ckeditor5-internal#2405
---
> Docs: renaming examples.

- docs/examples/builds/balloon-editor.md
Type: Message. Closes #13173.
---
> Docs: Corrected typos in imports in balloon editor example page

- docs/installation/getting-started/predefined-builds.md
Docs: repeating the npm method in the installation example. Closes cksource/ckeditor5-internal#2445
---
> Docs: repeating the npm method in installation example.

- packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js
- packages/ckeditor5-table/src/tablecolumnresize/utils.js
Fix (table): Adding table resizer elements on editing downcast to improve the performance. Closes #13097.
---
> Improving table column resize performance

- packages/ckeditor5-style/docs/features/style.md
Docs: additional info about styles and formatting across features. Closes #12772
---
> Docs: additional info about styles and formatting across features.

- packages/ckeditor5-autoformat/docs/features/autoformat.md
- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
- packages/ckeditor5-block-quote/docs/features/block-quote.md
- packages/ckeditor5-code-block/docs/features/code-blocks.md
- packages/ckeditor5-find-and-replace/docs/features/find-and-replace.md
- packages/ckeditor5-font/docs/features/font.md
- packages/ckeditor5-heading/docs/features/title.md
- packages/ckeditor5-indent/docs/features/indent.md
- packages/ckeditor5-minimap/docs/features/minimap.md
- packages/ckeditor5-typing/docs/features/text-transformation.md
Docs: examples revamp (13040 and others). Closes #13085 #13084 #13083 #13063 #13045 #13044 #13042 #13041 #13040
---
> Docs: examples revamp (13040 and other examples)

- docs/examples/custom/bottom-toolbar-editor.md
Docs: heading cleanup. Closes #13230
---
_Merge after_ cksource/ckeditor5-internal#2485
> Docs: heading cleanup.

- docs/features/image-upload.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
Docs: minor rewrites in the image upload guide. Closes cksource/ckeditor5-internal#1910
---
> Docs: minor rewrites.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: adding credentials info to the installation section. Closes #12988.
---
> Docs: adding credentials info to the installation section.

- packages/ckeditor5-engine/_src/view/document.js
- packages/ckeditor5-engine/_src/view/observer/focusobserver.js
- packages/ckeditor5-engine/_src/view/observer/selectionobserver.js
- packages/ckeditor5-engine/_src/view/renderer.js
- packages/ckeditor5-engine/src/view/document.ts
- packages/ckeditor5-engine/src/view/observer/focusobserver.ts
- packages/ckeditor5-engine/src/view/observer/selectionobserver.ts
- packages/ckeditor5-engine/src/view/renderer.ts
- packages/ckeditor5-engine/src/view/view.ts
- packages/ckeditor5-engine/tests/view/document.js
- packages/ckeditor5-engine/tests/view/observer/focusobserver.js
- packages/ckeditor5-engine/tests/view/observer/selectionobserver.js
- packages/ckeditor5-engine/tests/view/renderer.js
- packages/ckeditor5-engine/tests/view/view/view.js
Fix (engine): Fixed focus issue handling on Chrome which happened when nested editable was clicked.
---
> Fix editable focus issue

- packages/ckeditor5-engine/_src/view/observer/focusobserver.js
- packages/ckeditor5-engine/_src/view/observer/selectionobserver.js
- packages/ckeditor5-engine/src/view/observer/selectionobserver.ts
Docs (engine): Fixed the incorrect links in docs.
---
> Fixed the docs

- packages/ckeditor5-special-characters/docs/features/special-characters.md
- packages/ckeditor5-special-characters/src/specialcharacters.js
- packages/ckeditor5-special-characters/tests/specialcharacters.js
Feature (special-characters): add configurable order of special characters groups. Closes #13220.
> feat: add configurable order of special characters groups

- packages/ckeditor5-image/src/image/imageediting.js
- packages/ckeditor5-image/src/image/replaceimagesourcecommand.js
- packages/ckeditor5-image/src/imageinsert/imageinsertui.js
- packages/ckeditor5-image/tests/image/replaceimagesourcecommand.js
Other (image): Encapsulate image replacement into command. Closes #13217 .
> Other (image): Encapsulate image replacement into command

- docs/features/toolbar.md
- docs/framework/guides/development-tools.md
- packages/ckeditor5-alignment/docs/features/text-alignment.md
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-ckfinder/docs/features/ckfinder.md
- packages/ckeditor5-easy-image/docs/features/easy-image.md
- packages/ckeditor5-font/docs/features/font.md
- packages/ckeditor5-image/docs/features/images-inserting.md
- packages/ckeditor5-language/docs/features/language.md
- packages/ckeditor5-table/docs/features/table.md
- packages/ckeditor5-ui/docs/features/blocktoolbar.md
- packages/ckeditor5-undo/docs/features/undo-redo.md
- packages/ckeditor5-upload/docs/features/base64-upload-adapter.md
- packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
- packages/ckeditor5-word-count/docs/features/word-count.md
Docs: examples revamp (13139 and others). Closes #13139 #13138 #13165 #13140 #13167 #13169 #13175 #13176 #13177 #13178 #13179 #13180.
---
> Docs: examples revamp (13139 and others)

- packages/ckeditor5-list/src/documentlist/documentlistediting.ts
- packages/ckeditor5-list/src/list/listediting.ts
- packages/ckeditor5-list/theme/list.css
- packages/ckeditor5-list/theme/liststyles.css
Fix (list): Fix unordered list style. Closes: #13206
> Fix (list): Fix unordered list style

- packages/ckeditor5-list/src/documentlist/documentlistediting.ts
Other (list): Change list item reconversion priority. Closes #13290.
> Other (list): Change list item reconversion priority

- docs/framework/guides/tutorials/implementing-an-inline-widget.md
Docs: Add meaningful comments to snippets in Implementing an inline widget guide. Closes https://github.com/ckeditor/ckeditor5/issues/13189.
---
> Docs: Add meaningful comments to snippets in Implementing an inline widget guide

- docs/framework/guides/architecture/ui-library.md
Docs: Add meaningful comments to ellipses in UI library guide. Closes #13181.
---
> Docs: Add meaningful comments to ellipses in UI library guide.

- packages/ckeditor5-core/src/contextplugin.ts
Internal (core): Change the type of ContextPlugin#context property.
---
> Change the type of ContextPlugin#context property.

- docs/features/ui-language.md
Docs: Added meaningful comments to ellipses in UI language guide. Closes [#13166](https://github.com/ckeditor/ckeditor5/issues/13166).
---
1. In addition to commenting the ellipses, I wrapped the relevant code in `module.exports = { ... }` to make it clearer.
2. I fixed some minor linguistic issues in the opening paragraph.
> Docs: Added meaningful comments to ellipses in UI language guide.

- docs/features/math-equations.md
- docs/features/spelling-and-grammar-checking.md
- packages/ckeditor5-clipboard/docs/features/drag-drop.md
- packages/ckeditor5-clipboard/docs/features/paste-plain-text.md
- packages/ckeditor5-heading/docs/features/headings.md
- packages/ckeditor5-horizontal-line/docs/features/horizontal-line.md
- packages/ckeditor5-html-embed/docs/features/html-embed.md
- packages/ckeditor5-html-support/docs/features/general-html-support.md
- packages/ckeditor5-image/docs/features/images-installation.md
- packages/ckeditor5-image/docs/features/images-resizing.md
- packages/ckeditor5-image/docs/features/images-styles.md
- packages/ckeditor5-link/docs/features/link.md
- packages/ckeditor5-list/docs/features/document-lists.md
- packages/ckeditor5-list/docs/features/lists.md
- packages/ckeditor5-list/docs/features/todo-lists.md
- packages/ckeditor5-markdown-gfm/docs/features/markdown.md
- packages/ckeditor5-media-embed/docs/features/media-embed.md
- packages/ckeditor5-mention/docs/features/mentions.md
- packages/ckeditor5-page-break/docs/features/page-break.md
- packages/ckeditor5-paste-from-office/docs/features/paste-from-google-docs.md
- packages/ckeditor5-paste-from-office/docs/features/paste-from-word.md
- packages/ckeditor5-restricted-editing/docs/features/restricted-editing.md
- packages/ckeditor5-select-all/docs/features/select-all.md
- packages/ckeditor5-source-editing/docs/features/source-editing.md
- packages/ckeditor5-special-characters/docs/features/special-characters.md
- packages/ckeditor5-style/docs/features/style.md
Docs: Ck/13091 and other examples revamp. Closes #13091. Closes #13090. Closes #13089. Closes #13087. Closes #13086. Closes #13130. Closes #13120. Closes #13119. Closes #13118. Closes #13115. Closes #13112. Closes #13110. Closes #13109. Closes #13108. Closes #13107. Closes #13106. Closes #13102. Closes #13131. Closes #13132.
---
> Docs: Ck/13091 and other examples revamp

- docs/framework/guides/contributing/code-style.md
Docs: Add meaningful comments to ellipses in the Code style guide. Closes #13202.
---
> Docs: Add meaningful comments to ellipses in the Code style guide.

- docs/framework/guides/tutorials/using-react-in-a-widget.md
Docs: Add meaningful comments to ellipses in Using a React component guide. Closes #13191.
---
> Docs: Add meaningful comments to ellipses in Using a React component guide.

- packages/ckeditor5-ui/docs/framework/guides/external-ui.md
Docs: Make Third-party UI guide snippets compilable. Closes #13199.
---
> Docs: Make Third-party UI guide snippets compilable.

- docs/_snippets/examples/bottom-toolbar-editor.js
- docs/examples/custom/bottom-toolbar-editor.md
Docs: title redone, link added. Closes #13155
> Docs: splitting toolbar buttons.

- packages/ckeditor5-editor-decoupled/docs/framework/guides/document-editor.md
Docs: Make Document editor UI guide snippets compilable. Closes #13200.
---
> Docs: Make Document editor UI guide snippets compilable.

- packages/ckeditor5-heading/_src/headingediting.js
Docs: API fixes. Closes #13300
---
> Docs: API fixes.

- docs/framework/guides/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
- docs/framework/guides/abbreviation-plugin-tutorial/abbreviation-plugin-level-2.md
- docs/framework/guides/abbreviation-plugin-tutorial/abbreviation-plugin-level-3.md
Docs: Add meaningful comments to ellipses in abbreviation plugin guides.. Closes #13182.
---
> Docs: Add meaningful comments to ellipses in abbreviation plugin guides.

- packages/ckeditor5-cloud-services/src/index.ts
Internal: Added `TokenUrl` type to the package exports.
> Added `TokenUrl` type to the package exports

- README.md
---
"**will**" should read "**with**"
This is a small and obvious change, so I have not raised an issue 😀
> Docs: Fixed README typo

- package.json
- scripts/collect-svg-icons.js
Internal: Added script for collecting SVG icons from CKEditor 5 packages.
---
> Added script for collecting svg icons

- packages/ckeditor5-ui/docs/framework/guides/deep-dive/focus-tracking.md
Docs: Add meaningful comments to ellipses in Focus tracking guide. Closes #13196.
---
> Docs: Add meaningful comments to ellipses in Focus tracking guide.

- packages/ckeditor5-widget/_src/utils.js
- packages/ckeditor5-widget/src/utils.ts
Docs: Fixing API typo. Closes #13399
---
> Docs: Fixing API typo.

- docs/_snippets/features/wproofreader.html
- docs/_snippets/features/wproofreader.js
Docs: excluding external source.
---
> Docs: excluding external source.

- packages/ckeditor5-clipboard/docs/framework/guides/deep-dive/clipboard.md
Docs: Added meaningful comment to ellipsis in Clipboard guide. Closes [#13192](https://github.com/ckeditor/ckeditor5/issues/13192).
---
This task involved adding just one ellipsis comment.
> Docs: Added meaningful comment to ellipsis in Clipboard guide.

- packages/ckeditor5-ckbox/docs/_snippets/features/build-ckbox-source.html
- packages/ckeditor5-ckbox/docs/features/ckbox.md
- packages/ckeditor5-undo/docs/_snippets/features/undo-redo.html
Docs: updating CKBox CDN link. Closes cksource/ckeditor5-internal#2658
---
> Docs: updating CKBox CDN link.

- scripts/release/clean.js
Internal: Added the `--cwd` modifier to the `release:clean` script to allow running outside the CKEditor 5 repository.
> Added the "--cwd" flag to the "release:clean" script

- docs/installation/frameworks/angular.md
Docs: Documented disableTwoWayDataBinding option. See ckeditor/ckeditor5-angular#346.
---
> Documented disableTwoWayDataBinding option.

- docs/framework/guides/abbreviation-plugin-tutorial/abbreviation-plugin-level-1.md
Docs: Rephrase the first part of the abbreviation plugin guide. Closes https://github.com/cksource/ckeditor5-internal/issues/2478.
---
> Docs: Rephrase the first part of the abbreviation plugin guide.

- docs/features/read-only.md
- docs/installation/getting-started/configuration.md
- packages/ckeditor5-engine/docs/framework/guides/deep-dive/event-system.md
- packages/ckeditor5-highlight/docs/features/highlight.md
- packages/ckeditor5-remove-format/docs/features/remove-format.md
- packages/ckeditor5-widget/docs/framework/guides/deep-dive/widget-internals.md
Docs: examples revamp in various guides. Closes #13088. Closes #13117. Closes #13116. Closes #13037. Closes #13194. Closes #13197. 
---
> Docs: examples revamp in various guides

- scripts/docs/build-content-styles.js
- scripts/docs/utils.js
Fix: Fixed missing content styles. Closes #13451.
---
> Fixed missing content styles

- packages/ckeditor5-image/docs/framework/guides/deep-dive/upload-adapter.md
Docs: Add meaningful comments to ellipses in Custom image upload adapter guide. Closes #13193.
---
> Docs: Add meaningful comments to ellipses in Custom image upload adapter guide.

- packages/ckeditor5-engine/src/conversion/downcastdispatcher.ts
Internal: Defined a more specific type for `DowncastConversionApi.options`.
> Defined a more specific type for `DowncastConversionApi.options`

- packages/ckeditor5-html-embed/docs/features/html-embed.md
Docs: Updated HTML embed docs. Closes #13462.
> Docs: Updated HTML embed docs.

- packages/ckeditor5-enter/src/enter.ts
- packages/ckeditor5-enter/src/entercommand.ts
- packages/ckeditor5-enter/src/enterobserver.ts
- packages/ckeditor5-enter/src/shiftenter.ts
- packages/ckeditor5-enter/src/shiftentercommand.ts
- packages/ckeditor5-enter/src/utils.ts
Internal (enter): Clean-up docs for `ckeditor5-enter`. Closes #12702.
> Clean-up docs for `ckeditor5-enter`

- scripts/docs/build-content-styles.js
- scripts/docs/utils.js
Internal: The content styles script should handle TS and JS (depending on the environment). Closes #13451.
---
> Content styles builder handles TS

- packages/ckeditor5-select-all/src/selectall.ts
- packages/ckeditor5-select-all/src/selectallcommand.ts
- packages/ckeditor5-select-all/src/selectallediting.ts
- packages/ckeditor5-select-all/src/selectallui.ts
Internal (select-all): Clean-up docs for `ckeditor5-select-all`. Closes #12704 .
> Clean-up docs for `ckeditor5-select-all`

- packages/ckeditor5-core/src/index.ts
- packages/ckeditor5-engine/src/conversion/downcasthelpers.ts
- packages/ckeditor5-engine/src/index.ts
- packages/ckeditor5-engine/src/model/model.ts
- packages/ckeditor5-list/src/todolist/checktodolistcommand.ts
Other (engine, core, list): Various typescript type changes.
> Other (engine, core, list): Various typescript type changes.

- packages/ckeditor5-core/src/index.ts
- packages/ckeditor5-engine/src/index.ts
Internal (core, engine): Additional exports for TypeScript.
> Additional exports for TypeScript

- docs/features/ui-language.md
Docs: Improved table layout in the UI Language guide. Closes #13487.
---
> Docs: Improved table layout in the UI Language guide

- packages/ckeditor5-upload/src/adapters/base64uploadadapter.ts
- packages/ckeditor5-upload/src/adapters/simpleuploadadapter.ts
- packages/ckeditor5-upload/src/filereader.ts
- packages/ckeditor5-upload/src/filerepository.ts
- packages/ckeditor5-upload/src/ui/filedialogbuttonview.ts
- packages/ckeditor5-upload/src/uploadconfig.ts
Internal (upload): Cleaning doclets. Closes #12708.
---
> Updating API docs in upload package

- packages/ckeditor5-font/docs/features/font.md
Docs: adding a more informative title to the font guide. Closes cksource/ckeditor5-internal#2748
---
> Docs: more informative title.

- docs/installation/frameworks/react.md
Docs: Documented `watchdogConfig` option for react integration. See ckeditor/ckeditor5-react#360.
---
> Documented `watchdogConfig` option for react integration

- docs/examples/index.md
- docs/features/index.md
- docs/installation/index.md
Docs: removing docs usage help infobox on desktop. Closes cksource/ckeditor5-internal#2753
---
> Docs: removing docs usage help infobox on desktop.

- packages/ckeditor5-utils/src/index.ts
Other(utils): Export "diffToChanges" from utils. Closes #13579.
---
Needed for https://github.com/cksource/ckeditor5-internal/pull/2813#pullrequestreview-1317541615
> Export diffToChanges from utils

- docs/installation/frameworks/angular.md
Docs: Documented `editorWatchdogConfig` option for angular integration. See ckeditor/ckeditor5-angular#351.
---
> Documented `editorWatchdogConfig` option for angular integration

- scripts/release/clean.js
Internal: Fix release:clean command script
> Fix release:clean command script

- packages/ckeditor5-core/tests/editor/editor.js
- packages/ckeditor5-engine/src/view/observer/selectionobserver.ts
- packages/ckeditor5-engine/tests/model/model.js
- packages/ckeditor5-engine/tests/model/utils/insertcontent.js
- packages/ckeditor5-engine/tests/model/utils/insertobject.js
- packages/ckeditor5-engine/tests/view/observer/bubblingemittermixin.js
- packages/ckeditor5-engine/tests/view/observer/selectionobserver.js
- packages/ckeditor5-engine/tests/view/view/view.js
Tests: Tests changed so that they do not depend on debug mode. Closes #13593.
---
> Tests should not depend on debug mode.

- packages/ckeditor5-build-balloon-block/package.json
- packages/ckeditor5-build-balloon-block/tsconfig.json
- packages/ckeditor5-build-balloon-block/tsconfig.types.json
- packages/ckeditor5-build-balloon/package.json
- packages/ckeditor5-build-balloon/tsconfig.json
- packages/ckeditor5-build-balloon/tsconfig.types.json
- packages/ckeditor5-build-classic/package.json
- packages/ckeditor5-build-classic/tsconfig.json
- packages/ckeditor5-build-classic/tsconfig.types.json
- packages/ckeditor5-build-decoupled-document/package.json
- packages/ckeditor5-build-decoupled-document/tsconfig.json
- packages/ckeditor5-build-decoupled-document/tsconfig.types.json
- packages/ckeditor5-build-inline/package.json
- packages/ckeditor5-build-inline/tsconfig.json
- packages/ckeditor5-build-inline/tsconfig.types.json
- packages/ckeditor5-build-multi-root/package.json
- packages/ckeditor5-build-multi-root/src/ckeditor.ts
- packages/ckeditor5-build-multi-root/tsconfig.json
- packages/ckeditor5-build-multi-root/tsconfig.types.json
Internal: Fix TypeScript configuration for builds.
> Fix TypeScript configuration for builds

- packages/ckeditor5-table/src/converters/upcasttable.ts
- packages/ckeditor5-table/tests/converters/upcasttable.js
Fix (table): Change detection on heading rows and columns on table upcast. Closes #3172.
---
> Change detecting heading rows behavior.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: updating additional CKBox info. Closes cksource/ckeditor5-internal#2871
---
> Docs: updating additional CKBox info.

- packages/ckeditor5-engine/src/index.ts
- packages/ckeditor5-utils/src/index.ts
Internal (engine, utils): Fix exports of types in main package entry-points.
> Fix exports of types in main package entry-points

- tsconfig.json
Internal: Set TypeScript target to ES2019.
---
> Set TypeScript target to ES2019.

- docs/features/read-only.md
Docs: fixing guide order. Closes cksource/ckeditor5-internal#2903
---
> Docs: fixing guide order.

- packages/ckeditor5-widget/src/widgetresize/resizerstate.ts
- packages/ckeditor5-widget/tests/widgetresize/resizerstate.js
Fix (image): Fix the image resize handle displaying NaN in some scenarios. Closes #10776.
---
> Fix image resize handle displaying NaN.

- scripts/ci/exec-factory.js
- scripts/ci/should-run-short-flow.js
- scripts/ci/travis-check.js
Internal: Implemented a short flow on CI that skips checking the code if the commit changes the documentation only.
---
> Implemented short flow for CI

- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: rewording CKBox information.
---
_Also testing short CI run._
> Docs: rewording CKBox information.

- packages/ckeditor5-engine/src/view/view.ts
- packages/ckeditor5-engine/tests/view/view/view.js
- packages/ckeditor5-utils/src/dom/scroll.ts
- packages/ckeditor5-utils/tests/_utils/scroll.ts
- packages/ckeditor5-utils/tests/dom/scroll.js
- packages/ckeditor5-utils/tests/manual/scroll/scroll-config.html
- packages/ckeditor5-utils/tests/manual/scroll/scroll-config.js
- packages/ckeditor5-utils/tests/manual/scroll/scroll-config.md
- packages/ckeditor5-utils/tests/manual/scroll/scroll.html
- packages/ckeditor5-utils/tests/manual/scroll/scroll.js
Other (utils): Added configuration to the `View#scrollToTheSelection()` helper allowing to scroll to the top of the boundary. Closes #13688.
---
> Added configuration to View#scrollToTheSelection() allowing scrolling to the top of the scrollable boundary

- packages/ckeditor5-ui/docs/_snippets/features/blocktoolbar.js
Doc: unifying demos toolbars Batch Nine. Closes cksource/ckeditor5-internal#2944
---
_Part of_ cksource/ckeditor5-internal#2797
> Doc: unifying demos toolbars Batch Nine.

- packages/ckeditor5-link/src/linkcommand.ts
- packages/ckeditor5-link/tests/linkcommand.js
Fix: Link doesn't show a change in the link. Closes #12588.
---
> Link doesn't show a change in the link

- docs/umberto.json
Docs: collaboration features overview rewrite.
---
_TOC reordering. Merge together with_ cksource/collaboration-features#5065
> Docs: collaboration features overview rewrite.

- packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
Docs: infobox fix. Closes cksource/ckeditor5-internal#2976
---
> Docs: infobox fix.

- packages/ckeditor5-select-all/ckeditor5-metadata.json
Internal (select-all): Added the `ckeditor5-metadada.json` file.
---
> Added metadada file for ckeditor5-select-all plugin

- docs/installation/advanced/integrating-from-source-webpack.md
Docs: Add TypeScript option to the Integrating from source using webpack guide. Closes https://github.com/cksource/ckeditor5-internal/issues/2862.
---
> Docs: Add TypeScript option to the Integrating from source using webpack guide.

- docs/installation/advanced/integrating-from-source-vite.md
Docs: Add TypeScript option to the Integrating from source using Vite guide. Closes https://github.com/cksource/ckeditor5-internal/issues/2970.
---
> Docs: Add TypeScript option to the Integrating from source using Vite guide.

- docs/examples/builds/balloon-block-editor.md
- docs/examples/builds/balloon-editor.md
- docs/examples/builds/classic-editor.md
- docs/examples/builds/document-editor.md
- docs/examples/builds/inline-editor.md
- docs/examples/builds/multi-root-editor.md
Docs: code snippets fix. Closes cksource/ckeditor5-internal#3009
---
> Docs: code snippets fix.

- docs/installation/working-with-typescript.md
> Docs: Fixing typo

- scripts/ci/should-run-short-flow.js
Internal: Enabled full CI build when processing a CRON job. Closes #13728.
---
> Enabled full CI build when processing a CRON job

- docs/updating/update-to-36.md
- docs/updating/update-to-37.md
Doc: Added `docs/updating/update-to-37.md`. Closes #13811.
---
> Add docs/updating/update-to-37.md

- .eslintrc.js
- docs/installation/frameworks/vuejs-v2.md
- docs/installation/frameworks/vuejs-v3.md
Docs: Add TypeScript options in Vue integration. Closes https://github.com/cksource/ckeditor5-internal/issues/2991.
---
> Docs: Add TypeScript options in Vue integration.

- CHANGELOG.md
- docs/updating/update-to-37.md
Internal: Updated changelog and migration guide.
> Updated changelog and migration guide

- docs/installation/working-with-typescript.md
> Docs: Adding link from TypeScript overview to update guide.

- packages/ckeditor5-engine/tests/view/renderer.js
Tests (engine): Increase timeout on rendering 1000 nodes. Closes #13839.
---
> Change timeout.

- docs/updating/update-to-37.md
Docs: adding minimal Node version bump info to update guide. Closes cksource/ckeditor5-internal#3122
---
> Docs: adding Node bump info.

- packages/ckeditor5-autoformat/docs/features/autoformat.md
- packages/ckeditor5-basic-styles/docs/features/basic-styles.md
- packages/ckeditor5-font/docs/features/font.md
- packages/ckeditor5-highlight/docs/features/highlight.md
- packages/ckeditor5-minimap/docs/features/minimap.md
- packages/ckeditor5-remove-format/docs/features/remove-format.md
- packages/ckeditor5-style/docs/features/style.md
- packages/ckeditor5-typing/docs/features/text-transformation.md
Docs: adding the productivity pack to several related features sections. Closes cksource/ckeditor5-internal#3116
---
> Updating related features

- docs/installation/frameworks/react.md
Docs: Add TypeScript option to React integration. Closes https://github.com/cksource/ckeditor5-internal/issues/3082.
---
> Docs: Add TypeScript option to React integration.

- packages/ckeditor5-utils/src/mix.ts
Docs (utils): Fixes the order of super-classes in mixins.
---
> Change the order of base classes in mixed types

- docs/installation/frameworks/vuejs-v3.md
Docs: Add Vue 3 docs for `disableTwoWayDataBinding` property. See ckeditor/ckeditor5-vue#246.
---
> Add Vue 3 docs for `disableTwoWayBinding` property.

- CHANGELOG.md
Docs: 37.1.0 changelog review.
---
_Don't merge._
> 37.1.0 changelog review

- docs/installation/frameworks/vuejs-v3.md
Docs: Fix docs after Vue 3 `disableTwoWayDataBinding` update.
---
> Fix docs after Vue 3 `disableTwoWayDataBinding` update.

- docs/installation/getting-started/predefined-builds.md
- docs/installation/getting-started/quick-start.md
Docs: mentioning productivity pack in superbuild. Closes cksource/ckeditor5-internal#3154
---
_Merge together with https://github.com/cksource/ckeditor5-internal/pull/3155_
> Docs: mentioning pp in sb.

- packages/ckeditor5-font/src/ui/colortableview.ts
- packages/ckeditor5-font/src/ui/colorui.ts
- packages/ckeditor5-font/tests/ui/colorui.js
- packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
Internal (font): Implement model attribute value application for the colour picker. Closes [#2977](https://github.com/cksource/ckeditor5-internal/issues/2977).
---
> Implement model attribute value application for the colour picker

- docs/installation/frameworks/angular.md
- docs/installation/frameworks/react.md
- docs/installation/frameworks/vuejs-v3.md
- docs/installation/working-with-typescript.md
Docs: Add a clear indication that integrations work with TypeScript. Closes https://github.com/cksource/ckeditor5-internal/issues/3125.
---
The PR also closes https://github.com/cksource/ckeditor5-internal/issues/3146.
> Docs: Add a clear indication that integrations work with TypeScript.

- docs/framework/contributing/code-style.md
- docs/installation/frameworks/angular.md
- docs/installation/frameworks/vuejs-v2.md
- docs/installation/working-with-typescript.md
- packages/ckeditor5-editor-multi-root/src/multirooteditor.ts
- packages/ckeditor5-engine/src/model/markercollection.ts
- packages/ckeditor5-engine/src/model/selection.ts
- packages/ckeditor5-engine/tests/tickets/984.js
- packages/ckeditor5-typing/src/deleteobserver.ts
Docs: release 37.0.0 review. Closes cksource/ckeditor5-internal#3144
---
> Docs: release 37.0.0 review.

- packages/ckeditor5-ckbox/docs/features/ckbox.md
Docs: updating CKBox installation section. Closes #13917
---
> Docs: updating CKBox installation section.

- docs/framework/package-generator/typescript-package.md
Docs: Add `augmentation.ts` to docs for typescript package generator.
---
> Add `augmentation.ts` to docs for typescript package generator.

- docs/updating/updating-ckeditor-5.md
Docs: updating CS links. Closes cksource/ckeditor5-internal#3151
---
_Merge with_ cksource/collaboration-features#5216
> Docs: updating CS links.

- packages/ckeditor5-source-editing/docs/features/source-editing.md
Type: Message. Closes https://github.com/cksource/ckeditor5-internal/issues/3141.
---
> Docs: added information about Source Editing and non-RTC collaboration

- docs/framework/architecture/ui-components.md
Docs: snippet update. Closes cksource/ckeditor5-internal#3178
---
> Docs: snippet update.
